### ISSUE TITLE
如何分流请求到不同的rpc节点上？

### ISSUE THREAD

**Issue by seyoatda** [zeromicro/go-zero#1001]
所有的rpc节点都是一样的业务逻辑，如何在中心服务中选择根据权重/自定义分流策略分流到不同的节点上进行处理？
看了一下目前用的是 etcd 注册发现，这部分在 go-zero 有实现吗？
此外，如果请求某个节点服务失败，是否会自动转发到其他节点服务重试？
BTW, 官方文档对这方面的描述没看到过，能否加强一下文档里的相关内容。

**Comment by chenquan** [comment]
负载均衡用的是p2c+EWMA
自动重试应该还没有标准组件, 可以自己使用grcp的客户端 interceptor 封装自动重试功能

**Comment by kevwan** [comment]
自动重试会有问题的，小心处理，可以看我的视频分享

**Comment by seyoatda** [comment]
> 负载均衡用的是p2c+EWMA
> 自动重试应该还没有标准组件, 可以自己使用grcp的客户端 interceptor 封装自动重试功能

是否支持自定义的分流？支持用 grpc原生的 balancer ，或者是否有封装好的 balancer? 因为我看源码里 balancer 这部分是 private 的

**Comment by seyoatda** [comment]
> 自动重试会有问题的，小心处理，可以看我的视频分享

可以给个链接吗谢谢

**Comment by kevwan** [comment]
> > 自动重试会有问题的，小心处理，可以看我的视频分享
> 
> 可以给个链接吗谢谢

可以看下『微服务实践』公众号里的文章哈

**Comment by chenquan** [comment]
> > 负载均衡用的是p2c+EWMA
> > 自动重试应该还没有标准组件, 可以自己使用grcp的客户端 interceptor 封装自动重试功能
> 
> 是否支持自定义的分流？支持用 grpc原生的 balancer ，或者是否有封装好的 balancer? 因为我看源码里 balancer 这部分是 private 的

自动重试:https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry
