### ISSUE TITLE
[design question] what's the purpose of using opts in rest.Server?

### ISSUE THREAD

**Issue by zhaoweiguo** [zeromicro/go-zero#1037]
https://github.com/tal-tech/go-zero/blob/e8376936d577f8863b9de9f6351ab8f2e3c3dfed/rest/server.go#L22-L25
这儿设计 Server 结构体为什么不是直接用
```
	Server struct {
		ngin *engine
	}
这样也可以实现对 engine 的封装
```
有什么设计意图吗？与它名字相关的结构有一个
```
type RunOption func(*Server)
```
但感觉没啥关联啊，而且在

https://github.com/tal-tech/go-zero/blob/e8376936d577f8863b9de9f6351ab8f2e3c3dfed/rest/server.go#L49-L57
这儿还容易有误解

**Comment by kevwan** [comment]
go的典型设计模式，options

**Comment by zhaoweiguo** [comment]
https://github.com/tal-tech/go-zero/blob/e8376936d577f8863b9de9f6351ab8f2e3c3dfed/rest/server.go#L42-L61

56-58行是典型的 functional options
但我想问的是49-53行的这个 opts.

**Comment by kevwan** [comment]
start可以有多种方式

options是为了多个可配置项

**Comment by zhaoweiguo** [comment]
不太明白，能举个例子详细说说吗？真心想学习一下

**Comment by kevwan** [comment]
这里就是例子呀

**Comment by zhaoweiguo** [comment]
> 这里就是例子呀

这个例子完全没有感受到这样用有啥好处。而且 Server 的opts 字段和NewServer函数中的 opts 参数也很容易误以为有啥关系（而且一个类型是RunOption一个是runOption），但实际上没有关系。
