### ISSUE TITLE
The problem on using goctl

### ISSUE THREAD

**Issue by kotlin2018** [zeromicro/go-zero#1039]
文档链接 https://go-zero.dev/cn/rpc-call.html

![image](https://user-images.githubusercontent.com/56008171/133094602-d603f037-4b94-4510-afd3-8309ce951457.png)

在终端执行命令 `goctl rpc proto -src user.proto -dir .` ，则生成的 `user.go` `user.pb.go`文件都在 user 这个包下面了

正确的应该是: user.pb.go 文件在 user包下，user.go 文件在 userclient包下

**Comment by anqiansong** [comment]
@kotlin2018 

`goctl version 1.2.1 darwin/amd64`

```text
.
├── etc
│   └── user.yaml
├── go.mod
├── internal
│   ├── config
│   │   └── config.go
│   ├── logic
│   │   └── getuserlogic.go
│   ├── server
│   │   └── userserver.go
│   └── svc
│       └── servicecontext.go
├── user
│   └── user.pb.go
├── user.go
├── user.proto
└── userclient
    └── user.go
```

你执行一下 `goctl --version` 查看一下版本

**Comment by kotlin2018** [comment]
我的 goctl version 1.1.8 darwin/amd64
是我的 goctl 版本太高了么？

**Comment by kotlin2018** [comment]
好的好的，🙏哈

**Comment by kotlin2018** [comment]
报这种错哦
<img width="871" alt="截屏2021-09-15 上午11 08 52" src="https://user-images.githubusercontent.com/56008171/133364278-0d4b565a-babf-456c-bf8e-4874f9ba11a9.png">

<img width="258" alt="截屏2021-09-15 上午11 11 23" src="https://user-images.githubusercontent.com/56008171/133364361-13f4350f-c745-4f17-9ff0-99a62391b543.png">

.
├── LICENSE
├── README.md
├── etc
│   └── user.yaml
├── go.mod
├── go.sum
├── internal
│   ├── config
│   ├── logic
│   ├── server
│   └── svc
├── sql.sql
├── user
├── user.proto
└── userclient

**Comment by kotlin2018** [comment]
这代码没有生成出来哦

**Comment by anqiansong** [comment]
> 这代码没有生成出来哦

@kotlin2018 你把 `protoc-gen-go` 降级一下，执行 `go get -u github.com/golang/protobuf/protoc-gen-go@1.3.2`
最新版兼容还是有bug。

**Comment by kotlin2018** [comment]
* 这是个bug哦，我已经将 protoc-gen-go 降级到 protoc-gen-go@1.3.2  了，还是报上面的错误
* 如下是我的 protoc-gen-go 版本

<img width="329" alt="截屏2021-09-18 上午10 37 41" src="https://user-images.githubusercontent.com/56008171/133869600-f2b8a2c2-6109-4e55-9f54-c168ac38fe96.png">
了

**Comment by anqiansong** [comment]
> * 这是个bug哦，我已经将 protoc-gen-go 降级到 protoc-gen-go@1.3.2  了，还是报上面的错误
> * 如下是我的 protoc-gen-go 版本
> 
> <img alt="截屏2021-09-18 上午10 37 41" width="329" src="https://user-images.githubusercontent.com/56008171/133869600-f2b8a2c2-6109-4e55-9f54-c168ac38fe96.png">
> 
> 了

Fixed on #1076
