### ISSUE TITLE
rpc服务运行一段时间后，etcd 上注册的 key 失效

### ISSUE THREAD

**Issue by seyoatda** [zeromicro/go-zero#1044]
查看了一下，rpc服务还是正常运行，etcd服务也是正常运行。但是就是 etcd 上没有 rpc 的地址信息了。服务都是运行在一台机上的，不可能因为网络的问题导致没有刷新ttl

**Comment by kevwan** [comment]
etcdctl要用v3查看

**Comment by seyoatda** [comment]
是用的 etcdctl v3, 经排查是 etcd 还在维护以前的节点信息，导致 etcd 运行出现问题。rpc 服务访问 etcd 失败所以 key 过期了。
