### ISSUE TITLE
【建议】支持关闭CPU等指标监控

### ISSUE THREAD

**Issue by zhyllllll** [zeromicro/go-zero#1057]
![image](https://user-images.githubusercontent.com/42061317/133793075-d9bc97ee-b0ab-4be7-b907-3d44d1085145.png)

对于客户端来说不是很需要这个东西

**Comment by kevwan** [comment]
你可以disable stat的

**Comment by zhyllllll** [comment]
> 你可以disable stat的

![image](https://user-images.githubusercontent.com/42061317/133797048-b473ba1e-2ff1-4119-8449-1668fb778675.png)
这个吗？这只是关闭掉日志输出吧？不过也可以了
