### ISSUE TITLE
goctl api new 生成工程包错误

### ISSUE THREAD

**Issue by mascotli** [zeromicro/go-zero#1058]
../go/bin/goctl api new green

异常情况，生成的代码引用 模块 错误
<img width="776" alt="image" src="https://user-images.githubusercontent.com/11813278/133815620-b5d023b0-4295-412f-8f48-cb8b21c70f06.png">

命令
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11813278/133815654-35dd1750-b1df-453f-a794-ece6261f5a71.png">

目录
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11813278/133815785-ded3ab8f-547e-413e-bb4b-0dcce4b55f4c.png">

**Comment by anqiansong** [comment]
`/Users/niecolesli/git/green` 中有没有软连接到其他地方，如果有，你检查一下你的goctl版本，这个在goctl 1.2.0就已经修复了

**Comment by mascotli** [comment]
@anqiansong 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/11813278/133890063-8da07ae1-52c8-408f-b222-befb33903bc3.png">

目前是 1.2.1

**Comment by mascotli** [comment]
@anqiansong 

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/11813278/133890890-456395fe-184f-4512-854a-e25627242c82.png">

73行 TrimPrefix 时两个参数在 windows、mac 等环境下和 linux 环境不一样，有文件名大小写敏感的区别，比如路径是 /Users/niecoles/Git 但是 cd 是 /Users/niecoles/git 这种情况下存在无法去除路径前缀的问题

**Comment by mascotli** [comment]
@anqiansong 

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/11813278/133891189-bcc0ed89-cb58-4613-9029-3afd3114b1dd.png">

43 行
