### ISSUE TITLE
Problem on passing values with type [][]interface{}

### ISSUE THREAD

**Issue by fmzchao** [zeromicro/go-zero#1060]
type Request {
 Name string          `json:"name"`
 Args [][]interface{} `json:"args"`
}
type Response {
 Message string `json:"message"`
}
service greet-api {
 @handler GreetHandler
 post /index(Request) returns (Response);
}

Members with type [][]interface{} cannot be parsed on POST requests.

Affected versions: >= 1.1.8

It was working well with version 1.1.7
![1631953909384](https://user-images.githubusercontent.com/19552890/133882454-7abb89a2-7689-41da-9558-9d6723e7df7f.jpg)

But not working with version 1.1.8 and laters.

<img width="742" alt="企业微信20210918-163423@2x" src="https://user-images.githubusercontent.com/19552890/133882532-e048d248-db31-4c25-a0f1-ba9eb73df167.png">

**Comment by anqiansong** [comment]
It's intentional when we designed the api syntax, In my opinion, I think it should be clear, unambiguous and simple，It's not a copy of a golang struct. To define a struct what the struct should be.

**Comment by fmzchao** [comment]
I want to define the following structure and how to implement it in the new version？

{
    "name": "我是一个小标题",
    "args": [
        [
            "Leverage",
            10
        ]
    ]
}

**Comment by anqiansong** [comment]
As you defined, the data structure
```
["Leverage",10]
```
does not a json array, just not likes JavaScript, you should first know what an array is, the follow structure is recommend:
```
["Leverage", "Some", "another", "element"] // []string
```

or
```
[10, 11, 12] // []int
```

**Comment by fmzchao** [comment]
This method, there is no way to use in a complex application environment, the value of args is unpredictable, this method you have to divide the array, and then merge the back end, too much trouble, I hope can change back to the original method
