### ISSUE TITLE
rest middlewares not called in latest code

### ISSUE THREAD

**Issue by gsd1508** [zeromicro/go-zero#1068]
![image](https://user-images.githubusercontent.com/19414296/133973703-6e91e3bf-5920-4a47-8abf-5c121a3a2a73.png)
# #

![image](https://user-images.githubusercontent.com/19414296/133973825-b8d64ce0-5a97-4d32-b80a-4fa8bbe33074.png)

![image](https://user-images.githubusercontent.com/19414296/133973870-22aeba4e-9fbd-45a8-b32e-f8eae821740a.png)

万老师我不知道怎么回事，

**Comment by gsd1508** [comment]
demo代码地址在这里

**Comment by gsd1508** [comment]
https://gitee.com/meihuali/new-gungun

**Comment by gsd1508** [comment]
demo地址在这里大家帮忙看看
https://gitee.com/meihuali/new-gungun

**Comment by kevwan** [comment]
middleware里面需要调用 `next.ServeHTTP(w, r)`

我测试没问题呀

**Comment by kevwan** [comment]
Close it for the moment, reopen it if needed.
