### ISSUE TITLE
Please use English to communicate! / 尽量使用英文交流！

### ISSUE THREAD

**Issue by cyouraku** [zeromicro/go-zero#1071]
Hi, dear all

It would be gratefull if you guys could communicate with each oher in English. 
Thus, we could have more people around the world to join this project in the near future. 
Thanks again for your hard working and contribution to the open source community!

**Comment by kevwan** [comment]
Thanks for your suggestion!

Yes, we need to do that, because I found lots for people around the world starred this project.

Thanks again!

**Comment by kevwan** [comment]
期望大家理解，因为很多国外用户在尝试和使用 go-zero，并跟我反馈，他们无法参与交流！

**Comment by baiyuxiong** [comment]
wowowo 看大家的留言，浓浓中国味啊

**Comment by gogowaiting** [comment]
让他们用 中翻英 呢，要有文化自信

**Comment by scopeccsky** [comment]
google translate

**Comment by iamdaiyuan** [comment]
赶紧学习中文

**Comment by xiusin** [comment]
是不是代码里出现了中文注释就很 Low B?  英文才是高大上的

**Comment by kevwan** [comment]
> 是不是代码里出现了中文注释就很 Low B? 英文才是高大上的

没有low和高大上的区别，语言只是个工具，只是为了交流方便而已。

**Comment by chenkaiwei** [comment]
好，我个人决定在这里启用双语交流。Ok，I decieded that i would communicate with two language in the project

**Comment by WenTao-Love** [comment]
好大压力！

**Comment by AslanLau** [comment]
> Hi, dear all
> 
> It would be gratefull if you guys could communicate with each oher in English. Thus, we could have more people around the world to join this project in the near future. Thanks again for your hard working and contribution to the open source community!

你是中国人还是华裔？会几句英语了不起了？共建的社区需要大家去共同维护，创始人是中国人那就用中文有什么问题？世界上其他人看不懂方块字就不会谷歌？都和你一样手残？



> Thanks for your suggestion!
> 
> Yes, we need to do that, because I found lots for people around the world starred this project.
> 
> Thanks again!

作者大大，你也有点文化自信好伐？你的这个东西无疑是好的，国内推广完全没问题。但人家一个提议你就直接背离了国内同胞，不觉得太舔了点？

**Comment by cyouraku** [comment]
虽然对我本人没有太大影响，但是因为持续收到脱离讨论内容的邮件，还是有必要用中文和大家解释一下。
我们团队在国外，工作语言是英语，团队成员有新西兰人，韩国人，印度人，欧洲人的同事都只能用英语交流。
我也很乐意把国内优秀的项目翻译成英语分享给我的同事们。
但是如果项目本身就是国际化的项目，那样就可以省却很多翻译的精力。
谷歌翻译是机器翻译，无论是英译中，还是中译英都会有不少词不达意的地方。
语言只是语言，方便大家交流就好，选择什么语言交流也是大家的自由，提出这个issue本身没有任何其他目的。
可能是管理者起了一个不太合适的标题，如果换成如下标题或许就会避免很多误会。
-->
 Welcome to use English to communicate if possible./如有可能欢迎大家使用英语交流。

**Comment by DomineCore** [comment]
自动翻译的机器人能不能加个英译汉

**Comment by kpvt001** [comment]
国际化的项目确实应该使用联合国官方工作语言中的一种，各语言之间没有谁更高人一等的说法，主要要考虑主要作者的母语，以贴近作者的真实表达。

因此，建议使用联合国官方工作语言中，偏向作者母语的语言，作为交流语言使用更为恰当。

至于其他语言的使用者，可以使用翻译工具。

或者以较多使用者的母语作为交流语言也可。

**Comment by Razorro** [comment]
Technically speaking, that's plausible because I understand the effort of internationalizing this project.
Thanks for the excellent, out-of-box project, really save my lots of time and make my work much easier, I'll try my best to catch up with your guys!

**Comment by baby5** [comment]
更好的解决办法是大家都用母语，让github或者机器来帮忙解决翻译的问题。使用翻译机器人会让回复变得十分混乱。以现在的技术这不是很难的事情，希望人类以后可以无缝交流。

A better solution is for everyone to use their native language and let github or machines help solve the translation problem. Using a translation bot can make responses very confusing. This is not a difficult task with current technology, and I hope humans can communicate seamlessly in the future.

**Comment by Jinyun-Liu** [comment]
这是我们中国特色的golang开源框架，必须用中文表达，所有的功能习惯必须符合国人的思维和习惯。

**Comment by xuxing421** [comment]
It is really a big step for our engineers, we all need to learn some english for this terrible situation right?

**Comment by linzexin** [comment]
验证是真的不好用，httpx.Parse面向英文没问题，起码能传入中文的提示呀，只能通过strings去判断包含再转成中文太鸡肋了点吧，而且内置的验证规则那么简单，不是说不行，但起码能关闭或者替换validator呀，像引用其他规则多点的验证包，还得重写整块表单值接收

**Comment by linzexin** [comment]
> 验证是真的不好用，httpx.Parse面向英文没问题，起码能传入中文的提示呀，只能通过strings去判断包含再转成中文太鸡肋了点吧，而且内置的验证规则那么简单，不是说不行，但起码能关闭或者替换validator呀，像引用其他规则多点的验证包，还得重写整块表单值接收

虽然用httpx组合用里面原先表单解析重写个parse也行，但还是希望这些内置方便点,相信我不是第一个这么觉得的
