### ISSUE TITLE
A model tutorial will be appreciated

### ISSUE THREAD

**Issue by langbin522** [zeromicro/go-zero#1072]
The current document is only a general explanation, I hope to add some more common examples of code up. This will make it easier for newbies to quickly write the business logic.
More examples are expected to be added for middlewares, database operations. So that newcomers can understand it easily.

---

现在的文档只是大概的逻辑性讲解，希望加多一些常用的例子代码上去。这样新手可以更方便快速的去现实业务逻辑。
现在文档，应该从，中间件，数据库操作这些加多一些例子上去。这样新手一目了然了。

**Comment by anqiansong** [comment]
Thanks, for more information about mysql and mongo generation, see [mysql readme](https://github.com/zeromicro/go-zero/blob/master/tools/goctl/model/sql/README.MD) or [mongo readme](https://github.com/zeromicro/go-zero/blob/master/tools/goctl/model/mongo/readme.md). the site https://go-zero.dev has been introduced how to use middleware in rest, see [middleware](https://go-zero.dev/cn/middleware.html), if you have read the document  in oder, you will gain much more!
