### ISSUE TITLE
Invitation to represent the `go-zero` library on Layer5 landscape

### ISSUE THREAD

**Issue by Nikhil-Ladha** [zeromicro/go-zero#1077]
[Layer5](https://github.com/layer5io) represents the largest community of service meshes and maintainers all over the world. And, our [Service Mesh Landscape](https://layer5.io/service-mesh-landscape) depicts that.

Considering the above fact, we welcome the addition of the `go-zero` framework to our Landscape under the `Client Library` section on the [Service Mesh Comparison Matrix](https://layer5.io/service-mesh-landscape#service-mesh-comaprison-matrix).

If you are inclined in doing so, feel free to open an [Landscape Update Issue](https://github.com/layer5io/layer5/issues/new?assignees=&labels=area%2Flandscape%2C+help+wanted%2C+framework%2Fgatsby%2C+language%2Fmarkdown%2C+good+first+issue&template=landscape.md&title=%5BLandscape%5D) to track the same.

**Comment by kevwan** [comment]
Hi Nikhil,

Thanks for your invitation!

I'll work on it.

**Comment by kevwan** [comment]
https://github.com/layer5io/layer5/issues/2212

**Comment by Nikhil-Ladha** [comment]
That is the link for the issue, right?
Looks fine.
Someone will soon send out a PR for it (or you yourself can try it out).
Thanks :)

**Comment by kevwan** [comment]
> That is the link for the issue, right?
> Looks fine.
> Someone will soon send out a PR for it (or you yourself can try it out).
> Thanks :)

Great, thanks!

**Comment by kevwan** [comment]
![image](https://user-images.githubusercontent.com/1918356/134504902-636d0a94-024d-4688-a721-58d8824a3ed3.jpeg)

go-zero is already added. Close this issue.
