### ISSUE TITLE
I want to ask the difference between CacheRedis and Redis

### ISSUE THREAD

**Issue by qianxi0410** [zeromicro/go-zero#1097]

**Comment by kevwan** [comment]
There is no `CacheRedis`, only `Cache`.

The difference is:
- `Cache` is used for cache purpose, only some methods provided, like `Get`, `Set`, `Del`, `Take` etc.
- `Redis` is for general redis access purpose

**Comment by qianxi0410** [comment]
Thx :D. The naming in the document caused me to ask an unnutritious question, my fault.
