### ISSUE TITLE
A question on using redis

### ISSUE THREAD

**Issue by langbin522** [zeromicro/go-zero#1101]
redis锁需要重新初始化
为什么不直接放Cache下呢。我看Cache也是用redis的。这样调用起来不更方便一些吗？
如果要用Cache和Redis锁的话要初始化两次连接。

**Comment by kevwan** [comment]
cache是cache, lock是lock
两者不是一个目的，不适合放一起

**Comment by langbin522** [comment]
> 
> 
> cache是cache, lock是lock 两者不是一个目的，不适合放一起

但是两者都是使用了REDIS的呢。而且两都都需要重新初始化连接，能否在启动的时候就配置好连接让REDIS直接连接即可。后面如果调用直接调用 就行了。而不是每次都再去配置连接信息了呢

**Comment by langbin522** [comment]
> 
> 
> cache是cache, lock是lock 两者不是一个目的，不适合放一起

还有请问一下，如何取redisconn的连接，框架内是否有取这个连接的方法呢？如果没有的话是需要自己维护这个连接了是吗

**Comment by kevwan** [comment]
> > cache是cache, lock是lock 两者不是一个目的，不适合放一起
> 
> 但是两者都是使用了REDIS的呢。而且两都都需要重新初始化连接，能否在启动的时候就配置好连接让REDIS直接连接即可。后面如果调用直接调用 就行了。而不是每次都再去配置连接信息了呢

不鼓励混用，不同功能的分开

**Comment by kevwan** [comment]
> > cache是cache, lock是lock 两者不是一个目的，不适合放一起
> 
> 还有请问一下，如何取redisconn的连接，框架内是否有取这个连接的方法呢？如果没有的话是需要自己维护这个连接了是吗

没有提供raw connection

**Comment by kevwan** [comment]
Close it for the moment, reopen if needed.
