### ISSUE TITLE
time.Time is not supported in .api files

### ISSUE THREAD

**Issue by kotlin2018** [zeromicro/go-zero#1126]
<img width="620" alt="截屏2021-10-12 下午4 39 51" src="https://user-images.githubusercontent.com/56008171/136923204-95e99c9c-303c-4ffe-b079-34a31a3a24d7.png">

**Comment by anqiansong** [comment]
> Is a awesome Idea If write the model of database table to api file.

In practice, the fields in model should be converted into logic, rather than use directly.
