### ISSUE TITLE
window下创建链接需要管理员权限才行

### ISSUE THREAD

**Issue by jan-bar** [zeromicro/go-zero#1136]
每次敲命令都会出现没权限的提示。
![image](https://user-images.githubusercontent.com/14202095/137421964-18971d6b-3312-4f4c-87c1-93b69f276318.png)

问题代码如下，每次执行命令都要创建一次链接。但是在window下这种创建方式是需要管理员权限的。所以需要管理员权限打开的cmd窗口才能创建成功。但是不想每次都用管理员权限打开cmd窗口。所以这里可以改成已经创建成功就不重复创建吧。
![image](https://user-images.githubusercontent.com/14202095/137422034-6977daae-787a-4e25-842a-3d1971822006.png)

**Comment by anqiansong** [comment]
有方法可以把 windows 的 admin 改掉的，这个要自行 google 一下。

**Comment by jan-bar** [comment]
> 有方法可以把 windows 的 admin 改掉的，这个要自行 google 一下。

但是为什么每次执行都需要创建一次链接呢？这样不合理吧。这个创建链接的问题我在几个别的开源库里面也遇到了，window用户太受伤了。

**Comment by anqiansong** [comment]
不会每次都创建的，只需要创建一次就好了

**Comment by kevwan** [comment]
fixed.
