### ISSUE TITLE
how to manage proto file

### ISSUE THREAD

**Issue by bmbbms** [zeromicro/go-zero#1144]
Actually,using goctl rpc command is a great way for generating  rpc service and client.but  in actal project , the rpc client and service is separated，the client in project A， the service in project B，do we need to generate all the rpc service and client in both
project by using goctl or  do you have other good idea?

**Comment by bmbbms** [comment]
ok，Thanks for your reply.

**Comment by Danny5487401** [comment]
> In practice，there are two ways to manage proto file:
> 
> 1. As you said,  you can create a module or a git repository to manage the proto and the code which generated by grpc, for another projects, like server and client, you can create another modules which implements the grpc interface.
> 2. To create a module or a git repository to manage all protos and grpc codes

But how to related to goctl rpc command in this situation
