### ISSUE TITLE
[Question]:对于model缓存的疑问

### ISSUE THREAD

**Issue by xhochipe** [zeromicro/go-zero#1164]
在model中有三个对缓存操作的api如下
```
func (cc CachedConn) DelCache(keys ...string) error {

}

func (cc CachedConn) GetCache(key string, v interface{}) error {

}

func (cc CachedConn) SetCache(key string, v interface{}) error {
}
```
但是,对于查询列表来说,有可能不同的条件,查询的列表数据就不一样,如果添加一个 redis 集合的api,这样可以比如把一个列表的key放到集合中,如果添加或者更新数据的话,就清理集合中的key所对应的列表key的缓存数据,比较方便，是否有比较更加优雅的处理办法

**Comment by xiaowei520** [comment]
缓存是针对单行记录的；如果你想缓存列表类查询，建议也可以将query_field当做 cache key。我觉得取决于设计使用问题。

**Comment by xiaowei520** [comment]
缓存是针对单行记录的；如果你想缓存列表类查询，建议也可以将query_field当做 cache key。我觉得取决于设计使用问题。

**Comment by wavechao** [comment]
> 在model中有三个对缓存操作的api如下
> 
> ```
> func (cc CachedConn) DelCache(keys ...string) error {
> 
> }
> 
> func (cc CachedConn) GetCache(key string, v interface{}) error {
> 
> }
> 
> func (cc CachedConn) SetCache(key string, v interface{}) error {
> }
> ```
> 
> 但是,对于查询列表来说,有可能不同的条件,查询的列表数据就不一样,如果添加一个 redis 集合的api,这样可以比如把一个列表的key放到集合中,如果添加或者更新数据的话,就清理集合中的key所对应的列表key的缓存数据,比较方便，是否有比较更加优雅的处理办法

为什么我生成的model代码没有这三个方法
