### ISSUE TITLE
goctl v1.2.2 生成的service package名称为小驼峰问题, 不能向下兼容v1.1.x

### ISSUE THREAD

**Issue by Paaaaaaaaaul** [zeromicro/go-zero#1171]
**Describe the bug**
.proto文件中service命名如果为大驼峰命名, goctl v1.2.2版本生成文件中service package名称为小驼峰. v1.1.x版本为全小写. 不能向下兼容导致现在每次生成后要手动修改包名. 期望为支持全小写

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   option go_package = "userrpc";

   service UserRpc {
    ...
   }
   ```

2. The error is

   ```
   package userRpcClient
   ```

**Expected behavior**
期望为全小写 userrpcclient

**Comment by anqiansong** [comment]
It has been solved on pr #1170
