### ISSUE TITLE
can use the local protoc-gen-go

### ISSUE THREAD

**Issue by szpnygo** [zeromicro/go-zero#1196]
goctl内置了protoc-gen-go，导致无法使用系统上的protoc-gen-go。有时候为了保持版本一直。应该提供选择，可以使用goctl内置的也可以使用自行安装的protoc-gen-go

**Comment by anqiansong** [comment]
出于大家安装 `protoc-gen-go` 的版本不同和维护方不同，往往会导致大家在生成 `grpc` 时遇到各种各样的问题，目前这种做法是为了把大家上手难的复杂度降到最低，对于你提的这种情况，目前 `protoc-gen-goctl` 是 fork `protoc-gen-go@v1.3.2` 版本的，基本不会改变版本，不知道这点影响你是否可接受，否则又要回到原来的就问题上了。
> For everyone to install `protoc-gen-go` different versions and different maintenance parties, often lead to a variety of problems encountered in the generation `grpc`, the current approach is to minimize the complexity of getting started, for you to mention this situation, the current `protoc-gen-goctl` is fork `protoc-gen-go@v1.3 .2` version, basically will not change the version, I do not know whether this impact is acceptable to you, otherwise you have to go back to the original on the problem.

**Comment by szpnygo** [comment]
> 出于大家安装 `protoc-gen-go` 的版本不同和维护方不同，往往会导致大家在生成 `grpc` 时遇到各种各样的问题，目前这种做法是为了把大家上手难的复杂度降到最低，对于你提的这种情况，目前 `protoc-gen-goctl` 是 fork `protoc-gen-go@v1.3.2` 版本的，基本不会改变版本，不知道这点影响你是否可接受，否则又要回到原来的就问题上了。
> 
> > For everyone to install `protoc-gen-go` different versions and different maintenance parties, often lead to a variety of problems encountered in the generation `grpc`, the current approach is to minimize the complexity of getting started, for you to mention this situation, the current `protoc-gen-goctl` is fork `protoc-gen-go@v1.3 .2` version, basically will not change the version, I do not know whether this impact is acceptable to you, otherwise you have to go back to the original on the problem.

为什么不适用一个较新的版本？这个版本一直不升级吗？v1.3.2已经很老了吧。在go-zero v1.1.9的时候不是已经升级了v1.4.0。这等于版本回退了。从1.3.2刚升级到1.4又退回了1.3.2。

这两个版本主要是生成的pb里生成的变量不同。

**Comment by szpnygo** [comment]
```golang
	if useGoctl {
		outFlag = " --goctl_out"
	}
```
可以加参数去配置吧。如果为了用户方便。可以把使用goctl作为默认有限配置。

**Comment by anqiansong** [comment]
> > 出于大家安装 `protoc-gen-go` 的版本不同和维护方不同，往往会导致大家在生成 `grpc` 时遇到各种各样的问题，目前这种做法是为了把大家上手难的复杂度降到最低，对于你提的这种情况，目前 `protoc-gen-goctl` 是 fork `protoc-gen-go@v1.3.2` 版本的，基本不会改变版本，不知道这点影响你是否可接受，否则又要回到原来的就问题上了。
> > > For everyone to install `protoc-gen-go` different versions and different maintenance parties, often lead to a variety of problems encountered in the generation `grpc`, the current approach is to minimize the complexity of getting started, for you to mention this situation, the current `protoc-gen-goctl` is fork `protoc-gen-go@v1.3 .2` version, basically will not change the version, I do not know whether this impact is acceptable to you, otherwise you have to go back to the original on the problem.
> 
> 为什么不适用一个较新的版本？这个版本一直不升级吗？v1.3.2已经很老了吧。在go-zero v1.1.9的时候不是已经升级了v1.4.0。这等于版本回退了。从1.3.2刚升级到1.4又退回了1.3.2。
> 
> 这两个版本主要是生成的pb里生成的变量不同。

`protoc-gen-go` 版本是掌握在用户手里的，我只是对新版本的一些 flag 提供了支持，我们一致建议使用 1.3.2 版本哈。

**Comment by anqiansong** [comment]
> 看了一下，我本地这样可以改的吧。 我把protoc-gen-goctl link回protoc-gen-go，我看了下bin目录下是protoc-gen-goctl link到了goctl

在不改变 goctl 逻辑的前提下，你这个是最好的解法
> That's a recommend way to solve this problem

**Comment by szpnygo** [comment]
这个现在只有用master分支才可以是吧。我看1.2.2里的代码和master不一样，1.2.2里是unlink后重新link，每次启动都会修改link

**Comment by anqiansong** [comment]
We have a new solution to solve the grpc code generation, for details please move to #1226

**Comment by kevwan** [comment]
closing, reopen if needed.
