### ISSUE TITLE
httpx.Parse returns 500 error if all arguments have defaults and no value submitted

### ISSUE THREAD

**Issue by Cwt-ting** [zeromicro/go-zero#1197]
**Describe the bug**
提交参数只有2个可选时，2个参数都不传的情况下 会报 httpx.Parse 500 解析错误
![ed0b8003850ea7ac1082aa417771a10](https://user-images.githubusercontent.com/45840580/139800022-2e4ae627-61f0-4b16-b57a-569dfe1b9d96.png)

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   	var req types.ApplyFriendsListReq
		if err := httpx.Parse(r, &req); err != nil {
			httpx.Error(w, err)
			return
		}
   ```

2. The error is

   ```
   
![1635836540(1)](https://user-images.githubusercontent.com/45840580/139800606-fa70972a-44da-4bad-abb9-a8450b98a0db.png)

   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by kevwan** [comment]
I cannot reproduce this issue, check the code here: https://github.com/kevwan/zero-issues/tree/main/1197

**Comment by Cwt-ting** [comment]
The problem  from the definition of error handling

![1635986263(1)](https://user-images.githubusercontent.com/45840580/140238049-48afef05-a04d-4c04-a629-b8135ec09268.png)
