### ISSUE TITLE
why token limit lua script key ttl = min((cap/rate)*2) ?

### ISSUE THREAD

**Issue by sado0823** [zeromicro/go-zero#1227]
core/limit/tokenlimit.go
thanks to ur framework, it helps a lot.  i found that there is a distributed  token limit tool in go-zero which use "redis" and "golang.org/x/time/rate"?
i got two questions for that:
```go
1) this distributed  token limit just use a single endpoint redis, with so many requests In an instant, can it hold that?
2) how can u find that magic number `2`, can it be others number ? even remove this ttl, just set new_tokens and now, can it work?
```
![image](https://user-images.githubusercontent.com/51654192/141301453-773cec88-52f0-4cac-84f3-9e5a32155fa8.png)

lookforward to ur answer :)

**Comment by kevwan** [comment]
Q1: if you have a service with like 5 APIs, it's recommend to use separated keys for different APIs. And different keys located in different redis instances.

Q2: give more time for more stability.

**Comment by sado0823** [comment]
got it :)
