### ISSUE TITLE
discov package:  etcd support to use TLS configuration  CertFile/KeyFile/TrustedCAFile 

### ISSUE THREAD

**Issue by sunshineing** [zeromicro/go-zero#1230]
discov package:  etcd support to use TLS configuration  CertFile/KeyFile/TrustedCAFile

**Comment by sunshineing** [comment]
discov package: etcd can config TLS config using CertFile/KeyFile/TrustedCAFile

**Comment by kevwan** [comment]
@sunshineing PTAL.
