### ISSUE TITLE
how to serve file downloading?

### ISSUE THREAD

**Issue by xiaopinghot** [zeromicro/go-zero#1234]
How can I serve file downloading with go-zero? Like the code below for beego:

```go
func (c *DownloadController) Download() {
	...
	c.Ctx.Output.Download(zipFilePath, "download.zip")	
}
```

**Comment by lonphy** [comment]
Usually,we just get the file's path and/or access token from the micro service, and use a regular service(eg. nginx) to download file.  Because transferring files will cost a lot of bandwidth between micro services.
