### ISSUE TITLE
doc text err

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1240]
https://go-zero.dev/cn/api-config.html#
errInfo：
有很多参数我们并没有于config对齐，
correctinfo：
有很多参数我们并没有【与】config对齐，

**Comment by kevwan** [comment]
说的稍微详细点哈

**Comment by jsonMark** [comment]
文档写错啦!
于 
改为
与
字

**Comment by anqiansong** [comment]
Done.

**Comment by kevwan** [comment]
fixed, closing.
