### ISSUE TITLE
go mod tidy error with version V1.2.3

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#1241]
Go Version 1.17.3
Go-Zero Version V1.2.3

1. The code is

   ```go
   https://github.com/zeromicro/zero-doc/blob/main/docs/zero/bookstore.md
   ```

2. The error is

when go mod tidy
   ```
   error while importing github.com/tal-tech/go-zero/core/stores/sqlx: missing go.sum entry for module providing package github.com/go-sql-driver/mysql (imported by github.com/tal-tech/go-zero/core/stores/sqlx); to add:
	go get github.com/tal-tech/go-zero/core/stores/sqlx@v1.2.3
   ```

**Comment by zfkun** [comment]
follow the tips, may be work
`go get github.com/tal-tech/go-zero/core/stores/sqlx@v1.2.3`

**Comment by anqiansong** [comment]
> follow the tips, may be work `go get github.com/tal-tech/go-zero/core/stores/sqlx@v1.2.3`

The correct  way to use go-zero is `go get github.com/tal-tech/go-zero@v1.2.3`, I used version @v1.2.3, the ha no problem 
 to execute `go mod tidy`

**Comment by kevwan** [comment]
> > follow the tips, may be work `go get github.com/tal-tech/go-zero/core/stores/sqlx@v1.2.3`
> 
> 
> 
> The correct  way to use go-zero is `go get github.com/tal-tech/go-zero@v1.2.3`, I used version @v1.2.3, the ha no problem 
> 
>  to execute `go mod tidy`

If you don't need the specific version, just use `go get github.com/tal-tech/go-zero`.
