### ISSUE TITLE
控制台能不能高亮显示日志，类似于spring boot那样

### ISSUE THREAD

**Issue by leafmirror** [zeromicro/go-zero#1249]
![image](https://user-images.githubusercontent.com/25813184/141979217-d51b2b6f-66e0-464f-b97a-063c140ed7c0.png)

**Comment by kevwan** [comment]
这个我倾向于不支持哈，框架保持简单点。

**Comment by leafmirror** [comment]
> 这个我倾向于不支持哈，框架保持简单点。

主要是日志看起来会清晰点

**Comment by kevwan** [comment]
这个功能我觉得不会加的哈，因为最终基本会通过ELK处理，而染色增加不必要的负担

**Comment by kevwan** [comment]
won't fix, closing.
