### ISSUE TITLE
How  can I use  Redis' streaming command like "XADD" in go-zero ?

### ISSUE THREAD

**Issue by JackMin1314** [zeromicro/go-zero#1258]
Hi, When I used in _redigo/redis_ like below:

```go
 conn.Do("XADD", "stream_name",...)
```

But I can't found the similar method in go-zero. 
So, is that go-zero  has other function which I unknown to solve the issue or not implemented yet?

**Comment by kevwan** [comment]
not implemented, would you please submit a PR?
