### ISSUE TITLE
api type block, embed struct  cann't use json tag

### ISSUE THREAD

**Issue by QCU266** [zeromicro/go-zero#1263]
**Describe the bug**
in api define type block, embed struct  cann't use json tag

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
    type (
    	TestField {
    		Key string `json:"key"`
    	}
    	TopField {
    		TestField    `json:",inline"`
    		TestA string    `json:"test_a"`
    		TestB string    `json:"test_b"`
    	}
    )
   ```

2. The error is

   ```
   test.api line 6:9  extraneous input '`json:",inline"`' expecting {'}', '*', ID}
   goctl: generation error: tag.api line 6:9  extraneous input '`json:",inline"`' expecting {'}', '*', ID}
   goctl version: 1.2.3 linux/amd64
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.3]
 - goctl version [e.g. 1.2.3, optional]

**More description**

**Comment by kevwan** [comment]
This kind of feature it not support by API syntax, please give a concrete name.

**Comment by QCU266** [comment]
In my case, i use mongodb and [mongo-go-driver](https://github.com/mongodb/mongo-go-driver). 

I want to define a base type that contain several fields, that will be used in other types by embed.

However, mongo-go-driver  [bson](https://docs.mongodb.com/drivers/go/current/fundamentals/bson/#struct-tags) use struct tag `inline` to embed struct. So, I need define a bson tag  for embed struct.

**Comment by anqiansong** [comment]
> In my case, i use mongodb and [mongo-go-driver](https://github.com/mongodb/mongo-go-driver).
> 
> I want to define a base type that contain several fields, that will be used in other types by embed.
> 
> However, mongo-go-driver [bson](https://docs.mongodb.com/drivers/go/current/fundamentals/bson/#struct-tags) use struct tag `inline` to embed struct. So, I need define a bson tag for embed struct.

As designed as go-zero, the api can not be used directly in model, you should define a model struct and convert it, the api only supported json struct tag and it must be ID syntax type.

**Comment by Yuelioi** [comment]
我在使用gorm, 我想嵌入Model字段, 也遇到了一样的问题, 当我外部需要Marshal时, 不得不把所有内容都重新写个自定义函数

```
type Category {
	Model `json:"-"` 
	CID   string `json:"cid"`
```
