### ISSUE TITLE
go mod  version1.2.3

### ISSUE THREAD

**Issue by liuyue1995** [zeromicro/go-zero#1265]
import (
	"database/sql"
	"fmt"
	"strings"

	"github.com/tal-tech/go-zero/core/stores/builderx"
	"github.com/tal-tech/go-zero/core/stores/sqlc"
	"github.com/tal-tech/go-zero/core/stores/sqlx"
	"github.com/tal-tech/go-zero/core/stringx"
)

error:
` finding module for package github.com/tal-tech/go-zero/core/stores/builderx`

**Comment by kevwan** [comment]
Duplicate of #1256
