### ISSUE TITLE
当服务关闭的时候，数据库是如何关闭连接的，没有找到具体代码

### ISSUE THREAD

**Issue by wuyazi** [zeromicro/go-zero#1273]
这里会创建 sql 连接
https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/sqlconn.go#L75
没找到哪里调用的 db.Close() 也就是下面这个方法
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L884

**Comment by kevwan** [comment]
https://pkg.go.dev/database/sql#Open

> The returned DB is safe for concurrent use by multiple goroutines and maintains its own pool of idle connections. Thus, the Open function should be called just once. It is rarely necessary to close a DB.

**Comment by kevwan** [comment]
answered, closing.
