### ISSUE TITLE
API: how to set global custom request parse

### ISSUE THREAD

**Issue by loktarjugg** [zeromicro/go-zero#1277]
I need to parse`form tag` or `json tag` based on `Headers Content-Type`

how should I do?

how to extend the request parse that comes with `go-zero`?
the reason for this demand is because I believe that the way of passing parameters on the caller should not be limited.
we should parse the request parameters in accordance with the `Content-Type` passed by the caller

如何扩展 `go-zero` 自带的 request Parse 呢？ 
之所以有这个需求，是因为我认为不应该局限调用端的传参方式。
我们应该按照调用端传递的 `Content-Type` 去解析请求参数

refs
#1109 #161

**Comment by kevwan** [comment]
Write your own parse function and use it in templates.

**Comment by loktarjugg** [comment]
thanks for your reply, the problem is solved
