### ISSUE TITLE
goctl rpc proto -src transform.proto -dir . 执行报错

### ISSUE THREAD

**Issue by 9kill** [zeromicro/go-zero#1284]
上述执行执行后，下面是报错信息：

protoc  --proto_path=/Users/sunny/git/shorturl/api/rpc/transform transform.proto --go_out=plugins=grpc:/Users/sunny/git/shorturl/api/rpc/transform/transform --go_opt=Mtransform.proto=.
goctl: generation error: sh: /usr/local/bin/protoc: cannot execute binary file
goctl version: 1.2.3-cli darwin/amd64

**Comment by kevwan** [comment]
确保protoc可用哈，提示蛮明显的
