### ISSUE TITLE
goctl 几点问题

### ISSUE THREAD

**Issue by JeffreyBool** [zeromicro/go-zero#1285]
第一，types  能分多个文件吗？如果是一个文件，后续需要做处理不方便维护，虽然目前是不允许编辑的
第二，生成的方法能按照某个结构体生成方法吗？一个方法生成一个文件，到时候文件会非常多，不方便维护

**Comment by kevwan** [comment]
1，暂无计划支持，一个服务的type不会非常多的
2，有goctl-go-compact插件
