### ISSUE TITLE
最新goctl[1.2.4]生成的api文档中返回数据格式问题

### ISSUE THREAD

**Issue by xhochipe** [zeromicro/go-zero#1293]
如题:
   之前的版本都是(*types.OkResp, error)，最新版本改成了这样 (resp  *types.OkResp, err error)，然后会让新手踩到坑,假如这个resp里面嵌套一些字段,有可能会直接拿来用resp这个变量，没有初始化，在赋值的话,直接panic

**Comment by kevwan** [comment]
这个有啥区别？老的如果err != nil，返回的resp也会是nil的
