### ISSUE TITLE
goctl 生成的 main 函数所在的文件 怎么命名为 main.go ？

### ISSUE THREAD

**Issue by xybingbing** [zeromicro/go-zero#1295]
goctl 生成的 main 函数所在的文件 怎么命名为 main.go ？手动修改成main.go  重新执行 goctl 更新 proto 文件 就会以 proto 的文件名 生产一个 main 函数的入口文件。

**Comment by kevwan** [comment]
为什么总要叫main.go呢？

**Comment by xybingbing** [comment]
看到 main.go 这个文件就知道这个是 程序的入口。 方便定位main函数所在的文件。
