### ISSUE TITLE
how can i fixed goctl install issue?

### ISSUE THREAD

**Issue by stiffer831** [zeromicro/go-zero#1297]
![image](https://user-images.githubusercontent.com/23020938/144713153-7f2aac14-c148-480e-a8c5-1d6d9f29422d.png)

**Comment by kevwan** [comment]
what command did you use?

**Comment by Nuokaqiao** [comment]
me too .
maybe you should rm github.com/zeromicro.and Re execute the command   GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl@cli
or   GOPROXY=https://goproxy.cn/,direct go install github.com/tal-tech/go-zero/tools/goctl@cli
it work for me 

我也遇到了，我是先下载的github.com/zeromicro代码 ，出现这个问题，我删了仓库，再执行就好了

**Comment by kevwan** [comment]
```shell
# Go 1.15 及之前版本
GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl@cli

# Go 1.16 及以后版本
GOPROXY=https://goproxy.cn/,direct go install github.com/tal-tech/go-zero/tools/goctl@cli
```

**Comment by stiffer831** [comment]
Fixed!
