### ISSUE TITLE
Generate file via IDEA plugin can not generate all files with one click 

### ISSUE THREAD

**Issue by waltcow** [zeromicro/go-zero#1301]
**Describe the bug**

In Goland IDE ,  when I change `*.api.` or `*.proto`and regenerate file via go-zero plugin, it cannot generate all file in one time, but after one/two more trigger, all files generated as expected

**Environments (please complete the following information):**

## Goland Version
GoLand 2021.2.1
Build #GO-212.5080.40, built on August 19, 2021
Licensed to GoLand Evaluator
Expiration date: January 5, 2022
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: suggest.all.run.configurations.from.context=true, ide.completion.variant.limit=500
Non-Bundled Plugins:  cn.xiaoheiban.go-zero (0.7.18), github.cweijan.test-theme (1.6), com.markskelton.one-dark-theme (5.4.0), com.mallowigi (50.2.0), org.jetbrains.plugins.vue (212.5080.39), idea.plugin.protoeditor (212.5080.8)

**Comment by anqiansong** [comment]
@waltcow Thank you for your feedback, if the idea plugin generates api and grpc code without error event log, it means it is generated successfully, if the idea's file refresh mechanism is slow, in this case, you can right click to load by `Reload from Disk`
