### ISSUE TITLE
How to change the timeout param to deal with error context deadline exceeded

### ISSUE THREAD

**Issue by leafney** [zeromicro/go-zero#1326]
For some business methods that take a long time, `rpc` processing takes longer than the default `2s` and returns a `context deadline exceeded` error. When I tried to extend the timeout period by modifying the `Timeout` parameter, I found that it did not take effect.

For example, I use `time.sleep(5)` in rpc to simulate a long time-consuming business method. I want to set the `Timeout` parameter  to `10s` in the yaml config. There will not discuss whether the business time-consuming of `10s` is reasonable.

Test 1

Only modify the `Timeout` in the `api` or `rpc` , the default `2s` timeout will be executed, and then the error `context deadline exceeded` will be return.

Test 2

Set the `Timeout` parameter in `api` and `rpc` at the same time, you will found that after the `3s` timeout, and error `context deadline exceeded`.  I found that the default value set in `zrpc/internal/client.go` in the source code is `dialTimeout = time.Second * 3`  https://github.com/zeromicro/go-zero/blob/9d528dddd620c6d5a32cb8eed38edd710093ece4/zrpc/internal/client.go#L18

Test 3

Set the `Timeout` parameter in `api` and `rpc` at the same time, and then set  `rest.WithTimeout(time.Second*10)`  in `handler/Routes.go` in `api` , you will found that it returns success.

But the file `handler/Routes.go` will be overwritten every time when the `api` template is regenerated, because this file is `// Code generated by goctl. DO NOT EDIT.`

So, what is the correct configuration method of `Timeout`?

- go-zero version [v1.2.4]
- goctl version [v1.2.4]

**Comment by kevwan** [comment]
I don't really get the problem.

`Timeout` is in config file, it will not be overwritten.

And `Timeout` does work to control the timeout, so what's the problem?

**Comment by leafney** [comment]
Okay, I know. I will try again.

**Comment by leafney** [comment]
I seem to figure it out.

**Comment by stepbystep2** [comment]
> I seem to figure it out.

I have the same problem. So, what is the correct configuration method of `Timeout`? Thanks.

**Comment by kevwan** [comment]
> > I seem to figure it out.
> 
> I have the same problem. So, what is the correct configuration method of `Timeout`? Thanks.

Don't forget to change both client and server sides.

**Comment by stepbystep2** [comment]
> > > I seem to figure it out.
> > 
> > 
> > I have the same problem. So, what is the correct configuration method of `Timeout`? Thanks.
> 
> Don't forget to change both client and server sides.

So, both `rest.RestConf.Timeout`、`zrpc.RpcClientConf.Timeout` and `zrpc.RpcServerConf.Timeout` should be changed, right?
