### ISSUE TITLE
goctl template  --home 指定自定义模板目录不生效

### ISSUE THREAD

**Issue by leafney** [zeromicro/go-zero#1330]
我还是用中文描述吧！

**Describe the bug**

goctl release v1.2.4 使用 --home 指定自定义模板目录不生效
版本：
```
➜ goctl --version
goctl version 1.2.3-cli darwin/amd64
```

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   ➜ goctl api go -api="test.api" -dir="api" -style GoZero --home ./template/1.2.3-cli
   ```

2. The error is

我修改了默认模板中 api 的 handler 和 logic 模板  `api/handler.tpl` 和 `api/logic.tpl` ，通过上面的命令生成后发现还是使用的默认自带的模板。
更具体一点，我是参照 https://go-zero.dev/cn/template.html 这个例子，更改了 handler 中的返回格式 将 `httpx.OkJson(w, body)` 改成了 `reponse.Response(w, resp, err)`  这种。

开始我以为是目录的问题，然后我就放到了 `~/.goctl` 下面，测试发现还是不生效。

后来我又换回了之前使用的 goctl v1.2.1 , 发现这个是生效的。所以怀疑是 v1.2.4 有问题。

**Expected behavior**

**Environments (please complete the following information):**
 - OS: [macbook 11.4]
 - go-zero version [1.2.4]
 - goctl version [1.2.4]

**More description**

**Comment by 1278651995** [comment]
so do I

**Comment by anqiansong** [comment]
感谢反馈，这个问题已经发现了，目前我们已经在讨论这个解决方案，目前的解决方案是在通过 `--home` 指定的目录下需要创建一个与 `goctl` 版本号的目录来存放你的模板，这样 `--home`才能生效，如你的 goctl 版本为 1.2.3, 你的自定模板版本应该在 `path/to/custom/1.2.3/templates`, 那么 `--home` 指定的值应该为 `path/to/custom`

**Comment by leafney** [comment]
突然有一个想法，是否可以根据goctl的当前版本来自动判断加载哪个目录。或者是，将版本作为一个参数传入。
当然，不清楚你们这样设计的目的是为什么解决什么问题。只是觉得对于开发者来说，在使用上还是越简单越好，可能设计就会比较复杂一些。
谢谢！

**Comment by pengmingfong** [comment]
这个问题在哪个版本解决掉了呀？我go-zero 1.6.3 版本还是有这个问题

**Comment by pengmingfong** [comment]
@kesonan 这个问题在哪个版本解决掉了呀？我go-zero 1.6.3 版本还是有这个问题
