### ISSUE TITLE
【goctl】goctl rpc proto not create xxxclient file when go_package is same as parent folder name

### ISSUE THREAD

**Issue by xiang-xx** [zeromicro/go-zero#1340]
**Describe the bug**
When i use `goctl rpc proto --src mini.proto --dir .` to create project, the command will not create xxxclient folder if proto file has a option `go_package` which same as parent folder name。

**To Reproduce**
```sh
mkdir mini && cd mini
vi mini.proto
```

mini.proto
```
syntax = "proto3";

package mini;

option go_package="mini";

message Request {
  string ping = 1;
}

message Response {
  string pong = 1;
}

service TestService {
  rpc Ping(Request) returns(Response);
}
```

tree .

```
.
├── etc
│   └── mini.yaml
├── internal
│   ├── config
│   │   └── config.go
│   ├── logic
│   │   └── pinglogic.go
│   ├── server
│   │   └── testserviceserver.go
│   └── svc
│       └── servicecontext.go
├── mini
│   └── mini.pb.go
├── mini.go
├── mini.proto
└── testservice
    └── testservice.go
```

**Expected behavior**
will create xxxclient file（if i do not change parent fold name or package name）

**Environments (please complete the following information):**
 - ubuntu 20
 - goctl version 1.2.4-cli linux/amd64

**Comment by anqiansong** [comment]
for details please see https://go-zero.dev/en/goctl-rpc.html

**Comment by kevwan** [comment]
Answered, closing.
