### ISSUE TITLE
A Big Mistake In Reference When I Started Order Api

### ISSUE THREAD

**Issue by CBJerry993** [zeromicro/go-zero#1342]
When I type ```go run order.go -f etc/order.yaml``` at the terminal accoding to your [Reference](https://go-zero.dev/cn/micro-service.html) , it raise an error : ```config file etc/order.yaml, field UserRpc.Etcd.Key is not set.```

Throughing my unremitting efforts, i found that you miss a **blank** at the last column.

```
Name: order
Host: 0.0.0.0
Port: 8888
UserRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: user.rpc
```

**Comment by kevwan** [comment]
you mean missed a blank line at the end?

**Comment by lfny2580832** [comment]
I had the exact same problem

**Comment by lfny2580832** [comment]
Yes,the 'key' and 'host' under 'Etcd' are not aligned

**Comment by kevwan** [comment]
Fixed, closing.
