### ISSUE TITLE
demo Question

### ISSUE THREAD

**Issue by yann-y** [zeromicro/go-zero#1344]
windows11   go version 1.7.5
go run rpc 
# k8s.io/klog/v2
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:702:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:721:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:739:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:760:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:779:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:791:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:915:9: invalid operation: log != nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:1277:18: invalid operation: logging.logr == nil (mismatched types logr.Logger and nil)
..\..\..\..\pkg\mod\k8s.io\klog\v2@v2.4.0\klog.go:1278:21: cannot use nil as type logr.Logger in field value

**Comment by kevwan** [comment]
Does it related to go-zero?

**Comment by zhuoquany** [comment]
service\user\rpc> go mod why  k8s.io/klog/v2
# k8s.io/klog/v2
ipfsdisk/service/user/rpc
github.com/tal-tech/go-zero/zrpc
github.com/tal-tech/go-zero/zrpc/resolver
github.com/tal-tech/go-zero/zrpc/resolver/internal
k8s.io/client-go/rest
k8s.io/klog/v2


Problem with zrpc dependency

**Comment by zhuoquany** [comment]
> 它与归零有关吗？

service\user\rpc> go mod why k8s.io/klog/v2

k8s.io/klog/v2
ipfsdisk/service/user/rpc
github.com/tal-tech/go-zero/zrpc
github.com/tal-tech/go-zero/zrpc/resolver
github.com/tal-tech/go-zero/zrpc/resolver/internal
k8s.io/client-go/rest
k8s.io/klog/v2

Problem with zrpc dependency

**Comment by kevwan** [comment]
I've updated zero-examples, update to the latest k8s.io/klog/v2 works well.

**Comment by kevwan** [comment]
fixed.
