### ISSUE TITLE
goctl create delete function missing type

### ISSUE THREAD

**Issue by will0523** [zeromicro/go-zero#1363]
**Describe the bug**
I edit template file interface-delete.tpl in .goctl folder:
Delete(data *{{.upperStartCamelObject}}) error

when I execute command:
goctl model mysql xxx
the type is missing in delete  function:
Delete(data *\<no value\>) error

**Environments (please complete the following information):**
 - OS: win10
 - go-zero version [1.2.4]
 - goctl version [1.2.4]

**Comment by anqiansong** [comment]
Thank you very much for your feedback. In `Goctl`, modifying the template can only modify the content of non-variables. Otherwise, just like this issue, the parameters may be lost.

**Comment by kevwan** [comment]
Answered, closing.
