### ISSUE TITLE
mysql transactions cannot cross tables

### ISSUE THREAD

**Issue by guanguoyintao** [zeromicro/go-zero#1374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imlandidzu** [comment]
mysql 的事务go zero框架不支持跨表事务，或者说写起来不优雅，得绑定一个表，而跨表事务往往不需要绑定一张表

**Comment by yedf2** [comment]
@imlandidzu go-zero与分布式事务框架dtm进行了合作，提供了一站式分布式事务解决方案，详情参考go-zero文档：
https://go-zero.dev/cn/distributed-transaction.html

**Comment by imlandidzu** [comment]
@yedf2 那同库跨表级别的mysql事务后续还是要绑一张表上面吗，现在我的事务都是在model文件夹下面再做一个库级别的model文件，生成的mysql model文件事务并不好用，我需要单独做一个和表没有关系的model文件来存放我的事务操作
