### ISSUE TITLE
How to use other database in go-zero ?

### ISSUE THREAD

**Issue by CaiBaoHong** [zeromicro/go-zero#1379]
I am considering use go-zero to write an iot application, this application will use TDEngine [Go Driver](https://www.taosdata.com/cn/documentation/connector#go) to storage timeseries data。

I finish reading go-zero doucment, but can't find out how to use other database in go-zero. 

Is go-zero can only use MySQL?

Please help， Thanks！

**Comment by kevwan** [comment]
You can use any database which compatible with `database/sql`.

Check the code in `core/stores/postgres` for PostgreSQL.
