### ISSUE TITLE
How can i add middleware to a concrete handler not in @service layer

### ISSUE THREAD

**Issue by wyaow** [zeromicro/go-zero#1395]
How can i add middleware to a concrete handler not in @service layer?
Here, i has 3 handlers in same group 1 with one global middleware GlobalMiddleware
@service(
  group: group1
  middleware: GlobalMiddleware
)
@doc  “some doc”
@handler AHandler
/group1/a
...
/group1/b
...
/group1/c

All things goes well for few days, But, now, I want to add another middleware for /b,  and another middleware for /c.
You may advice me to divide /a, /b, /c into different group, but I think they should be together since them do same business.

Is there a better way for me to make it?

**Comment by kevwan** [comment]
> How can i add middleware to a concrete handler not in @service layer? Here, i has 3 handlers in same group 1 with one global middleware GlobalMiddleware @service( group: group1 middleware: GlobalMiddleware ) @doc “some doc” @handler AHandler /group1/a ... /group1/b ... /group1/c
> 
> All things goes well for few days, But, now, I want to add another middleware for /b, and another middleware for /c. You may advice me to divide /a, /b, /c into different group, but I think they should be together since them do same business.
> 
> Is there a better way for me to make it?

I think putting them in different groups is simple enough.
