### ISSUE TITLE
How to get path variables from the requests?

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#1400]
比如，路由配置了path variables， 比如/api/:name
r.Request.URL是 /api/joy

可以通过pathvar.Vars(r) 拿到path 参数，怎么在拿到这个url的源路径/api/:name

**Comment by kevwan** [comment]
你可以用闭包在注册路由时传进去

**Comment by chowyu12** [comment]
能给一个教程吗

**Comment by chowyu12** [comment]
建议开放出来一个api ，类似pathvar.Vars(r)，能返回原始api定义，方便做路由的metric

**Comment by chowyu12** [comment]
https://github.com/zeromicro/go-zero/pull/1412
