### ISSUE TITLE
实体的struct 字段都没有tag

### ISSUE THREAD

**Issue by lovemianhuatang** [zeromicro/go-zero#1420]
goctl version 1.2.5 darwin/arm64 
生成的model，实体的struct 字段都没有tag

**Comment by SpectatorNan** [comment]
是 postgres 吗

**Comment by jsonMark** [comment]
应该是版本问题，建议你把api啥的给一份，让其他人重新生成一下，排查一下问题

**Comment by anqiansong** [comment]
Sloved by on release https://github.com/zeromicro/go-zero/releases/tag/tools%2Fgoctl%2Fv1.2.6
