### ISSUE TITLE
By using the model, if you modify the database again, the operation is troublesome!

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1422]
我们在业务开发中，当涉及新增字段或者删除字段过程中，如果当前model有自己新增的方法，还需要自己手动复制粘贴自己type定义的相关方法。这个有解决方案吗？

**Comment by chenquan** [comment]
@anqiansong 或许可以把自动生成的interface和人为手动定义添加的拆开，然后嵌入到一个主体interface中

**Comment by jsonMark** [comment]
我试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kevin ***@***.***&gt;; 
发送时间: 2022年1月8日(星期六) 晚上9:23
收件人: ***@***.***&gt;; 
抄送: "水 煮 沉 浮 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zeromicro/go-zero] 使用model过程中，如果重复修改数据库，操作很麻烦！ (Issue #1422)





 
@anqiansong 或许可以把自动生成的interface和人为手动定义添加的拆开，然后嵌入到一个主体interface中
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jsonMark** [comment]
> @anqiansong 或许可以把自动生成的interface和人为手动定义添加的拆开，然后嵌入到一个主体interface中 列如：
> 
> ```go
> // UserModel 主体
> type UserModel interface{
>   UserBuildModel
>   UserCusModel
> }
> // UserBuildModel 自动生成
> type UserBuildModel interface{
> 
> }
> // UserCusModel 自定义
> type UserCusModel interface{
> 
> }
> ```

你这个方法解决了更新模型不需要备份，复制黏贴的问题，还有更新字段后插入的sql需要手动更新这个问题没解决，其次插入和更新对应的数据data需要手动改，针对这个新问题，我的建议是将吗，model的如下
query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, companyRowsExpectAutoSet)
代码在模板中设置成const变量，其他地方自己直接调用即可，这样可以解决一部分需求问题
