### ISSUE TITLE
Is there a health check mechanism for ectd service registry?

### ISSUE THREAD

**Issue by safejob** [zeromicro/go-zero#1427]
服务注册发现使用的是etcd，那么有两个地方我比较关心：

1，注册的时间，是先注册再启动的服务，还是先服务就绪了才注册的呢，如果服务还没有就绪，就注册上去了，那流量就会打到这个还没有就绪的服务上，必然在一个极短的时间里，打过来的请求是有问题的；

2，服务在运行过程中，如果挂了或者异常，有没有一个健康检查机制，可以自动从etcd上临时下线这个异常节点，此时实际上服务不可用，但服务发现还在，流量仍然会路由到这个节点上

go-zero是一个非常优秀的框架，自己准备使用，但上面两点还不是太清楚，烦请大佬指点一下 不胜感激

**Comment by kevwan** [comment]
问题很好！

1. 现在的实现是

```go
func (ags keepAliveServer) Start(fn RegisterFn) error {
	if err := ags.registerEtcd(); err != nil {
		return err
	}

	return ags.Server.Start(fn)
}
```

这里其实不会有问题，本地端口侦听是个很快的动作，注册到etcd，是一个网络io，然后客户端还得被通知到才会开始有流量过来，不过你希望先侦听再注册需要grpc支持启动后回调，否则很难知道什么时候启动完成了。

2. 现在有续期超时控制，并且kill下线会先revoke才会退出。

**Comment by safejob** [comment]
好的 谢谢  以前接触得比较多的是java的应用 启动慢 动不动还会fullgc 所以遇到这类问题稍多些  go应该还好 还有自适应降载 也不大会被打挂
