### ISSUE TITLE
Suggestion: Make the root package and project name common template variables that can be referenced by all templates

### ISSUE THREAD

**Issue by greper** [zeromicro/go-zero#1429]
![image](https://user-images.githubusercontent.com/1687298/148684803-a80ab11e-bfe7-467b-a33e-9578cce81822.png)

在自定义模版时，模版变量太少，导致必须在每个api项目里面定义一套自定义模版才能保证自动生成代码正常。
建议将包名和项目名做成公共的模版变量，让所有模版都能够引用。这样就只需要在项目根路径下配置一套模版即可。

另外在rpc生成userclient/user.go和user_server.go，缺少一个import的别名，否则会报错，需要加的user 在{{.imports}}中间,加模版变量好像也没法解决
![image](https://user-images.githubusercontent.com/1687298/148685025-b95b831f-af21-41c9-b9be-884d368ecfc0.png)

call.tpl 可以通过加name变量解决，但是server.tpl 没办法
![image](https://user-images.githubusercontent.com/1687298/148685191-debadb64-ce9c-4c2f-b91f-f4d332cf0091.png)

**Comment by anqiansong** [comment]
import 别名为 user 这个和不起别名是一样的哈，报错可能是其他原因，比如你的 mod 没有 tidy，这个不应该是 package 问题

**Comment by greper** [comment]
关于api模版里面，包名和项目名做成公共的模版变量，我觉得还是有点必要的

![](https://user-images.githubusercontent.com/1687298/148684803-a80ab11e-bfe7-467b-a33e-9578cce81822.png)
