### ISSUE TITLE
Logs are not merged with error files after setting `Compress: true`

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1438]
# Log configuration
Log:
ServiceName: api #Log name
Mode: file #Logging mode console|file|volume
TimeFormat: 2006-01-02T15:04:05.000Z07 #time format
Path: logs/api #path to log file, root directory of gomod
Level: info #Error level before writing info|error|severe
Compress: true #Whether to merge log files
KeepDays: 15 #the number of days to keep the logs
StackCooldownMillis: 100 #1436

After configuration
error.log and access.log
are not merged

**Comment by kevwan** [comment]
`access.log` and `error.log` will not be merged together (into one file).
