### ISSUE TITLE
11

### ISSUE THREAD

**Issue by kotlin2018** [zeromicro/go-zero#1439]

**Comment by kotlin2018** [comment]
<img width="603" alt="截屏2022-01-12 下午1 46 45" src="https://user-images.githubusercontent.com/56008171/149070983-c13b2cd7-da8f-43b2-bc37-be498f5cbdf8.png">
代码改成这样还是不行

**Comment by kevwan** [comment]
what's this?

**Comment by kevwan** [comment]
created the issue by mistake? closing.
