### ISSUE TITLE
could go-zero use consul to replace etcd? 

### ISSUE THREAD

**Issue by lxxwilliam** [zeromicro/go-zero#1442]
if he can , how to do? pls

**Comment by kevwan** [comment]
Yes, check it here: https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/consul

**Comment by lxxwilliam** [comment]
![image](https://user-images.githubusercontent.com/30308455/149313758-d80da0e3-e7aa-44b7-9c61-b49b4b13a544.png)
there is some bugs about the dependent packages, how to handle them? pls

**Comment by kevwan** [comment]
Upgrade klog package to the latest version.

**Comment by lxxwilliam** [comment]
thanks!

**Comment by kevwan** [comment]
Closing.
