### ISSUE TITLE
Question on the zero values of the request parameters.

### ISSUE THREAD

**Issue by titherman** [zeromicro/go-zero#1448]
gin在请求参数是零值的时候，如果我的字段类型是int64，但前端给的是”“(string空字符串)，它会自动帮我转换类型，但go-zero不会。我想知道我该怎么解决这个问题。只能修改httpx.Parse()方法么？ 有什么更好的办法么？

**Comment by kevwan** [comment]
Use optional.

**Comment by titherman** [comment]
> 使用可选。

I try to use optional ,but it is useless . go-zero version is v1.2.4. Is it an error because the version is not recent?

**Comment by kevwan** [comment]
Please show your code.

**Comment by titherman** [comment]
例如： 我的req为
xxxReq{
  Sys string `json:"sys,optional"` // 系统
  MenuId int64 `json:"menu_id,optional"`
}。 
我已经写了optional，对于 MenuId的类型为数字类型，但如果前端传“”（仅对于零值。不包括“3” 这种）。go-zero没有去把字符串零值转化成数字的零值。

**Comment by titherman** [comment]
> Please show your code.

例如： 我的req为
xxxReq{
Sys string json:"sys,optional" // 系统
MenuId int64 json:"menu_id,optional"
}。
我已经写了optional，对于 MenuId的类型为数字类型，但如果前端传“”（仅对于零值。不包括“3” 这种）。go-zero没有去把字符串零值转化成数字的零值。
