### ISSUE TITLE
stores/builderx package cannot be imported in the generated files by goctl.

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1450]
这个包无法加载
github.com/tal-tech/go-zero/core/stores/builderx

报错内容:

github.com/tal-tech/go-zero/core/stores/builderx: module github.com/tal-tech/go-zero@latest found (v1.2.5), but does not contain package github.com/tal-tech/go-zero/core/stores
/builderx

**Comment by kevwan** [comment]
去掉最后的x

**Comment by jsonMark** [comment]
建议新版本goctl工具统一换到这个仓库，命令行生成的代码最好别有问题。这样对初学者打击有点大

**Comment by kevwan** [comment]
你版本升级一下，这个问题早就修好了哈

**Comment by kevwan** [comment]
fixed, closing.
