### ISSUE TITLE
How to get http code from middleware?

### ISSUE THREAD

**Issue by mxyue** [zeromicro/go-zero#1459]
`rest/handler/loghandler.go`中的LogHandler定义了code，中间件无法获取 code。没法根据不同的status做处理

**Comment by mxyue** [comment]
或者可以给个方法 `rest/engine.go`
``` go
func (ng *engine) getLogHandler() func(http.Handler) http.Handler {}
```
可以重写上面函数返回的handler

**Comment by kevwan** [comment]
可以的，你可以看loghandler.go
