### ISSUE TITLE
A question about the project structure of go-zero

### ISSUE THREAD

**Issue by lxxwilliam** [zeromicro/go-zero#1466]
As we know,a module in go-zero just like "user"  have two services :api and rpc.
But, when we build a java micro-service project like "user" too,  there is just one service named "user" and the api or rpc functions alse in it.
how to understand the go-zero`s project structure and could not  we use one service to build a go-zero module just like java?

**Comment by anqiansong** [comment]
I think the essence of this question is actually asking what is microservice and what is rpc
