### ISSUE TITLE
rest.WithCors("*") and token verify the execution order.

### ISSUE THREAD

**Issue by cfscn** [zeromicro/go-zero#1472]
**Describe the bug**
Start JWT authentication, and use ajax to request without token, or when the token has expired. The framework will report CORS error.
If the Ajax request carries a valid token, there is no cros problem.
Use rest.WithCors("*") setting cros issues remains the same

**To Reproduce**
1. API starts JWT verification
2. Ajax requests the API with invalid token or without token
3. Cross domain error reported by the framework
4. Ajax carries a valid token
5. API returns to normal

1. The code is

   ```go
   	ctx := svc.NewServiceContext(c)
	server := rest.MustNewServer(c.RestConf,
		//Cros is set here. Token is invalid and does not take effect
		rest.WithCors("*"),
		rest.WithUnauthorizedCallback(func(w http.ResponseWriter, r *http.Request, err error) {
			//Cros settings take effect here
			origin := "*"
			header := w.Header()
			header.Set(allowOrigin, origin)
			header.Set(allowMethods, methods)
			header.Set(allowHeaders, allowHeadersVal)
			header.Set(exposeHeaders, exposeHeadersVal)
			if origin != allOrigins {
				header.Set(allowCredentials, allowTrue)
			}
			header.Set(maxAgeHeader, maxAgeHeaderVal)
			httpx.OkJson(w, nil)
		}))
	defer server.Stop()
   ```

2. The error is

   ```
   Browser reports CORS error
   ```

**Expected behavior**
It is hoped that cross domain settings can still be set when token is invalid No error is reported

**Screenshots**
nothing

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.4]
 - goctl version [e.g. 1.2.1, optional]

**More description**
After testing, the cros settings in rest.WithUnauthorizedCallback() are restored to normal.
The guess is that token authentication and cros settings are executed in the wrong order.

Happy New Year!

**Comment by kevwan** [comment]
Let's discuss this for details on wechat or slack?
