### ISSUE TITLE
Can errors such as parameter verification be normalized 

### ISSUE THREAD

**Issue by greper** [zeromicro/go-zero#1474]
Can errors such as parameter verification be normalized ,Use errors.Is or error.(type)  to determine the type of error

![image](https://user-images.githubusercontent.com/1687298/150461257-da6245ea-ec47-47ca-9472-2a9e00891c0c.png)

![image](https://user-images.githubusercontent.com/1687298/150461359-31bb2ffa-18d2-4ed2-a786-82d319156dbc.png)

**Comment by JeffreyBool** [comment]
@kevwan 考虑自定义错误类型，类似 `go-kratos.` 和 `go-micro` 的错误处理，服务之间传递错误使用 grpc.Status, 到服务了转换为 服务自己的 错误类型，自定义的错误类型实现 Is 方法就可使用 标准库的 errors.Is  方法
