### ISSUE TITLE
exec: "xdg-open": executable file not found in $PATH

### ISSUE THREAD

**Issue by ceoco** [zeromicro/go-zero#1506]
### What version of Goctl are you using (<code>goctl --version</code>)?

<pre>
$ goctl --version
1.3.0-20220201
</pre>

### What operating system and processor architecture are you using ?
<pre>
GOCTL_VERSION = "1.3.0-20220201"
GO_VERSION = "go1.17.6"
OS = "linux"
ARCH = "amd64"
</pre>

**Comment by ceoco** [comment]
goctl: generation error: exec: "protoc": executable file not found in $PATH

**Comment by anqiansong** [comment]
Installs the `protoc` into path to solve this issue, for details please see https://github.com/protocolbuffers/protobuf/releases
