### ISSUE TITLE
Is go-zero support etcd v3 server with user/password required?

### ISSUE THREAD

**Issue by VogueSogetsu** [zeromicro/go-zero#1508]
I want to config my go-zero rpc service to use etcd with user/password required, any probability? how?

**Comment by kevwan** [comment]
Yes.

**Comment by VogueSogetsu** [comment]
> Yes.

How to do that?thx

**Comment by kevwan** [comment]
Check out EtcdConf.

**Comment by VogueSogetsu** [comment]
> 

type EtcdConf struct {
	Hosts []string
	Key   string
}
mean this? Don't see any user/pwd field?

**Comment by kevwan** [comment]
Upgrade to the latest version.

**Comment by VogueSogetsu** [comment]
> Upgrade to the latest version.

Ok, I upgrade from 1.18 to 1.30 and found the user&pass fileds, thank.
Now I would like to know: Should I regenerate the rpc/api files due to this upgrade? (Note that I have fix all errors after upgrade to 1.30)

**Comment by kevwan** [comment]
No, you don't need.

Just use goctl migrate --verbose --version v1.3.0 to migrate.
