### ISSUE TITLE
go mod tidy error:module declares its path as: github.com/zeromicro/go-zero but was required as: github.com/tal-tech/go-zero

### ISSUE THREAD

**Issue by Apa7-zero** [zeromicro/go-zero#1515]
Follow the steps on the official website,When creating a new service,run "go mod tidy"Tips：
```
go: go-zero-test1/test1 imports
        github.com/tal-tech/go-zero/core/conf: github.com/tal-tech/go-zero@v1.3.0: parsing go.mod:
        module declares its path as: github.com/zeromicro/go-zero
                but was required as: github.com/tal-tech/go-zero
```

github.com/tal-tech/go-zero/core/conf/config.go Code of

```
import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path"
	"github.com/zeromicro/go-zero/core/mapping"
)
```

Change the model so that it can run

```
module go-zero
go 1.16
require github.com/tal-tech/go-zero v1.1.4
```

--------------------------------------------------------------------------------------------------------
我英语实在不好，基本都是机翻译用汉语再说一下

按照官网的步骤新建一个单体服务运行go mod tidy的时候提示：
```
go: go-zero-test1/test1 imports
        github.com/tal-tech/go-zero/core/conf: github.com/tal-tech/go-zero@v1.3.0: parsing go.mod:
        module declares its path as: github.com/zeromicro/go-zero
                but was required as: github.com/tal-tech/go-zero
```
我看到github.com/tal-tech/go-zero/core/conf/config.go的代码
```
import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path"

	"github.com/zeromicro/go-zero/core/mapping"
)
```
但是把go.mod改为
```
module go-zero

go 1.16

require github.com/tal-tech/go-zero v1.1.4
```
就可以成功。

默认下载的时 v1.3.0版本

**Comment by kevwan** [comment]
Use `goctl migrate —verbose —version v1.3.0` to migrate.

**Comment by Apa7-zero** [comment]
> 

run goctl migrate —verbose —version v1.3.0 information:
```
No help topic for 'migrate'
```
My goctl version is  1.1.9-pre windows/amd64

**Comment by kevwan** [comment]
```
# for Go 1.15 and earlier
GO111MODULE=on go get -u github.com/zeromicro/go-zero/tools/goctl@latest

# for Go 1.16 and later
go install github.com/zeromicro/go-zero/tools/goctl@latest
```

to upgrade goctl to latest version.

**Comment by xiaogu-space** [comment]
![image](https://user-images.githubusercontent.com/8435230/153573162-177185c6-dc40-43ab-8c33-5c4776db006e.png)

**Comment by alexcdever** [comment]
> ![image](https://user-images.githubusercontent.com/8435230/153573162-177185c6-dc40-43ab-8c33-5c4776db006e.png)

你版本那里漏了v，是v1.3.0，不是1.3.0

**Comment by xiaogu-space** [comment]
> > ![image](https://user-images.githubusercontent.com/8435230/153573162-177185c6-dc40-43ab-8c33-5c4776db006e.png)
> 
> 你版本那里漏了v，是v1.3.0，不是1.3.0

![image](https://user-images.githubusercontent.com/8435230/153573622-008616b8-0959-4717-b578-3673fc316eb2.png)

**Comment by alexcdever** [comment]
Your issue look strange, it's out of my power, need official support.
You may try to upgrade your goctl and then execute migrate again.

**Comment by xiaogu-space** [comment]
I have fix it by use "github.com/zeromicro/go-zero",thanks.
