### ISSUE TITLE
Is there a problem here?

### ISSUE THREAD

**Issue by bendh1** [zeromicro/go-zero#1516]
https://github.com/zeromicro/go-zero/blob/822ee2e1c5625ce77e9bf9033533a95ceacb9c3d/core/errorx/batcherror.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L29

**Comment by kevwan** [comment]
What's the problem?

**Comment by bendh1** [comment]
the return value of the function definition is of type error, but case default return []error

**Comment by kevwan** [comment]
checkout the code, it's defined as errorArray, and implemented `error` interface.

**Comment by bendh1** [comment]
so sorry. I didn't see the back

**Comment by kevwan** [comment]
No problem. :)
