### ISSUE TITLE
logx.timeFormat should be compatible time.RFC3339

### ISSUE THREAD

**Issue by hengfeiyang** [zeromicro/go-zero#1525]
**Is your feature request related to a problem? Please describe.**

when i collect go-zero log `@timestamp` will parse to time.Time, but parse error:

```
{
	"Layout": "2006-01-02T15:04:05Z07:00",
	"Value": "2022-02-11T10:58:31.456+08",
	"LayoutElem": "Z07:00",
	"ValueElem": "+08",
	"Message": ""
}
```

because `logx.timeFormat` defined `2006-01-02T15:04:05.000Z07`, not compatible with time.RFC3339 timeZone format `Z07:00`.

**Describe the solution you'd like**

i suggest that `logx.timeFormat` defined as `2006-01-02T15:04:05.000Z07:00` to compatible most standard time parser. 

**Describe alternatives you've considered**

**Additional context**

**Comment by kevwan** [comment]
goland defined as

```go
RFC3339     = "2006-01-02T15:04:05Z07:00"
RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
```

https://pkg.go.dev/time

But we're using `2006-01-02T15:04:05.000Z07:00`, it's not `ns` before timezone.
