### ISSUE TITLE
Customized headers not taking effect on using CORS.

### ISSUE THREAD

**Issue by Lewis-liuwei** [zeromicro/go-zero#1526]
![1644577625(1)](https://user-images.githubusercontent.com/16441657/153581365-eed1a2ec-e8f5-4847-9e94-45d6785b59ce.png)
添加的headers的参数，程序未读取到，例如：session已添加，但是在请求接口时，一直提示session字段不存在

**Comment by kevwan** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/1918356/153597719-4c54d15e-e669-487c-a37d-6d602dedf9c3.png">

Run main.go in `http/cors` of repo `zeromicro/zero-examples`.

**Comment by Lewis-liuwei** [comment]
![17cf502f86c19ad4b3604d71c1a05c7](https://user-images.githubusercontent.com/16441657/153799432-07e11175-d7ff-423f-b515-3548a6cf418c.png)
![1644812674(1)](https://user-images.githubusercontent.com/16441657/153799831-95ce0175-fbfc-409f-bfd3-783740035628.png)

本地curl是可以的，但是在其他项目调用接口就出现添加不了的情况

**Comment by Lewis-liuwei** [comment]
![1644813002(1)](https://user-images.githubusercontent.com/16441657/153800390-f0fff297-74d1-4fbe-bf33-3dadb72ede49.png)

**Comment by br41n10** [comment]
Based on your picture, the header is returned correctly. So I guess it's not issue with go-zero.

Look at your response, "access-control-allow-headers" represents 2 times, which is [not allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMultipleAllowOriginNotAllowed).

This is because `rest.WithCors()` [preset a default value](https://github.com/zeromicro/go-zero/blob/7727d706345bcb920ed89683936c6c9e658fb628/rest/internal/cors/handlers.go#L135).
Maybe you should use `w.Header().Set()` instead of `w.Header().Add()`

**Comment by Lewis-liuwei** [comment]
> Based on your picture, the header is returned correctly. So I guess it's not issue with go-zero.
> 
> Look at your response, "access-control-allow-headers" represents 2 times, which is [not allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMultipleAllowOriginNotAllowed).
> 
> This is because `rest.WithCors()` [preset a default value](https://github.com/zeromicro/go-zero/blob/7727d706345bcb920ed89683936c6c9e658fb628/rest/internal/cors/handlers.go#L135). Maybe you should use `w.Header().Set()` instead of `w.Header().Add()`

I had did as you said, but it didn‘t work

**Comment by akalittle** [comment]
Also didn't work by the codes following.

```go
func Headers(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Credentials", "true")
		w.Header().Set("Access-Control-Allow-Headers", "x-token, Content-Type, Origin, X-CSRF-Token, Authorization, AccessToken, Token, Range")
		w.Header().Set("Access-Control-Allow-Methods", "*")
		next(w, r)
	}
}


server.Use(Headers)

```
