### ISSUE TITLE
For goCtl1.3.0, you need to add the protoc -gen-go-grPC installation mode, and run the following command to download it:

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1529]
**Describe the bug**
For goCtl1.3.0, you need to add the protoc -gen-go-grPC installation mode, and run the following command to download it:
goctl1.3.0版本需要新增protoc-gen-go-grpc安装教程，下载命令如下:
```go
//1.16+版本使用go install
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
```

If the RPC code is generated, the following error will occur:
按照官网教程，生成rpc代码最终会出现如下报错:
https://go-zero.dev/cn/prepare.html
```shell
?[31mgoctl: generation error: 'protoc-gen-go-grpc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
--go-grpc_out: protoc-gen-go-grpc: Plugin failed with status code 1.
goctl version: 1.3.0-20220201 windows/amd64
?[0m
```

**Comment by anqiansong** [comment]
@jsonMark After goctl version `1.3.2`, you can execute the following command to install the goctl env:
```bash
$ goctl env check --install --force
```
