### ISSUE TITLE
Intsall goctl failed (no any info on the Internet)

### ISSUE THREAD

**Issue by Lisanaaa** [zeromicro/go-zero#1534]
- OS: macOS High Sierra
- Go version: 1.16.1

![image](https://user-images.githubusercontent.com/28261876/153863140-4871bccf-0cc8-4bc5-a7d5-d78a8d89fc87.png)
![image](https://user-images.githubusercontent.com/28261876/153863186-ede52d5d-990f-430a-ac98-142a39008f70.png)
Hope can get help from here

**Comment by jsonMark** [comment]
right type ：go install github.com/zeromicro/go-zero/tools/goctl@latest
you might learn go mod infomation

**Comment by kevwan** [comment]
Which go version are you using?
