### ISSUE TITLE
Unexpected results when using goctl to generate go code

### ISSUE THREAD

**Issue by int8259** [zeromicro/go-zero#1539]
**Describe the bug**
The code generated by goctl is incorrect.

**To Reproduce**
goctl api go -api issue.api -dir .

1. The code is
issue.api
```go
   syntax = "v1"

info(
	title: "type title here"
	desc: "type desc here"
	author: "type author here"
	email: "type email here"
	version: "type version here"
)

type (
	Request {
		Data subStruct `json:"data"`
	}

	subStruct {
		Id int32 `json:"id"`
	}
)

service demo{
	@doc(
		summary: "issue"
	)
	@handler Test
	post /test (Request) returns (subStruct)
}
   ```

2. The error is
types.go
```go
   // Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Data subStruct `json:"data"`
}

type SubStruct struct {
	Id int32 `json:"id"`
}
```

**Expected behavior**
   ```go
   // Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Data subStruct `json:"data"`
}

type subStruct struct {
	Id int32 `json:"id"`
}
   ```

**Environments (please complete the following information):**
 - OS: windows
 - go-zero version 1.3.0
 - goctl version 1.3.2 windows/amd64

**Comment by kevwan** [comment]
any difference?

**Comment by int8259** [comment]
subStruct != SubStruct

**Comment by chenquan** [comment]
> subStruct != SubStruct

No. I think `SubStruct` is right.It should be exported.

**Comment by chenquan** [comment]
> > > subStruct != SubStruct
> > 
> > 
> > No. I think `SubStruct` is right.It should be exported.
> 
> This will result in a compilation error.

```go

package types

type Request struct {
	Data SubStruct `json:"data"`
}

type SubStruct struct {
	Id int32 `json:"id"`
}
```
Maybe that's right.

**Comment by int8259** [comment]
> 

Fine.
