### ISSUE TITLE
Any plan to enable customizing DialTimeout of etcd?

### ISSUE THREAD

**Issue by jason-wj** [zeromicro/go-zero#1540]
开发和测试时，因客观因素导致网络不稳定，连接etcd总失败，后来发现是etcd的DialTimeout时间只有固定5秒，无法通过外部配置来调整这个时间。
虽然目前我们内网测试环境重新部署了一套etcd集群，将超时时间控制在5秒内了，但还是希望能将这些第三方组建的配置开放出来，方便开发人员根据自身需要来调整
![image](https://user-images.githubusercontent.com/13200618/153988933-6b61e9ec-7b1b-400a-b892-175e94854a43.png)
![image](https://user-images.githubusercontent.com/13200618/153988963-cdba4f14-4a67-4b73-886a-38180e4716d1.png)

**Comment by kevwan** [comment]
Use `direct connection mode` when developing.

**Comment by ZhouHr** [comment]
感觉放开第三方配置更适合一点
