### ISSUE TITLE
No help topic for 'protoc'

### ISSUE THREAD

**Issue by ObrookO** [zeromicro/go-zero#1548]
When I execute this command: 
goctl rpc protoc user.proto --go_out=./types --go-grpc_out=./types --zrpc_out=.

an error occured: 
No help topic for 'protoc'

os: mac os arm64
goctl version:  1.2.5 darwin/arm64
protoc-gen-go version: v1.26.0
go version: go1.17.6 darwin/arm64

**Comment by kevwan** [comment]
Use the following command to upgrade goctl.

```shell
GOPROXY=https://goproxy.cn/,direct go install github.com/zeromicro/go-zero/tools/goctl@latest
```

Use the following command to migrate from older versions.
```shell
goctl migrate —verbose —version v1.3.0
```

**Comment by capyun** [comment]
When I execute this command in the https://github.com/zeromicro/zero-doc/blob/main/doc/shorturl-en.md:
goctl rpc proto -src transform.proto -dir .

I get this error too.
So I run the above two commands, but can't solve problem.

protoc-gen-go.exe v1.27.1
goctl.exe version 1.3.4 windows/amd64
go 1.18

**Comment by hongtj** [comment]
> Use the following command to upgrade goctl.
> 
> ```shell
> GOPROXY=https://goproxy.cn/,direct go install github.com/zeromicro/go-zero/tools/goctl@latest
> ```
> 
> Use the following command to migrate from older versions.
> 
> ```shell
> goctl migrate —verbose —version v1.3.0
> ```
我执行了上面的命令，但还是在报同样的错：No help topic for 'proto'
环境：go version go1.18.1 darwin/amd64
           goctl version 1.3.4 darwin/amd64

**Comment by kevwan** [comment]
> > Use the following command to upgrade goctl.
> > ```shell
> > GOPROXY=https://goproxy.cn/,direct go install github.com/zeromicro/go-zero/tools/goctl@latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use the following command to migrate from older versions.
> > ```shell
> > goctl migrate —verbose —version v1.3.0
> > ```
> 
> 我执行了上面的命令，但还是在报同样的错：No help topic for 'proto' 环境：go version go1.18.1 darwin/amd64 goctl version 1.3.4 darwin/amd64

use `protoc` insted.
