### ISSUE TITLE
SQL parsing of the Model does not support the DISTINCT keyword

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1556]
**Describe the bug**
model的SQL解析不支持DISTINCT关键字:
SQL parsing of the Model does not support the DISTINCT keyword

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
query := fmt.Sprintf("SELECT DISTINCT `user_id` FROM %s WHERE `for_day` = ?;",  m.table)

The corresponding SQL：
SELECT DISTINCT `user_id` FROM `game_log` WHERE `for_day` = ?;
   
   ```

2. The error is

   ```
0 not matching destination to scan
   
   ```

**Comment by kotlin2018** [comment]
您 的SQL 语句写错了

**Comment by jsonMark** [comment]
> 您 的SQL 语句写错了
不是这里的问题，是解析的结构体不对。
query = fmt.Sprintf("SELECT SUM(win_amount) as win_amount, SUM(bet_amount) as bet_amount, SUM(fee_amount) as fee_amount,`app_id`, `com_id`,`user_id`, `for_day`, `user_name`, `status` FROM %s WHERE `user_id` = ?  GROUP BY `app_id`;", m.table)
正确的是:
var userIds []ReportMemberItem
	err := m.conn.QueryRows(&userIds, query, forDay)
