### ISSUE TITLE
Does goctl support generating Helm? Is there a corresponding plan?

### ISSUE THREAD

**Issue by wqwljz** [zeromicro/go-zero#1561]
as shown in the question.

**Comment by jsonMark** [comment]
Helm 不是主流配置方式，没必要支持吧！现在主流配置要要么yaml或者crd+operator。
Helm is not the mainstream configuration, there is no need to support it! Now the dominant configuration is either YAML or CRD + Operator

**Comment by wqwljz** [comment]
> Helm 不是主流配置方式，没必要支持吧！现在主流配置要要么yaml或者crd+operator。 Helm is not the mainstream configuration, there is no need to support it! Now the dominant configuration is either YAML or CRD + Operator

好吧，我试试自己实现吧
Well, I'll try to implement it
