### ISSUE TITLE
JWT aut after login error, request other requires authentication interface (already using rest. WithUnauthoriz

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#1572]
JWT aut after login error, request other requires authentication interface (already using rest. WithUnauthoriz
jwt aut在登录错误之后，请求其他需要认证的接口(已经使用rest.WithUnauthorizedCallback自定义错误)，api没有任何返回值，控制台打印:authorize failed: token contains an invalid number of segments

1. The code is

   ```go
   	//自定义jwt错误信息
	server := rest.MustNewServer(c.RestConf, rest.WithUnauthorizedCallback(func(w http.ResponseWriter, r *http.Request, err error) {

		authEerr := errorx.NewCodeError(errorx.SignErrCode,err.Error())
		var resp interface{}
		response.Response(r, w, resp, authEerr)

		//等同于
		//httpx.Error(w, body)
	}))
   ```

2.  The error is http is no return value，and console err is 

   ```
{"@timestamp":"2022-02-24T19:14:05.979+08","level":"error","content":"authhandler.go:104 authorize failed: token contains an invalid number of segments\n=\u003e POST 
   
   ```

**Comment by jsonMark** [comment]
Because apiPost is passing in the wrong data format
因为apipost传进来的数据格式不对
authorization:Bearer {{system_token}}"

**Comment by jsonMark** [comment]
the  http request header  
origin:http://127.0.0.1:39035
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:zh-CN
user-agent:ApiPOST Runtime +https://www.apipost.cn
connection:keep-alive
token:0d9991b4df88ff2f0cdaa88d2176ebe0
content-type:application/json
authorization:Bearer {{system_token}}
content-length:9

**Comment by jsonMark** [comment]
> Because apiPost is passing in the wrong data format 因为apipost传进来的数据格式不对 authorization:Bearer {{system_token}}"
抛出错误的代码路径在go-zero/rest/handler/authhandler.go文件的detailAuthLog方法里面
Throw an error code paths in the go - zero/rest/handler/authhandler go DE file
go-zero/rest/handler/authhandler.go

**Comment by songxiaokui** [comment]
想修改因为认证导致的错误状态码401，在回调函数里面设置 w.WriteHeader(http.StatusOK) 无效；这个怎么解决呢

**Comment by jsonMark** [comment]
> 想修改因为认证导致的错误状态码401，在回调函数里面设置 w.WriteHeader(http.StatusOK) 无效；这个怎么解决呢

复制我上面的代码放到你的api入口main方法，将
response.Response(r, w, resp, authEerr)换成你自己的错误error

**Comment by jsonMark** [comment]
> 我也是用的回调函数设置响应，但是我想把请求响应的状态码从401换成200；我的代码如下： main.go // add swagger cors server := rest.MustNewServer(c.RestConf, rest.WithNotAllowedHandler(middleware.NewCorsMiddleware().Handler()), rest.WithUnauthorizedCallback(middleware.UnAuthorizationCallBackFunc))
> 
> // middleware.UnAuthorizationCallBackFunc func UnAuthorizationCallBackFunc(w http.ResponseWriter, r *http.Request, err error) { // TODO The status code setting is invalid w.WriteHeader(http.StatusOK) response.Response(w, nil, errorx.NewCodeError(code.ErrAuthInvalidToken, err.Error())) return }
> 
> 响应是正常的，就是状态码不是我想要的

我之前修改是成功的。今天不加jwt也是没有抛出任何异常

authhandler.go:104 authorize failed: no token present in request
