### ISSUE TITLE
`goctl api doc` can't generate document when field is not basic type

### ISSUE THREAD

**Issue by brickzzhang** [zeromicro/go-zero#1573]
**Describe the bug**
`goctl api doc` can't generate document when field is not basic type.

**To Reproduce**

1. The code is

<img width="500" alt="image" src="https://user-images.githubusercontent.com/7894225/155644972-23366a24-98f8-4166-abba-5988ac96cf60.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/7894225/155644994-e0a30298-ee01-434e-9a64-e9eebbacab05.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/7894225/155645020-3f05990e-3325-4292-a302-67dce079f72d.png">

command:

```bash
goctl api doc --dir api -o doc
```

2. The error is

<img width="438" alt="image" src="https://user-images.githubusercontent.com/7894225/155645117-72b8499b-1eba-4ec5-8c89-550d99fb0ff4.png">

all.md content:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/7894225/155645132-af0c2a8f-70d1-4de1-80b0-5dfba688f0ee.png">

project/project.md content:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/7894225/155645207-d2ab9574-f8fa-4485-bced-a6679279ac28.png">

it's empty.

**Expected behavior**

`Project` definition should be shown in project.md or all.md document.

**Environments (please complete the following information):**
 - OS: [macos]
 - go-zero version [v1.3.0]
 - goctl version [goctl version 1.3.2 darwin/amd64]

**More description**
NA

**Comment by zlx362211854** [comment]
> **Describe the bug** `goctl api doc` can't generate document when field is not basic type.
> 
> **To Reproduce**
> 
> 1. The code is
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/7894225/155644972-23366a24-98f8-4166-abba-5988ac96cf60.png">
> 
> <img alt="image" width="583" src="https://user-images.githubusercontent.com/7894225/155644994-e0a30298-ee01-434e-9a64-e9eebbacab05.png">
> 
> <img alt="image" width="943" src="https://user-images.githubusercontent.com/7894225/155645020-3f05990e-3325-4292-a302-67dce079f72d.png">
> 
> command:
> 
> ```shell
> goctl api doc --dir api -o doc
> ```
> 
> 2. The error is
> 
> <img alt="image" width="438" src="https://user-images.githubusercontent.com/7894225/155645117-72b8499b-1eba-4ec5-8c89-550d99fb0ff4.png">
> 
> all.md content:
> 
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/7894225/155645132-af0c2a8f-70d1-4de1-80b0-5dfba688f0ee.png">
> 
> project/project.md content:
> 
> <img alt="image" width="458" src="https://user-images.githubusercontent.com/7894225/155645207-d2ab9574-f8fa-4485-bced-a6679279ac28.png">
> 
> it's empty.
> 
> **Expected behavior**
> 
> `Project` definition should be shown in project.md or all.md document.
> 
> **Environments (please complete the following information):**
> 
> * OS: [macos]
> * go-zero version [v1.3.0]
> * goctl version [goctl version 1.3.2 darwin/amd64]
> 
> **More description** NA

same question with you ,do you fixed this problem?

**Comment by brickzzhang** [comment]
> > **Describe the bug** `goctl api doc` can't generate document when field is not basic type.
> > **To Reproduce**
> > 
> > 1. The code is
> > 
> > <img alt="image" width="500" src="https://user-images.githubusercontent.com/7894225/155644972-23366a24-98f8-4166-abba-5988ac96cf60.png">
> > <img alt="image" width="583" src="https://user-images.githubusercontent.com/7894225/155644994-e0a30298-ee01-434e-9a64-e9eebbacab05.png">
> > <img alt="image" width="943" src="https://user-images.githubusercontent.com/7894225/155645020-3f05990e-3325-4292-a302-67dce079f72d.png">
> > command:
> > ```shell
> > goctl api doc --dir api -o doc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. The error is
> > 
> > <img alt="image" width="438" src="https://user-images.githubusercontent.com/7894225/155645117-72b8499b-1eba-4ec5-8c89-550d99fb0ff4.png">
> > all.md content:
> > <img alt="image" width="614" src="https://user-images.githubusercontent.com/7894225/155645132-af0c2a8f-70d1-4de1-80b0-5dfba688f0ee.png">
> > project/project.md content:
> > <img alt="image" width="458" src="https://user-images.githubusercontent.com/7894225/155645207-d2ab9574-f8fa-4485-bced-a6679279ac28.png">
> > it's empty.
> > **Expected behavior**
> > `Project` definition should be shown in project.md or all.md document.
> > **Environments (please complete the following information):**
> > 
> > * OS: [macos]
> > * go-zero version [v1.3.0]
> > * goctl version [goctl version 1.3.2 darwin/amd64]
> > 
> > **More description** NA
> 
> same question with you ,do you fixed this problem?

Not yet. Acutally i'm using api file directly when communicates with frontend colleague. And not sure whether the `New API AST` will fix this issue.  Anyway it's not severe.
