### ISSUE TITLE
JWT Auth Failed，How do I change the response status code from 401 to 200？

### ISSUE THREAD

**Issue by songxiaokui** [zeromicro/go-zero#1574]
I have defined a callback function for an authentication failure：

func UnAuthorizationCallBackFunc(w http.ResponseWriter, r *http.Request, err error) {
	w.WriteHeader(http.StatusOK)
	response.Response(w, nil, errorx.NewCodeError(code.ErrAuthInvalidToken, err.Error()))
	return
}

and rest registers the callback function：
server := rest.MustNewServer(c.RestConf, rest.WithNotAllowedHandler(middleware.NewCorsMiddleware().Handler()), rest.WithUnauthorizedCallback(middleware.UnAuthorizationCallBackFunc))

but the status code is not updated

**Comment by fynxiu** [comment]
@songxiaokui Bumping `go-zero` package to the latest version could solve your problem. 
Relevant issue: #1469

**Comment by songxiaokui** [comment]
@chenquan go-zero version v1.2.5

**Comment by chenquan** [comment]
> @songxiaokui Bumping `go-zero` package to the latest version could solve your problem. Relevant issue: #1469

yes， you should using latest version. @songxiaokui
