### ISSUE TITLE
Should we add example as document solution?

### ISSUE THREAD

**Issue by yangkequn** [zeromicro/go-zero#1583]
It would be fabulous  if go-zero add an example folder as document solution  like what tensorflow did.
Here's reason why:
1.more convinient to access documents, keep docs updated, tested more frequently 
2. more convinient to access code rather than take much time trying to understand document, especially for developer using english.
3. much more convinent for user making contribution to go-zero

tensorflow example ref,: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples

**Comment by yangkequn** [comment]
>1.more convinient to access documents, keep docs updated, tested more frequently 
in tensorflow, code example be the most frequently visited code.  
that counts

**Comment by kevwan** [comment]
https://github.com/zeromicro/zero-examples
