### ISSUE TITLE
is there any possible to specify git branch or tag while using goctl to generate project by remote template.

### ISSUE THREAD

**Issue by lynnickey** [zeromicro/go-zero#1609]
**Is your feature request related to a problem? Please describe.**
we did lots of customized work on go-zero template managed on our own gitlab repo. but we can't promise the latest version can adapt previous version. so if the  old version program re-generate api or rpc code by remote template, this may cause compiling-fail error.

**Describe the solution you'd like**
currently, goctl can only pull remote template from default branch. go-zero may consider supporting git tag or branch while use remote template like `goctl api new apitest -style go_zero -dir . -remote 'https://gitlab.xxxx.cn/xxx/go-zero-template -b v1.0.1'`

**Comment by kevwan** [comment]
good suggestion!

**Comment by anqiansong** [comment]
@lynnickey The pr #1617 has already fix it, you can use command as the following template:
```bash
$ goctl ${some commands and options} --remote ${git repo url} -branch ${git repo branch}
```
