### ISSUE TITLE
goctl use remote template error

### ISSUE THREAD

**Issue by runtu666** [zeromicro/go-zero#1614]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```
   goctl api go -api jarvisbilling.api -dir . -remote git@github.com:xxxx.git
   ```

2. The error is

   ```
   fatal: R#* '/Users/yangtao/.goctl/.git/xxx'@ME*: Not a directory
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: macOs
 - go-zero version  latest
 $ goctl --version
goctl version 1.3.2 darwin/amd64

**More description**
if .goctl is file not dir this error will be happened

**Comment by kevwan** [comment]
Please try the latest version, if problem still exist, please let us know.

**Comment by runtu666** [comment]
> 

$ goctl --version
goctl version 1.3.2 darwin/amd64

**Comment by runtu666** [comment]
if .goctl is file not dir this error will be happened
