### ISSUE TITLE
how to use zRpc in k8s ?

### ISSUE THREAD

**Issue by tenchiicode** [zeromicro/go-zero#1623]
i use then TencentCloud k8s to deploy my code,in docker 

step1:i deploy a user.rpc
step2:i deplaoy a order.rpc,which will use user.rpc,

but i get err:

2022/03/09 00:42:34 rpc dial: discov://10.0.0.12:2379/user.rpc, error: context deadline exceeded, make sure rpc service "user.rpc" is already started

why?

**Comment by kevwan** [comment]
User.rpc isn't started.

**Comment by kevwan** [comment]
If there are starting order problems, add `NonBlock: true` in your config file.

**Comment by tenchiicode** [comment]
3q
