### ISSUE TITLE
goctl api format don't support import other api declare type

### ISSUE THREAD

**Issue by 1278651995** [zeromicro/go-zero#1627]
**Describe the bug**
goctl api format don't support import other api declare type

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

a.api
   ```go
   type A {}
   ```
b.api
```go
import "a.api"
type B {
Data []A 
}
```

2. The error is

   ```
   can not found declaration 'A' in context
   ```

3. goctl 1.3.2

**Comment by kevwan** [comment]
1. format b.api will report errors.
2. generate go code from b.api, a.api should also be formatted.
