### ISSUE TITLE
PowerShell:1mgoctl: generation error: open LogFiles/WMI/RtBackup: Access is denied.

### ISSUE THREAD

**Issue by acalephx** [zeromicro/go-zero#1628]
**Describe the bug**
`my go-zero is v1.3.0, goctl version:1.3.2`
then i try to upgrade go-zero
`go install github.com/zeromicro/go-zero/tools/goctl@latest`
this one success

1. The code is

then i try:
` goctl migrate verbose version v1.3.1`

2. The error is

`[31mgoctl: generation error: open LogFiles/WMI/RtBackup: Access is denied.
goctl version: 1.3.2 windows/amd64
[0m`

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: win10
 - go-zero version [1.3.0]
 - goctl version [1.3.2]

**More description**
![Uploading 微信截图_20220309181247.png…]()

**Comment by acalephx** [comment]
I run the powershell by administrator

**Comment by acalephx** [comment]
![微信截图_20220309181247](https://user-images.githubusercontent.com/29752506/157421972-eda29840-e863-401f-a2a2-5042d0057085.png)

**Comment by acalephx** [comment]
i change `go.mod`
`github.com/zeromicro/go-zero v1.3.0`
to
`github.com/zeromicro/go-zero v1.3.1`
then run `go mod tidy`

**Comment by chenquan** [comment]
@acalephx You need to execute the command under the project folder.

**Comment by chenquan** [comment]
> i change `go.mod` `github.com/zeromicro/go-zero v1.3.0` to `github.com/zeromicro/go-zero v1.3.1` then run `go mod tidy`

Upgrade from 1.3.0 to 1.3.1 modify  version in go.mod
`github.com/zeromicro/go-zero v1.3.0` -> `github.com/zeromicro/go-zero v1.3.1`

**Comment by kevwan** [comment]
Problem fixed?

Why to put the project in C:\Windows\system32?
