### ISSUE TITLE
User-defined metrics in Prometheus is not collected

### ISSUE THREAD

**Issue by SaneHe** [zeromicro/go-zero#1631]
- 增加一个中间件, 自定义一个指标

```golang
const serverNamespace = "golang"

type CheckCustomerUuidMiddleware struct {
	metric metric.GaugeVec
}

func NewCheckCustomerUuidMiddleware(env string) *CheckCustomerUuidMiddleware {

	return &CheckCustomerUuidMiddleware{
		metric: metric.NewGaugeVec(&metric.GaugeVecOpts{
			Namespace: serverNamespace,
			Subsystem: "fail",
			Name:       "_notification",
			Help:      "template and customer uuid not match.",
			Labels:    []string{"mid"},
		}),
	}
}

func (m *CheckCustomerUuidMiddleware) Handle(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			m.metric.Add(1, "33")
			m.metric.Add(1, "103")
			m.metric.Set(11, "33")
			m.metric.Set(11, "103")
		}()

		next.ServeHTTP(w, r)
	}
}
```

- rest.WithMiddlewares 设置全局中间件

- 结果:  框架自带的指标数据提交了, 自定义的没有

- 环境
- go version go1.16.6 windows/amd64
- zeromicro/go-zero v1.3.1
- win 11

**Comment by chenquan** [comment]
`Add(v float64, labels ...string)`中labels需要与是`metric.GaugeVecOpts`中`Labels`设置的内容.
`Set(v float64, labels ...string)` 同理

**Comment by chenquan** [comment]
> @chenquan 是的 我的 `mid` 的值是 `33` `103` 等等

`m.metric.Set(103, "mid")`应该这样吧

**Comment by SaneHe** [comment]
![image](https://user-images.githubusercontent.com/28290710/157808636-d02fd184-fe2c-450f-b96f-7bee060b3ecc.png)
![image](https://user-images.githubusercontent.com/28290710/157808657-a8802dd9-725b-4505-9104-059fab95daa8.png)

上图是我用原生的 Prometheus 的 sdk 推送的   我的这种写法推的数据没问题呀

**Comment by chenquan** [comment]
> ![image](https://user-images.githubusercontent.com/28290710/157808636-d02fd184-fe2c-450f-b96f-7bee060b3ecc.png) ![image](https://user-images.githubusercontent.com/28290710/157808657-a8802dd9-725b-4505-9104-059fab95daa8.png)
> 
> @changkun 上图是我用原生的 Prometheus 的 sdk 推送的 我的这种写法推的数据没问题呀

抱歉,这样看来是我误解这个api的含义了,我之前用的时候,按照我说的那样操作是能成功收集到metric的

**Comment by SaneHe** [comment]
@chenquan  没事 我现在的问题是我自定义的指标 go-zero 并不会收集到 只收集到了框架自定义的那些指标

**Comment by zhoushuguang** [comment]
``我写了个例子你可以看下
1. 如果你需要全局都加这个指标的话，如代码注释部分使用srv.Use方法添加中间件
2. 如果使用rest.WithMiddlewares的话，方法如代码所示
```golang
package main

import (
	"net/http"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/metric"
	"github.com/zeromicro/go-zero/core/prometheus"
	"github.com/zeromicro/go-zero/core/service"
	"github.com/zeromicro/go-zero/rest"
)

const serverNamespace = "golang"

type CheckCustomerUuidMiddleware struct {
	metric metric.GaugeVec
}

func NewCheckCustomerUuidMiddleware(env string) *CheckCustomerUuidMiddleware {

	return &CheckCustomerUuidMiddleware{
		metric: metric.NewGaugeVec(&metric.GaugeVecOpts{
			Namespace: serverNamespace,
			Subsystem: "fail",
			Name:      "_notification",
			Help:      "template and customer uuid not match.",
			Labels:    []string{"mid"},
		}),
	}
}

func (m *CheckCustomerUuidMiddleware) Handle(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			m.metric.Add(1, "33")
			m.metric.Add(1, "103")
			m.metric.Set(11, "33")
			m.metric.Set(11, "103")
		}()

		next.ServeHTTP(w, r)
	}
}

func main() {
	srv := rest.MustNewServer(rest.RestConf{
		Port: 8888,
		ServiceConf: service.ServiceConf{
			Prometheus: prometheus.Config{
				Host: "0.0.0.0",
				Port: 9101,
				Path: "/metrics",
			},

			Log: logx.LogConf{
				Path: "logs",
			},
		},
	})

	//srv.Use(NewCheckCustomerUuidMiddleware("test").Handle)
	//
	//srv.AddRoute(rest.Route{
	//	Method: http.MethodGet,
	//	Path:   "/user",
	//	Handler: func(w http.ResponseWriter, r *http.Request) {
	//		w.Write([]byte("hello user"))
	//	},
	//})

	r := rest.Route{
		Method: http.MethodGet,
		Path:   "/animal",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("hello animal"))
		},
	}
	rs := rest.WithMiddlewares([]rest.Middleware{NewCheckCustomerUuidMiddleware("test").Handle}, []rest.Route{r}...)
	srv.AddRoutes(rs)

	srv.Start()
}

```

**Comment by SaneHe** [comment]
@zhoushuguang  不好意思  可能我没描述清楚 如你所说的一样  本地使用 Prometheus agent 的方式确实收集到了 如下图：
![企业微信截图_16472435862482](https://user-images.githubusercontent.com/28290710/158128593-b52148b2-b35b-4571-ab4e-e4dd624b70bf.png)

但是其实我想做的是自定义 [writer](https://github.com/zeromicro/go-zero/blob/master/core/stat/metrics.go#L53)  然后推送到 Prometheus 的 pushgateway   这样子收集不到自定义的指标  

![writer](https://user-images.githubusercontent.com/28290710/157808636-d02fd184-fe2c-450f-b96f-7bee060b3ecc.png)
这个里面的打印  不会输出自定义的指标

**Comment by ZhouHr** [comment]
![image](https://user-images.githubusercontent.com/5792781/158565145-a7364a6b-0126-4e14-96a8-80efedef2a19.png)
看源码应该暂时只支持agent模式

**Comment by ZhouHr** [comment]
![image](https://user-images.githubusercontent.com/5792781/158565145-a7364a6b-0126-4e14-96a8-80efedef2a19.png)
看源码应该暂时只支持agent模式

**Comment by SaneHe** [comment]
@ZhouHr  也有个支持上报的
![image](https://user-images.githubusercontent.com/28290710/158572280-0da92995-f4bd-4b11-8811-9aff11516752.png)
