### ISSUE TITLE
Wrong imports when using group in API file.

### ISSUE THREAD

**Issue by Zach-Lu** [zeromicro/go-zero#1635]
是这样，默认情况下，按照 api 编写规则，go-zero 每个请求都会生成logic和handler两个文件。为了简化文件目录，我使用了
goctl-go-compact 和 group。

操作步骤如下：
第一步：
<img width="622" alt="image" src="https://user-images.githubusercontent.com/62736001/158004421-125285b1-7746-47eb-a307-7e8bf9b13873.png">

第二步：
` goctl api plugin -p goctl-go-compact -api greet.api -dir . `

生成目录如图
<img width="501" alt="image" src="https://user-images.githubusercontent.com/62736001/158004463-c10abeeb-9446-4e41-b38f-eab72c011a7b.png">

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/62736001/158004515-3b7ff10f-a688-4efc-9a7f-1bfa896218c3.png">

查看 handles.go 文件，发现里面的包名称使用错误，仍然是logic。实际上用group的时候，此处应该使用 greet 包名，如图：
<img width="696" alt="image" src="https://user-images.githubusercontent.com/62736001/158004572-36a996f2-f9ce-4531-b166-ac96de84e677.png">

感谢 Kevin 的框架，这里还请费心优化一下😄。

**Comment by kevwan** [comment]
It's goctl-go-compact related, I've asked devs to work on it.

**Comment by kingxt** [comment]
Problem resolved, please use latest version of goctl-go-compact

**Comment by kevwan** [comment]
fixed.
