### ISSUE TITLE
How to use "goctl rpc protoc" when proto file has "option go_package"?

### ISSUE THREAD

**Issue by betNevS** [zeromicro/go-zero#1644]
项目结构：
```shell
shorturl
├── go.mod
├── go.sum
└── rpc
    └── transform.proto
```

transform.proto 的内容：
```proto
syntax = "proto3";

option go_package = "./transformpb";

message Req {
  string name = 1;
}

message Resp {
  string content = 1;
}

service Hello {
  rpc Say(Req) returns (Req);
}
```

此时，使用`cd shorturl/rpc`，然后使用命令`goctl rpc protoc transform.proto --go_out=. --go-grpc_out=. --zrpc_out=.`，这样是能够正常生成 `rpc` 相关代码的。

但是如果我将 `transform.proto` 中的 `option go_package = "./transformpb";` 改为 `option go_package = "shorturl/rpc/transformpb";`  我怎么使用 `goctl rpc protoc` 才能够生成正常的 `rpc` 代码？

我也试了目前 `goctl rpc protoc` 不支持 `--go_opt=paths=source_relative` 这个选项的。

麻烦解答下，谢谢~

**Comment by jsonMark** [comment]
> 这个问题，能帮忙回复下么？ @anqiansong

只要文件夹名字不冲突即可，这个是grpc的规范。常见用法都是当前rpc名字Client，而我则是使用rpc_client，我司项目:
syntax = "proto3";

package user;


//protoc-gen-go 版本大于1.4.0, proto文件需要加上go_package,否则无法生成
option go_package = "./user_pb";
，最终会在生成的rpc目录生成etc、internal、user、user_pb(就是option go_package配置的结果)

**Comment by betNevS** [comment]
> > 这个问题，能帮忙回复下么？ @anqiansong
> 
> 只要文件夹名字不冲突即可，这个是grpc的规范。常见用法都是当前rpc名字Client，而我则是使用rpc_client，我司项目: syntax = "proto3";
> 
> package user;
> 
> //protoc-gen-go 版本大于1.4.0, proto文件需要加上go_package,否则无法生成 option go_package = "./user_pb"; ，最终会在生成的rpc目录生成etc、internal、user、user_pb(就是option go_package配置的结果)

但是你这个并不是我想问的，你这个方式，我前面已经提了。

**Comment by anqiansong** [comment]
@betNevS `goctl rpc protoc` 是支持 `--go_opt=paths=source_relative`的，只是goctl里面没有定义这些字段，只要你的使用的是protoc相关指令，都会被原封不动执行的哈。
---
`-goctl rpc protoc` is supported by `-go_opt=paths=source_relative`, just goctl does not define these flags, as long as your use is protoc-related instructions, it will be executed.
