### ISSUE TITLE
How to use the `Model.FindId()` method?

### ISSUE THREAD

**Issue by Cyberpunk314** [zeromicro/go-zero#1650]
The Model.FindId() method return two params, Query and error. So I can not get the result from it. 

`func (mm *Model) FindId(id interface{}) (Query, error) {
	return mm.query(func(c Collection) Query {
		return c.FindId(id)
	})
}`

I try another way, use the Model.GetCollection().FindId().One() method, which works. 

There are images below.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/100133397/158407567-96d24fbe-1a98-409b-9c39-f57a2804f29f.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/100133397/158408214-33b2bc77-b6fe-4ba2-9b46-e6995e9eb2d6.png">

**Comment by kevwan** [comment]
`query.One()`

**Comment by Cyberpunk314** [comment]
I used the `query.One()` from the returned `query`, but it paniced because of `panic: Session already closed [recovered]`.

If we use `FindId()` firstly, then use the `query.One()` from returned `query`, it will fail. Maybe the session is the problem.


<img width="1443" alt="image" src="https://user-images.githubusercontent.com/100133397/158501106-3acca8e0-4e7a-43d3-ae5f-fbd18e9ea3eb.png">
