### ISSUE TITLE
The design of ShutdownListener and WrapUpListener 

### ISSUE THREAD

**Issue by elvizlai** [zeromicro/go-zero#1664]
For code example:
```
func main() {
	w1 := proc.AddShutdownListener(func() {
		fmt.Println("stop db")
	})
	defer w1()

	w2 := proc.AddShutdownListener(func() {
		// graceful time gap for handilg remaining requests
		time.Sleep(time.Second)
		fmt.Println("stop svc")
	})
	w2()
}
```

the purpose maybe stop `svc` first, then `db`.

So, why can we using FILO when stop and do not using goroutine?

https://github.com/zeromicro/go-zero/blob/448029aa4b76a5d4c0fea8095ae766003549e73e/core/proc/shutdown.go#L87

And for most case, when all WrapUp notify done, the process exist, maybe there's no opportunity to run Shutdown related notify. Shall we provide a signal to mark both has been done?

**Comment by kevwan** [comment]
FILO is working like defer in Go.

shutdown listeners are called in the latest version.

**Comment by elvizlai** [comment]
In practice, the close order maybe svc --- mq --- db --- log.

**Comment by kevwan** [comment]
> In practice, the close order maybe svc --- mq --- db --- log. For go-zero, when svc killed with graceful, the process exist, but the mq, db, log may still has some data to flush.

It's user's responsibility to make sure the shutdown callbacks being called before exit.

like calling `w1()` and `w2()` at the end of main function.
