### ISSUE TITLE
2022/03/23 17:26:01 error: config file ./etc/identity.yaml, error: type mismatch for field Auth

### ISSUE THREAD

**Issue by mrgAndysm** [zeromicro/go-zero#1697]
yaml配置：

Auth:
  AccessSecret: "ae0536sddd"
  AccessExpire: 1000

Conf文件：

type Config struct {
	Mysql struct { // 数据库配置，除mysql外，可能还有mongo等其他数据库
		DataSource string // mysql链接地址，满足 $user:$password@tcp($ip:$port)/$db?$queries 格式即可
	}
	CacheRedis cache.CacheConf // redis缓存
	zrpc.RpcServerConf // rpc server配置

	Auth struct {
		AccessSecret string
		AccessExpire int64
	}
}

但是他就报 ：2022/03/23 17:26:01 error: config file ./etc/identity.yaml, error: type mismatch for field Auth 错误

**Comment by kevwan** [comment]
format error

```yaml
Auth:
    AccessSecret: "ae0536sddd"
    AccessExpire: 1000
```

**Comment by kevwan** [comment]
problem solved.
