### ISSUE TITLE
use goctl rpc proto fail

### ISSUE THREAD

**Issue by ifconfigure** [zeromicro/go-zero#1701]
command: goctl rpc proto -src xxx.proto  -dir . 

> goctl error: unsupported plugin protoc-gen-go which installed from the following source:
google.golang.org/protobuf/cmd/protoc-gen-go, 
github.com/protocolbuffers/protobuf-go/cmd/protoc-gen-go;
Please replace it by the following command, we recommend to use version before v1.3.5:
go get -u github.com/golang/protobuf/protoc-gen-go
goctl env:
GOCTL_OS=darwin
GOCTL_ARCH=amd64
GOCTL_HOME=/Users/xxx/.goctl
GOCTL_DEBUG=False
GOCTL_CACHE=/Users/xxx/.goctl/cache
GOCTL_VERSION=1.3.3
PROTOC_VERSION=3.14.0
PROTOC_GEN_GO_VERSION=v1.28.0
PROTO_GEN_GO_GRPC_VERSION=1.2.0
> 

But the  PROTOC_GEN_GO_VERSION is  v1.28

How to fix ? ?

**Comment by 1369521908** [comment]
try this command

go install github.com/golang/protobuf/protoc-gen-go

**Comment by ifconfigure** [comment]
is done .
on my solution.
1.use goctl version in v1.2.6  

` go install github.com/tal-tech/go-zero/tools/goctl@v1.2.6` 

2.use protoc-gen-go@v1.3.2 
` go install github.com/golang/protobuf/protoc-gen-go@v1.3.2`
