### ISSUE TITLE
The service is started and registered successfully, but the etcd warn information is always reported

### ISSUE THREAD

**Issue by mrgAndysm** [zeromicro/go-zero#1703]
log info：
{"level":"warn","ts":"2022-03-24T14:22:02.645+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00050a540/192.168.33.11:12379","attempt": 0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup etcd1: no such host\""}

docker-compose.yaml：

etcd1:
    image: quay.io/coreos/etcd
    container_name: etcd1
    command: etcd -name etcd1 -advertise-client-urls http://etcd1:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "12379:2379"
      - "12380:2380"
    expose:
      - 12379
    networks:
      - backend

  etcd2:
    image: quay.io/coreos/etcd
    container_name: etcd2
    command: etcd -name etcd2 -advertise-client-urls http://etcd2:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "22379:2379"
      - "22380:2380"
    networks:
      - backend

  etcd3:
    image: quay.io/coreos/etcd
    container_name: etcd3
    command: etcd -name etcd3 -advertise-client-urls http://etcd3:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "32379:2379"
      - "32380:2380"
    networks:
      - backend

**Comment by dfang** [comment]
1. format your docker-compose.yml for readability pls

2. how you run your rpc service, is it on your local laptop? Are etcd1, etcd2, etcd3 reachable? Can you ping them? and also please unset http_proxy or HTTP_PROXY environment variables

fyi: https://etcd.io/docs/v3.5/faq/#what-is-the-difference-between-listen-clientpeer-urls-advertise-client-urls-or-initial-advertise-peer-urls
