### ISSUE TITLE
Consideration about the refactor of the code generation of `sql model`

### ISSUE THREAD

**Issue by fynxiu** [zeromicro/go-zero#1710]
There's always a need to modify the model code generated by `goctl model` during the dev process. But it's always slightly comfortable when modified the generated code.
Currently, I use this approach to alleviate this discomfort:

``` go
type FooModelEx interface {
	FooModel
	Bar(ctx context.Context,  whatever interface{}) (int64, error)
}
```
So far so good, and wouldn't it be better if we separated the interface from this file? This way we can extend the `FooModel` interface as we wish, and `goctl` can override the implementation of the interface at will without affecting the user experience.

**Comment by chenquan** [comment]
This is a good proposal!

**Comment by kevwan** [comment]
Sounds great! We'll discuss more on this.

**Comment by kevwan** [comment]
Would you please describe what kind of scenarios that we need to re-generate the model?

**Comment by fynxiu** [comment]
We sometimes need to adjust the structure of the table, such as adding fields, modifying indexes, etc.
Such requirements are literally inevitable, especially when using a development model similar to prototype-driven.

**Comment by kevwan** [comment]
I see, thanks!

**Comment by kevwan** [comment]
Currently, the `foomodel.go` looks like:

```go
type FooModel interface {
	Insert(ctx context.Context, data *Foo) (sql.Result, error)
	FindOne(ctx context.Context, foo string) (*Foo, error)
	...
}

type defaultFooModel {
}
```

Do you mean by moving `FooModel` interface to a separated file?

Thanks!

**Comment by fynxiu** [comment]
Could we change all the declarations in `foomodel.go` to private and generate a new model in a new file, as shown in the following code?

``` go
type FooModel interface {
	fooModel //private model interface 
	Bar(ctx context.Context,  whatever interface{}) (int64, error)
}
```
@kevwan

**Comment by fynxiu** [comment]
This makes fewer changes and does not break the existing `model.tpl` structure.
