### ISSUE TITLE
goctl docker template optimization

### ISSUE THREAD

**Issue by dfang** [zeromicro/go-zero#1714]
**Describe the bug**
goctl docker 生成的模板

```
✦ λ  tree -L 2
.
├── order
│   ├── api
│   ├── model
│   └── rpc
├── pay
│   ├── api
│   ├── model
│   └── rpc
├── product
│   ├── api
│   ├── model
│   └── rpc
└── user
    ├── api
    ├── model
    └── rpc

16 directories, 0 files
```
以go-zero-mall项目为例，进入order/api目录生成Dockerfile (由于goctl docker 没有-o选项只能进入相应的服务目录去运行)
```
cd service/order/api
goctl docker --go order.go --port 9000
```

在service/order/api 服务有go.mod go.sum 的情况下，该命令生成的是

```
FROM golang:alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.cn,direct

RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /build

ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
COPY ./etc /app/etc
RUN go build -ldflags="-s -w" -o /app/order ./order.go


FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ Asia/Shanghai

WORKDIR /app
COPY --from=builder /app/order /app/order
COPY --from=builder /app/etc /app/etc

EXPOSE 9000

CMD ["./order", "-f", "etc/order.yaml"]
```

在service/order/api 服务没有go.mod go.sum 的情况下，该命令生成的是

```
FROM golang:alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.cn,direct

RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /build

ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
COPY service/order/api/etc /app/etc
RUN go build -ldflags="-s -w" -o /app/order service/order/api/order.go


FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ Asia/Shanghai

WORKDIR /app
COPY --from=builder /app/order /app/order
COPY --from=builder /app/etc /app/etc

EXPOSE 9000

CMD ["./order", "-f", "etc/order.yaml"]
```

这个情况下 `RUN go build -ldflags="-s -w" -o /app/order service/order/api/order.go`  最后的那个路径是不对的，需要手动修正

通常情况下，每个微服务一个Dockerfile，单独build镜像，build context就是该服务整个目录。而`go build` 不要指定输入文件的。
所以`RUN go build -ldflags="-s -w" -o /app/order` 这样就够了

也就是说截图中画圈的完全可以去掉

**Screenshots**
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1277047/160269976-c69ffba6-7d3b-4594-bc56-5b72b59328bd.png">

**Environments (please complete the following information):**
 - OS: mac OS
 - go-zero version  1.3.3
 - goctl version 1.3.3

**Comment by kevwan** [comment]
You're not correct, we need to build the image from the dir where go.mod exists.

**Comment by dfang** [comment]
不是应该在每个服务下go mod init 一下吗？

**Comment by kevwan** [comment]
No, we're using mono repo, with only one go.mod file.

**Comment by dfang** [comment]
but goctl rpc new NAME will generate a go.mod

**Comment by dfang** [comment]
even for microservices in mono repo, one go.mod for one service is better, you can use go-zero@v1 in svc A, and go-zero@v1.1 in svc B

**Comment by kevwan** [comment]
I won't let our team to do that.

**Comment by kevwan** [comment]
then you might need to change the generated dockerfile.

**Comment by kevwan** [comment]
If you really want that, fork and change it.

**Comment by lanphan** [comment]
Hi @kevwan ,
Just 1 quick question: as you said go-zero using mono repo, does it mean that if there are 1000 services, we need to have 1 big mono repo contains all 1000 services?

**Comment by kevwan** [comment]
> Hi @kevwan ,
> 
> Just 1 quick question: as you said go-zero using mono repo, does it mean that if there are 1000 services, we need to have 1 big mono repo contains all 1000 services?

We're using mono repo with hundreds services.

**Comment by lanphan** [comment]
Hi @kevwan ,
I wonder there is any reason to use mono repo here? In case we want to use polyrepo (each service in 1 repo), is there any advice for this? 

In case polyrepo is not supported, what if we have a balanced way like below: In case our system can be divided into 3 big separated domain business context, is it possible to have 3 mono-repo which each repo contains several services? Maybe there are some common items (like enum, constants, common contracts ...) can be duplicated in these 3 mono-repo

**Comment by kevwan** [comment]
> Hi @kevwan ,
> 
> I wonder there is any reason to use mono repo here? In case we want to use polyrepo (each service in 1 repo), is there any advice for this? 
> 
> 
> 
> In case polyrepo is not supported, what if we have a balanced way like below: In case our system can be divided into 3 big separated domain business context, is it possible to have 3 mono-repo which each repo contains several services? Maybe there are some common items (like enum, constants, common contracts ...) can be duplicated in these 3 mono-repo

go-zero works with monorepo and polyrepo. You can have a shared repo in that case.
