### ISSUE TITLE
feat: add linting to .api file

### ISSUE THREAD

**Issue by dfang** [zeromicro/go-zero#1719]
Add lint subcommand to api for .api file ?

**Comment by kevwan** [comment]
What actions that `lint` subcommand can do?

**Comment by dfang** [comment]
like `buf lint`, to enforce a good api design

https://docs.buf.build/lint/overview

**Comment by kevwan** [comment]
What's the good design though?

**Comment by dfang** [comment]
https://go-zero.dev/cn/api-grammar.html

**Comment by kevwan** [comment]
If not correct, it will not pass the generation.

**Comment by dfang** [comment]
ok, didnt try that. maybe formatter is more suitable here.

anyway this is a nice-to-have-but it's-ok-if-there-is-none feature.

let's focus on more important issues first

closing
