### ISSUE TITLE
rpc服务在启动时必须要求该服务内注册发现的其他rpc服务要先启动吗 ？这个可以配置吗？

### ISSUE THREAD

**Issue by lxxwilliam** [zeromicro/go-zero#1723]
rpc dial: consul://127.0.0.1:8500/user.rpc?wait=14s, error: context deadline exceeded, make sure rpc service "user.rpc?wait=14s" is already started

**Comment by kevwan** [comment]
`NonBlock: true`

**Comment by lxxwilliam** [comment]
thanks
