### ISSUE TITLE
Goctl model generated bigint unsigned wrong

### ISSUE THREAD

**Issue by smithyj** [zeromicro/go-zero#1724]
Should be `uint64`
![image](https://user-images.githubusercontent.com/9820142/160746479-2da40160-a9ba-477d-a6d3-422064d3c4fc.png)
![image](https://user-images.githubusercontent.com/9820142/160746537-7e065e11-3025-471b-8bf5-2c180dde59d5.png)

**Comment by fyyang** [comment]
顺便能不能把tinyint 类型改成int8 或者是 int

**Comment by smithyj** [comment]
sq l.GetLastId is return int64，should be pr to the sql package

**Comment by anqiansong** [comment]
See #1794

**Comment by smithyj** [comment]
是否可以考虑官方内置一个模板？如果让用户自己来定义的话就比较蛋疼了
