### ISSUE TITLE
文档图片挂了

### ISSUE THREAD

**Issue by yuanjize** [zeromicro/go-zero#1725]
**Describe the bug**
https://go-zero.dev/cn/shorturl.html 这个页面的图片挂了

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by kevwan** [comment]
fixed.
