### ISSUE TITLE
unsupported plugin "protoc-gen-go"

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#1727]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/81024796/161184341-028896b1-2df6-4453-b741-ca5d0baaa9d9.png">

but when install from github.com

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/81024796/161181833-378467fe-55f5-40cc-9498-650f81ac8267.png">

[github.com/golang/protobuf](https://pkg.go.dev/github.com/golang/protobuf) is Deprecated

<img width="834" alt="image" src="https://user-images.githubusercontent.com/81024796/161181959-f3f07019-05f7-4e46-b056-bcc994d4ce78.png">

**Comment by Linij** [comment]
https://go-zero.dev/cn/rpc-call.html?q=goctl%20rpc%20protoc

<img width="785" alt="image" src="https://user-images.githubusercontent.com/8857514/161187445-3726f4a9-2343-498e-b440-1ee625251b11.png">

you can try this way to create.

I use the go 1.8 
proto-gen-go v1.28.0
proto-gen-go-grpc v1.1.0
it's google official website support, but not work at goctl v1.3.3.

so, wait goctl update support it.

**Comment by tcxiaotudou** [comment]
遇到同样的问题，我的环境是：
go version go1.18 darwin/arm64
GOCTL_VERSION=1.3.3
PROTOC_VERSION=3.20.0
PROTOC_GEN_GO_VERSION=v1.28.0
PROTO_GEN_GO_GRPC_VERSION=1.2.0

**Comment by chowyu12** [comment]
源码编译一下goctl（master），我这边暂时解决 了

**Comment by anqiansong** [comment]
> 遇到同样的问题，我的环境是： go version go1.18 darwin/arm64 GOCTL_VERSION=1.3.3 PROTOC_VERSION=3.20.0 PROTOC_GEN_GO_VERSION=v1.28.0 PROTO_GEN_GO_GRPC_VERSION=1.2.0

Use `goctl rpc protoc` instead, the `goctl rpc proto` has already removed in release [v1.3.4](https://github.com/zeromicro/go-zero/releases/tag/tools%2Fgoctl%2Fv1.3.4)
