### ISSUE TITLE
bug on using protoc-gen-go with mac m1

### ISSUE THREAD

**Issue by dqzg12300** [zeromicro/go-zero#1734]
在m1下使用生成grpc时，会被覆盖protoc-gen-go。然后覆盖的这个文件无法兼容这个系统，导致不能正常生成。
测试流程如下。首先找到protoc-gen-go的路径。然后查看文件的md5。然后测试能否正常生成proto，发现可以生成的。
然后执行命令goctl rpc proto -src transform.proto -dir . 
执行失败，然后重新测试能否正常生成proto，发现这时生成失败了。然后再md5查看protoc-gen-go，发现文件变了。然后用file命令查一下。/Users/king/go/bin/protoc-gen-go: Mach-O 64-bit executable arm64
发现确实是m1的arm64文件。最后直接运行一下protoc-gen-go这个命令。发现运行就立马kill了。

 king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  which protoc-gen-go                             
/Users/king/go/bin/protoc-gen-go
 king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  md5 /Users/king/go/bin/protoc-gen-go
MD5 (/Users/king/go/bin/protoc-gen-go) = 1ebab5ac5c19ecf43b1346997d6ffce5
 king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  protoc  --proto_path=/Users/king/work/code/go_project/go_server/mikServer/rpc/transform transform.proto --go_out=plugins=gr
pc:/Users/king/work/code/go_project/go_server/mikServer/rpc/transform --go_opt=Mtransform.proto=././transform
 king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  
 king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  goctl rpc proto -src transform.proto -dir .     
deprecated: use "goctl rpc protoc" instead, for the details see "goctl rpc protoc --help"
[goctl-env]: preparing to check env

[goctl-env]: looking up "protoc"
[goctl-env]: "protoc" is installed

[goctl-env]: looking up "protoc-gen-go"
[goctl-env]: "protoc-gen-go" is not found in PATH
[goctl-env]: preparing to install "protoc-gen-go"
"protoc-gen-go" installed from cache
[goctl-env]: "protoc-gen-go" is already installed in "/Users/king/go/bin/protoc-gen-go"

[goctl-env]: looking up "protoc-gen-go-grpc"
[goctl-env]: "protoc-gen-go-grpc" is installed

[goctl-env]: congratulations! your goctl environment is ready!
protoc  --proto_path=/Users/king/work/code/go_project/go_server/mikServer/rpc/transform transform.proto --go_out=plugins=grpc:/Users/king/work/code/go_project/go_server/mikServer/rpc/transform --go_opt=Mtransform.proto=././transform
goctl error: --go_out: protoc-gen-go: Plugin killed by signal 9.
goctl env:
GOCTL_OS=darwin
GOCTL_ARCH=arm64
GOCTL_HOME=/Users/king/.goctl
GOCTL_DEBUG=False
GOCTL_CACHE=/Users/king/.goctl/cache
GOCTL_VERSION=1.3.3
PROTOC_VERSION=3.17.3
PROTOC_GEN_GO_VERSION=
PROTO_GEN_GO_GRPC_VERSION=1.2.0

 ✘ king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  protoc  --proto_path=/Users/king/work/code/go_project/go_server/mikServer/rpc/transform transform.proto --go_out=plugins=
grpc:/Users/king/work/code/go_project/go_server/mikServer/rpc/transform --go_opt=Mtransform.proto=././transform
--go_out: protoc-gen-go: Plugin killed by signal 9.
 ✘ king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  md5 /Users/king/go/bin/protoc-gen-go       
MD5 (/Users/king/go/bin/protoc-gen-go) = 1562a760d5fc1740e20a13c6677451e6
 king@kingdeMacBook-Pro  ~/work/code/go_project/go_server/mikServer/rpc/transform  
 king@kingdeMacBook-Pro  ~/git_src/go_server_rpc  which protoc-gen-go
/Users/king/go/bin/protoc-gen-go
 king@kingdeMacBook-Pro  ~/git_src/go_server_rpc  file /Users/king/go/bin/protoc-gen-go
/Users/king/go/bin/protoc-gen-go: Mach-O 64-bit executable arm64
 king@kingdeMacBook-Pro  ~/git_src/go_server_rpc  protoc-gen-go
[1]    50297 killed     protoc-gen-go
 ✘ king@kingdeMacBook-Pro  ~/git_src/go_server_rpc  protoc-gen-go
[1]    50326 killed     protoc-gen-go

**Comment by tyGavinZJU** [comment]
我的暂时解决方案是把protoc-gen-go 的可执行文件删除，然后通过

go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26

重新安装

**Comment by dqzg12300** [comment]
依然没有解决，安装1.26后，提示我要使用v1.3.5

[goctl-env]: congratulations! your goctl environment is ready!
protoc  --proto_path=/Users/king/work/code/go_project/go_server/mikServer/rpc/transform transform.proto --go_out=plugins=grpc:/Users/king/work/code/go_project/go_server/mikServer/rpc/transform --go_opt=Mtransform.proto=././transform
goctl error: unsupported plugin protoc-gen-go which installed from the following source:
google.golang.org/protobuf/cmd/protoc-gen-go, 
github.com/protocolbuffers/protobuf-go/cmd/protoc-gen-go;

Please replace it by the following command, we recommend to use version before v1.3.5:
go get -u github.com/golang/protobuf/protoc-gen-go

**Comment by evan2884** [comment]
我也碰到同样的问题，你可以检查下你的proto文件内容，我的文件内容特别注意的地方如下，供你参考：
```
package userclient;
option go_package = "./userclient";
```

执行命令：
1. 先用goctl安装环境
```
> goctl env check -i -f
```
2. 生成rpc代码
```
> goctl rpc protoc ./rpc/user.proto --go_out=./rpc --go-grpc_out=./rpc --zrpc_out=./rpc
```

供你参考，希望能帮到你

> 依然没有解决，安装1.26后，提示我要使用v1.3.5
> 
> [goctl-env]: congratulations! your goctl environment is ready! protoc --proto_path=/Users/king/work/code/go_project/go_server/mikServer/rpc/transform transform.proto --go_out=plugins=grpc:/Users/king/work/code/go_project/go_server/mikServer/rpc/transform --go_opt=Mtransform.proto=././transform goctl error: unsupported plugin protoc-gen-go which installed from the following source: google.golang.org/protobuf/cmd/protoc-gen-go, github.com/protocolbuffers/protobuf-go/cmd/protoc-gen-go;
> 
> Please replace it by the following command, we recommend to use version before v1.3.5: go get -u github.com/golang/protobuf/protoc-gen-go

**Comment by dqzg12300** [comment]
> 

感谢帮助，可以使用。
