### ISSUE TITLE
goctl model command does not support multiple tables in one command

### ISSUE THREAD

**Issue by litecy** [zeromicro/go-zero#1740]
currently only support one table for on goctl model command. It has no convenience for a large amount of tables to generate model

**Comment by fynxiu** [comment]
@litecy 
It does support multi-table generation. 
Could you show me a SQL file that can reproduce the above problem?
Thanks.

**Comment by litecy** [comment]
> 

I use goctl model generate with datasource, not ddl

**Comment by anqiansong** [comment]
You can specify a pattern expression to generate multiple tables, for example, there are three tables `user`、`order`、`pay`, you can execute command `goctl model ddl --src="*"` to generate model code for all tables

**Comment by litecy** [comment]
Not for all tables, or a list tables describe by a pattern.

I use `goctl model ddl` but `goctl model datasource` because of the table ddl is separated into some .sql files after a long development process

**Comment by anqiansong** [comment]
@litecy Got it, I'll support this feature.

**Comment by anqiansong** [comment]
@litecy See the design solution #1794
