### ISSUE TITLE
goctl model generated code mixed custom function

### ISSUE THREAD

**Issue by litecy** [zeromicro/go-zero#1741]
Use goctl to generate model code, also add some custom function to generated code.

Some days later， the table add some primary key， and I wan't to use goctl to regenerate the model. 

But how to do it, regenerate will override the custom function, and i don't know other developer add custom function or not.

So the custom function and the  generated code can be placed in different go files, and union with struct or other method

**Comment by fynxiu** [comment]
@litecy 
The next version of `goctl` will fix it.

**Comment by litecy** [comment]
About when to release, is version 1.3.4?

**Comment by kevwan** [comment]
> About when to release, is version 1.3.4?

yes, next week.
