### ISSUE TITLE
[Chinese Version] goctl extension design spec（WIP）

### ISSUE THREAD

**Issue by anqiansong** [zeromicro/go-zero#1753]
[English version](https://github.com/zeromicro/go-zero/issues/1755)
# goctl extension 设计文档（WIP）

## 背景

随着 go-zero 的用户日益增长，用户需求增加，goctl 的功能在不断扩充，不管是什么产品，都不可能做到 100% 的覆盖到各个用户的需求，因此，goctl 的扩展就很有必要性了，之前我在学习一下 golang 官方的 pr 规范时，无意中发现了一个仓库 [review](https://github.com/golang/review), 其是 git 的一个扩展工具，可以用于分析 golang 的 pr 规范，除此之外，gh 也提供了 extension 功能。

## 实现目标

- 方便用户对 goctl 进行功能扩展，实现个性化需求

- goctl 对扩展工具集中管理，便于用户查找、安装和使用

### goctl 扩展

通过从环境变量中检测出所有可执行文件，对带有 `goctl-` 前缀的可执行文件会被 goctl 认为是对 goctl 的扩展。
用户可以从os.Stdin里面读取对应的spec信息，以对goctl进行扩展。

除此外：原来的 `goctl xx --plugin` 形式将使用这种形式替代。

例如：我在mac OS 上用 golang 写了一个 hello 的 goctl 插件，文件名为 goctl-hello
我们将以上二进制放到 PATH 中，通过 `goctl hello` 就能运行最简单的 goctl 扩展，如需向插件传递flag参数，必须以`${plugin_name}_${flag}`形式传递，以区分goctl内置flag和避免被goctl 内置flag误读，例如，hello 插件提供了 out 的参数，你可以通过 `goctl hello hello_out=.` 来指定。

```shell
$ goctl hello
Hello goctl
```

以上扩展在通过 `goctl --help` 能够查看对应帮助信息，扩展功能将排列在goctl内置指令后 `--help` 前。（**TODO: 待确认**）

```shell
$ goctl --help
NAME:
   goctl - a cli tool to generate code

USAGE:
   goctl [global options] command [command options] [arguments...]

VERSION:
   1.3.4 darwin/amd64

COMMANDS:
   bug         report a bug
   upgrade     upgrade goctl to latest version
   env         check or edit goctl environment
   migrate     migrate from tal-tech to zeromicro
   api         generate api related files
   docker      generate Dockerfile
   kube        generate kubernetes files
   rpc         generate rpc code
   model       generate model code
   template    template operation
   completion  generation completion script, it only works for unix-like OS
   hello       say hello to goctl
   help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

### goctl 扩展管理

新增 `goctl extension` 指令来管理扩展功能，类似 docker 对镜像管理一样，goctl 的扩展预期将会在 zeromico 下建立一个新的 repo 名为 goctl-extensions 来存储对应的描述扩展功能描述文件，以方便 goctl 可以进行集中管理，对于实现了 goctl 扩展功能开发者，可以将自己的扩展以描述文件形式提交至此仓库，以便更多用户使用你的扩展。

`goctl extension` 指令预期功能

- `ls`  列出所有扩展工具

- `pull` 下载安装指定扩展

- `clean` 清理本地所有已安装的扩展工具

- `create` 创建一个yaml描述文件来定义扩展工具，方便提交到 goctl-extensions 仓库集中管理

```bash
$ goctl extension --help
NAME:
   goctl extension - a goctl extension manager

USAGE:
   goctl extension command [command options] [arguments...]

COMMANDS:
   ls        list all extensions
   install   install extension
   clean     clean all extensions
   create    create a yaml description file

OPTIONS:
   --help, -h      show help

```

#### goctl extension ls

`ls` 指令用于查看所有扩展工具信息，展示仓库 `goctl-extensions` 中所有的扩展工具，可以用户如下 flag 筛选。

- `--local`  仅展示本地已安装的扩展工具

- `$extension_name` 当 `goctl extension ls` 后值为非 flag 参数时，且参数格式只有一个时，认为时查看指定扩展的详细信息；如 `goctl extension ls hello` 代表着查看扩展工具 `hello` 的详细信息

以下为各指令场景下展示的信息格式

**默认**：不带任何参数，列表按照 Repo 字母排序

```shell
$ goctl extension ls
Name                Status              Created            Description
hello               mount               2022-04-03         A sample goctl extension
echo                unmount             2022-04-05         A goctl extension created by keson
...                 ...                    ...             ...   
```

字段说明

| 名称          | 说明                            | 示例值                 |
| ----------- | ----------------------------- | ------------------- |
| Name        | 扩展工具名称，即描述文件中的name字段值         | hello               |
| Status      | 安装状态，mount:已安装,unmount: 未安装   | mount               |
| Created     | 创建时间，即描述文件中meta.created字段值    | 2022-04-04 00:09:23 |
| Description | 描述，即描述文件中的meta.description字段值 | balabala....        |

**--local**：仅查看本地扩展工具列表

```shell
$ goctl extension ls --local
Name                Status              Created                Description
hello               mount               2022-04-03             A sample goctl extension
...                 ...                 ...                    ...   
```

**查看指定扩展信息**：查看工具工具名称为 `hello` 的详细信息

```shell
$ goctl extension ls hello

Description:    hello is a goctl extension, it's just for show how to create an extension for goctl.


Tag            Created        DownloadCount        ChangeLog
v1.0.0         2022-01-02     1051                 A sample extension for goctl
v1.0.1         2022-02-03     889                  Fix typo
...            ...            ...                  ...
```

| 名称            | 说明                         | 示例值                 |
| ------------- | -------------------------- | ------------------- |
| Tag           | 扩展工具名称，即描述文件中的name字段值      | hello               |
| Created       | 创建时间，即描述文件中meta.created字段值 | 2022-04-04 00:09:23 |
| DownloadCount | 下载次数                       | 888                 |
| ChangeLog     | Release描述                  | balabala....        |

#### goctl extension install

`install` 用于安装置顶扩展，其可以通过如下 flag 进行简单的功能控制

- `--verbose, v`： 是否输出日志，true：是，false：否，默认不输出日志

示例：安装名称为 `hello` 的扩展工具

```shell
$ goctl extension install hello --verbose
.....
```

#### goctl extension clean

`clean` 用于清理本地已安装的所有扩展，其可以通过如下 flag 进行简单的功能控制

- `--verbose, v`： 是否输出日志，true：是，false：否，默认不输出日志

- `--force, f`：是否强制清理，true：是，false：否，会弹窗进行二次确认

示例

```shell
$ goctl extension clean --verbose 
Do you want to clean all extensions? [y for yes, n for no]: y
....
```

#### goctl extension create

`create` 用于创建一个 yaml 描述文件，开发者可将该描述文件push到 `goctl-extensions` 仓库下，方便 goctl 集中管理，上文中的 `goctl extension ls` 就是获取仓库 `goctl-extensions` 仓库中所有描述文件进行列表展示的。

此指令是一个交互式的，执行后需要用户填写对应信息。

示例：创建一个扩展名称为 `hello` 的描述文件

```shell
$ goctl extension create
What's the extension name?(awesomeProject): hello
What's the extension belong to: zeromicro
What's the extension description[optional]: balabala....
Done.
```

yaml 描述文件内容

```yaml
name: hello
meta:
  author: zeromicro
  created: 2022-04-03 11:37:35
  description: balabala....
repo:
  host: github
  name: zeromicro/goctl-hello
```

| 名称               | 类型     | 说明                                                                                                             | 示例值                 |
| ---------------- | ------ | -------------------------------------------------------------------------------------------------------------- | ------------------- |
| name             | string | 扩展名称,扩展名称不用加 goctl- 前缀                                                                                         | hello               |
| meta.author      | string | 作者或者组织名称                                                                                                       | zeromicro           |
| meta.created     | string | 创建日期，自动获取当前日期                                                                                                  | 2022-04-03 11:47:50 |
| meta.description | string | 扩展说明                                                                                                           | balabala....        |
| repo.host        | string | 仓库域名，系统预设几个常量值，当使用系统预设值时默认通过ssh形式拉取对应产物，如果当前值不为系统预设值，则代表自定义仓库，开发者需要保证该域名仓库中的tag有产物，系统预设值 github\|gitlab\|gitee | github              |
| repo.name        | string | 仓库名称，由goctl自动生成，如果开发者修改，名称需要保证为各位为{orgnization_name}/{extension_name}，不用添加域名，扩展名建议以 goctl- 开头                  | goctl-hello         |

**Comment by fynxiu** [comment]
That's brilliant!
IMHO, `goctl` is essentially a code generation tool. Can we refer to the [CommandLineInterface](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.command_line_interface) of protobuffers and provide all the necessary information for users who wish to extend it?
