### ISSUE TITLE
goctl model: The generated files are inconsistent with the tutorial.

### ISSUE THREAD

**Issue by capyun** [zeromicro/go-zero#1772]
goctl model mysql ddl -src user.sql -dir . -c
In tutorial, this cmd just generate usermodel.go and vars.go, but I get extra file named usermodel_gen.go. I am confused and need help.

**Comment by kevwan** [comment]
We separated the generated code and the handwritten code.

Thanks for your remind, we'll update the tutorials.

**Comment by capyun** [comment]
thank you, url is https://go-zero.dev/cn/model-gen.html.
BTW: In tutorial, I can use jwt by this, and I want to know how to use ouath2.0.
@server(
    jwt: Auth
)

**Comment by anqiansong** [comment]
Done

**Comment by kevwan** [comment]
@capyun thanks for reporting and please verify.
