### ISSUE TITLE
Can I use  custom DTO in goctl api file, or must I  copy and paste the custom DTO into api file

### ISSUE THREAD

**Issue by kpkym** [zeromicro/go-zero#1774]
custom struct from other file
```go
type DTO struct {
	Code string `json:"code"`
}
```

api file
```go
type Response struct {
    // that DTO struct is not in api file
	DTOs []DTO `json:"dtos"`
}
```

**Comment by fynxiu** [comment]
@kpkym Sorry, it is not currently supported.

**Comment by kpkym** [comment]
@fynxiu Will it be supported in the future version

**Comment by fynxiu** [comment]
@kpkym 
Would you mind telling me the circumstances in which you need to use this feature?

**Comment by kpkym** [comment]
@fynxiu 
Here is my situation.
I wanna list file info in dir. File info struct generated by the custom utils method. I wanna use the list of file info as response. In currently. I need modify the response struct generated by Goctl api, Or I copy the same struct code and paste info api file, after generate code, I need convert custom file info struct to api generated file info struct for response

**Comment by fynxiu** [comment]
@kpkym 
IMHO, it is not a good idea to declare types that are not defined in the `api` file.
You could either use the second method you mentioned, or patch `types.go` automatically in your script.

**Comment by kpkym** [comment]
@fynxiu  OK. thanks for helping
