### ISSUE TITLE
questions on proto json tag with omitempty

### ISSUE THREAD

**Issue by bigbeer1** [zeromicro/go-zero#1792]
![image](https://user-images.githubusercontent.com/52517974/163660413-07a703d2-8b66-49de-849d-4263a9c0f013.png)
希望添加
[protoc-go-inject-tag](https://github.com/favadi/protoc-go-inject-tag)
注释方式去可自定义

**Comment by kevwan** [comment]
It depends on protoc.

**Comment by bigbeer1** [comment]
所以可以 借鉴下[protoc-go-inject-tag](https://github.com/favadi/protoc-go-inject-tag)吗

**Comment by kevwan** [comment]
Not in plan yet.

**Comment by 664485186** [comment]
I don't know why I have to speak English, but can I remove omitEmpty when generating proto, I think I should go to Proto and ask?
