### ISSUE TITLE
use go work goctl generates file import error

### ISSUE THREAD

**Issue by jan-bar** [zeromicro/go-zero#1793]
**Describe the bug**

This is my test project
[testWork.zip](https://github.com/zeromicro/go-zero/files/8499531/testWork.zip)

This module compiles fine

```shell
cd web/api
goctl api go -style goZero -dir .. -api web.api
cd ..
go mod tidy
go build web.go
```

This module has a compilation error because of import problems

```shell
cd webNew/api
goctl api go -style goZero -dir .. -api web.api
cd ..
go mod tidy
go build web.go
```

The picture shows the following

![da2663860ee020eb9745cbf741104f6](https://user-images.githubusercontent.com/14202095/163667876-8038ae82-9c95-4bdd-ad19-eb80165800a9.png)

Maybe my understanding of go work is not deep enough, maybe I'm using it wrong?

**Comment by fynxiu** [comment]
@jan-bar This issue doesn't seem to be directly related to `go work`. I'll probably look at the exact implementation of this part later tomorrow and give you feedback.
