### ISSUE TITLE
[Feature] Model optimization design manual (Simplified Chinese Version)

### ISSUE THREAD

**Issue by anqiansong** [zeromicro/go-zero#1794]
# model 优化方案

## 现状

- [ ] 1. 对于 model 的生成，目前会对自动生成字段进行忽略，比如 id 可以依靠 mysql 的 auto_increment 特性，create_time 和 update_time 依靠 `timestamp` 自动生成，
但并非所以用户都会把字段命名为 `create_time`、`update_time`，比如，`create_time`、`update_time` 的争议比较大，有些用户命名为 `create_at`、`update_at` 等。
- [ ] 2. 数据类型的转换规则，目前对mysql中以 `*int*` 模式命名的字段都会被转换为 int64 或者 sqlNullInt64 类型，但对很多用户可能对 `tinyint(1)` 需要将其转换为 `bool` 类型，甚至有些对 `bigint` 需要转换为 `int64`，`unsigned bigint` 转换为 `uint64` 等。
- [x] 3. 多表生成，目前的多表生成是按照通配符筛选满足条件的表进行生成，无法精确控制需要生成的多表。

为了灵活支持字段忽略和类型转换规则，model 生成将考虑增加 “配置” 形式来解决这个问题。

#### 配置方案

配置方案主要解决现状中 [1,2] 两个问题，用户可以从配置中读取需要的规则，配置的读取途径有3种，配置会从以下3种来源进行数据采集，最终会将配置结果进行合并。

1. 命令行指定
2. 从全局配置读取
3. 内置字段

通过命令行直接指定字符串值或者配置文件进行配置，`goctl model mysql` 中将新增几种 options 来指定，详见下文help中红色文字部分。

**mysql ddl**

<pre>
$ goctl model mysql ddl -h   
NAME:
   goctl model mysql ddl - generate mysql model from ddl

USAGE:
   goctl model mysql ddl [command options] [arguments...]

OPTIONS:
   --src value, -s value         the path or path globbing patterns of the ddl
   --dir value, -d value         the target dir
   --style value                 the file naming format, see [https://github.com/zeromicro/go-zero/tree/master/tools/goctl/config/readme.md]
   --cache, -c                   generate code with cache [optional]
   --idea                        for idea plugin [optional]
   --database value, --db value  the name of database [optional]
   --home value                  the goctl home path of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
   --remote value                the remote git repo of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
                                 The git repo directory must be consistent with the https://github.com/zeromicro/go-zero-template directory structure
   --branch value                the branch of the remote repo, it does work with --remote
<span style="color:red">   --ignore, i value             fields to ignore, comma-separated</span> 
<span style="color:red">   --rules, r value              the name of the configuration rules file</span> 
</pre>

**mysql datasource**

<pre>
$ goctl model mysql datasource -h                                  
NAME:
   goctl model mysql datasource - generate model from datasource

USAGE:
   goctl model mysql datasource [command options] [arguments...]

OPTIONS:
   --url value              the data source of database,like "root:password@tcp(127.0.0.1:3306)/database"
   --table value, -t value  the table or table globbing patterns in the database
   --cache, -c              generate code with cache [optional]
   --dir value, -d value    the target dir
   --style value            the file naming format, see [https://github.com/zeromicro/go-zero/tree/master/tools/goctl/config/readme.md]
   --idea                   for idea plugin [optional]
   --home value             the goctl home path of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
   --remote value           the remote git repo of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
                            The git repo directory must be consistent with the https://github.com/zeromicro/go-zero-template directory structure
   --branch value           the branch of the remote repo, it does work with --remote
<span style="color:red">   --ignore, i value        fields to ignore, comma-separated</span> 
<span style="color:red">   --rules, r value         the name of the configuration rules file</span>
</pre>

**pg datasource**

<pre>
$ goctl model pg datasource -h                                      17:45:49  羽102ms
NAME:
   goctl model pg datasource - generate model from datasource

USAGE:
   goctl model pg datasource [command options] [arguments...]

OPTIONS:
   --url value               the data source of database,like "postgres://root:password@127.0.0.1:5432/database?sslmode=disable"
   --table value, -t value   the table or table globbing patterns in the database
   --schema value, -s value  the table schema, default is [public]
   --cache, -c               generate code with cache [optional]
   --dir value, -d value     the target dir
   --style value             the file naming format, see [https://github.com/zeromicro/go-zero/tree/master/tools/goctl/config/readme.md]
   --idea                    for idea plugin [optional]
   --home value              the goctl home path of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
   --remote value            the remote git repo of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
                             The git repo directory must be consistent with the https://github.com/zeromicro/go-zero-template directory structure
   --branch value            the branch of the remote repo, it does work with --remote
<span style="color:red">   --ignore, i value         fields to ignore, comma-separated</span> 
<span style="color:red">   --rules, r value          the name of the configuration rules file</span>
</pre>

#### 参数介绍

`--ignore` 可以直接通过文本告知 goctl 需要忽略而自动生成的字段名称（写操作时需要忽略的字段），多个字段以英文逗号分隔，值不可以包含自增的主键，如果用户指定了自增的主键字段， goctl 会将其剔除。

`--rules` 指定model代码生成规则的文件，文件中可以指定需要忽略的字段和类型转换规则，格式为 yaml 文件，其配置规则示例：

```yaml
ignore: [create_time,create_at,update_time,update_at] # 主键将无效，会被 goctl 剔除
mapper: # 数据库类型到golang数据类型的映射规则
  bigint: # key 为 mysql 或者 pg 中的数据类型，必须要全小写
    type: int64
    unsignedType: uint64
    nilType: sql.NullInt64
  tinyint:
    type: bool
    nilType: sql.NullBool
  varcahr:
    type: string
    nilType: sql.NullString

```

**yaml 配置规则**

`ignore` 是对需要依靠数据库自动生成而忽略的字段（写操作时需要忽略的字段），注意：主键不可忽略，goctl 会将其从配置中剔除。
`converter` 是数据库类型到golang数据类型的映射规则定义，其孩子节点中的 key 对应为数据库类型名称的小写，每个 key 支持3种映射规则，开发者可以根据情况定义对应的规则，我们通过对 yaml 对应的 golang 结构体来进行描述：

```golang
type Rule struct {
    Ignore []string         `yaml:"ignore"` // 写操作时需要忽略的字段
    Mapper map[string]Value `yaml:"mapper"` // 数据库数据类型-golang数据类型映射规则,key为数据库数据类型小写名称，value为golang数据类型
}

type Value struct {
    Type string         `yaml:"type"`           // golang 数据类型
    UnsignedType string `yaml:"unsignedType"`   // golang 数据类型，针对数值类型为 unsigned 修饰字段时使用，对非数值类型无效，例如数据库类型 varchar 时此字段无效。
    NilType      string `yaml:"nilType"`        // golang 数据类型，当满足字段没有默认值或者允许为null时使用，当满足Null条件时，nilType 优先级高于 type 和 sunsignedType
}
```

**支持映射的数据库类型**

- bit
- tinyint
- smallint
- mediumint
- int
- ...

### 多表方案

将原 goctl 中的指令 `--table` 从字符串转换为字符串数组类型，当用户通过 `--table` 指定多表时可以精确控制，当然这里还是支持通配符的，其在 goctl 中会多用户指定的所有表进行合并处理，如：
现在有如下表
```text
+------------------+
| Tables_in_gozero |
+------------------+
| user             |
| order            |
| pay              |
| after_sale       |
| product          |
+------------------+
```

假设我们通过如下指令对多张表进行代码生成

```shell
$ goctl model mysql datasource --table="*er" --table="user" --table="pay"
```
由于第一个参数 `--table` 的值为 `*er`，因此 goctl 会匹配出 `user`、`order` 两张表，另外两个 `--table` 指定了精确值 `user`、`pay` 字段，因此 `user` 表其实就被多次指定了，这是 goctl 会去重合并，最终合并结果为
`user`、`order`、`pay`，因此不会重复执行代码生成。

**Comment by dfang** [comment]
这个配置文件是打算写到~/.goctl/config.yaml 的吗？ 增加一个对应 --style的？

**Comment by smithyj** [comment]
mark

**Comment by smithyj** [comment]
最好是内置一个默认方案啊

**Comment by diandengs** [comment]
goctl version 1.5.1 darwin/arm64

生成不了，help发现并没有rules参数，所以这个功能现在是有还是没有的呢？数据库这么多表和int, bigint, tinyint字段，有符号的和无符号的，生成的全是int64类型，导致业务代码里，各种info，列表结构都需要定义成int64类型，如果不定义int64就导致出现各种为了转换而写的各种转换的冗余代码，还会导致浪费内存，就因为生成的底层model里的类型不理想，所以这个功能现在是能不能用啊？

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/3427751/236654340-1f593314-d2c3-46dc-8b90-7bac6a6cbcd4.png">
