### ISSUE TITLE
gracefulStop  bug

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#1804]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/81024796/163956719-c9b205f9-f2e4-449d-9938-de929eef551a.png">

main函数在gracefulStop 执行完毕前退出

**Comment by kevwan** [comment]
Use the following method to make sure it's called before exiting.

```go
	waitForCalled := proc.AddShutdownListener(func() {
		println("shutdown")
	})
	srv.Start()
	waitForCalled()
```

Also, there is `AddWrapUpListener` for earlier stage events on getting signals.

**Comment by chowyu12** [comment]
`proc.SetTimeToForceQuit(time.Second * 60)`
not work

**Comment by kevwan** [comment]
> `proc.SetTimeToForceQuit(time.Second * 60)` not work

It's force to quit after specific duration. Not wait this time interval.
