### ISSUE TITLE
goctl upgrade question

### ISSUE THREAD

**Issue by gofromzero** [zeromicro/go-zero#1809]
![image](https://user-images.githubusercontent.com/30290644/164354836-0d758795-b4b4-4732-80cd-3fe2f63ba813.png)
![image](https://user-images.githubusercontent.com/30290644/164355132-c71c97a0-3e89-4f20-8bfd-f4db4649ad86.png)

Why does goctl show this after execution?

**Comment by kevwan** [comment]
We've disabled this. It's for statistics.
