### ISSUE TITLE
Monolithic service best practices

### ISSUE THREAD

**Issue by kevwan** [zeromicro/go-zero#1813]
## Background

1. For startups or small projects, micro services are not a must.
2. Lots of devs asked for the best practices for developing monolithic service.
3. `goctl api` only supports single `service` definition in one `API` file, and cannot generate code with multiple `API` files.

## Purpose

1. To support monolithic service generation better with `goctl api` command.

### Usage

1. `goctl api` with multiple `API` files.

   ```shell
   goctl api go -api api/download.api -api api/upload.api -dir .
   ```

2. `goctl api` with wildcard `API` files.

   ```shell
   goctl api go -api api/*.api -dir .
   ```

> `main.go` will be generated in the target directory.

### File layout

```
.
├── api
│  ├── download.api
│  └── upload.api
├── etc
│  └── config.yaml
├── main.go
├── go.mod
└── internal
   ├── config
   │  └── config.go
   ├── download
   │  ├── handler
   │  │  ├── downloadhandler.go
   │  │  └── routes.go
   │  ├── logic
   │  │  └── downloadlogic.go
   │  ├── svc
   │  │  └── servicecontext.go
   │  └── types
   │     └── types.go
   └── upload
      ├── handler
      │  ├── routes.go
      │  └── uploadhandler.go
      ├── logic
      │  └── uploadlogic.go
      ├── svc
      │  └── servicecontext.go
      └── types
         └── types.go
```

The final solution: https://dev.to/kevwan/best-practices-on-developing-monolithic-services-in-go-3c95

**Comment by MikyChow** [comment]
Maybe goctl api go -api specify a specific directory is more in common use

**Comment by kevwan** [comment]
> Maybe goctl api go -api specify a specific directory is more in common use

good suggestion, let me update the design.

**Comment by kevwan** [comment]
Checkout the example here:

https://github.com/zeromicro/zero-examples/tree/main/monolithic

After discussion, we found this might be a better solution.

**Comment by MikyChow** [comment]
Thanks,That's very useful in use

**Comment by kevwan** [comment]
I wrote an article on this for the best practices.

https://dev.to/kevwan/best-practices-on-developing-monolithic-services-in-go-3c95
