### ISSUE TITLE
template optimization

### ISSUE THREAD

**Issue by zundaren** [zeromicro/go-zero#1823]
![a6446d8a4fccbce6eab4b3b27afaa48](https://user-images.githubusercontent.com/44863479/165007059-50dbbf3a-8b72-4c4c-87a4-bc406ac97798.png)
logic merge into one file, handler merge into one file, 

package user

import ()

//first api
type FileLogic struct {}
func NewFileLogic(ctx context.Context, svcCtx *svc.ServiceContext) *FileLogic {}
func (l *FileLogic) File(req *types.FileDTO) (resp *types.Response, err error) {}

//second api
type FileLogic struct {}
func NewFileLogic(ctx context.Context, svcCtx *svc.ServiceContext) *FileLogic {}
func (l *FileLogic) File(req *types.FileDTO) (resp *types.Response, err error) {}

//third api 
type FileLogic struct {}
func NewFileLogic(ctx context.Context, svcCtx *svc.ServiceContext) *FileLogic {}
func (l *FileLogic) File(req *types.FileDTO) (resp *types.Response, err error) {}

...

**Comment by zundaren** [comment]
Too many files can be a hassle

**Comment by chenquan** [comment]
I don't think so. Isolation of different business logic is also very important.

**Comment by kevwan** [comment]
https://github.com/zeromicro/goctl-go-compact

use this plugin to combine the files.
