### ISSUE TITLE
there is have a problem with the document .

### ISSUE THREAD

**Issue by Funny-dot** [zeromicro/go-zero#1824]
read doc for https://go-zero.dev/cn/jwt.html

Check the introduction of jwt in the document. After copying the code, there is an error of jwt undefined. Is the document incomplete?

my code:

```go
package logic

import (
	"book/service/user/api/internal/svc"
	"book/service/user/api/internal/types"
	"book/service/user/model"
	"context"
	"errors"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/logx"
)

type LoginLogic struct {
	logx.Logger
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLoginLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LoginLogic {
	return &LoginLogic{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *LoginLogic) Login(req *types.LoginReq) (resp *types.LoginReply, err error) {
	// todo: add your logic here and delete this line
	if len(strings.TrimSpace(req.Username)) == 0 || len(strings.TrimSpace(req.Password)) == 0 {
		return nil, errors.New("参数错误")
	}
	user, err := l.svcCtx.UserModel.FindOneByNumber(req.Username)
	switch err {
	case model.ErrNotFound:
	case nil:
		return nil, errors.New("账户不存在")
	default:
		return nil, err

	}
	if user.Password != req.Password {
		return nil, errors.New("密码不正确")
	}
	now := time.Now().Unix()
	expriceTime := l.svcCtx.Config.Auth.AccessExpire
	jwtToken, err := l.getJwtToken(l.svcCtx.Config.Auth.AccessSecret, now, expriceTime, user.Id)
	if err != nil {
		return nil, err
	}

	return &types.LoginReply{
		Id:           user.Id,
		Name:         user.Name,
		AccessToken:  jwtToken,
		AccessExpire: now + expriceTime,
		RefreshAfter: now + expriceTime/2,
	}, nil
}

func (l *LoginLogic) getJwtToken(secretKey string, iat, seconds, userId int64) (string, error) {
	claims := make(jwt.MapClaims)
	claims["exp"] = iat + seconds
	claims["iat"] = iat
	claims["userId"] = userId
	token := jwt.New(jwt.SigningMethodHS256)
	token.Claims = claims
	return token.SignedString([]byte(secretKey))
}
```

**Comment by anqiansong** [comment]
Please paste your error text here first, Thanks

**Comment by Funny-dot** [comment]
> Please paste your error text here first, Thanks
I followed the code written in the document, but it won't work when I get to the jwt certification.
How did the jwt in the red box in the screenshot come from?
![image](https://user-images.githubusercontent.com/27287970/165195890-1759a215-6051-4cbd-8eb4-a4f0742b42da.png)
![image](https://user-images.githubusercontent.com/27287970/165195902-d1271d70-9ac1-459d-9bcf-36f0d22ccce1.png)

**Comment by rxrddd** [comment]
you should got package for jwt 
`go get github.com/dgrijalva/jwt-go`

**Comment by rxrddd** [comment]
> > Please paste your error text here first, Thanks
> > I followed the code written in the document, but it won't work when I get to the jwt certification.
> > How did the jwt in the red box in the screenshot come from?
> > ![image](https://user-images.githubusercontent.com/27287970/165196107-4c0e9347-2084-4e4b-a9d5-e4ced2867aa9.png)

you should got package of jwt

`go get github.com/dgrijalva/jwt-go`
