### ISSUE TITLE
Are there any good practices for the type of scheduled tasks（crontab）?

### ISSUE THREAD

**Issue by shencw** [zeromicro/go-zero#1825]
I have a lot of scripts that need to be executed regularly.

I want to see if the seniors have any better suggestions to learn.

😁

**Comment by kevwan** [comment]
kubernetes jobs.

**Comment by shencw** [comment]
> kubernetes jobs.

What if you don't use k8s

**Comment by kevwan** [comment]
> > kubernetes jobs.
> 
> What if you don't use k8s

We also have go-queue for delayed tasks.

**Comment by aonoa** [comment]
You see see [go-zero的新版本讲解和用户答疑，以及社区一些重点示例项目的讲解](https://b23.tv/9RTz7LW) in the 32nd minute
