### ISSUE TITLE
go-zero/core/stat module is panic on centos6.9 

### ISSUE THREAD

**Issue by qgweb** [zeromicro/go-zero#1826]
question:  go-zero/core/stat module is panic on centos6.9 

go version: 1.18
go-zero version: v1.3.2

![image](https://user-images.githubusercontent.com/13936532/165094169-3226d750-a787-4e22-83f7-ce3921926396.png)

**Comment by qgweb** [comment]
![image](https://user-images.githubusercontent.com/13936532/165205904-ecc4ed6c-328d-4788-ab92-cdecfd4f9e64.png)

I think the check is fail 

![image](https://user-images.githubusercontent.com/13936532/165206770-3507def7-1a5c-4dce-9676-5e4ec28eb6ed.png)


![image](https://user-images.githubusercontent.com/13936532/165206635-17a33952-01aa-436a-a7c3-58749fcae63e.png)

**Comment by qgweb** [comment]
can use this way to pull amd64 image

`docker pull --platform=amd64 centos:6.9`

**Comment by kevwan** [comment]
```shell
$ docker run --rm -it --platform=linux/amd64 -v `pwd`:/build -w /build centos:6.9 /build/adhoc/main
{"@timestamp":"2022-04-26T06:44:39.161Z","level":"stat","content":"CPU: 0m, MEMORY: Alloc=1.9Mi, TotalAlloc=4.3Mi, Sys=14.5Mi, NumGC=1"}
```

**Comment by kevwan** [comment]
The kernel is version 2.6.
