### ISSUE TITLE
zrpc\internal\client.go:51:46: undefined: grpc.WithBalancerName

### ISSUE THREAD

**Issue by anyone0034** [zeromicro/go-zero#1829]
> ### run `go run order.go` errors
 github.com/zeromicro/go-zero/zrpc/internal
..\..\..\pkg\mod\github.com\zeromicro\go-zero@v1.3.2\zrpc\internal\client.go:51:46: undefined: grpc.WithBalancerName

> ### go version
go version go1.17.8 windows/amd64

> ### goctl env
GOCTL_OS=windows
GOCTL_ARCH=amd64
GOCTL_HOME=C:\Users\china\.goctl
GOCTL_DEBUG=False
GOCTL_CACHE=C:\Users\china\.goctl\cache
GOCTL_VERSION=1.3.4
PROTOC_VERSION=3.15.8
PROTOC_GEN_GO_VERSION=v1.28.0
PROTO_GEN_GO_GRPC_VERSION=1.2.0

Operation steps
> ### step1：order.proto
syntax = "proto3";
option go_package = "./order";

package stream;

message StreamReq {
  string name = 1;
}

message StreamResp {
  string greet = 1;
}

service StreamGreeter {
  rpc greet(StreamReq) returns (StreamResp);
}

> ### step2：goctl rpc protoc order.proto --go_out=./types --go-grpc_out=./types --zrpc_out=.
> ### step3：go run .\order.go
github.com/zeromicro/go-zero/zrpc/internal
..\..\..\pkg\mod\github.com\zeromicro\go-zero@v1.3.2\zrpc\internal\client.go:51:46: undefined: grpc.WithBalancerName

**Comment by kevwan** [comment]
Fixed.

**Comment by anyone0034** [comment]
> Fixed.

thanks!Happy working!

**Comment by ysongyang** [comment]
grpc upgrade to 1.46 还是会出现 undefined: grpc.WithBalancerName 呢？

**Comment by kevwan** [comment]
grpc 1.46 removed grpc.WithBalancerName, use grpc 1.45 or earlier.

Or use go-zero master version.

go-zero 1.3.3 will be released next week, which will solve the problem.
