### ISSUE TITLE
How to stop log output

### ISSUE THREAD

**Issue by qq50520271** [zeromicro/go-zero#1831]
How to stop log output
2022/04/26 16:56:09 {"@timestamp":"2022-04-26T16:56:09.048+08:00","level":"stat","content":"CPU: 0m, MEMORY: Alloc=10.0Mi, TotalAlloc=228.9Mi, Sys=36.9Mi, NumGC=60"}

**Comment by kevwan** [comment]
`logx.DisableStat()`

**Comment by qq50520271** [comment]
no 
![image](https://user-images.githubusercontent.com/40230389/165910451-fd4dd8a1-5a4a-4164-85f4-a833c11c81db.png)

**Comment by zebinh** [comment]
> no ![image](https://user-images.githubusercontent.com/40230389/165910451-fd4dd8a1-5a4a-4164-85f4-a833c11c81db.png)

maybe you can try add ```logx.DisableStat()``` at where the server startup. like this.
![图片](https://user-images.githubusercontent.com/16345470/166129043-7befecb6-51ff-4ed8-86dd-f6d2548dd953.png)

**Comment by qq50520271** [comment]
I only quoted the limit module, did not use the complete package, and did not have a server Start(), how do I close the log in this case
