### ISSUE TITLE
pipeliner.Exists Result return value is incorrect in redis.PipelinedCtx 

### ISSUE THREAD

**Issue by smithyj** [zeromicro/go-zero#1832]
@kevwan 
**To Reproduce**
- `redis` set two keys or more

1. The code is
   ```go
   if err = l.svcCtx.Redis.Pipelined(func(pipeliner redis.Pipeliner) error {
		v, err := pipeliner.Exists(l.ctx, accountKey, sessionKey).Result()
		if err != nil {
			return err
		}
		l.Logger.Error("======", v)
		l.Logger.Error("======", accountKey)
		l.Logger.Error("======", sessionKey)
		if v < 2 {
			return errors.New('key count not matched')
		}
		return nil
	}); err != nil {
		l.Logger.Error(err)
	}
   ```

2. The error is
- `pipeliner.Exists` result always is `0` 

**Expected behavior**
- `pipeliner.Exists` result return `2`

**Screenshots**
![image](https://user-images.githubusercontent.com/9820142/165284892-c34f152e-64d4-4068-92eb-339167282347.png)
![image](https://user-images.githubusercontent.com/9820142/165284929-ad3b81ef-0d93-47b7-894d-369e2aa79e79.png)
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/9820142/165284970-fc6d70df-0dad-4038-b37d-c5dbd2ff5811.png">

**Comment by kevwan** [comment]
The results from pipeline need to be evaluated after `Pipelined` returns.

```go
package main

import (
	"context"
	"fmt"

	"github.com/zeromicro/go-zero/core/stores/redis"
)

func main() {
	var val *redis.IntCmd
	rds := redis.New("localhost:6379")
	err := rds.Pipelined(func(pipeliner redis.Pipeliner) error {
		val = pipeliner.Exists(context.Background(), "foo", "bar")
		return nil
	})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(val.Val())
}
```
