### ISSUE TITLE
No help topic for 'protoc'

### ISSUE THREAD

**Issue by hongtj** [zeromicro/go-zero#1834]
当执行这个命令时：
goctl rpc proto -src ./rpc/product.proto -dir ./rpc

报错:
No help topic for 'protoc'

环境：
os: mac os arm64
go version go1.18.1 darwin/amd64
goctl version 1.3.4 darwin/amd64

**Comment by kevwan** [comment]
Use `protoc` subcommand.

**Comment by aonoa** [comment]
https://go-zero.dev/cn/docs/goctl/zrpc#%E7%94%A8%E6%B3%95
goctl rpc protoc ./rpc/product.proto --go_out=./rpc --go-grpc_out=./rpc --zrpc_out=./rpc
