### ISSUE TITLE
Expect to support generics on API files, goctl go doc to generate nested structs

### ISSUE THREAD

**Issue by zundaren** [zeromicro/go-zero#1843]
![image](https://user-images.githubusercontent.com/44863479/165879877-5ae5ddb4-b0b4-48f3-ab3e-21a87aa1582d.png)
![image](https://user-images.githubusercontent.com/44863479/165879899-820c36ff-539c-448b-80b7-a4d54f6b787e.png)
![image](https://user-images.githubusercontent.com/44863479/165879971-f4f653ad-ba81-4270-8a7b-dd0bf615d94d.png)

生成接口文档时能够带上所有的字段

**Comment by kevwan** [comment]
Generics is not going to be supported in API, at least not in plan.
