### ISSUE TITLE
What is the default logx.LogConf.Mode

### ISSUE THREAD

**Issue by tim1116** [zeromicro/go-zero#1844]
when i use the log component of logx. I found the default  mode is File.  But I read the document found the document says That the default mode is console. I'm confused about that，so What is the default logx.LogConf.Mode?

https://github.com/zeromicro/go-zero/blob/3bbc90ec248bdcd3735d85692036360f7218c580/core/logx/logs.go#L152

![image](https://user-images.githubusercontent.com/9588681/165881200-5dfe8c2c-952c-4184-8484-de81f2f84283.png)

**Comment by kevwan** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/1918356/165881861-56d0ffb5-114f-4509-8168-33a8c3d50058.png">

Default is `console`.

**Comment by tim1116** [comment]
已经收到你的来信，我会尽快查阅的....

**Comment by tim1116** [comment]
`package main

import (
	"github.com/zeromicro/go-zero/core/logx"
	"time"
)

func main() {
	logx.MustSetup(logx.LogConf{
		//Mode: "console",
	})
	logx.CollectSysLog()

	line := "This is log message"
	logx.Info(line)
	logx.Error(line)
	logx.Alert(line)
	time.Sleep(time.Second)
}
`

I have written a demo code on the above. When using the default configuration it  will print ‘log path must be set’ 

![image](https://user-images.githubusercontent.com/9588681/165883671-094abd7c-cc5d-43de-bf76-6930e55b99c7.png)

**Comment by kevwan** [comment]
It's not default to `console`. You created `logx.LogConf` on your own, but we recommend to do that by loading config.yaml.

**Comment by tim1116** [comment]
OK thanks
