### ISSUE TITLE
JWT token is still take effect after the token is removed from redis( by call the method clear token)

### ISSUE THREAD

**Issue by Oxygenese** [zeromicro/go-zero#1848]
JWT token is still take effect after the token is removed from redis( by call the method clear token from redis)
I just configure the app of api with JwtAuth conponent like document.

(1)Geting a jwt token by calling the api of login.I can see the jwt token in redis. 
(2)Clearing the token by calling the api of logout.The token in redis has been cleared.
(3)Now I call an API that requires authentication, and the token is still valid.

I guess the built-in authentication middleware only uses "AccessSecret" to verify the token, but does not verify whether there is a corresponding token in redis.

Therefore, in the built-in scheme, the JWT token will only expire due to expiration, and the logout scheme needs to be implemented additionally.

**Comment by kevwan** [comment]
JWT token is stateless. Removing from redis doesn't affect the validation.

**Comment by smithyj** [comment]
在jwt token中增加session_id存储 把session_id再放redis里面存储就好了

**Comment by Oxygenese** [comment]
> JWT token is stateless. Removing from redis doesn't affect the validation.

Is there any other authentication scheme, such as oauth2?

**Comment by Oxygenese** [comment]
> 在jwt token中增加session_id存储 把session_id再放redis里面存储就好了
可以，这个方案没啥问题，谢谢啦

**Comment by chenchat** [comment]
> 

没太理解，能具体说说吗

**Comment by chenchat** [comment]
> > 在jwt token中增加session_id存储 把session_id再放redis里面存储就好了
> > 可以，这个方案没啥问题，谢谢啦

Bro, can you tell me more about how it worked out
