### ISSUE TITLE
Wrong filename with goctl api command

### ISSUE THREAD

**Issue by cmkcmk181** [zeromicro/go-zero#1850]
**Describe the bug**
使用goctl生成api时，如果使用group，生成的.go/.yaml文件名称会使用group定义的名称而不是根据.api的文件名生成相应文件名。

**Screenshots**
![360截图17891222657991](https://user-images.githubusercontent.com/8915324/166135806-027652a3-7649-48df-afd2-c2d84353bd74.png)

**Environments (please complete the following information):**
 - OS: [e.g. Windows]
 - go-zero version [e.g. 1.3.5]
 - goctl version [e.g. 1.3.5, optional]

**Comment by jiang4869** [comment]
我试了一下，并不是根据group名字生成的，而是根据service的名字生成的。你这个.go/.yaml跟group名字一样只是巧合。
![image](https://user-images.githubusercontent.com/44432198/166225480-84346b55-c0ff-4aea-a720-e7cac147bbc6.png)
