### ISSUE TITLE
Suggestion:  it's more idiomatic to  return pointer type instead of value type in logic.tpl 

### ISSUE THREAD

**Issue by cdz620** [zeromicro/go-zero#1859]
**Is your feature request related to a problem? Please describe.**
 it's more idiomatic to  return pointer instead of value in logic.tpl. more info: please refer to: [https://go.dev/doc/effective_go#allocation_new](https://go.dev/doc/effective_go#allocation_new).

Should be changed file: [genlogic.go](https://github.com/zeromicro/go-zero/blob/a40254156f/tools/goctl/api/gogen/genlogic.go#L29)

**Describe the solution you'd like**
```go 
func New{{.logic}}(ctx context.Context, svcCtx *svc.ServiceContext) {{.logic}} {
	return {{.logic}}{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}
``` 
should be change to 
```go
func New{{.logic}}(ctx context.Context, svcCtx *svc.ServiceContext) *{{.logic}} {
	return &{{.logic}}{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}
```

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by kevwan** [comment]
It's already returns pointer. Please upgrade your goctl.
