### ISSUE TITLE
goctl plug syntax problem---goland

### ISSUE THREAD

**Issue by zc24** [zeromicro/go-zero#1867]
![屏幕截图 2022-05-05 230334](https://user-images.githubusercontent.com/61010755/166954827-c8a2822b-40d0-4cb1-9188-3d3606675bbb.png)
![屏幕截图 2022-05-05 230501](https://user-images.githubusercontent.com/61010755/166954837-1e99537b-16df-4790-8020-a33e9ca80e33.png)
goctl插件版本1.1.1
goland版本2022.1

问题描述：提示“prefix: userapi/v1”这一行中，/v1不是期待的输入（extraneous input '/v1' expecting ')'）

问题代码如下:
```
@server(
	group: user
	prefix: userapi/v1
)
service user-api{
	@doc "获取用户信息"
	@handler userInfo
	post /user/info (UserInfoReq) returns (UserInfoResp)
```

**Comment by anqiansong** [comment]
You can post it under project https://github.com/zeromicro/goctl-intellij, thanks!
