### ISSUE TITLE
goctl bug， When the request parameter is empty, it should be removed here

### ISSUE THREAD

**Issue by zundaren** [zeromicro/go-zero#1874]
![image](https://user-images.githubusercontent.com/44863479/167255537-50ad4a2d-3968-4824-9223-2cb54857478e.png)

**Comment by re-dylan** [comment]
You can use this code in your template.
**{{if .HasRequest}}"github.com/zeromicro/go-zero/rest/httpx"{{end}}**

**Comment by zundaren** [comment]
> You can use this code in your template. **{{if .HasRequest}}"github.com/zeromicro/go-zero/rest/httpx"{{end}}**

yes, temporary rescue

**Comment by kevwan** [comment]
The default template is working incorrectly?

**Comment by zundaren** [comment]
> The default template is working incorrectly?

{{if .HasRequest}}"github.com/zeromicro/go-zero/rest/httpx"{{end}}  is ok, default template as the picture shows

**Comment by re-dylan** [comment]
> > The default template is working incorrectly?
> 
> {{if .HasRequest}}"github.com/zeromicro/go-zero/rest/httpx"{{end}} is ok, default template as the picture shows

https://github.com/zeromicro/go-zero/blob/master/tools/goctl/api/gogen/handler.tpl#L21

default template use **httpx.Error** as response,  so default should work fine.

You should change your handler.tpl  if you change resp.

**Comment by zundaren** [comment]
> > > The default template is working incorrectly?
> > 
> > 
> > {{if .HasRequest}}"github.com/zeromicro/go-zero/rest/httpx"{{end}} is ok, default template as the picture shows
> 
> https://github.com/zeromicro/go-zero/blob/master/tools/goctl/api/gogen/handler.tpl#L21
> 
> default template use **httpx.Error** as response, so default should work fine.
> 
> You should change your handler.tpl if you change resp.

is my problem
