### ISSUE TITLE
api error optional

### ISSUE THREAD

**Issue by zundaren** [zeromicro/go-zero#1876]
![image](https://user-images.githubusercontent.com/44863479/167259620-0af3481b-0769-4d8a-a254-5412d54194c0.png)

some function return don't want error, for example download -> http.ResponseWriter.write("666") , continue to return maybe 666{"code":"ok"} ， {"code":"ok"} do not expect 

![image](https://user-images.githubusercontent.com/44863479/167259801-5d3c70bc-3f07-461d-9eec-41c8478ee8ab.png)
Is it possible to configure the number of return values in the api file

**Comment by kevwan** [comment]
How to return the error to clients?

**Comment by zundaren** [comment]
> How to return the error to clients?

If I don't need error, don't show return error in logic， only execute http.ResponseWriter
if i need error, show return error in logic

**Comment by kevwan** [comment]
It's not only for server-side code. client side code is also generated from this api file.
