### ISSUE TITLE
Want the go-zero document to look like this 

### ISSUE THREAD

**Issue by feng99** [zeromicro/go-zero#1877]
![image](https://user-images.githubusercontent.com/13182572/167280154-90e82399-9205-42ac-9bfe-e911c86dd0d3.png)
![image](https://user-images.githubusercontent.com/13182572/167280168-10f48dba-e2e6-48c7-b46c-91168e23145c.png)
![image](https://user-images.githubusercontent.com/13182572/167280188-9214bba2-fde2-49ac-af31-7301d96ff23d.png)

The more detailed the documentation, the better.
thanks.

**Comment by zhenhua1** [comment]
赞同
