### ISSUE TITLE
Need for better documents.

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#1883]
希望作者能把文档给详细的给完善出来，最好能在出一个系列的课程，对于初接触go-zero是真心的很吃力

**Comment by aonoa** [comment]
You see see [go-zero-looklook](https://github.com/Mikaelemmmm/go-zero-looklook/)，害，我不装了，英语真不会，这个项目文档全面，b站上还有视频，然后公众号 And [go-zero.dev](https://go-zero.dev/cn/docs/prepare/prepare)，Look at the simple project source code，包括官方示例 [zero-examples](https://github.com/zeromicro/zero-examples)，最后就是不耻下问
