### ISSUE TITLE
The system reported cannot find the path specified when I used goctl

### ISSUE THREAD

**Issue by DavinciEvans** [zeromicro/go-zero#1894]
My PC is win10 and I was following thte quick start. When I used `goctl` to create a new api, it print `Stat : The system cannot find the path specified.` But when I used the command `goctl -h` alone, it can work well. 

![image](https://user-images.githubusercontent.com/45795384/167981658-9cd88a4b-1ef9-4b94-8bde-03a31d908e92.png)

And after I ran the command of creating new api, it created an .api file under the path,  no other files can be found.

![image](https://user-images.githubusercontent.com/45795384/167982918-67a888bf-23e0-474a-84ff-dfe7b70f5bc0.png)

I had suspected that it was an environment variable problem, but when I checked the environment variables there didn't seem to be any missing, otherwise I wouldn't have been able to see the goctl documentation. Is there an environment variable I'm missing?

My golang version is 1.16 and goctl version is 1.3.5

**Comment by anqiansong** [comment]
@DavinciEvans  It has been resolved on #1897

**Comment by chenweik** [comment]
use go env -w GO111MODULE=auto

**Comment by zhaoMing8** [comment]
I have this mistake too
Maybe your working directory is not in the system environment variable.

Please do this:

cd D:\Code\Go-pro
go mod init

goctl api new greet

**Comment by dyz1027543829** [comment]
First cd to your working directory D:\Code\Go-pro

Then create a go.mod file in your directory using:
go mod init greet

Finally use goctl to create a new api using:
goctl api new .
