### ISSUE TITLE
Don't put slaves in the config, slaves are used as backups.

### ISSUE THREAD

**Issue by cgc1983** [zeromicro/go-zero#1895]
Don't put slaves in the config, slaves are used as backups.

_Originally posted by @kevwan in https://github.com/zeromicro/go-zero/issues/1893#issuecomment-1124542341_

my redis cluster mode is cluster ,not sentinal . DOES go-zero support cluster ?

**Comment by kevwan** [comment]
> Don't put slaves in the config, slaves are used as backups.
> 
> 
> 
> _Originally posted by @kevwan in https://github.com/zeromicro/go-zero/issues/1893#issuecomment-1124542341_
> 
> 
> 
> my redis cluster mode is cluster ,not sentinal . DOES go-zero support cluster ?

Sure.

**Comment by cgc1983** [comment]
THIS is the error show in console 

got 4 elements in cluster info address, expected 2 or 3

**Comment by toventang** [comment]
> 

https://github.com/go-redis/redis/issues/2085
redis should downgrade to 6.2.7 currently, go-redis does not support 7.0 yet.
