### ISSUE TITLE
mssql conn QueryRowCtx with: sql.Name("id",id)); format stmt error

### ISSUE THREAD

**Issue by nicolaswumao** [zeromicro/go-zero#1896]
my code is 
```go
query := fmt.Sprintf("select top 1 %s from %s where id = @id ", userRows, m.table)
var resp User
err := m.conn.QueryRowCtx(ctx, &resp, query , sql.Name("id",id))
```
error at 
```go
go-zero/core/stores/sqlx/stmt.go
stmt, err := format(q, args...)
if err != nil

```

how can i solve it

**Comment by re-dylan** [comment]
https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/stmt_test.go#L28
plese see this demo

**Comment by nicolaswumao** [comment]
> https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/stmt_test.go#L28 plese see this demo
thanks,

placeholder: ?
it works as mysql but not in sqlserver/mssql

**Comment by WenTao-Love** [comment]
SOS,help.Me too!

**Comment by abnerwei** [comment]
> > https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/stmt_test.go#L28 plese see this demo
> > thanks,
> 
> placeholder: ? it works as mysql but not in sqlserver/mssql

mybe you can use `?`, `:`, `$`
