### ISSUE TITLE
GunzipHandler can not compress responsewriter,Most web frameworks support compress responsewriter

### ISSUE THREAD

**Issue by zundaren** [zeromicro/go-zero#1906]
![image](https://user-images.githubusercontent.com/44863479/168420328-80351b70-1856-40ca-8ca1-dcb498e13833.png)

**Comment by kevwan** [comment]
GunzipHandler uncompresses the incoming requests. Not for outgoing requests.

You can add a middleware to compress the output.

**Comment by zundaren** [comment]
> GunzipHandler uncompresses the incoming requests. Not for outgoing requests.
> 
> You can add a middleware to compress the output.

These functions should be included by default，users focus only on logic and config
