### ISSUE TITLE
Error while dialing dial tcp 127.0.0.1:2379: connectex: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by shizigou9000** [zeromicro/go-zero#1917]
$ go run lowcodeadmin.go -f etc/lowcodeadmin.yaml
Starting rpc server at 127.0.0.1:8080...
{"level":"warn","ts":"2022-05-20T09:09:06.128+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00013a000/127.0.0.1:2379","attempt":0,"error":"rpc error: code =
DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing
dial tcp 127.0.0.1:2379: connectex: No connection could be made because the target machine actively refused it.\""}
{"@timestamp":"2022-05-20T09:09:06.143+08:00","level":"error","content":"server.go:90 context deadline exceeded"}
panic: context deadline exceeded

goroutine 1 [running]:
github.com/zeromicro/go-zero/zrpc.(*RpcServer).Start(0x1feffc0)
        XXXX/go/pkg/mod/github.com/zeromicro/go-zero@v1.3.3/zrpc/server.go:91 +0x88
main.main()
        XXXXX/rpc/lowcodeadmin/lowcodeadmin.go:39 +0x2c5
exit status 2

**Comment by MaxToby** [comment]
please make sure that etcd is running

**Comment by shizigou9000** [comment]
> please make sure that etcd is running

ok
