### ISSUE TITLE
Can the generated handler and logic filenames be separated by an underscore?

### ISSUE THREAD

**Issue by zze326** [zeromicro/go-zero#1919]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MaxToby** [comment]
--style value   the file naming format, see [https://github.com/zeromicro/go-zero/tree/master/tools/goctl/config/readme.md]
``` shell
 goctl rpc proto -src test.proto -dir . -style go_zero
```
