### ISSUE TITLE
goctl 生成 Postgres model 不支持  type uuid 格式

### ISSUE THREAD

**Issue by Cincan** [zeromicro/go-zero#1920]
goctl version 1.3.5 
执行：  goctl model pg datasource -url="postgres://username:pwd@hostname:port/db?sslmode=disable" -table="tablename" -c -dir .
报错：unsupported database type: uuid
希望可以支持 uuid 格式的列。

**Comment by WenTao-Love** [comment]
哎……为什么中文提问了，到现在还没答复呢？咱们文化自信些，但愿go-zero团队不是崇洋媚外的！不然，我们得换框架了。
