### ISSUE TITLE
rpc not discovered after ETCD down and restarted

### ISSUE THREAD

**Issue by Lewis-liuwei** [zeromicro/go-zero#1926]
etcd崩溃的原因有可能是因为服务压力大造成的
重启之后，发现已经启动的rpc服务无法自动在etcd注册
然后手动重新启动所有rpc服务就可以了

**Comment by kevwan** [comment]
I tried many times, didn't get it reproduced.

What's the steps to reproduce it?

**Comment by laowenyi** [comment]
我们这边也出现了这种情况，复现步骤如下：
1. 开启一个服务，正常注册到etcd 中，观察etcd的节点  etcdctl get xxx_service --prefix=true,可以观察到注册成功
2. 切掉服务和etcd的网络，然后观察 注册的数据还在，但是租约到期之后节点就没了
3. 恢复网络，这时候是没法再次注册上去的，这样的话consumer会一直找不到注册的节点，这种情况下只能手动去重启服务，才能再次注册上去 @kevwan

**Comment by geata** [comment]
I have the same problem，follow the steps:
1. I have host A and host B
2. host A run etcd and rpc server
3. host B run the same rpc server
4. restart etcd
5. run  _etcdctl get --prefix ""_ 
the rpc server on host A have registed，but the one on host B not

**Comment by kevwan** [comment]
<img width="838" alt="image" src="https://github.com/zeromicro/go-zero/assets/1918356/4c658ba6-9e0b-44b5-b0f2-d3889e8e316d">
<img width="303" alt="image" src="https://github.com/zeromicro/go-zero/assets/1918356/c6614f31-97a1-4da5-b167-c448c872aa6c">

I tried injecting an network error and restarting etcd. But both worked well. Am I not right on the reproducing steps?
