### ISSUE TITLE
go mod tidy has a error

### ISSUE THREAD

**Issue by ChenArno** [zeromicro/go-zero#1930]
go: github.com/zeromicro/go-zero@v1.3.3 requires
	go.mongodb.org/mongo-driver@v1.9.0: verifying go.mod: go.mongodb.org/mongo-driver@v1.9.0/go.mod: Get "https://sum.golang.org/lookup/go.mongodb.org/mongo-driver@v1.9.0": dial tcp 142.251.43.17:443: i/o timeout

**Comment by kevwan** [comment]
GOPROXY?

**Comment by ChenArno** [comment]
yes ,is GOPROXY,thanks
