### ISSUE TITLE
Add "shorten.lua" file.

### ISSUE THREAD

**Issue by Dhuliang** [zeromicro/go-zero#1931]
Following [https://github.com/zeromicro/zero-doc/blob/47c959da3c9938dbccefb565c3bddce232807299/website/i18n/en/docusaurus-plugin-content-docs/current/extension/shorturl.md](url) example, last step I want to test benchmark.

Use `wrk -t10 -c1000 -d30s -s shorturl.lua --latency "http://localhost:8888"`, it turns `shorturl.lua: cannot open shorturl.lua: No such file or directory`, please add `shorturl.lua` for testing.

**Comment by tommy921092** [comment]
I encountered the same problem forllowing the example. I think the team should include the shorturl.lua file as not all knows what to input in the lua file.

**Comment by kevwan** [comment]
Because wrk has some bugs on last requests before stopping. We turned into the tool hey. I can't find the shorturl.lua. It's just a simple test script.
