### ISSUE TITLE
The ability to customize getLogHandler

### ISSUE THREAD

**Issue by kunyu** [zeromicro/go-zero#1932]
当前log 很难满足我的需求，比如我希望在每个请求中加入user_id字段，方便查找问题，但是现在我完全没有办法

**Comment by kevwan** [comment]
下一个版本就完全可定制了

**Comment by kunyu** [comment]
下个礼拜什么时候会发布呢

**Comment by kevwan** [comment]
端午节

**Comment by kunyu** [comment]
关于redis db可选择的问题 会有什么结论吗？我希望作为框架 应该要提供这样的能力 但是可以建议用同一个
