### ISSUE TITLE
joint primary key not supported

### ISSUE THREAD

**Issue by xminao** [zeromicro/go-zero#1945]
When my table structure has a joint primary key, there will be an error when using goctl model and cannot be generated.
err: _"db: db:public, table:table_2, joint primary key is not supported"_
Is there any solution?

**Comment by jsonMark** [comment]
show more detail

**Comment by anqiansong** [comment]
Code generation does not support for joint primary key

**Comment by jjkoh95** [comment]
Hi
I faced similar issue with this, Is there a plan to have this feature?
Happy to take a look into this

**Comment by xminao** [comment]
> Hi I faced similar issue with this, Is there a plan to have this feature? Happy to take a look into this

Hi!
I didn't use the joint primary key afterwards.
But if you want several keys to joint without duplication, try to use UNIQUE constraints, it solved my problem.  
Hope it helps. : )

**Comment by jjkoh95** [comment]
Thanks for your prompt response!
I decided to move ahead with `gorm-gen`, but I hope this will be supported in go-zero ecosystem so I can use a single generator to keep my code base consistent (also without modifying my current table structures)
Thanks once again
