### ISSUE TITLE
Will go-zero support static resource services in future versions?

### ISSUE THREAD

**Issue by licat233** [zeromicro/go-zero#1949]
Will go-zero support static resource services in future versions?

**Comment by re-dylan** [comment]
Static resource can just use nginx  or  oss.

**Comment by licat233** [comment]
> Static resource can just use nginx or oss.  

Yes, this is the only way to do it at present.  
Will it not be supported in the future version of go zero?

**Comment by kevwan** [comment]
https://github.com/zeromicro/zero-examples/tree/main/http/download

Is this what you want?

**Comment by licat233** [comment]
> https://github.com/zeromicro/zero-examples/tree/main/http/download
> 
> Is this what you want?

Dear Kevwan, thank you for your reply!!  
Sorry，This is not what I want.

What I want is this:
```go
package main
import "net/http"
func main() {
	http.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("assets"))))
	http.ListenAndServe(":8080", nil)
}
```
## But I don't know how to realize it with go-zero

**Comment by kevwan** [comment]
https://github.com/zeromicro/zero-examples/tree/main/http/static

**Comment by licat233** [comment]
> https://github.com/zeromicro/zero-examples/tree/main/http/static

Thank you very much for your help！

**Comment by slrem** [comment]
> https://github.com/zeromicro/zero-examples/tree/main/http/static

No recursion！There are more folders in the folder！
