### ISSUE TITLE
goctl 1.3.2 execute goctl api go -api xxx.api -dir ../../ -style goZero very slow

### ISSUE THREAD

**Issue by qxdo** [zeromicro/go-zero#1955]
goctl version: 1.3.2
system: Windows Feature Experience Pack 120.2212.3920.0 (windows 10)
execute: goctl api go -api xxx.api -dir ../../ -style goZero
I want know, this command execute is very slow, take almost 1minutes, before this goctl version, took less than 10s, is there some update can slow it down? or just normal?

**Comment by anqiansong** [comment]
@qxdo No performance changes have been made, you can communicate with me on WeChat in the community group, I will check it for you
