### ISSUE TITLE
log format and log output file

### ISSUE THREAD

**Issue by lrtxpra** [zeromicro/go-zero#1974]
1: I think the json output format doesn't see the output fields in the log very well. so I wrap zap by adding customized encoder, and use logx.Disable to shutdown go-zero inner logs. but then stat log disappear. i wanna get stat log.(is there any way to get stat?)
2: usually info log and warning log output to different files will be easy to check situation that code running. but it seems that logx could not support different output files.(I checked all docs but did not find any description)

**Comment by kevwan** [comment]
You can customize the logging with go-zero v1.3.4
