### ISSUE TITLE
more powerful request validation

### ISSUE THREAD

**Issue by qwernser** [zeromicro/go-zero#1986]
please allow users to define/pass custom validation functions into httpx.Parse(), or add regex support in tag modifier

**Comment by re-dylan** [comment]
You cant just verify req by yourself. add verification in handler. like this:

```go
func loginHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.LoginReq
		if err := httpx.Parse(r, &req); err != nil {
			httpx.Error(w, err)
			return
		}
	        if err := verify(req); err != nil {
			httpx.Error(w, err)
			return
		}

		// ....
	}
}
```

You can use template add your code.

**Comment by qwernser** [comment]
> You cant just verify req by yourself.

I think you mean "You CAN just ..." here



> You can use template add your code.

yes, but I believe built in support is preferred by a lot of users
