### ISSUE TITLE
support import go package in the .api, so that i can reuse model data struct in the response struct

### ISSUE THREAD

**Issue by zhaomin1993** [zeromicro/go-zero#1989]
now i need defined twice the same struct in the different package, and then use copy value in other struct, it's very unfriendly

**Comment by re-dylan** [comment]
We won't support this. zero-api is a RESTful API description language. 
It can't import go file.

**Comment by joshq00** [comment]
Can you copy your `MyType` definition into the .api file and use `types.MyType` in the original location?

**Comment by gaochuwuhan** [comment]
if response data is a complex nested data structure from other package  i would like to return in a gozero api , thats 's a big engining to re-define in .api file
