### ISSUE TITLE
Get resulting http.Handler?

### ISSUE THREAD

**Issue by joshq00** [zeromicro/go-zero#1991]
We run our API on AWS Lambda using [Lambda go API proxy](https://github.com/awslabs/aws-lambda-go-api-proxy) 

To use this, you pass a handler function and it does a conversion of the lambda event to match `http.Request` and runs it through your handler as normal.

I'm not able to find a way to get the server's resulting handler. We don't want to run a server, just use the mux. Is there a way we can achieve this?

**Comment by re-dylan** [comment]
Yes, go-zero not support this  for now.
It seems [Lambda go API proxy](https://github.com/awslabs/aws-lambda-go-api-proxy) just use middleware handler, you can wrap handler by yourself. Just like this.

```go
package main

import (
	"net/http"

	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/httpadapter"
	"github.com/justinas/alice"
	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/handler"
	"github.com/zeromicro/go-zero/rest/httpx"
	"github.com/zeromicro/go-zero/rest/router"
)

func main() {
	r := router.NewRouter()
	builderHandler(r, rest.Route{
		Method:  http.MethodPost,
		Path:    "/ping",
		Handler: nil, // logic handler
	})

	lambda.Start(httpadapter.New(r).ProxyWithContext)
}

func builderHandler(r httpx.Router, route rest.Route) {
	// add what you need
	chain := alice.New(
		handler.TracingHandler("demo", route.Path),
		handler.PrometheusHandler(route.Path),
		//handler.MaxConns(ng.conf.MaxConns),
		//handler.BreakerHandler(route.Method, route.Path, metrics),
		//handler.SheddingHandler(ng.getShedder(fr.priority), metrics),
		//handler.TimeoutHandler(ng.checkedTimeout(fr.timeout)),
		handler.RecoverHandler,
		//handler.MetricHandler(metrics),
		//handler.MaxBytesHandler(ng.checkedMaxBytes(fr.maxBytes)),
		handler.GunzipHandler,
	)
	handle := chain.ThenFunc(route.Handler)

	err := r.Handle(route.Method, route.Path, handle)
	if err != nil {
		panic(err)
	}
}

```

**Comment by joshq00** [comment]
Thanks. Sadly I'll miss out on the generated code.

Would you be opposed to a PR that adds something like `RegisterRoutes` to the generated service?

After [RegisterHandlers](https://github.com/zeromicro/go-zero/blob/c27e00b45cd9e7eba825ed7cfea5e7e76bb0de3b/tools/goctl/api/gogen/genroutes.go#L33) it could have a function that receives a `Router` and `ServiceContext`?

**Comment by joshq00** [comment]
Perhaps extract this template https://github.com/zeromicro/go-zero/blob/c27e00b45cd9e7eba825ed7cfea5e7e76bb0de3b/tools/goctl/api/gogen/genroutes.go#L23-L41 into a file that I can use with `goctl api go --home`?
