### ISSUE TITLE
Desire for vim/nvim plugin like intellij/vscode

### ISSUE THREAD

**Issue by fourierrr** [zeromicro/go-zero#2000]
I notice that there are vscode and intellij plugin for go-zero

is there any **vim/nvim** plugin for .api file

just want some basic feature like

- hightlight
- autocompelet
- format

many thanks!

**Comment by jinying-che** [comment]
+1

**Comment by qmarliu** [comment]
+1

**Comment by jiz4oh** [comment]
hi @kevwan, could you consider this? this will help more developer
