### ISSUE TITLE
go-zero(http grateful stop Problem --->proc.AddWrapUpListener)---Goversion 1.17

### ISSUE THREAD

**Issue by Danny5487401** [zeromicro/go-zero#2015]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/64348131/173492551-02da6b13-1107-4138-8cf6-b9490f2715d3.png">

![image](https://user-images.githubusercontent.com/64348131/173496530-7d83e4cf-76e9-4921-a6d8-d7b2d1d6683e.png)

@kevwan 请问官方这个errwe为nil设计打印是否正确？为啥如此设计？

**Comment by re-dylan** [comment]
Yes, It should be , you can make a pr
```go
if e := server.Shutdown(context.Background()); e != nil {
    logx.Error(e)
}
```

**Comment by Danny5487401** [comment]
> Yes, It should be ：
> 
> ```go
> if e := server.Shutdown(context.Background()); e != nil {
>     logx.Error(e)
> }
> ```
> 
> you can make a pr

that is exactly what i thought of!

**Comment by kevwan** [comment]
> > Yes, It should be ：
> > ```go
> > if e := server.Shutdown(context.Background()); e != nil {
> >     logx.Error(e)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you can make a pr
> 
> that is exactly what i thought of!

PR please!

**Comment by Danny5487401** [comment]
> > > Yes, It should be ：
> > > ```go
> > > if e := server.Shutdown(context.Background()); e != nil {
> > >     logx.Error(e)
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > you can make a pr
> > 
> > 
> > that is exactly what i thought of!
> 
> PR please!

@kevwan  By the way, i have to add 5 seconds to stop gracefully!
![image](https://user-images.githubusercontent.com/64348131/174927967-b951445c-94e9-424b-9bf6-d77fbc4d516b.png)

**Comment by kevwan** [comment]
Do you mean logs are lost?

**Comment by Danny5487401** [comment]
when i have 5 seconds to stop,it will be ok .
![image](https://user-images.githubusercontent.com/64348131/175192168-86b232e2-1a01-4196-ba7f-ffbf08820696.png)

by by contrast,i do not have 5 seconds to leave, main goroutine will go away immediately, i cannot release the sentry resource.
![image](https://user-images.githubusercontent.com/64348131/175192524-28d3ebbb-efae-4570-9883-8a13b73229d5.png)

![image](https://user-images.githubusercontent.com/64348131/175193132-daac2d1e-62c3-4a5b-bfcd-f2c2b5a98dda.png)
i suggest the signal goroutine should not be set in the child goroutine and putting addtional 5 seconds in the main goroutine.
