### ISSUE TITLE
Problems about etcd key when upgrading to version 1.3.4

### ISSUE THREAD

**Issue by LorinHan** [zeromicro/go-zero#2017]
In version 1.3.2, I used etcd key:/aihc/xxx rpc. When upgrading to version 1.3.4, the dependent service has such an error: rpc dial: discov://127.0.0.1:2379//aihc/xxx.rpc , error: context deadline exceeded, make sure rpc service "xxx.rpc" is already started.

**Comment by pitifulnoble** [comment]
+1
{"@timestamp":"2022-06-27T21:51:56.273+08:00","caller":"zrpc/server.go:90","content":"context deadline exceeded","level":"error"}
panic: context deadline exceeded

goroutine 1 [running]:
github.com/zeromicro/go-zero/zrpc.(*RpcServer).Start(0x2994bc0?)
        /Users/bytedance/go/pkg/mod/github.com/zeromicro/go-zero@v1.3.4/zrpc/server.go:91 +0x85
main.main()
        /Users/bytedance/tools/code/study/shorturl/rpc/transform/transform.go:39 +0x2c5

**Comment by pitifulnoble** [comment]
> 

➜  api nmap 127.0.0.1 -p2379
Starting Nmap 7.91 ( https://nmap.org ) at 2022-07-01 13:32 CST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00021s latency).

PORT     STATE SERVICE
2379/tcp open  etcd-client

Nmap done: 1 IP address (1 host up) scanned in 0.16 seconds

then etcd is started

**Comment by fyyang** [comment]
emmm 有答案了吗?
