### ISSUE TITLE
go-zero api WithNotFoundHandler & WithNotAllowedHandler 未兼容 WithCustomCors & WithCors

### ISSUE THREAD

**Issue by smithyj** [zeromicro/go-zero#2018]
在 go-zero 中对 NotFoundHandler & NotAllowedHandler 的这种情况进行了封装
![image](https://user-images.githubusercontent.com/9820142/173626841-6949f898-7e5e-4e04-8784-fa009e68d318.png)
正常可到达请求返回 Header 如下
![image](https://user-images.githubusercontent.com/9820142/173626719-d208ac2d-c08a-41f2-bfec-beeafc67570b.png)
但是在请求 NotFoundHandler & NotAllowedHandler 不存在的链接时，没有出现 Cors Header 头信息，这样就会导致前端跨域报错，然后整个开发体验会不是很友好
![image](https://user-images.githubusercontent.com/9820142/173627213-e08e0353-78b5-407e-ab13-b7efbeba8613.png)

**Comment by smithyj** [comment]
周末我看看能否提个PR，这块的实现目前确实不优雅

**Comment by chowyu12** [comment]
我有同样的问题

**Comment by smithyj** [comment]
@chowyu12 跟踪下这个PR合并进度就好了，不知道万总会不会在下一个版本调整 #2023
