### ISSUE TITLE
how to get path params?

### ISSUE THREAD

**Issue by zlx362211854** [zeromicro/go-zero#2022]
I am new to GO and I would like to ask how do I get the parameters on the route as in the following example?

```go
{
  Method:  http.MethodPut,
  Path:    "/task/:id",
  Handler: TaskUpdateHandler(serverCtx),
},
```

Then send the request below

```
PUT /task/62907b47e8e2104acc7eaac1
```

how do i get the key in go-zero `62907b47e8e2104acc7eaac1` ?

**Comment by smithyj** [comment]
@zlx362211854 [API语法](https://go-zero.dev/docs/design/grammar#:~:text=json%3A%22fooo%22-,path,-Routing%20path%2C%20such)

**Comment by jsonMark** [comment]
> I am new to GO and I would like to ask how do I get the parameters on the route as in the following example?
> 
> ```go
> {
>   Method:  http.MethodPut,
>   Path:    "/task/:id",
>   Handler: TaskUpdateHandler(serverCtx),
> },
> ```
> 
> Then send the request below
> 
> ```
> PUT /task/62907b47e8e2104acc7eaac1
> ```
> 
> how do i get the key in go-zero `62907b47e8e2104acc7eaac1` ?
.api文件对应请求体定义一个对应的id ，就是接收这个参数的
type Foo{
    Id int `path:"id"`
}

**Comment by zlx362211854** [comment]
> @zlx362211854 [API语法](https://go-zero.dev/docs/design/grammar#:~:text=json%3A%22fooo%22-,path,-Routing%20path%2C%20such)

thank you so much
