### ISSUE TITLE
`\u003cnil\u003e` error for api server

### ISSUE THREAD

**Issue by brickzzhang** [zeromicro/go-zero#2052]
**Describe the bug**
each time when api server shutdown, it will produce an error log with content: `\u003cnil\u003e`. 

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```json
   {
    "level":"error",
    "content":"\u003cnil\u003e"
}
   ```

**Expected behavior**
No error should be logged.

**Screenshots**

**Environments (please complete the following information):**
 - OS: linux
 - go-zero version: v1.3.4
 - goctl version: N/A

**More description**
As checked go-zero source code, don't understand why it uses `err` variable instead of `e`, as `err` will always be `http.ErrServerClosed` when server exit normally. Suppose it might be a bug, on the row 42. Source codes are like below:

```go
func start(host string, port int, handler http.Handler, run func(svr *http.Server) error,
	opts ...StartOption) (err error) {
	server := &http.Server{
		Addr:    fmt.Sprintf("%s:%d", host, port),
		Handler: handler,
	}
	for _, opt := range opts {
		opt(server)
	}

	waitForCalled := proc.AddWrapUpListener(func() {
                //  *********** why using err here instead of e ************
		if e := server.Shutdown(context.Background()); err != nil {
			logx.Error(e)
		}
	})
	defer func() {
		if err == http.ErrServerClosed {
			waitForCalled()
		}
	}()

	return run(server)
}
```

source code file: `github.com/zeromicro/go-zero/rest/internal/starter.go`

**Comment by re-dylan** [comment]
Yes, you can make a pr fix this error.

**Comment by kevwan** [comment]
fixed.

**Comment by Xuan-Goldenf** [comment]
![image](https://user-images.githubusercontent.com/40749214/182280212-4d4538da-e32f-4573-9ceb-c086576af92c.png)

I noticed the variable "err" is from return, so how it is work?.
![image](https://user-images.githubusercontent.com/40749214/182281164-65e05ab5-2b34-4283-b1f2-a87f55bb299b.png)
it should look like this.

**Comment by brickzzhang** [comment]
> ![image](https://user-images.githubusercontent.com/40749214/182280212-4d4538da-e32f-4573-9ceb-c086576af92c.png)
> 
> I noticed the variable "err" is from return, so how it is work?. ![image](https://user-images.githubusercontent.com/40749214/182281164-65e05ab5-2b34-4283-b1f2-a87f55bb299b.png) it should look like this.

Agree with you, this one looks more reasonable.
