### ISSUE TITLE
use Mapreduce  lead to sort disable

### ISSUE THREAD

**Issue by Holyson** [zeromicro/go-zero#2053]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by re-dylan** [comment]
You can sort after mr.

**Comment by Holyson** [comment]
> You can sort after mr.

can you give me a example?
i after mapreduce use the sort.SliceStable, total cost 1.3~1.5 s,so long
