### ISSUE TITLE
In etc yaml file, when use ${} replace value failed

### ISSUE THREAD

**Issue by chaozwn** [zeromicro/go-zero#2054]
**Describe the bug**
I doubt if the replacement fails because of options[node,cluster], other variables are normal.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

![image](https://user-images.githubusercontent.com/51357674/175988520-f7875a83-ecd2-4cc0-9c65-d42f81c0770d.png)
![image](https://user-images.githubusercontent.com/51357674/175988615-da3814b7-27c0-4383-b7e7-f45799e44916.png)

**Comment by kevwan** [comment]
conf.UseEnv()

**Comment by chaozwn** [comment]
> conf.UseEnv()

thanks, it's great.
