### ISSUE TITLE
goctl model mongo not generated correctly.

### ISSUE THREAD

**Issue by czyt** [zeromicro/go-zero#2062]
I use command to generate mongo model
```bash
goctl model mongo -t User  --dir .
```
two files generated,but it seems not using the tpl file embed in the source code.
expect
![1ab8a424b5ddffbad162bd517d8b608](https://user-images.githubusercontent.com/19337206/176341657-5b5bc167-3ae8-4fa7-992a-0112fdf7195a.png)
but get
![e0efae493fb962ef16020f2b157fcc8](https://user-images.githubusercontent.com/19337206/176341677-3989a41f-2879-4d21-8f4b-a597098381af.png)
I use `goctl template update -c model` and `goctl template clean` but still the same.

**Comment by czyt** [comment]
using my forked version source code compiled,run the same command worked as expect

**Comment by anqiansong** [comment]
What's your goctl version ?  the latest mongo code generation is still on branch master, it does not release.

**Comment by czyt** [comment]
> generation

v 1.3.8
