### ISSUE TITLE
Install goctl error and Command 'goctl' not found

### ISSUE THREAD

**Issue by ximury** [zeromicro/go-zero#2075]
My go version is go1.18.3 linux/amd64

I had did these:
$ go get -u github.com/zeromicro/go-zero
$ go get -u github.com/zeromicro/go-zero/tools/goctl
$ goctl

Command 'goctl' not found, did you mean:

  command 'doctl' from snap doctl (v1.77.0)

See 'snap info <snapname>' for additional versions.

$ go install github.com/zeromicro/go-zero/tools/goctl

# github.com/zeromicro/ddl-parser/gen
../../go/pkg/mod/github.com/zeromicro/ddl-parser@v1.0.3/gen/mysql_lexer.go:6585:32: lexerDeserializer.DeserializeFromUInt16 undefined (type *antlr.ATNDeserializer has no field or method DeserializeFromUInt16)
../../go/pkg/mod/github.com/zeromicro/ddl-parser@v1.0.3/gen/mysql_parser.go:4071:34: deserializer.DeserializeFromUInt16 undefined (type *antlr.ATNDeserializer has no field or method DeserializeFromUInt16)

How deal with it?

**Comment by jsonMark** [comment]
show you go version and see you gopath/bin checkout goctl 

if not exsist ,please exec 
go install github.com/zeromicro/go-zero/tools/goctl@latest
