### ISSUE TITLE
文档应该严谨稳重，这段“解放我们的双手👈”应该删掉或者换个描述

### ISSUE THREAD

**Issue by kybom** [zeromicro/go-zero#2076]
> 
>安装 goctl 工具
>
>goctl 读作 go control，不要读成 go C-T-L。goctl 的意思是不要被代码控制，而是要去控制它。其中的 go 不是指 golang。在设计 goctl >之初，我就希望通过 她 来解放我们的双手👈

最后一句可能给人感觉不好。

**Comment by zhibisora** [comment]
xs 确实有可能让人产生奇怪的联想  还是变一下吧
