### ISSUE TITLE
docker log not working well on `mode: volume` in docker.

### ISSUE THREAD

**Issue by whoneed** [zeromicro/go-zero#2095]
Mode: volume 

go-zero:v1.2.1，能正常输出
升级到:v1.3.4，在指定目录，能正常创建文件，但是文件内容一直为空。

**Comment by whoneed** [comment]
进入到相应的docker容器中，目录也已经正常挂载

**Comment by whoneed** [comment]
docker同样目录挂载，go-zero:v1.2.1，是正常的。v1.3.4就不能正常输出

**Comment by whoneed** [comment]
go-zero，版本退回到V1.3.3，就是正常的。

**Comment by kevwan** [comment]
Any example code and configuration details?

**Comment by whoneed** [comment]
// =======================  config.yaml
####### Log
Log:
  ServiceName: gate-api
  Mode: volume
  Path: /data/log
  KeepDays: 7

// ======================= svc/*
logx.Info()

// ======================= logic/*
l.Info()

//======================== main.go
func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)

	ctx := svc.NewServiceContext(c)
	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	handler.RegisterHandlers(server, ctx)

	fmt.Printf("Starting server at %s:%d...\n", c.Host, c.Port)
	server.Start()
}

**Comment by whoneed** [comment]
知道原因了，需要reset()一下
