### ISSUE TITLE
why hard code here?

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#2100]
https://github.com/zeromicro/go-zero/blob/fabea4c4485ad5223b375e62f6d46fdffb7da81c/tools/goctl/model/sql/gen/insert.go#L34

**Comment by anqiansong** [comment]
That's a default principle to ignore `create_time` and `update_time` while create or update data, you should add a constraint `NOT NULL DEFAULT TIMESTAMP` on columns `create_time` and `update_time` .

**Comment by anqiansong** [comment]
I am looking for a solution to solve it.
