### ISSUE TITLE
can we use grpcurl to test zrpc server api

### ISSUE THREAD

**Issue by waltcow** [zeromicro/go-zero#2103]
How can we use [grpcurl](https://github.com/fullstorydev/grpcurl) (Command-line tool for interacting with gRPC servers like curl) to test zrpc api in development ?

**Comment by waltcow** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3941174/177733647-34ddb24b-b234-438b-af42-0581ac8048ab.png">

after enable grpc reflection flag in dev mode, problem solved

**Comment by kevwan** [comment]
It's built inside.
