### ISSUE TITLE
ID, UpdateAt,CreateAt not automatically generated when inserting data with mongo

### ISSUE THREAD

**Issue by MiHuaaaaaaaa** [zeromicro/go-zero#2134]
**Describe the bug**
ID, UpdateAt,CreateAt not automatically generated when inserting data with mongo

**To Reproduce**
Steps to reproduce the behavior, if applicable:
Using the goctl model mongo generated Insert function

1. The code is

   ```go

        user = &model.User{Phone: req.Phone, Password: password}

	if err = l.svcCtx.UserModel.Insert(l.ctx, user); err != nil {
		return nil, err
	}

   
        func (m *defaultUserModel) Insert(ctx context.Context, data *User) error {
	      if !data.ID.IsZero() {
		      data.ID = primitive.NewObjectID()
		      data.CreateAt = time.Now()
		      data.UpdateAt = time.Now()
	      }
      
	      _, err := m.conn.InsertOne(ctx, data)
	      return err
      }
   ```

2. The error is

   ```
   info 	mongo(users) - InsertOne - ok - [{"id":"000000000000000000000000","updateAt":"0001-01-01T00:00:00Z","createAt":"0001-01-01T00:00:00Z","phone":"xxxxxx","password":"333130"}]
   ```

**Expected behavior**
ID, UpdateAt,CreateAt can be generated automatically
**Screenshots**
<img width="681" alt="image" src="https://user-images.githubusercontent.com/54028379/178457380-37f25d77-77bf-406f-a5fc-8bde455a252f.png">

**Environments (please complete the following information):**
 - OS: mac 
 - go-zero version v1.3.5
 - goctl version 1.3.9 darwin/arm64

**Comment by czyt** [comment]
改为
```go
func (m *defaultUserModel) Insert(ctx context.Context, data *User) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}
```
应该就正确了 @MiHuaaaaaaaa
