### ISSUE TITLE
Feature Request: logx: support Debug level (or addtional logging levels)

### ISSUE THREAD

**Issue by janosmiko** [zeromicro/go-zero#2135]
**Is your feature request related to a problem? Please describe.**
Many of the widely used external logging libraries in go support multiple logging levels on top of the defaults (info, error, fatal), like debug, trace and others.
- https://pkg.go.dev/go.uber.org/zap#Logger.Debug
- https://github.com/sirupsen/logrus#level-logging
- https://github.com/rs/zerolog#leveled-logging

I think it would be useful to have at least one additional logging level for debugging purposes to hide "code smell".
Use case: 
- log information for regular users using logx.Info()
- log debug information in special cases for developers using logx.Debug() - and enable these logs using a logx_debug configuration/environment variable

**Describe the solution you'd like**
Provide support for Debug logging in logx.

**Describe alternatives you've considered**
Support general implementation of custom logging levels instead of specializing to the debug level. I think this would be a bigger effort and I'm not sure if there's a huge need for this.

**Comment by StellarisW** [comment]
I really want this too.

**Comment by keroro6** [comment]
I really want this too.
