### ISSUE TITLE
报etcd的错误，线上服务全部重启了，请问我应该用Etcd的哪个版本比较稳定？

### ISSUE THREAD

**Issue by whoneed** [zeromicro/go-zero#2138]
{"level":"warn","ts":"2022-07-13T11:30:47.622+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000558540/xx-etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"info","ts":"2022-07-13T11:31:08.717+0800","logger":"etcd-client","caller":"v3@v3.5.4/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
{"level":"warn","ts":"2022-07-13T11:31:50.606+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000558540/xx-etcd:2379","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}

**Comment by whoneed** [comment]
go-zero: v.1.3.4

**Comment by kevwan** [comment]
How many nodes of the etcd cluster?
