### ISSUE TITLE
v1.3.3 之后，慢请求会无响应，但日志输出正常响应 200

### ISSUE THREAD

**Issue by zze326** [zeromicro/go-zero#2140]
![image](https://user-images.githubusercontent.com/49554487/178881881-51c3bbf8-c9ab-4e2c-aeef-389675dac4be.png)
![image](https://user-images.githubusercontent.com/49554487/178882020-120d201d-ae64-403e-92a1-cce723ef364f.png)
![image](https://user-images.githubusercontent.com/49554487/178882077-662b986b-b974-4534-95ae-96133af6012f.png)
![image](https://user-images.githubusercontent.com/49554487/178882184-82b3c96e-274a-49ad-be43-6f9fbd9c67ee.png)

**Comment by miaogaolin** [comment]
我测试了下，如果说的不对，可以提出来：
api 文件中的超时配置，决定的是局部请求
conf 配置文件中 Timeout 值决定的是全局，而这个值默认 3s ，所有要保证 conf 中的Timeout （单位毫秒）配置大于 @server 中的超时配置
![image](https://user-images.githubusercontent.com/57740293/178946546-7931514e-9ca0-49c6-ba0d-c5f456c7dac6.png)

**Comment by zze326** [comment]
> 我测试了下，如果说的不对，可以提出来： api 文件中的超时配置，决定的是局部请求 yaml 配置文件中 Timeout 值决定的是全局，而这个值默认 3s ，所有要保证 yaml 文件中的Timeout （单位毫秒）配置大于 @server 中的超时配置 ![image](https://user-images.githubusercontent.com/57740293/178946546-7931514e-9ca0-49c6-ba0d-c5f456c7dac6.png)

不合理，应该是允许局部（@server）覆盖全局（yaml），而且输出的响应日志和实际响应报文也不一致，且 v1.3.3（含） 之前没有这个问题，所以我认为这是一个 bug

**Comment by smithyj** [comment]
> > 我测试了下，如果说的不对，可以提出来： api 文件中的超时配置，决定的是局部请求 yaml 配置文件中 Timeout 值决定的是全局，而这个值默认 3s ，所有要保证 yaml 文件中的Timeout （单位毫秒）配置大于 @server 中的超时配置 ![image](https://user-images.githubusercontent.com/57740293/178946546-7931514e-9ca0-49c6-ba0d-c5f456c7dac6.png)
> 
> 不合理，应该是允许局部（@server）覆盖全局（yaml），而且输出的响应日志和实际响应报文也不一致，且 v1.3.3（含） 之前没有这个问题，所以我认为这是一个 bug

赞同这个说法，局部的应该覆盖全局

**Comment by kevwan** [comment]
Will work on it.
