### ISSUE TITLE
go-zero@v1.3.5 init greet demo fail

### ISSUE THREAD

**Issue by JackRanGitHub** [zeromicro/go-zero#2142]
**Describe the bug**
go-zero@v1.3.5 init greet demo fail

**Screenshots**
![Uploading image.png…]()

**Environments (please complete the following information):**
 - OS: [windows]
 - go-zero version [1.18.3]
 - goctl version [1.2.2 windows/amd64]

**Comment by JackRanGitHub** [comment]
$ go.exe mod tidy
go: finding module for package github.com/tal-tech/go-zero/core/logx
go: finding module for package github.com/tal-tech/go-zero/rest
go: finding module for package github.com/tal-tech/go-zero/core/conf
go: finding module for package github.com/tal-tech/go-zero/rest/httpx
go: found github.com/tal-tech/go-zero/core/conf in github.com/tal-tech/go-zero v1.3.5
go: found github.com/tal-tech/go-zero/rest in github.com/tal-tech/go-zero v1.3.5
go: found github.com/tal-tech/go-zero/rest/httpx in github.com/tal-tech/go-zero v1.3.5
go: found github.com/tal-tech/go-zero/core/logx in github.com/tal-tech/go-zero v1.3.5
go: greet imports
        github.com/tal-tech/go-zero/core/conf: github.com/tal-tech/go-zero@v1.3.5: parsing go.mod:
        module declares its path as: github.com/zeromicro/go-zero
                but was required as: github.com/tal-tech/go-zero

**Comment by kevwan** [comment]
You're using old version of goctl. Upgrade your goctl and retry.

**Comment by JackRanGitHub** [comment]
Ok,Thanks
