### ISSUE TITLE
goctl api code generation error encountered.

### ISSUE THREAD

**Issue by csh995426531** [zeromicro/go-zero#2164]
**Describe the bug**
Code generation error encountered.

**To Reproduce**
I use the command：

1. The code is

   ```goctl api go --api "./service/api/shiva.api" --dir "./service/api" --home "./service/api/.goctl"```

2. The error is

   ```2022/07/18 12:34:57 template: handlerTemplate:6:6: executing "handlerTemplate" at <.After1_1_10>: can't evaluate field After1_1_10 in type gogen.handlerInfo```

**Expected behavior**
success

**Screenshots**
![image](https://user-images.githubusercontent.com/23441583/179446393-d05dc2f1-12b9-4d03-88c3-e1d4dff4d9a5.png)

**Environments (please complete the following information):**
 - OS: mac os
 - go-zero version v1.3.4
 - goctl version  v1.3.9

**More description**

**Comment by 664485186** [comment]
I had the same problem

**Comment by 664485186** [comment]
How do you solve this problem

**Comment by 664485186** [comment]
goctl version 1.3.9 windows/amd64

**Comment by 664485186** [comment]
There is a problem in 1.3.9. If you go back to 1.3.8, you will be fine

**Comment by kevwan** [comment]
Try it in v1.4.0

**Comment by linbuxiao** [comment]
> Try it in v1.4.0

still error

**Comment by anqiansong** [comment]
If you are a custom template, you can refer to the latest handler.tpl content to adjust the latest template has been moved out of the `After1_1_10` variable, if not a custom template please first execute `goctl template clean`, and then `goctl template init` to reinitialize
