### ISSUE TITLE
PHP invokes microservices

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#2169]
How does PHP get and call microservices as a client? Is there an example project for reference

**Comment by kevwan** [comment]
It's the question about how PHP call gRPC services. As I remember that later versions of PHP works with gRPC.

But I'm not sure, you'd better google it.

**Comment by zhenhua1** [comment]
If other frameworks of golang use the RPC server of go zero as a client, does the client code need to be generated, written and encapsulated by itself? Or is there an example of other frameworks calling the RPC server of go zero

**Comment by kevwan** [comment]
It's just gRPC, nothing changed in go-zero. Any framework works with gRPC can call go-zero.
