### ISSUE TITLE
Does goctl tpl contain RespType?

### ISSUE THREAD

**Issue by yigeqiji** [zeromicro/go-zero#2180]
Does goctl tpl contain RespType?
How do I find the variable contained in the *.tpl? Is this confidential?
//virtual goctl code
  //normal
  var req types.{{.RequestType}}
  //The error occurs when I use the code like below:
  var resp types.{{.ResponseType}}
I want to know where is the variable for goctl *.tpl.

**Comment by kevwan** [comment]
goctl template init

And check the dir .goctl in your HOME directory.

**Comment by yigeqiji** [comment]
> goctl template init
> 
> And check the dir .goctl in your HOME directory.

Thanks a lot, I know how to use it.
I mean I want to know where can I see all the goctl template variables, can I customize these variables?

**Comment by yigeqiji** [comment]
Can anyone help with this issue.

**Comment by kevwan** [comment]
Variables are all in templates.
