### ISSUE TITLE
In windows10, run the goctl.exe rpc new rpc command to throw an error，that's why?

### ISSUE THREAD

**Issue by midsummer-hub** [zeromicro/go-zero#2185]
$ goctl.exe rpc new rpc
Error: ERROR: 2022/07/24 00:44:30 [profiling] error parsing flags: when -address isn't specified, you must include -stream-stats-catapult-json
Usage:
  goctl rpc new [flags]

Flags:
      --branch string   The branch of the remote repo, it does work with --remote
  -h, --help            help for new
      --home string     The goctl home path of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
      --idea            Whether the command execution environment is from idea plugin.
      --remote string   The remote git repo of the template, --home and --remote cannot be set at the same time, if they are, --remote has higher priority
                        The git repo directory must be consistent with the https://github.com/zeromicro/go-zero-template directory structure
      --style string    The file naming format, see [https://github.com/zeromicro/go-zero/tree/master/tools/goctl/config/readme.md] (default "gozero")
  -v, --verbose         Enable log output

?[31mERROR: 2022/07/24 00:44:30 [profiling] error parsing flags: when -address isn't specified, you must include -stream-stats-catapult-json?[0m

**Comment by NStart** [comment]
I also encountered the same problem, and it was solved after trying to delete cmd.exe in the bin directory. This command will affect the cmd command of the system, and this cmd.exe is precisely compiled by the protoc-gen-go-grpc project

**Comment by NStart** [comment]
I also encountered the same problem, and it was solved after trying to delete cmd.exe in the bin directory. This command will affect the cmd command of the system, and this cmd.exe is precisely compiled by the protoc-gen-go-grpc project @midsummer-hub
