### ISSUE TITLE
How to set timeout params in sqlx.NewMysql

### ISSUE THREAD

**Issue by andy-zhangtao** [zeromicro/go-zero#2202]
Hi, 

I want to set some mysql params (e.g. timeout), but I found the SqlOption is private var. 

```golang
func NewMysql(datasource string, opts ...SqlOption) SqlConn {
	opts = append(opts, withMysqlAcceptable())
	return NewSqlConn(mysqlDriverName, datasource, opts...)
}
```

```
SqlOption func(*commonSqlConn)
```
So how to fix or workaround?

**Comment by andy-zhangtao** [comment]
I found a workaround. Add timeout params in Mysql DSN string, but it not what my expect . So how to fix it?

**Comment by andy-zhangtao** [comment]
Is there any progress?

**Comment by andy-zhangtao** [comment]
Is there any progress?

**Comment by andy-zhangtao** [comment]
Has left six days, but there is no progress ....  💔

**Comment by andy-zhangtao** [comment]
Open 10 days ago, no progress still ...

**Comment by andy-zhangtao** [comment]
Open 18 days ago, no progress still ...

**Comment by kevwan** [comment]
Sorry, but what timeout do you want to set?

**Comment by andy-zhangtao** [comment]
Dial , the Ping phase, to be exact..  I expect to control the timeout when execute Ping(). If ping failed, then it will quick failure

**Comment by kevwan** [comment]
Did you encounter any problem so far?

**Comment by kevwan** [comment]
Would you give a detail example on the scenarios?

**Comment by andy-zhangtao** [comment]
in core/stores/sqlx/sqlmanager.go L43
```go
func getSqlConn(driverName, server string) (*sql.DB, error) {
	pdb, err := getCachedSqlConn(driverName, server)
	if err != nil {
		return nil, err
	}

	pdb.once.Do(func() {
		err = pdb.Ping()
	})
	if err != nil {
		return nil, err
	}

	return pdb.DB, nil
}
```

If mysql connect failed, the Ping() will hang about 30s. In fact, we needn't this hang time. So I want to add some timeout params in NewMysql with SqlOption (e.g.  5s for ping timeout). 
 
```go
func NewMysql(datasource string, opts ...SqlOption) SqlConn {
	opts = append(opts, withMysqlAcceptable())
	return NewSqlConn(mysqlDriverName, datasource, opts...)
}
```
But `SqlOption func(*commonSqlConn)` is private var, I can not use it in my code.  Now I use mysql dsn with timeout params.

I want to know , is there has other ways to change it?

If you wants to get more detail info, please let know.

**Comment by andy-zhangtao** [comment]
Open 25 days ago, no substantial progress, and I think there has a inactive community

**Comment by kevwan** [comment]
Didn't figure out a good solution. I read but no reply, sorry.

**Comment by kevwan** [comment]
> I found a workaround. Add timeout params in Mysql DSN string, but it not what my expect . So how to fix it?

I think the timeout params in DSN is already a better soluion.
