### ISSUE TITLE
pains on generating rpc services.

### ISSUE THREAD

**Issue by bigbeer1** [zeromicro/go-zero#2204]
rpc不能拆分  通常一个rpc 可以长达1000多行 不利于维护 

使用protoc-gen-go 生成rpc时 会自动加入omitempty  导致  0和  “”字段会被忽略， 所以上层api接受的时候 还需要再硬复制到一个变量能增加代码量 同时还需要实例返回内容，建议修改优化

**Comment by anqiansong** [comment]
https://github.com/zeromicro/go-zero/blob/master/tools/goctl/rpc/README.md
rpc支持分组的哈，你可以从 master 安装体验一下，至于 pb 的生成这个不受 goctl 控制哈。
It has already support rpc grouping, you can upgrade goctl to the latest version via the master branch, for the tag `omitempty` of pb,  it is generated by protoc-gen-go, so we can't fix it.

**Comment by kevwan** [comment]
Released.
