### ISSUE TITLE
According to the document operation appears httpx redeclared in this block error

### ISSUE THREAD

**Issue by chenzijia12300** [zeromicro/go-zero#2206]
**Describe the bug**
[Quick Start](https://go-zero.dev/cn/docs/introduction/#5-quick-start) document  operation appears httpx redeclared in this block error

**Expected behavior**
No duplicate package introduction errors

**Screenshots**
![image](https://user-images.githubusercontent.com/48479242/181675816-e3869169-45eb-44f7-b029-abd337545f4b.png)

**Environments (please complete the following information):**
 - OS: [e.g. Window10]
 - go-zero version [1.3.5]
 - goctl version [1.3.9 windows/amd64]

**Comment by anqiansong** [comment]
https://github.com/zeromicro/go-zero/pull/2172/files
It has already been fixed

**Comment by chenzijia12300** [comment]
So should I upgrade the version of goctl, which seems to be the latest version already
