### ISSUE TITLE
希望未来版本能将goctl新增mysql的datasource方式生成.api文件和.proto文件

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#2217]
具体需求：
我们在常用curd操作中，重复定义.api和.proto两个文件，并且api代码同质化严重，个人认为最佳开发方式如下：
第一种方式：定义mysql表结构====>通过这个配合自己修改的.tpl模版生成对应的.api ====>根据.api自动生成网关代码====>根据.api生成.proto文件
第二种方式：定义mysql表结构====>通过这个配合自己修改的.tpl模版生成对应的.proto ====>根据.proto 配合修改模版实现自定义代码

**Comment by waltcow** [comment]
Maybe you can https://github.com/ent/ent @jsonMark 
1. define model schema
2. generate related proto file with plugin

**Comment by jsonMark** [comment]
> 

我试试，感谢!

**Comment by kevwan** [comment]
closing.
