### ISSUE TITLE
goctl generate code duplicate in import part

### ISSUE THREAD

**Issue by alexanyang** [zeromicro/go-zero#2221]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
     import (
	"net/http"

	"book/service/user/api/internal/logic"
	"book/service/user/api/internal/svc"
	"book/service/user/api/internal/types"
	"github.com/zeromicro/go-zero/rest/httpx"

	"github.com/zeromicro/go-zero/rest/httpx"
    )
   
   ```

2. The error is

   ```
     "github.com/zeromicro/go-zero/rest/httpx" // duplicate
   ```

**Expected behavior**
no duplicated import

**Screenshots**

**Environments (please complete the following information):**
 - OS: [mac os 11.5.2]
 - go-zero version [ 1.3.5]
 - goctl version [1.3.5, optional]
 - may be other version is still with this question 

**More description**
Just do like :https://go-zero.dev/cn/docs/quick-start/micro-service
It will appear in /internal/handler

**Comment by kevwan** [comment]
Fixed in v1.4.0
