### ISSUE TITLE
simplify ConsistentHash.Get method

### ISSUE THREAD

**Issue by hitzhangjie** [zeromicro/go-zero#2224]
```go
func (h *ConsistentHash) Get(v interface{}) (interface{}, bool) {
        ...
	index := sort.Search(len(h.keys), func(i int) bool {
		return h.keys[i] >= hash
	}) % len(h.keys)
        ...
}
```
here `% len(h.keys)` is needless. 
sort.Search(n, func(...)) returns an index in [0,n) which won't be larger than len(h.keys).

**Comment by kevwan** [comment]
From the doc.
> If there is no such index, Search returns n.

**Comment by kevwan** [comment]
From the doc.
> If there is no such index, Search returns n.

**Comment by hitzhangjie** [comment]
thanks
