### ISSUE TITLE
AtomicXXX type consideration

### ISSUE THREAD

**Issue by anyoptional** [zeromicro/go-zero#2228]
Currently, syncx package defines atomic types like following:
```
type AtomicBool uint32
type AtomicDuration int64
type AtomicFloat64 uint64
```
In this way, we cannot prohibit developers from using them as non-atomic types. Isn't it better to define it like this?
```
type AtomicBool struct {
    state uint32
}
```

**Comment by kevwan** [comment]
I think it's a good idea.
