### ISSUE TITLE
Any example on using apollo as configuration center?

### ISSUE THREAD

**Issue by congim** [zeromicro/go-zero#2229]
Any example on using apollo as configuration center?

**Comment by jsonMark** [comment]
https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry
默认就支持etcd，下面的需要自己扩展：
[consul](https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/consul)
[nacos](https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/nacos)
[polaris](https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/polaris)
apollo不确定

**Comment by kevwan** [comment]
> 如题，配置这块有支持apollo、etcd的打算吗

No plan yet.
