### ISSUE TITLE
core/stores/redis.Pair.Score is int64, redis/v8.Z.Score is float64 ? why do this convert

### ISSUE THREAD

**Issue by htlhenry** [zeromicro/go-zero#2230]
hello i want use go-zero/core/stores/redis as my redis client, but i saw in the redis.ZaddsCtx(), score is type int64, but wrapped redis client is float64, why do this convert? 
 
https://github.com/zeromicro/go-zero/blob/34294702b0e88ad7d3e7e0ac494ee15cf103f0db/core/stores/redis/redis.go#L1878

**Comment by kevwan** [comment]
For compatibility reason. But any problem on this?

**Comment by htlhenry** [comment]
that will be problem when i want store float not int, float may be more compat.

**Comment by kevwan** [comment]
fixed.
