### ISSUE TITLE
Setting sql connection pool

### ISSUE THREAD

**Issue by huuhoait** [zeromicro/go-zero#2241]
How can i set the max,min db connection

**Comment by kevwan** [comment]
Any scenario to set it?

**Comment by huuhoait** [comment]
I built monolithic model, but i can not set the max pool (the default is 64), and must edit file sqlx/sqlmanager.
How can i init the connection pool Max/Min in generate project.

**Comment by kevwan** [comment]
Why to set these parameters? Got any connection problem?

**Comment by huuhoait** [comment]
yes, there are some issue with timeout & lock record in db and handle connection

**Comment by kevwan** [comment]
I think you might use https://github.com/kevwan/tproxy to check if any connection problem.

Or please describe more on your specific scenarios.
