### ISSUE TITLE
Does it support RESTful API Gateway? 

### ISSUE THREAD

**Issue by chewojia** [zeromicro/go-zero#2242]
Does it support RESTful API Gateway? Because I have very few RPC services and a lot of Web services. I want to support RPC services in Web services so that I can easily transform my existing projects

**Comment by kevwan** [comment]
yes, check it here.

https://github.com/zeromicro/go-zero/tree/master/gateway

**Comment by chewojia** [comment]
> yes, check it here.
> 
> https://github.com/zeromicro/go-zero/tree/master/gateway

It seems to be starting an Http service in the GRPC service, but I want to start a GRPC service in the Http service, I don't want to start another GRPC service, my GRPC service may only have one external interface. It's kind of a waste of resources. I don't know what to do...
