### ISSUE TITLE
when log use file mode with plain, i found info log in error log file, and loss log。

### ISSUE THREAD

**Issue by Kittoa** [zeromicro/go-zero#2247]
when log use file mode with plain, i found info log in error log file, and loss log。
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/17596488/183575024-9301fe9e-8354-49d0-942c-0c603720b4f5.png">

**Comment by kevwan** [comment]
Which version? And any code to reproduce it?

**Comment by Kittoa** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/17596488/184570136-f202af20-05f0-4a18-a6bb-b227483482e7.png">
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/17596488/184570199-b34fdb09-21a8-46a7-91e7-b7ab68076a6d.png">

**Comment by chenquan** [comment]
Fixed: #2424
