### ISSUE TITLE
some feature request about gateway

### ISSUE THREAD

**Issue by showurl** [zeromicro/go-zero#2250]
**Get parameters from request headers or context, and set them to rpc request parameters**
I have an rpc interface called `SetUserInfo`, Its request parameters are as follows:
```protobuf
message ReqSetUserInfo {
  string selfId = 1; // requester's user id
  string ip = 2; // requester's ip address
  string nickname = 3; 
}
```
The client does not need to set the `selfId` and `ip` when calling the http api. Because the requester id can be obtained in the `authMiddleware`, and the requester ip can be obtained in the `request header`.
So I need you to provide a way to set the value I need in the context or the value in the request header as the rpc request parameter.

maybe as follows:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/49354784/183851510-3560b94a-fadb-4603-adae-0d91af25402b.png">

**Support for custom api response wrapper**
In most cases, the response of rpc cannot be used as the final response of api.
One of the response structures we use the most is as follows:
```json
{
  "code": 0,
  "msg": "success",
  "data": {
    "id": "xxx"
  }
}
```
or:
```json
{
  "code": -1,
  "msg": "forbidden"
}
```
Now, gateway doesn't provide a way to customize response wrapping
I may need to write the rpc response into `$.data`, and maybe set the code value to `-1`.
My current solution is as follows:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/49354784/183854977-8c9c4060-60e5-4610-8e52-de7dff63562d.png">

**Use proto set bytes instead of filename**
I can use go:embed to embed files during compilation, but it's not necessary.

**Comment by hehanpeng** [comment]
一般网关都要折叠grpc 的数据 ，然后带上code 和msg 没有企业级最佳实践，得自己改

**Comment by showurl** [comment]
I can modify the goctl template code to achieve

**Comment by akalittle** [comment]
> I can modify the goctl template code to achieve

Hey, how do you implement this. Can you provide more codes?
