### ISSUE TITLE
httpc  reponse parse to struct err

### ISSUE THREAD

**Issue by clukboy** [zeromicro/go-zero#2253]
I use httpc.ParseJsonBody parse to struct because the following error occurs when there is a field in the returned result with a default value of type
![问题图片](https://user-images.githubusercontent.com/89188315/184056385-6c9d6ccb-26f4-4c70-9488-887175dba27e.png)
e

**Comment by kevwan** [comment]
Make sure the json body is correct.

```go
func TestParseWithZeroValue(t *testing.T) {
	var val struct {
		Foo int `header:"foo"`
		Bar int `json:"bar"`
	}
	svr := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("foo", "0")
		w.Header().Set(header.ContentType, header.JsonContentType)
		w.Write([]byte(`{"bar":0}`))
	}))
	defer svr.Close()
	req, err := http.NewRequest(http.MethodGet, svr.URL, nil)
	assert.Nil(t, err)
	resp, err := DoRequest(req)
	assert.Nil(t, err)
	assert.Nil(t, Parse(resp, &val))
	assert.Equal(t, 0, val.Foo)
	assert.Equal(t, 0, val.Bar)

}
```

**Comment by clukboy** [comment]
I was really wrong to use this, But I have no problem using JSON parsing
[image: image.png]

**Comment by clukboy** [comment]
I was really wrong to use this, But I have no problem using JSON parsing
![unnamed](https://user-images.githubusercontent.com/89188315/184811346-eb28cc50-8551-44d5-a7b9-8e801c25fefd.png)

**Comment by clukboy** [comment]
> 确保 json 正文是正确的。
> 
> ```go
> func TestParseWithZeroValue(t *testing.T) {
> 	var val struct {
> 		Foo int `header:"foo"`
> 		Bar int `json:"bar"`
> 	}
> 	svr := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> 		w.Header().Set("foo", "0")
> 		w.Header().Set(header.ContentType, header.JsonContentType)
> 		w.Write([]byte(`{"bar":0}`))
> 	}))
> 	defer svr.Close()
> 	req, err := http.NewRequest(http.MethodGet, svr.URL, nil)
> 	assert.Nil(t, err)
> 	resp, err := DoRequest(req)
> 	assert.Nil(t, err)
> 	assert.Nil(t, Parse(resp, &val))
> 	assert.Equal(t, 0, val.Foo)
> 	assert.Equal(t, 0, val.Bar)
> }
> ```

**Comment by clukboy** [comment]
I was really wrong to use this, But I have no problem using JSON parsing @kevwan 
![unnamed](https://user-images.githubusercontent.com/89188315/184812016-b127c768-dcd9-4718-8217-66c20de78cfd.png)

**Comment by kevwan** [comment]
Show your code please.

**Comment by clukboy** [comment]
[image: image.png]

Kevin Wan ***@***.***> 于2022年8月18日周四 08:21写道：

**Comment by clukboy** [comment]
this my code

Kevin Wan ***@***.***> 于2022年8月18日周四 08:21写道：

**Comment by clukboy** [comment]
This my code,I use httpc Do will also fail to parse, so I encapsulate the
post request myself
[image: image.png]

Kevin Wan ***@***.***> 于2022年8月18日周四 08:21写道：

**Comment by clukboy** [comment]
This my code,I use httpc Do will also fail to parse, so I encapsulate the
post request myself

Kevin Wan ***@***.***> 于2022年8月18日周四 08:21写道：

**Comment by clukboy** [comment]
This my code,I use httpc Do will also fail to parse, so I encapsulate the post request myself

**Comment by clukboy** [comment]
func (c *DouYinClient) JsCode2Session(req *JsCodeReq) (*JsCodeResp, error) {
	req.Appid = c.conf.AppId
	req.Secret = c.conf.Secret
	resp, err := tools.Post(Code2SessionURL, req)
	if err != nil {
		logx.Errorf("err:%+v", err)
		return nil, err
	}

	var data JsCodeResp
	//err = httpc.Parse(resp, &data)
	//err = httpc.ParseJsonBody(resp, &data)
	all, err := io.ReadAll(resp.Body)
	err = json.Unmarshal(all, &data)
	if err != nil {
		logx.Errorf("err:%+v", err)
		return nil, err
	}
	return &data, nil
}

**Comment by clukboy** [comment]
I use httpc Do will also fail to parse, so I encapsulate the post request myself
`
func (c *DouYinClient) JsCode2Session(req *JsCodeReq) (*JsCodeResp, error) {
	req.Appid = c.conf.AppId
	req.Secret = c.conf.Secret
	resp, err := tools.Post(Code2SessionURL, req)
	if err != nil {
		logx.Errorf("err:%+v", err)
		return nil, err
	}

	var data JsCodeResp
	//err = httpc.Parse(resp, &data)
	//err = httpc.ParseJsonBody(resp, &data)
	all, err := io.ReadAll(resp.Body)
	err = json.Unmarshal(all, &data)
	if err != nil {
		logx.Errorf("err:%+v", err)
		return nil, err
	}
	return &data, nil
}

`

**Comment by clukboy** [comment]
I use httpc Do will also fail to parse, so I encapsulate the post request myself
` func (c *DouYinClient) JsCode2Session(req *JsCodeReq) (*JsCodeResp, error) {
	req.Appid = c.conf.AppId
	req.Secret = c.conf.Secret
	resp, err := tools.Post(Code2SessionURL, req)
	if err != nil {
		logx.Errorf("err:%+v", err)
		return nil, err
	}

	var data JsCodeResp
	//err = httpc.Parse(resp, &data)
	//err = httpc.ParseJsonBody(resp, &data)
	all, err := io.ReadAll(resp.Body)
	err = json.Unmarshal(all, &data)
	if err != nil {
		logx.Errorf("err:%+v", err)
		return nil, err
	}
	return &data, nil
}
`
