### ISSUE TITLE
data is not syncing after balance error.

### ISSUE THREAD

**Issue by bigbeer1** [zeromicro/go-zero#2268]
{"level":"warn","ts":"2022-08-17T16:38:33.322+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000138380/127.0.0.1
:30000","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection closed before server preface received"}
{"level":"info","ts":"2022-08-17T16:38:33.322+0800","logger":"etcd-client","caller":"v3@v3.5.4/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}

**Comment by kevwan** [comment]
Does etcdctl work on this scenario? Or the etch cluster is not working at all?

**Comment by brucewenyu** [comment]
whether single node or etcd clusters have above this message, but etcd single node or cluster can work at all。

**Comment by brucewenyu** [comment]
{"level":"warn","ts":"2022-10-13T10:45:51.872+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000282540/127.0.0.1:12379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup etcd3: i/o timeout\""}

**Comment by za-lee** [comment]
local environment, change 127.0.0.1 to localhost
```
Etcd:
  Hosts:
  - localhost:2379
```
