### ISSUE TITLE
stringx.Replace was broken

### ISSUE THREAD

**Issue by taobig** [zeromicro/go-zero#2269]
stringx.Replace was broken since commit f1102fb2.
the example code from https://github.com/zeromicro/zero-doc/blob/main/go-zero.dev/cn/keywords.md
```
replacer := stringx.NewReplacer(map[string]string{
  "日本":    "法国",
  "日本的首都": "东京",
  "东京":    "日本的首都",
})
fmt.Println(replacer.Replace("日本的首都是东京"))
```
expected: 东京是日本的首都
actual: 法国的首都是日本的首都

**Comment by kevwan** [comment]
I think the result is correct. We need to update the doc.

The logic is that, after replacement, if there are still words afterwards, we need to go back to the start of the replaced segment.

**Comment by taobig** [comment]
The docs was updated.
https://github.com/zeromicro/zero-doc/commit/92dc94b982978d71505df2a9c2a2d0b9e6b8e662
