### ISSUE TITLE
Need more methods for cache.

### ISSUE THREAD

**Issue by bigbeer1** [zeromicro/go-zero#2276]
cache redis 方式外部调用只有  get set和一些常规的 希望提供  scan  hset  hget

**Comment by jsonMark** [comment]
> cache redis 方式外部调用只有 get set和一些常规的 希望提供 scan hset hget

目前只能自己重新实例化一个go-redis的对象来实现，你是什么场景下需要这种需求？？？？

**Comment by re-dylan** [comment]
当我们使用 mongoc sqlc 的时候，我们希望 cache 的结构仅仅只是一种 kv 结构。不应该支持其他的结构，否则会造成缓存失效特别麻烦。可以讲一下的场景需求。
