### ISSUE TITLE
About configuring the information security mode

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#2277]
1.大家是希望跟java的spring一样，密码等核心信息加密，程序运行之后再解密｜We hope that the core information such as password will be encrypted and decrypted after the program runs, just like Java Spring.
2.还是通过镜像的docker的环境变量来控制｜It is also controlled by the mirrored Docker's environment variables；
3.其他方式？|Other ways?

**Comment by kevwan** [comment]
We use the first one.
