### ISSUE TITLE
How to specify rpc endpoints in API services?

### ISSUE THREAD

**Issue by themoonbear** [zeromicro/go-zero#2281]
API服务和RPC服务都是多节点, 使用etcd做节点发现, RPC服务使用grpc的双向流, API服务如何连接指定的RPC节点

**Comment by kevwan** [comment]
Endpoints in yaml.

**Comment by themoonbear** [comment]
> Endpoints in yaml.

感谢回复, 我想在API服运行起来之后, 根据参数动态的去连接RPC服, 目前只知道RPC的名字, 但不知道有几个RPC节点, 是不是需要自己来监听etcd呢? 还是说zero有接口可以获得当前有几个rpc节点?

**Comment by kevwan** [comment]
Etcd in yaml.

**Comment by re-dylan** [comment]
Go-zero has implemented ETCD's automatic service discovery capability, you can check https://github.com/zeromicro/zero-examples/blob/main/rpc/client/lb/main.go#L30
