### ISSUE TITLE
Use of internal package not allowed

### ISSUE THREAD

**Issue by alan890104** [zeromicro/go-zero#2282]
- OS: Ubuntu 22.04
- Go: Golang 1.18.1

I follow [official instruction](https://go-zero.dev/cn/docs/quick-start/micro-service) to build microservice.
However, as I execute `go run user.go -f etc/user.yaml` in bash, it raises the error:
```bash
package command-line-arguments
        imports go-zero-demo/mall/user/rpc/internal/server
        imports go-zero-demo/mall/user/rpc/internal/svc
        internal/svc/servicecontext.go:4:2: use of internal package go-zero-demo/mall/order/api/internal/config not allowed
package command-line-arguments
        imports go-zero-demo/mall/user/rpc/internal/server
        imports go-zero-demo/mall/user/rpc/internal/logic
        internal/logic/getuserlogic.go:7:2: use of internal package go-zero-demo/mall/order/api/internal/svc not allowed
package command-line-arguments
        imports go-zero-demo/mall/user/rpc/internal/server
        imports go-zero-demo/mall/user/rpc/internal/logic
        internal/logic/getuserlogic.go:8:2: use of internal package go-zero-demo/mall/order/api/internal/types not allowed
```
The problem possibly  causes by the generated-directory name `internal`. 
Is there any way to fix it without renaming the default directory name?
![image](https://user-images.githubusercontent.com/48343225/185733200-0156ff94-0a82-4d2e-887d-ae1e7f3739fa.png)

![image](https://user-images.githubusercontent.com/48343225/185733219-b7a6c0a5-12b6-4a91-9887-93ea3697f94e.png)

**Comment by alan890104** [comment]
go env -w GO111MODULE="on"
and **DO NOT** modify golang default env variables

**Comment by kevwan** [comment]
Do you mean goctl changed go env?

**Comment by alan890104** [comment]
It's my own mistake. I changed my golang default env variables before.

**Comment by kevwan** [comment]
I see. Thanks for your reply!
