### ISSUE TITLE
hope to have traceid in sql trace and aliyun database dashboard

### ISSUE THREAD

**Issue by Danny5487401** [zeromicro/go-zero#2285]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/64348131/185899922-688d75ed-116d-4485-ad2a-697867b9d95d.png)

hope to  add the traceinfo in future version after 1.3.5!

**Comment by kevwan** [comment]
Added in v1.4.0, I remember.

**Comment by Danny5487401** [comment]
> Added in v1.4.0, I remember.
![image](https://user-images.githubusercontent.com/64348131/186048091-95c5abb9-dd86-45be-a7f3-708d98a6c795.png)
![image](https://user-images.githubusercontent.com/64348131/186048144-0f1206c2-82cc-419f-9c28-0445c35f974b.png)

i have seen the original code in v1.4.0, which is not including any sql stmt log. Only print the sql stat in console! @kevwan 
![image](https://user-images.githubusercontent.com/64348131/186048530-c0dee056-98a6-4c3f-8ead-09872cc27011.png)

**Comment by kevwan** [comment]
Didn't submit details for security reasons. What kind of info you like to submit?

**Comment by Danny5487401** [comment]
> Didn't submit details for security reasons. What kind of info you like to submit?

Ok.  Hope to include the sql related database in the trace panel. From the trace panel , i can get the traceId , then get the sql log from the sls service searching by the trace id.

**Comment by Danny5487401** [comment]
@kevwan  hope to print sql like "/*TRACE_3f5a0e4904d43b0632e260c2a1db3d28*/SELECT t1.`id`, t1.`external_type`, t1.`external_id`FROM `esdocownerstriggerlog` t1WHERE t1.`is_synced` = 0ORDER BY t1.`id` ASCLIMIT 200"

**Comment by xuerbujia** [comment]
I hope to commit sql statement too, because Alibaba Cloud's database analytics function rely on it.
