### ISSUE TITLE
error: config file etc/greet-api.yaml, open etc/greet-api.yaml: The system cannot find the path specified.

### ISSUE THREAD

**Issue by 1242048704** [zeromicro/go-zero#2293]
Win10 environment, prompt can not find the yaml configuration file, has not moved anything, confused for a long time, ask the big guy.Hope to help with it.
![image1](https://user-images.githubusercontent.com/44760784/186454156-42cdea3e-963f-4b0e-9683-0965eba803a4.png)
![image2](https://user-images.githubusercontent.com/44760784/186454757-29e85964-cee2-477b-b148-ab6dccab5853.png)

**Comment by kevwan** [comment]
Please check your working directory.

**Comment by 1242048704** [comment]
Thanks a lot!
