### ISSUE TITLE
Hope to have log audit feature.

### ISSUE THREAD

**Issue by maomao94** [zeromicro/go-zero#2298]
在开发中，出现问题，想看下当前服务调用 http/rpc/db/redis/mq 的完整请求响应数据比较困难
希望新增一个auditlog文件夹作为审计日志目录  目录包括 client.log 可以根据trace=5e4f8263ec86c2b45107e0fadcb3d694 来看到所有的client 请求 和响应数据便于定位问题

**Comment by kevwan** [comment]
why not use jaeger etc?

**Comment by hehanpeng** [comment]
jaeger 看不到请求和响应的数据，还是根据数据查问题更直观
