### ISSUE TITLE
Timeout on first insert into cloud mysql using model.

### ISSUE THREAD

**Issue by happys2333** [zeromicro/go-zero#2300]
如题问题，程序框架是前端发请求到api然后api给rpc的这么一个标准流程。

但是现在遇到是，当刚刚跑起来rpc和api服务的时候，发送请求会遇到 context deadline的问题，报错如下：
```shell
{"@timestamp":"2022-08-26T00:17:49.712+08:00","caller":"clientinterceptors/durationinterceptor.go:25","content":"fail - etcd:/127.0.0.1:2379/user.rpc/user.User/sms - countryCode:86  phone:11451498  verifyCode:114514 - rpc error: code = 
DeadlineExceeded desc = context deadline exceeded","duration":"2001.1ms","level":"info","span":"62f365ebf480a33e","trace":"c72fb114b15587fe726e337ff3ae75ec"}
```

使用的代码是
```go
userInfos, err := l.svcCtx.UserModel.QueryByPhone(l.ctx, in.Phone)
...
// 报错行
result, err := l.svcCtx.UserModel.Insert(l.ctx, &model.User{
			...
		})
...
```

代码运行中我首先会去查询是否有这个用户然后再帮助用户注册，但是第一次去进行查询的时候反倒没有context deadline，第二次插入才出现

Insert是使用的model生成的代码调用的，QueryByPhone是基于model生成代码自己写的查询代码，使用的QueryRows的函数。
```go
...
m.conn.QueryRows(&resp, query, phone)
...
```

值得区分的是，生成代码里面采用了CacheRedis，但是redis我本身跑在本地上，不应该会导致超时。Mysql服务器则跑在了一个远程服务端。
然后这里最诡异的是这个bug只会在刚刚跑起来的第一次请求出现，而不会在第二次请求的时候出现，甚至后续请求也没有出现，所以不太清楚是什么导致的。

**Comment by kevwan** [comment]
Timeout on db connection.

**Comment by re-dylan** [comment]
这个不是 db 连接超时的问题。需要看下你的所有API RPC超时设置，还有 每个语句的具体时长。
当你所有的数据库操作都使用context 的时候，他是共用所有的超时时间。
比如配置  RPC 超时 3s.
QueryByPhone 使用了2s, 那 Insert 就只剩下了 1s. 所以 insert 很有可能超时。

同样 API 的超时在 go-zero 也会传递到 RPC 中的。

**Comment by happys2333** [comment]
> 这个不是 db 连接超时的问题。需要看下你的所有API RPC超时设置，还有 每个语句的具体时长。 当你所有的数据库操作都使用context 的时候，他是共用所有的超时时间。 比如配置 RPC 超时 3s. QueryByPhone 使用了2s, 那 Insert 就只剩下了 1s. 所以 insert 很有可能超时。
> 
> 同样 API 的超时在 go-zero 也会传递到 RPC 中的。

我的疑问主要是围绕在，第一次调用这个api的时候会超时出500错误，但是再次调用就不会出现500错误，数据库也能正常插入，只有在刚刚运行的时候第一次调用才会遇到这个问题，而且第一次调用可以感受到肉眼可见的慢（前端发数据到接收用了2秒），但是后面就不会遇到，不知道是怎么回事

**Comment by re-dylan** [comment]
了解，你说的这种 case ，那就是db 建立连接的时候比较慢了。
https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/sqlconn.go#L98
https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/sqlconn.go#L291
看这个代码，初始化 SqlConn 确实并没有建立连接，是在第一次执行的时候才会真正建立连接。

**Comment by happys2333** [comment]
> 了解，你说的这种 case ，那就是db 建立连接的时候比较慢了。 https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/sqlconn.go#L98 https://github.com/zeromicro/go-zero/blob/master/core/stores/sqlx/sqlconn.go#L291 看这个代码，初始化 SqlConn 确实并没有建立连接，是在第一次执行的时候才会真正建立连接。

ok，感谢。那大概了解了，这个issue可以close了

**Comment by xhochipe** [comment]
@re-dylan 我timeout设置了150s测试，然后api请求发过来就直接出现这个错误
