### ISSUE TITLE
k8s generate yaml

### ISSUE THREAD

**Issue by dawnFromDark** [zeromicro/go-zero#2320]
Thanks for the nice feature of generating K8S scripts, but I found that adding a "--targetprot" option would be perfect. as the picture shows
<img width="671" alt="1f15a705c3ec2a17481ba65f8d7afd8" src="https://user-images.githubusercontent.com/44474000/187079666-e04ae062-7c0d-418f-b818-f0488526ec7a.png">
k8s also often uses the "targetport" option, right?

**Comment by anqiansong** [comment]
Sounds great! Welcome to pull request if you could be.
