### ISSUE TITLE
Question about mongo transaction

### ISSUE THREAD

**Issue by JhouXerox** [zeromicro/go-zero#2324]
model(dao) level allows to input context, but not expose any mongo client.

when use mongo-driver,i usually call:
client.UseSession(...)

to create transaction context.but dao is generated by goctl.

how do i create session in service level? Is there any suggestion

**Comment by pabno** [comment]
> model(dao) level allows to input context, but not expose any mongo client.
> 
> when use mongo-driver,i usually call: client.UseSession(...)
> 
> to create transaction context.but dao is generated by goctl.
> 
> how do i create session in service level? Is there any suggestion

I meet the same problem，if you solve this?

**Comment by JhouXerox** [comment]
@pabno 
`type transactable interface {
	Transact(ctx context.Context, fn func(sessionContext mongo.SessionContext) (interface{}, error)) (interface{}, error)
}`
I custom the template let dao implement this interface 
`func (m *defaultFirmwareJobTaskModel) Transact(ctx context.Context, fn func(sessionContext mongo.SessionContext) (interface{}, error)) (interface{}, error) {
	sess, err := m.conn.StartSession()
	defer sess.EndSession(ctx)
	if err != nil {
		return nil, err
	}
	res, err := sess.WithTransaction(ctx, fn)
	return res, err
}`
