### ISSUE TITLE
jwt in go-zero can only use sha to sign

### ISSUE THREAD

**Issue by ddzrc** [zeromicro/go-zero#2325]
i find out jwt can not use rsa to sign token？  please sure it

**Comment by nicklaros** [comment]
english please :(

**Comment by MarkJoyMa** [comment]
Yes, currently only the signature verification method of hmac-sha256 is supported.

**Comment by MarkJoyMa** [comment]
Customize the verification logic by customizing Middleware, and you need to turn off the zero verification switch.
