### ISSUE TITLE
Docs and comments are not retained when using goctl to generate code from api file

### ISSUE THREAD

**Issue by nicklaros** [zeromicro/go-zero#2326]
**Describe the bug**
The doc [here](https://go-zero.dev/docs/design/grammar/?_highlight=api&_highlight=json#doccomment) says that `it retain the original mark of //, /*, */.` But when I generate code using go-ctl, docs and comments are removed (except inline comments)
![image](https://user-images.githubusercontent.com/2937466/187319289-9906f757-3962-4a0d-b386-66ff620ac7bc.png)

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. test.api  file

   ```go
    syntax = "v1"
    
    info (
	    title: "test service"
	    desc: "service to test bug"
	    author: ""
	    email: ""
    )
    
    type PingReq {
	    // State where ping request come from.
	    From string `json:"from"` // eg: ip address, origin host
    }
    
    type PingResp {
	    // Ack message.
	    Message string `json:"message"`
    }
    
    service test-api {
	    @handler HandlePing
	    post /ping(PingReq) returns(PingResp)
    }
   ```

2. Generate code using goctl

   ```
   goctl api go -api test.api
   ```

3. The generated `types.go` file, see that docs and comments are gone with the exception of inline comments

   ```
    // Code generated by goctl. DO NOT EDIT.
    package types
    
    type PingReq struct {
	    From string `json:"from"` // eg: ip address, origin host
    }
    
    type PingResp struct {
	    Message string `json:"message"`
    }
   ```

**Expected behavior**
All docs and comments from api files were retained in produced types.go

**Environments:**
 - OS: WSL Ubuntu
 - go-zero version v1.4.0
 - goctl version 1.4.0 linux/amd64

**Comment by MarkJoyMa** [comment]
Comments and definitions can be brought into the generated code.
example:
`
 type PingResp {
     Message string `json:"message"`  // Ack message.
 }
`

**Comment by nicklaros** [comment]
Yes I aware that inline comment is retained.

But what if I need to add multiline comments? I think it also need to be retained in the generated code because if I need to add complete documentation for a field, most likely it will be multiline comments

**Comment by kevwan** [comment]
```go
 type PingResp {
     // ACK message
     // second line
     Message string `json:"message"`
 }
```

Not working?

**Comment by nicklaros** [comment]
It's not working. It will be removed on generated `types.go` file

**Comment by kevwan** [comment]
@MarkJoyMa @anqiansong PTAL.

**Comment by nicklaros** [comment]
hi team, any update on this?
