### ISSUE TITLE
how to replace loghandler to custom loghandler by myself?  if can't ,  how to  close the loghandler

### ISSUE THREAD

**Issue by keroro6** [zeromicro/go-zero#2329]

**Comment by MarkJoyMa** [comment]
The Logger module is an interface, you can implement your own log by yourself.

**Comment by keroro6** [comment]
@MarkJoyMa sorry, i mean that log middleware

**Comment by keroro6** [comment]
![image](https://user-images.githubusercontent.com/46135673/187595936-5825dccb-8b55-4297-ab7d-f24c18b2bf2a.png)

**Comment by keroro6** [comment]
@MarkJoyMa  sorry,  I mean  the log middleware

**Comment by kevwan** [comment]
You can organize middlewares on your own by using `WithChain`.
