### ISSUE TITLE
How do I create an instance of a Redis Cluster？

### ISSUE THREAD

**Issue by linganmin** [zeromicro/go-zero#2332]
The following is my config。

![image](https://user-images.githubusercontent.com/17434123/187396240-3baaf0c6-4201-4a9f-b2cd-103dcb46b3fa.png)

i want create a redis client ，but the `redisclustermanager.go` just use one address to `NewClusterClient`

![image](https://user-images.githubusercontent.com/17434123/187396805-39abe5ed-92d9-40cb-bc85-1fe910a68ba5.png)

**Comment by linganmin** [comment]
> I have the same problem, how did you solve it in the end?

sorry，I just saw your message. i create a new client reference the docs https://redis.uptrace.dev/guide/ , hope that is useful to you.
![image](https://user-images.githubusercontent.com/17434123/210227630-19535705-839b-431c-a66a-ac59fde35473.png)

**Comment by kevwan** [comment]
> The following is my config。
> 
> ![image](https://user-images.githubusercontent.com/17434123/187396240-3baaf0c6-4201-4a9f-b2cd-103dcb46b3fa.png)
> 
> i want create a redis client ，but the `redisclustermanager.go` just use one address to `NewClusterClient`
> 
> ![image](https://user-images.githubusercontent.com/17434123/187396805-39abe5ed-92d9-40cb-bc85-1fe910a68ba5.png)

redis client loads the cluster info automatically. So only one addr is enough to start.
