### ISSUE TITLE
go-zero 可以支持查询数组?can go-zero support querying arrays?

### ISSUE THREAD

**Issue by daifuyang** [zeromicro/go-zero#2334]
如图，我需要制作一个批量删除内容的接口，目前期望的地址是批量传递一些ids。如下图：
![image](https://user-images.githubusercontent.com/19951467/187601295-80cb359b-6b1b-4e82-99c0-825f9f75ea5c.png)
通过api的配置如下
![172761661922151_ pic](https://user-images.githubusercontent.com/19951467/187607700-fc4d42dc-aed4-4512-95d5-d212863f4b4d.jpg)
如你所见，他报错了。请问我的做法正确嘛？
我自己在logic中处理是可以获取到的
<img width="429" alt="image" src="https://user-images.githubusercontent.com/19951467/187602535-e5f290fb-ba27-4896-a43a-b2fe3c445e32.png">
请问有什么好的办法吗？我希望在api中自动生成以便使用

**Comment by MarkJoyMa** [comment]
There is no need to use [] in the tag, only the type is defined as an array, and the incoming is separated by commas.
example: 
```go
articlesDelReq {
    ids []int `form:"ids,optional"`
}
```

**Comment by MarkJoyMa** [comment]
english please :(

**Comment by daifuyang** [comment]
thanks for your help。but i try it doesn't work
you can see this feedback
![image](https://user-images.githubusercontent.com/19951467/187615119-6a1562e1-4650-42f4-946b-b69ff3671dc5.png)
![image](https://user-images.githubusercontent.com/19951467/187615240-f4b6aced-6939-4ce7-899c-5f54841f6b80.png)
this is ok but get value is null
![image](https://user-images.githubusercontent.com/19951467/187615837-41333d3e-d32f-4e7c-bcad-a425b988dfc7.png)
this is my article.api
<img width="349" alt="image" src="https://user-images.githubusercontent.com/19951467/187615367-4aeabe6e-4c2b-4b60-b0dc-dea1a63f13f7.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/19951467/187615419-6e6f0370-a79e-41c7-b31e-2c3c9c1649e8.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/19951467/187616106-b8667c9e-5c9a-49ef-8ff9-7972cdea86a1.png">
so，it is something wrong?
Looking forward to your help again
very thanks

**Comment by daifuyang** [comment]
> There is no need to use [] in the tag, only the type is defined as an array, and the incoming is separated by commas. example:
> 
> ```go
> articlesDelReq {
>     ids []int `form:"ids,optional"`
> }
> ```

thanks for your help。but i try it doesn't work
you can see this feedback
![image](https://user-images.githubusercontent.com/19951467/187615119-6a1562e1-4650-42f4-946b-b69ff3671dc5.png)
![image](https://user-images.githubusercontent.com/19951467/187615240-f4b6aced-6939-4ce7-899c-5f54841f6b80.png)
this is ok but get value is null
![image](https://user-images.githubusercontent.com/19951467/187615837-41333d3e-d32f-4e7c-bcad-a425b988dfc7.png)
this is my article.api
<img width="349" alt="image" src="https://user-images.githubusercontent.com/19951467/187615367-4aeabe6e-4c2b-4b60-b0dc-dea1a63f13f7.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/19951467/187615419-6e6f0370-a79e-41c7-b31e-2c3c9c1649e8.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/19951467/187616106-b8667c9e-5c9a-49ef-8ff9-7972cdea86a1.png">
so，it is something wrong?
Looking forward to your help again
very thanks

**Comment by MarkJoyMa** [comment]
Sorry, I confirmed it, and it is determined that form passing arrays is not supported in zero. There are two ways to solve it, 1. Pass the string in the form and decode it in the business 2. Pass the body。

**Comment by daifuyang** [comment]
> Sorry, I confirmed it, and it is determined that form passing arrays is not supported in zero. There are two ways to solve it.
> 
> 1. Pass the string in the form and decode it in the business.
> 2. Pass the body.

Thanks for your help again. I know how to get it to work. The only thing left to do is wait for an official fix.

**Comment by anqiansong** [comment]
目前 go-zero 是支持form 数组的，参考写法如下：
api 文件
```
articlesDelReq {
    ids []int `form:"ids,optional"`
}
```
对于 GET 方法，你可以通过如下格式访问：
`http://{baseURL}{path}?ids=[1,2,3]`

对于 POST 方法，你可以通过如下格式访问：
`http://{baseURL}{path}`
|key|value|
|:---|:---|
|ids|[1,2,3]|

最终，你将获取到 ids 为`1`,`2`,`3`的数组

> Currently go-zero supports form arrays, the reference is as follows:
> Api file
```
articlesDelReq {
    ids []int `form:"ids,optional"`
}
```
For `HttpMethodGet`, you can write as follows:
`http://{baseURL}{path}?ids=[1,2,3]`

And for `HttpMethodPost`, you can write as follows:
`http://{baseURL}{path}`
|key|value|
|:---|:---|
|ids|[1,2,3]|
> Finally, you will get an array with ids `1`, `2`, `3`
