### ISSUE TITLE
Path problem on generating zrpc.Client.

### ISSUE THREAD

**Issue by 599259501** [zeromicro/go-zero#2338]
假设定义一个proto文件
```
package exp_coupon;
option go_package = "./exp_coupon";
```

根据goctl version 1.3.8 版本执行命令
`
gctl rpc protoc ./proto_files/exp_coupon.proto --go_out=./pb --go-grpc_out=./pb --zrpc_out=.
`
生成的zrpc.client实现会在当前目录单独创建expcoupon目录存储zrpcclient

这个zrpclient能否单独指定输出路径？

**Comment by anqiansong** [comment]
不支持 client 的目录指定，目前只能指定 rpc 服务的目录，client 会放在 rpc 服务目录下
> The directory of the client is not supported, currently you can only specify the directory of the rpc service, the client will be placed in the rpc service directory

**Comment by jsonMark** [comment]
> > 不支持 client 的目录指定，目前只能指定 rpc 服务的目录，client 会放在 rpc 服务目录下
> > > The directory of the client is not supported, currently you can only specify the directory of the rpc service, the client will be placed in the rpc service directory
> 
> 后续是否会有这块的支持？目前存在这种需求，如果多proto文件下这种模式下服务目录下太多的文件了，看起来把zero脚手架生成的整体项目融合在一起了

你还不如直接改成XXX_pb

**Comment by jsonMark** [comment]
> > 不支持 client 的目录指定，目前只能指定 rpc 服务的目录，client 会放在 rpc 服务目录下
> > > The directory of the client is not supported, currently you can only specify the directory of the rpc service, the client will be placed in the rpc service directory
> 
> 后续是否会有这块的支持？目前存在这种需求，如果多proto文件下这种模式下服务目录下太多的文件了，看起来把zero脚手架生成的整体项目融合在一起了

你们是语言开发吗？你可以直接改成go_package = "./XXX_pb";
