### ISSUE TITLE
time.Time无法生成客户端代码，推荐使用int64

### ISSUE THREAD

**Issue by wonderfate** [zeromicro/go-zero#2339]
time.Time无法生成客户端代码，推荐使用int64

_Originally posted by @kevwan in https://github.com/zeromicro/go-zero/issues/404#issuecomment-763368476_

hi there 

I find [ent](https://github.com/ent/ent/blob/1cf4fc88c7889fe05178bb2216eec95b97b85909/schema/field/field.go#L57) seems to be able generated the `time.Time` code.

Have you considered add this feature?

**Comment by anqiansong** [comment]
ent is the mysql code generation tool, and the recommended use of int64 here refers to the response body in the api service. goctl generates mysql code that also supports time.

**Comment by wonderfate** [comment]
> ent is the mysql code generation tool, and the recommended use of int64 here refers to the response body in the api service. goctl generates mysql code that also supports time.

oh, I see.

**Comment by wonderfate** [comment]
> ent is the mysql code generation tool, and the recommended use of int64 here refers to the response body in the api service. goctl generates mysql code that also supports time.

oh, I see.  Thanks

I have one more question. about the goctl api to generate `[2]float64 `

some code snippets as below: 

`my.api`
```
type (
	MyPointResp {
		Coords  [2]float64  `json:"coords"`
	}
)
```

**Current Behavior**

types/types.go:
```go
type MyPointResp struct {
	Coords  []float64  `json:"coords"`
}
```

**Expected Behavior** 

types/types.go:
```go
type MyPointResp struct {
	Coords  [2]float64  `json:"coords"`
}
```

**Comment by anqiansong** [comment]
Got it, you can delete this description and pull a new issue because this problem does not match the title. I'll fix it, for this issue, if you have no any other question ,plz close this issue, thanks!
