### ISSUE TITLE
关于etc/yaml的有一个体验性的问题

### ISSUE THREAD

**Issue by 47968546** [zeromicro/go-zero#2343]
关于etc/yaml的有一个问题

Name: baseadmin.rpc
ListenOn: 127.0.0.1:8080

因为etcd是在本机上测试的话还好
但是如果是在集群和docker下每次都得修改
建议goctl默认生成的时候就直接0.0.0.0

**Comment by jsonMark** [comment]
> 关于etc/yaml的有一个问题
> 
> Name: baseadmin.rpc ListenOn: 127.0.0.1:8080
> 
> 因为etcd是在本机上测试的话还好 但是如果是在集群和docker下每次都得修改 建议goctl默认生成的时候就直接0.0.0.0

这个是写死到代码里面的，到时候可以统一抽离到.tpl模版

**Comment by kevwan** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1918356/189596147-5a5bbda6-c9bc-40ed-9a6f-c927c7557f48.png">

Change to `0.0.0.0` will cause this prompt window in macos.
