### ISSUE TITLE
How can goctl update relevant files instead of deleting and creating when I modify then .api file

### ISSUE THREAD

**Issue by shishisongsong** [zeromicro/go-zero#2346]
Look forward to receiving your answer : )

**Comment by re-dylan** [comment]
What's your specific question?

**Comment by shishisongsong** [comment]
thanks for your reply, I guess I've found the solution

**Comment by kevwan** [comment]
Closing, if any further problem, reopen it.

**Comment by peterinfra** [comment]
@shishisongsong: Can you help document your solution for others too ? 

```
goctl api go -api greet.api -dir greet
greet/etc/greet-api.yaml exists, ignored generation
greet/internal/config/config.go exists, ignored generation
greet/greet.go exists, ignored generation
greet/internal/svc/servicecontext.go exists, ignored generation
greet/internal/handler/greethandler.go exists, ignored generation
greet/internal/logic/greetlogic.go exists, ignored generation
```
If I change a service in the api file, how do I ensure that the other business logic I have written is not overwritten ? As an example, if I were to update the greeter.api to include a new service or update the service with a new parameter, then how does the update logic work ? Pointers in the documentation is appreciated. Thanks
