### ISSUE TITLE
文档不够详细

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#2348]
go-zero框架确实不做，但是希望作者能注重文档的编写，能向其他框架一样文档尽可能的详细并跟随框架、工具同步更新，这是我们很多人的心声。相信go-zero会越来越好，越来越完美

**Comment by re-dylan** [comment]
我们正在计划重新编写文档，争取完善文档，是其更易阅读理解。也欢迎社区一起共同建设。
