### ISSUE TITLE
cache.Cache need Fuzzy query keys

### ISSUE THREAD

**Issue by shrkx** [zeromicro/go-zero#2350]
cache.Cache need Fuzzy query keys
中文：cache.Cache 进行模糊查询keys的方法

要是可以有一个do原始方法就好了

**Comment by chenquan** [comment]
The `keys` command is not recommended for use in a production environment.
https://redis.io/commands/keys/

**Comment by flkgk** [comment]
> `keys`不建议在生产环境中使用该命令。 https://redis.io/commands/keys/

那进行模糊删除的时候，怎么操作呢？

**Comment by chenquan** [comment]
I prefer to specify the exact key to delete the data.
You can pre-store a class of key into the collection, and then take out the key in the collection to delete.
