### ISSUE TITLE
TimingWheel:numSlots

### ISSUE THREAD

**Issue by szmgfcsp** [zeromicro/go-zero#2366]
`type (
	// Execute defines the method to execute the task.
	Execute func(key, value interface{})

	// A TimingWheel is a timing wheel object to schedule tasks.
	TimingWheel struct {
		interval      time.Duration
		ticker        timex.Ticker
		slots         []*list.List
		timers        *SafeMap
		tickedPos     int
		numSlots      int
		execute       Execute
		setChannel    chan timingEntry
		moveChannel   chan baseEntry
		removeChannel chan interface{}
		drainChannel  chan func(key, value interface{})
		stopChannel   chan lang.PlaceholderType
	}

	timingEntry struct {
		baseEntry
		value   interface{}
		circle  int
		diff    int
		removed bool
	}

	baseEntry struct {
		delay time.Duration
		key   interface{}
	}

	positionEntry struct {
		pos  int
		item *timingEntry
	}

	timingTask struct {
		key   interface{}
		value interface{}
	}
)`

时间轮的numSlots具体什么含义，设置多大合适，能否自动适配，感谢

**Comment by kevwan** [comment]
Will work on it to auto tune the parameter numSlots.
