### ISSUE TITLE
Can I create WS service in rpc？

### ISSUE THREAD

**Issue by shrkx** [zeromicro/go-zero#2369]
# 需求：我需要在rpc的服务里面创建ws的服务，因为我需要在其他的服务里面进行消息的发送，通过grpc进行发送ws的消息

## 现有的是api有ws的服务
![1662552115948](https://user-images.githubusercontent.com/44461869/188874584-5dfb42e4-19a0-427b-aa91-1ca5ae4bf9bb.png)

**Comment by kevwan** [comment]
I don't think it's a good practice to do that.

Use WS in api services.

**Comment by flkgk** [comment]
> 我认为这样做不是一个好习惯。
> 
> 在 api 服务中使用 WS。

但是我需要后台的其他的服务，推送ws的消息的时候怎么处理呢？

**Comment by chenquan** [comment]
I think a reasonable route:
`client` -> `api(ws)` -> `rpc`

**Comment by flkgk** [comment]
> 我认为合理的路线： `client`-> `api(ws)`->`rpc`

业务的逻辑需要的线路是： rpc -> ws
 其他的服务发送任务的时候需要进行同步推送ws的消息

**Comment by kevwan** [comment]
It's nothing to do with RPC. You just need to send messages to the clients through WS.

In spite of RPC or HTTP services, you need to know the WS connections where to send the messages.

**Comment by genewoo** [comment]
Also, in case of single direct push notification, use MQ instead.

**Comment by Suyghur** [comment]
why not use rpc stream instead of it?
