### ISSUE TITLE
I want to get the painc signal for custom logic processing !!!

### ISSUE THREAD

**Issue by zekecc** [zeromicro/go-zero#2372]
I want to get the Painc signal for custom logic processing. For example, after capturing panic, send email or enterprise wechat
<img width="565" alt="image" src="https://user-images.githubusercontent.com/39179091/189114140-09641480-eb12-472a-b051-d4cef39b6fc6.png">

**Comment by tiptok** [comment]
```go
func main(){
        defer rescue.Recover(func() {
		// todo 机器人告警
		log.Println("panic recover")
	})
	proc.AddShutdownListener(func() {
		// todo 机器人告警
		log.Println("do shutdown listener")
	})
	server.Start()
	time.Sleep(time.Second*3) 
	panic("error")
}
```

**Comment by kevwan** [comment]
Use `server.Use(...)` to add middleware to detect panics.

**Comment by zekecc** [comment]
> Use `server.Use(...)` to add middleware to detect panics.

thanks ！
