### ISSUE TITLE
how to pass errors in rpc services back into api services?

### ISSUE THREAD

**Issue by xkejiy** [zeromicro/go-zero#2398]
在写rpc 的时候, 我想把 rpc的某个业务流程方面的错误返回给api.   return xx.Reply, errorx.CodeError()  这个errorx.CodeError()对象到api 的时候,类型就不在是 CodeError类型的error了. 现在只能在 reply里面定义code 和msg 我想问下, 好的go-zero项目 关于 rpc返回业务流程错误是怎么做的? 求求大佬给一个好的建议. (业务流程的错误可能有几种)

**Comment by gitsang** [comment]
Try using type assertions

**Comment by titherman** [comment]
> Try using type assertions

好像是没有办法断言的 在到达api层的时候,他的类型已经不是errorx.CodeErr了

**Comment by chenquan** [comment]
Refer to Google's error way:
https://cloud.google.com/apis/design/errors#error_model

Use `status.Status.WithDetails(details ...proto.Message)` to return detailed business errors to the client.

**Comment by gitsang** [comment]
You should not use `errorx` in your svc or biz layer. `errorx` is design for api.

I think that each layer of the program should handle and wrap errors individually, and should not throw errors >2 layers, otherwise the error will become un-enumerable when the upper layer handles errors.

### Bad

```go
// db layer
var ErrNotFound = errors.New("not found")
func Find() error {
    return ErrNotFound
}

// svc layer
func Find() error {
    return db.Find()
}

// logic layer
func FindLogic() (int, interface{}) {
    err := svc.Find()
    if err != nil {
        if errors.Is(db.ErrNotFound, err) { // logic layer should not handle error from db layer
            return 404, "fail"
        } else {
            return 200, "success"
        }
    }
}
```

### Bad

```go
// db layer
var ErrNotFound = errors.New("not found")
func Find() (int, error) {
    return 404, ErrNotFound // logic layer should not consider about api error
}

// svc layer
func Find() (int, error) {
    return db.Find()
}

// logic layer
func FindLogic() (int, interface{}) {
    return svc.Find()
}
```

### Good

```go
// db layer
var ErrNotFound = errors.New("not found")
func Find() error {
    return ErrNotFound
}

// svc layer
var ErrNotFound = errors.New("not found") // wrap the error
func Find() error {
    err := db.Find()
    if err != nil {
        if errors.Is(db.ErrNotFound, err) {
            return ErrNotFound
        } else {
            return nil
        }
    }
}

// logic layer
func FindLogic() (int, interface{}) {
    err := svc.Find()
    if err != nil {
        if errors.Is(svc.ErrNotFound, err) { // should only handle svc error
            return 404, "fail"
        } else {
            return 200, "success"
        }
    }
}
```

**Comment by gitsang** [comment]
> > Try using type assertions
> 
> 好像是没有办法断言的 在到达api层的时候,他的类型已经不是errorx.CodeErr了

`errorx.CodeErr` is the implement of `error`. It should be possible to be asserted
