### ISSUE TITLE
a doubt of goctl help message

### ISSUE THREAD

**Issue by tim1116** [zeromicro/go-zero#2408]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9588681/190881599-17e941c6-4b8e-4990-b419-8e07fe3f6e53.png)

**To Reproduce**
goctl api -h         

1. The code is

   ```go
   goCmd = &cobra.Command{
		Use:   "go",
		Short: "Generate go files for provided api in yaml file",
		RunE:  gogen.GoCommand,
	}
   ```

2. The error is

   ```
   Generate go files for provided api in yaml file
   ```

**Expected behavior**
Generate go files for provided api in api file

**Environments (please complete the following information):**
 - OS: [Linux]
 - go-zero version [1.4.0]

**More description**

I think, Generate go files for provided api in api file not in yaml file

**Comment by MarkJoyMa** [comment]
ok, got it, thanks for pointing it out
