### ISSUE TITLE
How can goctl add a new model method, I named it as follows and it didn't work, how can it work or is there any other better solution?

### ISSUE THREAD

**Issue by yigeqiji** [zeromicro/go-zero#2415]
![image](https://user-images.githubusercontent.com/59365443/190958062-e330f343-e084-4f16-9186-a9cf50634160.png)

**Comment by yigeqiji** [comment]
I've added it to another template for now, but I don't think it's a good solution.
![image](https://user-images.githubusercontent.com/59365443/190961156-c8483dab-ee5a-4441-8b9f-2ac3bec6cb46.png)

**Comment by anqiansong** [comment]
The template file does not support adding files, you can only modify the content on the existing template file or modify the template based on the existing variables in the template

**Comment by jsonMark** [comment]
我是直接在update这个模版新增方法，然后修改goctl代码，新增自己需要的参数
