### ISSUE TITLE
goctl版本对不上

### ISSUE THREAD

**Issue by xhochipe** [zeromicro/go-zero#2419]
![image](https://user-images.githubusercontent.com/9391575/191025624-ea98c8ce-9675-4c5a-9300-d14661a56ee2.png)
重新拉去的，一直是1.4.0，不是1.4.1

**Comment by anqiansong** [comment]
This release has omitted the revision of the goctl version, which does not affect the use of the function, and there has no major changes on this release.

**Comment by bensonfx** [comment]
@xhochipe go-zero 最新版本是：1.4.1， 但goctl的最新版本是1.4.0
