### ISSUE TITLE
rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"}

### ISSUE THREAD

**Issue by yuwei43** [zeromicro/go-zero#2423]
rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"}

Call the rpc to return this error
What is the reason for this? The encoding I requested has been converted to utf-8

**Comment by leafney** [comment]
Encountered the same problem, again request will be normal. No reason was found.
