### ISSUE TITLE
goctl gen model with pg and cache leads to a column "xxx" does not exist error

### ISSUE THREAD

**Issue by akalittle** [zeromicro/go-zero#2428]
**Describe the bug**
I use the code generated by `goctl model pg datasource -url="postgresql://postgres@localhost:5432/postgres?sslmode=disable" -table="xxx" -c`

the ddl is below and there is a `unique index` 

```
CREATE TABLE tx_status (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    network character varying(255) NOT NULL,
    hash text NOT NULL,
    status character varying NOT NULL,
    receipt jsonb NOT NULL DEFAULT '{}'::jsonb,
    "createAt" timestamp with time zone NOT NULL,
    "updateAt" timestamp with time zone NOT NULL
);


-- Indices -------------------------------------------------------


CREATE UNIQUE INDEX tx_network_hash_uniq_index ON tx_status(network text_ops,hash text_ops);

```

 
**To Reproduce**

1. The code is

   ```go
   	res, err := l.svcCtx.DB.FindOneByNetworkHash(l.ctx, network, in.Hash)

   ```

2. The error is

   ```
   {"@timestamp":"2022-09-21T15:03:22.197+08:00","caller":"sqlx/utils.go:140","content":"stmt: select id,network,hash,status,receipt,createAt,updateAt from \"public\".\"tx_status\" where network = 'xxx' and hash = 'xxx' limit 1, error: pq: column \"createat\" does not exist","level":"error","span":"754988c3cdf31f51","trace":"d69c8f5d160d9b30dbab024f1b353bd4"}

   ```

It's strange while in the log the column  is camelcase , but in the error message the column is lowercased.

**Expected behavior**
no error
**Screenshots**
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/38489160/191438707-5ffd4b10-6e74-408f-bc1a-cdeb069e02c9.png">

**Environments (please complete the following information):**
 - OS: macos 12.5.1
 - github.com/zeromicro/go-zero v1.4.1
 - goctl version 1.4.0 darwin/amd64

**Comment by akalittle** [comment]
The fields are from :
```
	txStatusFieldNames          = builder.RawFieldNames(&TxStatus{}, true)
	txStatusRows                = strings.Join(txStatusFieldNames, ",")
```

I can hack this time. But it's not the right way to solve this problem forever.

**Comment by akalittle** [comment]
This error also happens in `FindOne`  function.
```
{"@timestamp":"2022-09-22T10:23:00.305+08:00","caller":"sqlx/utils.go:139","content":"stmt: select id,network,hash,status,receipt,createAt,updateAt from \"public\".\"tx_status\" where id = 16268 limit 1, error: pq: column \"createat\" does not exist","level":"error","span":"7cbb99e9939a30e0","trace":"ebdd9781527ac4e87500db7ea60e2d29"}

```

**Comment by MaxToby** [comment]
Postsql is case sensitive, just change the uuutest field name to lowercase

**Comment by akalittle** [comment]
> Postsql is case sensitive, just change the uuutest column name to lowercase. https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

Do you see the sql statement above ?
It's the right case.

**Comment by akalittle** [comment]
Anyone follow this issue ?

**Comment by akalittle** [comment]
Hey, is anyone following this issue ?

**Comment by anqiansong** [comment]
See #2100

**Comment by akalittle** [comment]
> See #2100

So what about the column `uuuTest` ?

**Comment by akalittle** [comment]
Can you have a look at this issue? It's been a long time.
@anqiansong  @kevwan
