### ISSUE TITLE
logx: support Warn/Warning level

### ISSUE THREAD

**Issue by lhcGinv** [zeromicro/go-zero#2438]
**Is your feature request related to a problem? Please describe.**

When using logx, I found that the current log level is not enough for the production environment. Generally, there is also a warning level log between the info level and the error level.

**Describe the solution you'd like**

At present, I find that the next version of go-zero will add debug level logs(https://github.com/zeromicro/go-zero/commit/e6aa6fc3619450a89039c75361cadf6eddb44b12), so is it possible to add warning level logs in the next version？🙏

**Comment by lsixi** [comment]
Each team has different requirements for log levels. However, popular log repositories such as zap or logrus have warn level logs or even richer logs. debug, info, warn, and error are the most commonly used log levels

**Comment by lsixi** [comment]
Maybe the custom log level is also a positive solution

**Comment by chenquan** [comment]
Hey, we'll revisit the issue when there are more voices.

**Comment by kevwan** [comment]
> Maybe the best solution is to customize the log level

Good suggestion.

**Comment by nicklaros** [comment]
my team need the Warn level so bad. I think logx should have this as built-in functionality
