### ISSUE TITLE
aliyun k8s，api failed to call rpc

### ISSUE THREAD

**Issue by chenqiaorui** [zeromicro/go-zero#2449]
背景：服务使用无状态(Deployment)部署，pod容器使用supervisord去启动api和rpc服务，如user-api和user-rpc，user-api会去调用user-rpc。

问题：正常情况下，user-api能顺利调通user-rpc，etcd也能查到user-rpc注册上去的 `pod容器ip:port`。但当我滚动更新Deployment之后，新起的user-api会连到旧的user-rpc地址，可是旧的user-rpc已经下线了，etcd上查到的只有新的user-rpc的pod地址加端口。上面的情况是不稳定复现的，滚动更新30次可能会有1、2次发生。

**Comment by kevwan** [comment]
multiple services in one pod?

**Comment by chenqiaorui** [comment]
Yes, using supervisord to start rpc and api service in one pod. The supervisord script can be see below. :)

**Comment by chenqiaorui** [comment]
![image](https://user-images.githubusercontent.com/28795155/192182408-13215d10-d4c7-40e6-98e8-e1e3a7d6181e.png)

**Comment by jsonMark** [comment]
> 背景：服务使用无状态(Deployment)部署，pod容器使用supervisord去启动api和rpc服务，如user-api和user-rpc，user-api会去调用user-rpc。
> 
> 问题：正常情况下，user-api能顺利调通user-rpc，etcd也能查到user-rpc注册上去的 `pod容器ip:port`。但当我滚动更新Deployment之后，新起的user-api会连到旧的user-rpc地址，可是旧的user-rpc已经下线了，etcd上查到的只有新的user-rpc的pod地址加端口。上面的情况是不稳定复现的，滚动更新30次可能会有1、2次发生。

你都k8s了，为什么不单独部署镜像？？你是阿里云ack还是ask？？？其次你们是有历史遗留问题吗？服务注册与发现可以直接使用k8s，这样可以少维护一套组件。我们ask跑了4个月，暂时感觉还可以（没多少流量）

**Comment by chenqiaorui** [comment]
@jsonMark 没有单独部署镜像是因为我们内部微服务数量过多，基本上一个模块就有rpc+api，单独部署感觉会难以维护。K8s是ack类型。至于你说"服务注册与发现可以直接使用k8s"，你是指直接使用k8s的etcd集群做服务注册发现还是通过K8s 的endpoints实现服务间访问？

**Comment by chenqiaorui** [comment]
我的Deployment是通过supervisor去管理rpc和api的。后来我在supervisor的配置加了一个priority属性，让rpc先于api服务启动，观察了一段时间没有出现问题。

**Comment by jsonMark** [comment]
> @jsonMark 没有单独部署镜像是因为我们内部微服务数量过多，基本上一个模块就有rpc+api，单独部署感觉会难以维护。K8s是ack类型。至于你说"服务注册与发现可以直接使用k8s"，你是指直接使用k8s的etcd集群做服务注册发现还是通过K8s 的endpoints实现服务间访问？

AdminRpc:
  Timeout: 10000
  Target: k8s://admin-namespace/admin-rpc-svc:1000
