### ISSUE TITLE
How can i set grpc message size

### ISSUE THREAD

**Issue by sithu-go** [zeromicro/go-zero#2451]
In grpc, I can do like that
```go
		grpcServerOption := grpc.MaxRecvMsgSize(1024 * 1024 * 10)
```

but in zrpc, I don't find ## zrpc.MaxRecvMsgSize

```json
{
    "error": "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5862997 vs. 4194304)"
}
```

**Comment by kevwan** [comment]
Use `svr.AddOption(grpc.MaxRecvMsgSize(1024 * 1024 * 10))`

**Comment by Verystone** [comment]
I use this in the rpc  server
s.AddOptions(grpc.MaxRecvMsgSize(1024 * 1024 * 10))
s.AddOptions(grpc.MaxSendMsgSize(1024 * 1024 * 10))

The api call rpc, get error msg :  grpc: received message larger than max (7617251 vs. 4194304)

How to config for the rpc client ?

**Comment by Verystone** [comment]
I solved this problem. Use this for the client

    dialOption := grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*10))
    opt := zrpc.WithDialOption(dialOption)

    zrpc.MustNewClient(config, opt)

**Comment by Verystone** [comment]
> I use this in the rpc server s.AddOptions(grpc.MaxRecvMsgSize(1024 * 1024 * 10)) s.AddOptions(grpc.MaxSendMsgSize(1024 * 1024 * 10))
> 
> The api call rpc, get error msg : grpc: received message larger than max (7617251 vs. 4194304)
> 
> How to config for the rpc client ?

I solved this problem. Use this for the client

    dialOption := grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*10))
    opt := zrpc.WithDialOption(dialOption)

    zrpc.MustNewClient(config, opt)

**Comment by dyjfighting** [comment]
> > I use this in the rpc server s.AddOptions(grpc.MaxRecvMsgSize(1024 * 1024 * 10)) s.AddOptions(grpc.MaxSendMsgSize(1024 * 1024 * 10))
> > The api call rpc, get error msg : grpc: received message larger than max (7617251 vs. 4194304)
> > How to config for the rpc client ?
> 
> I solved this problem. Use this for the client
> 
> ```
> dialOption := grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*10))
> opt := zrpc.WithDialOption(dialOption)
> 
> zrpc.MustNewClient(config, opt)
> ```

config is what?
