### ISSUE TITLE
alert some error messages while using one etcd endpoint

### ISSUE THREAD

**Issue by brucewenyu** [zeromicro/go-zero#2461]
{"ts":"2022-09-27T18:22:43.423+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007101c0/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
panic: context deadline exceeded

func (rs *RpcServer) Start() {
	if err := rs.server.Start(rs.register); err != nil {
		logx.Error(err)
		panic(err)
	}
}

panic(err) 

How did I solve this problem? Can anyone help fix this? thanks~

**Comment by akalittle** [comment]
From the log message, it's `context deadline exceeded`. You should check whether the connection is normal first.

**Comment by brucewenyu** [comment]
> From the log message, it's `context deadline exceeded`. You should check whether the connection is normal first.
> 
> Is the host named `etcd` reachable in your machine ?

It's my mistake, thanks a lot~
