### ISSUE TITLE
go-zero looks great! 🥇 

### ISSUE THREAD

**Issue by gkuanine** [zeromicro/go-zero#2465]
但是好像没有  使用开源的go-zero成套开源商业项目  （收费也行） （小项目也可以）不然小白感觉用的很费力 目前还是用gin+gorm开发单体简单点

**Comment by gkuanine** [comment]
对比了jupiter   go-kratos  感觉落地有难度  现在看go-zero好像成熟一些 start也更快  想用这个框架

**Comment by re-dylan** [comment]
You can get more demo at https://github.com/Mikaelemmmm/go-zero-looklook

**Comment by rxrddd** [comment]
you can see `https://github.com/zeromicro/awesome-zero`

**Comment by jsonMark** [comment]
这个是你想要的https://github.com/arklnk/ark-admin-zero还有https://github.com/suyuan32/simple-admin-core这个，其他项目就看知乎https://zhuanlan.zhihu.com/p/504337301。近期会长期更新的。
