### ISSUE TITLE
support proto to support the generation of multiple files

### ISSUE THREAD

**Issue by phpmaple** [zeromicro/go-zero#2469]
I hope to support proto to support the generation of multiple files at the same time as soon as possible. Just like the generation of api, multiple protos can be generated in different folders in a service. Now we have too many interfaces in one service, and protos are not easy to maintain

**Comment by jsonMark** [comment]
这个功能我也想要，类似api的分组功能，不知道还有多少人需要这个功能。

**Comment by gghtrt520** [comment]
I want this function too

**Comment by xhochipe** [comment]
+1

**Comment by crazy6995** [comment]
+1
