### ISSUE TITLE
The APIs to create MongoDB connection need official options.

### ISSUE THREAD

**Issue by jiangz222** [zeromicro/go-zero#2475]
For instance, [NewModel](https://github.com/zeromicro/go-zero/blob/master/core/stores/mon/model.go#L50).

We expect mongoDB connection URI can cover most of mongoDB-official-driver's option, and [ApplyURI](https://github.com/mongodb/mongo-go-driver/blob/master/mongo/options/clientoptions.go#L244) can get options from URI.

But it doesn't work for every option, like [Monitor](https://github.com/mongodb/mongo-go-driver/blob/master/mongo/options/clientoptions.go#L114).

**Comment by kevwan** [comment]
Would you please give an example to show what do you expect? Code snippet? Thanks!

**Comment by jiangz222** [comment]
I want to set monitor when create connection to mongoDB
```go
	m := &event.CommandMonitor{}
	m.Succeeded = func(ctx context.Context, succeededEvent *event.CommandSucceededEvent) {
		fmt.Println("callback ", succeededEvent.CommandName)
	}
	opt := opts.Client().SetMonitor(m)
	client, err = mongo.Connect(ctx, opt)
```

In go-zero, `mongo.Connect` only get options from URI by `ApplyURI`, URI can't carry every [options](https://github.com/mongodb/mongo-go-driver/blob/master/mongo/options/clientoptions.go#L96)
```go
func getClient(url string) (*mongo.Client, error) {
	val, err := clientManager.GetResource(url, func() (io.Closer, error) {
		cli, err := mongo.Connect(context.Background(), mopt.Client().ApplyURI(url))
		if err != nil {
			return nil, err
		}

		concurrentSess := &ClosableClient{
			Client: cli,
		}

		return concurrentSess, nil
	})
	if err != nil {
		return nil, err
	}

	return val.(*ClosableClient).Client, nil
}
```
