### ISSUE TITLE
like rpc, provide the unified method to call api services, with service register and discover

### ISSUE THREAD

**Issue by mengdj** [zeromicro/go-zero#2481]
希望提供rest(api)统一的调用方式，类似rpc一样，服务注册，客户端调用时的负载均衡(类似springboot里的feignclient)
api启动后自身完成注册，并生成interface,其它api或rpc直接通过接口即可调用

我这随便写了一个，通过插件的形式实现的，不知道有没有啥问题
[https://github.com/mengdj/goctl-rest-discover](url)

**Comment by foliet** [comment]
Why do you want to do this? Usually, rest services are used as gateway converting http request into grpc request and finishing something other. When do them need to be called?🤔

**Comment by mengdj** [comment]
> 

因为api和rpc 组合起来感觉很麻烦，每个都要写的话
