### ISSUE TITLE
How to stop api/rpc service

### ISSUE THREAD

**Issue by WoolenWang** [zeromicro/go-zero#2490]
**Is your feature request related to a problem? Please describe.**
https://github.com/zeromicro/go-zero/blob/master/rest/server.go#L102
https://github.com/zeromicro/go-zero/blob/master/zrpc/server.go#L98

now the Stop is a fake stop.. how to stop the service by code..

**Describe the solution you'd like**
let the stop be Real stop service, make a fake stop is “大聪明“ idea .

**Describe alternatives you've considered**

**Additional context**

**Comment by kevwan** [comment]
Check it here:

https://github.com/zeromicro/go-zero/blob/fc59aec2e7f591ec70359b90fb1af32c731e8386/rest/internal/starter.go#L41
