### ISSUE TITLE
httpx.Parse() not working well with customized data types, complains "type mismatch for field"

### ISSUE THREAD

**Issue by lxxwilliam** [zeromicro/go-zero#2492]
如何解析自定义数据类型

**Comment by kevwan** [comment]
Please give an example.

**Comment by lxxwilliam** [comment]
![image](https://user-images.githubusercontent.com/30308455/194763853-629570c3-73a3-4f2c-b51e-3065ee646b5a.png)
![image](https://user-images.githubusercontent.com/30308455/194763923-fbc1286c-99b7-4904-9282-2e3963222d9e.png)
这是我的自定义数据类型 实现了MarshalJSON、UnmarshalJSON方法 httpx.Parse()方法无法映射到对应的结构体上并提示type mismatch for field

**Comment by Suyghur** [comment]
go-zero使用的是自己的jsonx而并非标准库，所以你实现了标准库的接口也并不能完成解析
