### ISSUE TITLE
IntelliJ plugin "Goctl" should support resolve import api file elements 

### ISSUE THREAD

**Issue by axiangcoding** [zeromicro/go-zero#2494]
**Is your feature request related to a problem? Please describe.**
```
import "../../../common/types.api"

...

service user-api {
	@handler update
	post /user/update (CommonReq) returns (CommonResp)
}
```
`CommonReq` and `CommonResp` are both describe in "../../../common/types.api", and goctl generate code successfully.
However on the UI, goland shows "can not resolve CommonReq", this may be misleading to users

**Describe the solution you'd like**
plugin "Goctl" should support resolve elements from imported api files.

**Describe alternatives you've considered**
If it is difficult to achieve, maybe change the error message, for example: `can not resolve CommonReq, could be from imported api files`

**Additional context**
"Goctl" plugin version 1.1.3

**Comment by anqiansong** [comment]
You can post a new issue in repo https://github.com/zeromicro/goctl-intellij/issues

**Comment by waltcow** [comment]
this bug is very annoying

**Comment by kesonan** [comment]
fix on https://github.com/zeromicro/goctl-intellij/pull/29
