### ISSUE TITLE
Form Files

### ISSUE THREAD

**Issue by hayden-erickson** [zeromicro/go-zero#2498]
**Is your feature request related to a problem? Please describe.**
Currently, when I define a type there is no way to specify a form file field. In other words, I'd like to define an endpoint that can accept a multipart form file. The form file part of the request is a complex type containing a header with file metadata and the actual file content split by a delimiter which is also defined in the header. 

**Describe the solution you'd like**
In a request type, I'd like to specify that there is a form field, say `upload_file` for instance that represents a multipart form file.

for example
```
@server(
  group: files
  prefix: /files
  middleware: CurrentUser
)

service files {
  @handler UploadFile
  post /upload (UploadFileRequest) returns ()
}

type UploadFileRequest {
  File []byte `form:"upload_file"` // This is the part that is not supported from what I can tell.
}
```

**Describe alternatives you've considered**
Defining a custom http handler. This works, but we lose the code generation and shared middleware of our other endpoints. 

**Additional context**

**Comment by Suyghur** [comment]
If you want to parse the file byte stream in the form, you see zero-example repo

**Comment by jsonMark** [comment]
you can see [ ](https://github.com/zeromicro/zero-examples/tree/main/http/upload) ,it may be sure you
