### ISSUE TITLE
why not using singleton pattern for routinegroup?

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#2502]
core/threading/routinegroup.go

// A RoutineGroup is used to group goroutines together and all wait all goroutines to be done.
type RoutineGroup struct {
	waitGroup sync.WaitGroup
}

// NewRoutineGroup returns a RoutineGroup.
func NewRoutineGroup() *RoutineGroup {
	return new(RoutineGroup)
}

**Comment by chenquan** [comment]
`RoutineGroup` is an encapsulation of `sync.WaitGroup` that controls the behavior of a group of coroutines. The behavior of each group of coroutines may be different.
