### ISSUE TITLE
Consider replacing the mongo driver library with an official one that is still being maintained

### ISSUE THREAD

**Issue by me-cs** [zeromicro/go-zero#2506]
**Is your feature request related to a problem? Please describe.**
https://github.com/globalsign/mgo is inactive

**Describe the solution you'd like**
Change the mongodb driver to the official

**Describe alternatives you've considered**
such as  https://github.com/mongodb/mongo-go-driver

**Additional context**

**Comment by chenquan** [comment]
Completed in  in [v1.3.3](https://github.com/zeromicro/go-zero/releases/tag/v1.3.3): https://github.com/zeromicro/go-zero/pull/1782

**Comment by me-cs** [comment]
good
