### ISSUE TITLE
httpx.Parse 解析到结构体时会出现数据不一致

### ISSUE THREAD

**Issue by thunur** [zeromicro/go-zero#2509]
实体配置
userCollectReq {
        id int64    `json:"id"`
        Type int64  `json:"type,options=1|2|3|4|5|6|7"`
 }
json示例：
{
    "id": 3535025560474504129,
    "type": 4,
}
实际赋值到结构体上的值
![image](https://user-images.githubusercontent.com/30105521/195547888-69874e0a-f943-4fdc-bbe6-dd777d640522.png)

从上图可以看到最后的129已经变0了，
如果是长度问题，那么我将第一位3改成4的时候
![image](https://user-images.githubusercontent.com/30105521/195548062-23c63680-ced4-4387-a153-607ed5ac3449.png)

实际数据则也变化了。

**Comment by thunur** [comment]
在go int64中长度也是支持的，现在我只能用string接收，在转成int64

**Comment by xhochipe** [comment]
你这个不是框架问题，是你使用问题，你用postman传递参数你试试，前端int64会精度丢失...查下资料就知道了
