### ISSUE TITLE
problems on deserializing empty strings

### ISSUE THREAD

**Issue by DomineCore** [zeromicro/go-zero#2517]
## 我的需求：在写api文件时，定义一个不可为空的参数repo:
<img width="800" alt="企业微信截图_1f4179db-0764-4b61-ac31-3d8fd93c2686" src="https://user-images.githubusercontent.com/50765823/195758647-9d4f1d19-9966-416c-b21c-67855a400335.png">
## 现象：当我传入repo=''时，可以通过校验
<img width="518" alt="企业微信截图_5c6f63c9-ddc1-4a05-b262-98855050d774" src="https://user-images.githubusercontent.com/50765823/195758701-fad34912-a0de-4daf-a13b-a036bd13c7d9.png">
## 现象：当我传入repo=null时，不可以通过校验
<img width="356" alt="企业微信截图_5609d4f9-b574-4837-b0a8-08fafb4ab057" src="https://user-images.githubusercontent.com/50765823/195758754-40ff094b-e16e-4f8c-9fec-8dc3b2cddd13.png">
## 我的期望：对于字符串，传入''也应该不通过校验

**Comment by Suyghur** [comment]
其实没什么问题，空值也是一种值，确实不等于null，我觉得比喻说判断空字符串这种操作交由给用户处理会更恰当

**Comment by wsx864321** [comment]
可以自己在业务层当中去做校验

**Comment by anqiansong** [comment]
The nil tips of go-zero means zero-value, you should define your request structure as follows:
```
createRespositortRequest{
  Repo string `json:"repo,optional"`
....
}
```
