### ISSUE TITLE
timeout changed after passing api context to rpc

### ISSUE THREAD

**Issue by xiaoliao666-1** [zeromicro/go-zero#2518]
api代码
![image](https://user-images.githubusercontent.com/83824794/195810593-3d3fcbd5-a881-4743-b84e-0f04af14b4f9.png)
api context传递
![image](https://user-images.githubusercontent.com/83824794/195810518-c4ed3ca7-32a0-451f-b242-08b880251812.png)

rpc context打印
![image](https://user-images.githubusercontent.com/83824794/195810348-6e186305-e666-4d2e-810a-a90c15c85054.png)

api结果

![image](https://user-images.githubusercontent.com/83824794/195811469-079d29fd-0ed0-46e9-99b2-7d384de8ea43.png)

rpc结果

![image](https://user-images.githubusercontent.com/83824794/195811562-3da1d444-170b-41c3-8bf5-211dc8a37e60.png)

**Comment by wsx864321** [comment]
你当前的context的超时时间只会对当前服务有影响，你在rpc中看到的context的超时时间RpcServerConf中的超时时间，看你的截图猜测应该就是默认的配置的2000ms

**Comment by xiaoliao666-1** [comment]
![image](https://user-images.githubusercontent.com/83824794/195970132-2f174a7f-b1b8-4b48-81d0-9b095247c808.png)
当我配置文件修改了后
![image](https://user-images.githubusercontent.com/83824794/195970152-1fade131-5532-4665-ac96-b284a8d0843b.png)
![image](https://user-images.githubusercontent.com/83824794/195970161-06f366dd-e570-4f23-850e-20535f0306d9.png)
依然是没起效果，我的操作问题吗？

**Comment by re-dylan** [comment]
Please put Timeout After ListenOn, like this
`
Name: formalasset.rpc
ListenOn: 0.0.0.0:8080
Timeout: 100000
Etcd:
  Hosts: 
  - 127.0.0.1:2379
  Key: formalasset.rpc
`

**Comment by xiaoliao666-1** [comment]
timeOut这个值都能拿到但是我的超时还是2s

**Comment by Crystalplan** [comment]
遇到同样的超时设置不生效问题，希望得到回答解决，谢谢

**Comment by kevwan** [comment]
you need to set timeout in both client and server sides.

**Comment by hachi-zzq** [comment]
遇到同样的问题，我在RPC 端设置的超时时间是 5s, 假如我不通过 API 调用，而是通过 RPC 其他工具调用，超时的配置是生效的，但是我用 API 调用，超时时间就变成了默认的两秒。
