### ISSUE TITLE
Recommend to update docs and examples.

### ISSUE THREAD

**Issue by wyzlhf** [zeromicro/go-zero#2530]
首先关于kevwan电商博客的案例中，有如下问题：
1、在Order服务中的api获取orderlist在api文件中的response返回的是单一response，不是responselist，导致此处不能跑通。已在群中进行询问，需要进一步封装一遍。
2、博客案例和官网文档对rpc调用时候使用名称还是名称+client比较混乱，我这里使用名称+client调用是成功的。两周前刚开始使用go-zero时候，看官网文档还是名称就行，但是过两天发现报错。群中咨询后据说是改版了，然后发现官网也相应做了调整。但是昨天翻官网好像又改回了名称调用。请尽量保持文档和示例的正确和稳定啊！！！示例如下：
`type ServiceContext struct {
	Config config.Config

	PayModel model.PayModel

	UserRpc  user.User
	OrderRpc order.Order
}`以上是博客示例给出的，现在似乎应该是如下的方式：
`type ServiceContext struct {
	Config config.Config
	PayModel model.PayModel

	UserRpc userclient.User
	OrderRpc orderclient.Order
}`。目前在大多数文档中，都没有进行更新。

同样，servicecontext.go中也应该是：
func NewServiceContext(c config.Config) *ServiceContext {
	conn:=sqlx.NewMysql(c.Mysql.DataSouce)
	return &ServiceContext{
		Config: c,
		PayModel: model.NewPayModel(conn,c.CacheRedis),
		UserRpc: userclient.NewUser(zrpc.MustNewClient(c.UserRpc)),
		OrderRpc:orderclient.NewOrder(zrpc.MustNewClient(c.OrderRpc)),
	}
}

**Comment by wyzlhf** [comment]
_, err := l.svcCtx.UserRpc.UserInfo(l.ctx, &user.UserInfoRequest{
		Id: in.Uid,
	})
改为：
_,err:=l.svcCtx.UserRpc.UserInfo(l.ctx,&userclient.UserInfoRequest{
		Id: in.Uid,
	})

**Comment by leafney** [comment]
> 对rpc调用时候使用名称还是名称+client比较混乱

我也遇到过这个问题。有的时候生成是 `user.User` ，有的时候生成是 `userclient.User` 。不知道是为什么，也没找到规律。可能大概也许跟天气有关吧

**Comment by anqiansong** [comment]
@wyzlhf 建议将此问题移动到文档仓库下，文档问题并非 go-zero 问题
> It is recommended to move this issue to the documentation repository, the documentation issue is not a go-zero issue

**Comment by zhenhua1** [comment]
特别强的强烈建议定期更新文档

**Comment by jsonMark** [comment]
> userclient

userclient.User 这是go-zero版本升级导致的
