### ISSUE TITLE
goctl model pg datasource  无法生成表结构有数组的字段

### ISSUE THREAD

**Issue by zhouzun8709** [zeromicro/go-zero#2541]
**Describe the bug**
goctl model pg datasource  无法生成表结构有数组的字段

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is
goctl model pg datasource  --url="postgres://postgres:****@1****:9543/zz_oms_2.0?sslmode=disable" --table="tbl_cd" --dir="./model"

2. The error is
![fb26cbb1c0cbb359a3987e310c62f9d](https://user-images.githubusercontent.com/34676599/197095908-638af8cb-41eb-42ed-b8a0-166aabd3ac83.png)

**Screenshots**
![a9f52470449b6f11645a797a1caa3c8](https://user-images.githubusercontent.com/34676599/197096030-9829f2cb-5638-4bff-bf16-f6e824ca6112.png)

**Environments (please complete the following information):**
 - OS: windows11
 - go-zero version 1.4
 - goctl version 1.4

**More description**

**Comment by chenquan** [comment]
@anqiansong
