### ISSUE TITLE
postgresql, numeric(12,4) should be float in struct, but got int64

### ISSUE THREAD

**Issue by zhouzun8709** [zeromicro/go-zero#2550]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by zhouzun8709** [comment]
postgresql  某a字段类型int2 ,go 结构体中int64 字段a,做条件查询时返回：<nil> pq: operator does not exist: ` smallint

**Comment by M-MoMoMo** [comment]
This problem has not been solved so far.

**Comment by kevwan** [comment]
@anqiansong
