### ISSUE TITLE
API struct  Support both form and Json tag

### ISSUE THREAD

**Issue by coverthesea** [zeromicro/go-zero#2554]
**Is your feature request related to a problem? Please describe.**
When setting the form and json tag, Request error
Hope that the interface can support both form and json format requests

希望接口能同时支持json和form的格式的请求，现在如果同时设置json和form，请求会报错

**Comment by chenquan** [comment]
Can you give a detailed example?

**Comment by kevwan** [comment]
For a parameter, it should be clear that if it's in form or json body.
