### ISSUE TITLE
Feature survey: do you use ` to assemble the query statements for sql in customized model templates?

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#2563]
如果大家都有这种需求，我就把model全部挪到tpl文件代码提交到官方。下面这种`id`写法：
query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
如果大家都有这个需求，我就把model的模版统一挪到tpl格式文件，避免官方下面代码

package template

// Tag defines a tag template text
const Tag = "`db:\"{{.field}}\"`"

的`和自己的`id`的`冲突

**Comment by fyyang** [comment]
没太懂你想表达的啥

**Comment by jsonMark** [comment]
> 没太懂你想表达的啥

代码我提交了仓库了https://github.com/zeromicro/go-zero/pull/2564，主要解决2点：
1.方便改造goctl模板用户升级goctl版本，现在模板名字和最终template init 生成的模板文件名称是一致的
2.自定SQL中带有 ` 这种符号会和现有这种 模板变量 使用``包含冲突

**Comment by jsonMark** [comment]
> 没太懂你想表达的啥

代码我提交了仓库了https://github.com/zeromicro/go-zero/pull/2564%EF%BC%8C%E4%B8%BB%E8%A6%81%E8%A7%A3%E5%86%B32%E7%82%B9%EF%BC%9A
1.方便改造goctl模板用户升级goctl版本，现在模板名字和最终template init 生成的模板文件名称是一致的(昨天发现的)
2.自定SQL中带有 ` 这种符号会和现有这种 模板变量 使用``包含冲突

**Comment by fyyang** [comment]
I remember someone mentioned this before, but generally the template will be modified for application
