### ISSUE TITLE
can not run the program

### ISSUE THREAD

**Issue by your-ben-brother** [zeromicro/go-zero#2565]
when i run the example programe,i got the error below and don't know why , i'm a newer to go, just want to run demo, now it's blocked,so big brother i need you help 

GOROOT=D:\software\go #gosetup
GOPATH=D:\go\gopath #gosetup
D:\software\go\bin\go.exe build -o C:\Users\daben\AppData\Local\Temp\GoLand\___1go_build_go_zero_demo_mall_user_rpc.exe go-zero-demo/mall/user/rpc #gosetup
go build k8s.io/client-go/applyconfigurations/core/v1: D:\software\go\pkg\tool\windows_amd64\compile.exe: exit status 0xc0000374

Compilation finished with exit code 1

**Comment by kevwan** [comment]
You need to compile your `hello world` program in Go first. I guess.
