### ISSUE TITLE
can we support request param field type like interface, json.RawMessage?

### ISSUE THREAD

**Issue by wyaow** [zeromicro/go-zero#2592]
sometimes, the field may be not a concrete type (like int, string ...). 
It may be interface{} type. But this can not be solved by go-zero framework.
``` go
type Request struct {
	YData json.RawMessage `json:"YData"`       // can not be parsed
	ZData interface{}     `json:"ZData"`               // can not be parsed
        ...

        // interface type now can be achived by define map[string]interface{}, like below：
	Data map[string]interface{} `json:"data"`    // this is ok, can parse body success
}
```

**Comment by bensonfx** [comment]
can you explain more detail in what case you need this?

because we have to unmarshal the json string to type, I'am afraid you need to add a custom json unmarshal function. 

I think it need more discuss

**Comment by wyaow** [comment]
> 

+1
