### ISSUE TITLE
No limit package in goctl 1.4.2?

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#2599]
goctl 1.4.2但是没有limit这个包没有NewPeriodLimit
![image](https://user-images.githubusercontent.com/22211474/201517054-e7cc9448-59d9-435a-9a8c-9466fb6ddb29.png)

这是不是意味着底层没有做限流

**Comment by kevwan** [comment]
check it out here: https://github.com/zeromicro/go-zero/tree/v1.4.2/core/limit
