### ISSUE TITLE
goctl completion has trouble in mac m1 pro !

### ISSUE THREAD

**Issue by a-dwarf** [zeromicro/go-zero#2603]
### 问题描述

当前版本 https://github.com/zeromicro/go-zero/blob/master/tools/goctl 引用 github.com/spf13/cobra v1.4.0
有一点问题，我看cobra新版本已经解决了. 之前的版本导入路径写死的。新版本` $(brew --prefix)`

#### goctl completion zsh -h
macOS:
	goctl completion zsh > /usr/local/share/zsh/site-functions/_goctl

#### cobra最新版本
macOS:
        looklook completion zsh > $(brew --prefix)/share/zsh/site-functions/_looklook

### 建议 
是不是应该升级一下cobra

**Comment by MarkJoyMa** [comment]
alright, got it
