### ISSUE TITLE
Divide generated types in API into different packages, to avoid conflicts of defined arguments

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#2604]
这下面的变量也可以搞一个分包吧，解决变量冲突的问题
internal/types/types.go
是大家通用的需求吗？？？

**Comment by Flipped199** [comment]
支持

**Comment by anqiansong** [comment]
I don't think this is something that can be solved by supporting this feature, I would suggest that a sensible naming is more important than supporting this feature.
