### ISSUE TITLE
gotctl 1.4.2: How to find the path parameter in the URL 

### ISSUE THREAD

**Issue by lhcGinv** [zeromicro/go-zero#2606]
before version 1.4.2， gotctl create ts file like this:
```ts
export function userDetail(params: components.UserDetailReqParams) {
	return ssoms.get<components.UserForm>("/user/:uuid", params)
}
```
so I can find the basic uri is `/user/:uuid`, and easy to replace the path params `:uuid` to `params.uuid`, most important of all， it make easy to authorization the request by server config。
in version 1.4.2， gotctl create ts file like this:
```ts
export function updateBook(params: components.UpdateBookReqParams, req: components.UpdateBookReq, bookUUID: string) {
	return docms.put<components.UpdateBookReply>(`/book/${bookUUID}`, params, req)
}
```
out of the ts file, only the real url be received, so I don't konw how to authorization now

**Comment by lsixi** [comment]
In addition, I found that there are unnecessary parameters in version 1.4.2 , and these unnecessary parameters are at the front of the function, which makes the code look terrible

```ts
export function bookDetail(params: components.BookDetailReqParams, bookUUID: string) {
	return docms.get<components.BookForm>(`/book/${bookUUID}`, params)
}
```

when I use it:
```
// the first params is empty object and useless
// Others don't know what the first parameter represents
bookDetail({}, 'foo')
```
