### ISSUE TITLE
redis  Get support return raw cmd ?

### ISSUE THREAD

**Issue by me-cs** [zeromicro/go-zero#2608]
![image](https://user-images.githubusercontent.com/49519858/202078758-dac494f8-1d19-41cb-9961-e01b6e8e1f4d.png)

When I am using redis get, I want to be able to use the native Scan method of StringCmd, how do I do that?

![image](https://user-images.githubusercontent.com/49519858/202078827-93a01f55-2c62-47e6-ab89-e659714ba466.png)

**Comment by kevwan** [comment]
Just use `go-redis` directly.

**Comment by me-cs** [comment]
> Just use `go-redis` directly.

Ok, I'll try. But the official Redis does not encapsulate the breaker. What a pity!
