### ISSUE TITLE
How to customize built-in error messages

### ISSUE THREAD

**Issue by daifuyang** [zeromicro/go-zero#2626]
ParentId int `json:"parent_id"`

When I submit the request, it prompts me that field ParentId is not set。How can I customize the error message？

----------------------------------------------------------------------------------------------------------------------------------
提交请求时提示未设置字段ParentId。请问如何自定义错误信息呢？

**Comment by Mikaelemmmm** [comment]
> ParentId int `json:"parent_id"`
> 
> When I submit the request, it prompts me that field ParentId is not set。How can I customize the error message？
> 
> 提交请求时提示未设置字段ParentId。请问如何自定义错误信息呢？

It is not supported yet, you can use a third-party library instead, such as  github.com/go-playground/validator
