### ISSUE TITLE
How to save my log in file?

### ISSUE THREAD

**Issue by keepTrying** [zeromicro/go-zero#2630]
I can only see logs in flies by go-zero without my own logs.I use l.logx.info() to log.How can I do?

**Comment by chenquan** [comment]
Can you give me more information?

**Comment by keepTrying** [comment]
Log:
  ServiceName: user-rpc
  Level: info
  Mode: file
  Path: /usr/src/code/logs

Above is my log config in rpc config file.Then I use logx.Error() or l.Logger.Error() in logic code.But my log info still disappears in console.

**Comment by keepTrying** [comment]
I upgraded go-zero to latest version.

**Comment by chenquan** [comment]
> Log:ServiceName: user-rpcLevel: infoMode: filePath: /usr/src/code/logs
> 
> Above is my log config in rpc config file.Then I use logx.Error() or l.Logger.Error() in logic code.But my log info still disappears in console.

Provide the formatted configuration. Maybe it's an indentation error in your configuration.

**Comment by keepTrying** [comment]
```
Name: user.rpc
ListenOn: 0.0.0.0:9000
Mode: dev
Timeout: 10000


Mysql:
  DataSource: root:123456@tcp(mysql:3306)/ff?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
- Host: redis:6379
  Type: node

Telemetry:
 Name: user.rpc
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

Prometheus:
  Host: 0.0.0.0
  Port: 9090
  Path: /metrics

Log:
  ServiceName: user-rpc
  Level: info
  Mode: file
  Path: /usr/src/code/logs
```

**Comment by keepTrying** [comment]
Above is my whole rpc config file.

**Comment by chenquan** [comment]
When Mode is file, the log is output to a file instead of the console.

**Comment by keepTrying** [comment]
Yes,log of go-zero is output to the file.But my log in code is still in console.I hope it can be saved to files too.

**Comment by chenquan** [comment]
When and where in your code calls the `logx.Error`, it is output in the console

**Comment by chenquan** [comment]
Before calling `logx.Error`, you need to ensure that `logx.SetUp` has been called, usually it will be called automatically when the service starts.
https://github.com/zeromicro/go-zero/blob/97a8b3ade59014539081ce63e3c07ca30c239b70/core/logx/logs.go#L226

**Comment by chenquan** [comment]
The path to the automatic call:

rpc: `zrpc.NewServer` -> `servier.SetUp` -> `logx.SetUp`
rest: `rest.NewServer` -> `servier.SetUp` -> `logx.SetUp`

**Comment by keepTrying** [comment]
OK，I go to check it.

**Comment by keepTrying** [comment]
I can see my log in file now.Maybe I made some mistakes before.Thx.
