### ISSUE TITLE
How to get parameters in http header and ip info in logic?

### ISSUE THREAD

**Issue by keepTrying** [zeromicro/go-zero#2631]
Our client passes some parameters in headers like version,os etc.I can only see them in handler.But they aren't passed to logic interface.I can't understand this design.

**Comment by chenquan** [comment]
https://go-zero.dev/cn/docs/design/grammar?_highlight=header#type%E8%AF%AD%E6%B3%95%E5%9D%97

**Comment by keepTrying** [comment]
Got it.Thx.
