### ISSUE TITLE
404 for encodeURIComponent path parameter

### ISSUE THREAD

**Issue by veezhang** [zeromicro/go-zero#2638]
**Describe the bug**

Use `encodeURIComponent` to encode the path parameter, but is response 404.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```
   GetFileInfoReq {
       File string `path:"file"`
   }

   GetFileInfoResp {
   }
   get /files/:file(GetFileInfoReq) returns(GetFileInfoResp);
   ```

3. The error is

   ```
   curl 127.0.0.1:8080/files/%2Fa%2Fb%2Fc.jpg
   # it response 404
   ```

**Expected behavior**
It's show hit the route, and then call the logic.

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by anqiansong** [comment]
You can find it  in golang's request URI, the value of which is `a/b/c.jpg` in http.Request, a path that does not match the target route `files/:file`

**Comment by veezhang** [comment]
@anqiansong I can understand what you said, but should the following be supported?
`127.0.0.1:8080/files/%2Fa%2Fb%2Fc.jpg`
