### ISSUE TITLE
goctl model pg  database unsupported database type: bpchar

### ISSUE THREAD

**Issue by zhouzun8709** [zeromicro/go-zero#2640]
**Describe the bug**
pb database unsupported database type: bpchar
![char](https://user-images.githubusercontent.com/34676599/204079661-b7146ce3-a5aa-4b78-b5d1-c00eaa9cb467.png)

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by anqiansong** [comment]
The pg types we currently support are reference https://www.postgresql.org/docs/current/datatype.html, Please use the official type to solve this problem.
