### ISSUE TITLE
Please advise on the respective responsibilities of api and rpc services.

### ISSUE THREAD

**Issue by gerardhb** [zeromicro/go-zero#2642]
参考了几个项目，但发现RPC的职责都比较重，大部分业务都是在RPC中完成，api完全充当了网关。对此我产生了疑惑，他们为什么会把大部分的职责都给了RPC，api和RPC的职责到底如何很好的划分呢，希望跟大家讨论讨论。

**Comment by gerardhb** [comment]
用户登录，生成token的逻辑是放在RPC服务，还是在API呢？

**Comment by gerardhb** [comment]
我现在要对接一个第三方SSO登录，我去获取`SSOToken`时，会有一个重定向的回调，通过重定向回调获取`SSOToken`，然后在通过`SSO`的`Token`获取用户信息。获取用户信息的接口，我写在了RPC服务中，但是回调又需要API。所以我在想要不要把获取用户信息的逻辑也写在API服务，当然也可以把这个重定向的接口，继续从API调到RPC，只不过让API当了一次网关，但是会加长流程的时长。

**Comment by smithyj** [comment]
usually in rpc，but there are exception，result by the project

**Comment by jsonMark** [comment]
> 我现在要对接一个第三方SSO登录，我去获取`SSOToken`时，会有一个重定向的回调，通过重定向回调获取`SSOToken`，然后在通过`SSO`的`Token`获取用户信息。获取用户信息的接口，我写在了RPC服务中，但是回调又需要API。所以我在想要不要把获取用户信息的逻辑也写在API服务，当然也可以把这个重定向的接口，继续从API调到RPC，只不过让API当了一次网关，但是会加长流程的时长。

Jwt生成是同时支持api和rpc端生成的。
