### ISSUE TITLE
gozero rpc error print

### ISSUE THREAD

**Issue by lynnzhang89** [zeromicro/go-zero#2645]
hi, i have a logic code in rpc service below:
![image](https://user-images.githubusercontent.com/102532661/204433949-4eb5d305-c34a-4d49-8c82-2b3a2cad5de7.png)

i use grpc error to pass error to api service to indicate error info.

but gozero interceptor will print error in https://github.com/zeromicro/go-zero/blob/master/zrpc/internal/clientinterceptors/durationinterceptor.go like below:
![image](https://user-images.githubusercontent.com/102532661/204448167-84c79cde-80f1-4122-a7af-5c57f7011ec2.png)

error like Invalid Argument should not print error log while this error is caused by user input.
and duration interceptor is used to print slow call error log, grpc error print should not put in it.

so i suggest if it is possible to remove error log print in duration interceptor?

**Comment by Mikaelemmmm** [comment]
> 

https://github.com/zeromicro/go-zero/issues/1886  You can refer to this to filter out

**Comment by lynnzhang89** [comment]
hmm, it works fine but seems rude....

**Comment by foliet** [comment]
I think filtering through string matching, it will waste CPU resources. Why not add an option to the log output at this location?

**Comment by foliet** [comment]
Customizing error codes in business should be a common behavior, right?
