### ISSUE TITLE
logx module print jwt unauthorized  error 

### ISSUE THREAD

**Issue by jhaifei** [zeromicro/go-zero#2646]
hi!I have a upload service and I set the jwt auth,so when I post without authorization or with error authorization, it is unauthorized, but the logx print the error with request content,you see the request conent contains the files unicode,logx has a long time to print the error,the request client is timeout.

![f91e62a48888078f4eea756227779d2](https://user-images.githubusercontent.com/44052069/204487400-44f9c295-7e43-41a2-a7d8-f8adde8aaf58.png)

**Comment by re-dylan** [comment]
What's your RestConf.Verbose in config?
Or can you give a demo?

**Comment by jhaifei** [comment]
> What's your RestConf.Verbose in config? Or can you give a demo?

I use the default config.I think it is maybe because the auth module(authhandler.go) set "true" to collect the request body detail.
![55f26db089eff00b1373b859e39621f](https://user-images.githubusercontent.com/44052069/204977683-5627c04d-8b64-4cfb-b976-3891da9d245b.jpg)
