### ISSUE TITLE
v1.2.3 nacos timeout

### ISSUE THREAD

**Issue by moschinoZ** [zeromicro/go-zero#2647]
**Describe the bug**
use nacos to registe and discover, first connection is ok, but restart api, connect timeout

**To Reproduce**
what should i do? upgrade can solve this problum?

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by bensonfx** [comment]
pls figure out your go-zero and goctl version.
post a simply test enviroment and the error log
