### ISSUE TITLE
go tool pprof cannot open trace-1201134430.pprof file

### ISSUE THREAD

**Issue by maojinhua** [zeromicro/go-zero#2652]
不好意思，打扰了，有个pprof相关的问题想请教下

问题：
在线上执行两次 kill -usr2 命令后获取到相关pprof采集数据

core-1-block-1201134430.pprof		core-1-mem-1201134430.pprof		core-1-threadcreate-1201134430.pprof
core-1-cpu-1201134430.pprof		core-1-mutex-1201134430.pprof		core-1-trace-1201134430.pprof

在本地使用go tool pprof -http=:9991 命令打开pprof文件，基本上都正常打开。只有 core-1-trace-1201134430.pprof 这个文件无法打开

go tool pprof -http=:9991 core-1-trace-1201134430.pprof
报错信息如下：
core-1-trace-1201134430.pprof: parsing profile: unrecognized profile format
failed to fetch any source profiles

**Comment by maojinhua** [comment]
请问要怎么打开 trace-xx.pprof呢？直接用 go tool pprof就可以了吗？还是要别的命令打开才可以呢

**Comment by MarkJoyMa** [comment]
You can come to the go-zero community group to consult.
