### ISSUE TITLE
go build open etc/greet.yaml: The system cannot find the path specified

### ISSUE THREAD

**Issue by zhouzun8709** [zeromicro/go-zero#2653]
![build](https://user-images.githubusercontent.com/34676599/205034991-31939281-972e-46c8-8730-676b456958af.png)

**Environments (please complete the following information):**
 - OS: windows and linux
 - go-zero version 1.4.2
 - goctl version  1.4.2

**More description**

**Comment by MarkJoyMa** [comment]
You need to use -f to specify the file path.

**Comment by zhouzun8709** [comment]
> is go build not go run;
go version 1.19.2

**Comment by bensonfx** [comment]
your yaml path is wrong: 
![image](https://user-images.githubusercontent.com/3302960/205213853-ddc9422d-b4cf-4dba-b4bc-08989a7f40e0.png)

**Comment by zhouzun8709** [comment]
是以打包后生成的执行文件所在位置，作为相对路径查找配置文件
