### ISSUE TITLE
an error of validate data can  be more detailed ？

### ISSUE THREAD

**Issue by tim1116** [zeromicro/go-zero#2657]
**Is your feature request related to a problem? Please describe.**

When an error occurs while use httpx.Parse functon to parses the request，sometimes the error description is very simple. 
For example,define a field UserId and its typpe is uint,when the request parameter is not of an uint type，like string "aaa",the return error is only tell us  【the value "aaa" cannot parsed as uint】，and not any other message.I don t know which field caused it.I hope the error tell me  the field UserId Cause this mistake.

**Describe the solution you'd like**

I think the error can be defined  as a  cusstomError struct and Implement the interface error. the struct can carry additional information like field name or any other message.so the client can assert an error to get some more information

**Comment by tim1116** [comment]
在api请求中 当请求参数异常时  httpx.Parse如何才能获取到更详细的错误字段信息

**Comment by smithyj** [comment]
maybe use third-party validator is good idea ?
eg: `go-playround/validator`?

**Comment by tim1116** [comment]
> maybe use third-party validator is good idea ? eg: `go-playround/validator`?

I used go-playround/validator after httpx.Parse

**Comment by smithyj** [comment]
@tim1116 change goctl `api/handler.api` template content, example:
```
package {{.PkgName}}

import (
        "net/http"

        "appservice/src/pkg/resps"
        {{.ImportPackages}}
        {{if .HasRequest}}"appservice/src/pkg/validator"{{end}}

        {{if .HasRequest}}
        "github.com/zeromicro/go-zero/rest/httpx"
        {{end}}
)

func {{.HandlerName}}(svcCtx *svc.ServiceContext) http.HandlerFunc {
        return func(w http.ResponseWriter, r *http.Request) {
                {{if .HasRequest}}var req types.{{.RequestType}}
                if err := httpx.Parse(r, &req); err != nil {
                        resps.HttpParamErrorResult(r, w, err)
                        return
                }

                if err := validator.StructValidate(req, validator.ParseLang(r)); err != nil {
                        resps.HttpParamErrorResult(r, w, err)
                        return
                }

                {{end}}l := {{.LogicName}}.New{{.LogicType}}(r.Context(), svcCtx)
                {{if .HasResp}}resp, {{end}}err := l.{{.Call}}({{if .HasRequest}}&req{{end}})

                {{if .HasResp}}resps.HttpResult(r, w, resp, err){{else}}resps.HttpResult(r, w, nil, err){{end}}
        }
}

```

**Comment by tim1116** [comment]
@smithyj   I mean That the error is returned in the httpx.Parse. 

for example
  
The api file is

```
type (
	ReqUserId {
		UserId uint `form:"user_id"`
	}
)
```

and the request id 

`curl  -X POST -d "user_id=aaa" '127.0.0.1:8888/xxx/xxxxx'`


the error message is 

`the value "aaa" cannot parsed as uint`

I want to return information containing UserId filed Cause a mistake

**Comment by tim1116** [comment]
I want to implement the parse myself to solve the problem
 
But I think the framework can be optimized under this problem

**Comment by smithyj** [comment]
good idea, try to commit PR?

**Comment by cpj555** [comment]
我现在的解决方案是把参数全部改成optional,httpx.Parse只做结构体映射,然后让验证器返回错误信息
