### ISSUE TITLE
when executing the "API" module, it prompts: empty etcd hosts

### ISSUE THREAD

**Issue by Locter9001** [zeromicro/go-zero#2660]
this is the config file (.yaml)  for the API module
![image](https://user-images.githubusercontent.com/96331179/205497371-a999a212-47a7-4f1b-9b71-c0d5cc9931c5.png)

and this is the config file (.yaml) for the RPC module
![image](https://user-images.githubusercontent.com/96331179/205497605-e0841b8b-c8c4-4bfe-9154-3863388e9ce3.png)

and this is the error prompted by the console
![image](https://user-images.githubusercontent.com/96331179/205497867-73bb4bb2-e198-43f3-994e-e21482bdc01b.png)

RPC module is normal !!!

this is Config structs
```Go
package config

import (
	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/zrpc"
)

type Config struct {
	rest.RestConf
	JwtAuth struct {
		AccessSecret string
		AccessExpire int64
	}

	UserRpc zrpc.RpcClientConf
}
```

**Comment by chenquan** [comment]
Modify `userServiceRpcConf` to `UserRpc` in the `userService.yaml`

**Comment by Locter9001** [comment]
> Modify `userServiceRpcConf` to `UserRpc` in the `userService.yaml`

okay,  this works!   thank you!!!!!
