### ISSUE TITLE
command `goctl model` had a different result 

### ISSUE THREAD

**Issue by CrazyZard** [zeromicro/go-zero#2662]
command `goctl model mysql datasource -url="*" -table="*" -dir="./model"`
constant RowsExpectAutoSet  RowsWithPlaceHolder changed in same ddl

![image](https://user-images.githubusercontent.com/33921085/205625597-3d7a7282-7352-414f-9d58-02ab369f289b.png)

**Comment by jsonMark** [comment]
goctl model mysql datasource -url="root:123456a@tcp(127.0.0.1:3306)/admin" -table="user"  -dir="." -i 'create_time' -i 'update_time' 
你第一次应该是使用这种方式生成的，建议把所有东西放在一起

**Comment by kevwan** [comment]
fixed.
