### ISSUE TITLE
How to make http.Parse support specific type?

### ISSUE THREAD

**Issue by cpj555** [zeromicro/go-zero#2663]
github.com/bwmarrin/snowflake

```
type res struct {
	Id   snowflake.ID       `json:"id,optional"
}
```

场景:使用snowflake作为数据库id,它本身实现了MarshalJSON和UnmarshalJSON,返回给前端会使用自定义的json序列化转化回stirng,解决精度丢失的问题,同时当前端传递(string)id回来时会自动转换会uint64,但是这个时候http.parse就会报错
```
error: type mismatch for field id
```

另一个问题:goctl也不支持自定义type (snowflake.ID)

个人认为这是一个比较常见的业务场景,不知道其他人有没有解决过类似问题,我能想到的办法就是每次手动做uint64转到string的转换

**Comment by kevwan** [comment]
It's already supported, which version are you using?

**Comment by cpj555** [comment]
最新的版本，需要如何配置呢。文档上找不到相关的内容
