### ISSUE TITLE
how to set class RpcClientConf member variable Endpoints 

### ISSUE THREAD

**Issue by jinkaz** [zeromicro/go-zero#2679]
we use nacos cluster,actually we all use this frame in pro enviroment.
my yaml content is below like that:

Nucleus:
   Endpoints: 
   - 192.168.135.1:8848/nucleus-grpc

i did not set App and token  params(although i havn't found any introduction of the two params)
Endpoints,this param i set 192.168.135.1:8848 or nacos://192.168.135.1:8848/nacos.rpc?timeout=5000s like demo seted
it did not work。

when i launch the app  it warned

":rpc dial: direct:///192.168.135.1:8848/nucleus-grpc, error: context deadline exceeded, make sure rpc service "nu
cleus-grpc" is already started","level":"error

**Comment by MarkJoyMa** [comment]
https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/nacos

**Comment by jinkaz** [comment]
> You can refer to the practice here: https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/nacos

it did not work. import (
	"flag"
	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/zrpc"
	_ "github.com/zeromicro/zero-contrib/zrpc/registry/nacos"
)

func main() {
	flag.Parse()

	var c zrpc.RpcClientConf
	conf.MustLoad(*configFile, &c)
	zrpc.MustNewClient(c)
}

i tested the code like demo. always warned  rpc dial: nacos://192.168.135.1:8848/nacos.rpc?timeout=5000s, error: context deadline exceeded, make sure rpc service "nacos.rpc?timeout=5000s" is already started.

but it's strange that the client demo could substribe the server service ,even my own server service program.

**Comment by jinkaz** [comment]
行了，自行通过nacos官方sdk搞定了。

**Comment by xiaocode337317439** [comment]
> 行了，自行通过nacos官方sdk搞定了。

请问下怎么解决的，我也遇到了，求大佬解惑
