### ISSUE TITLE
sqlx/utils.go:139,error: context canceled

### ISSUE THREAD

**Issue by as11144410** [zeromicro/go-zero#2680]
{"@timestamp":"2022-12-08 15:53:56","caller":"sqlx/utils.go:139","content":"stmt: select `id`,`gateway_uni_id`,`gateway_model`,`serial_number`,`relate_company_id`,`run_software_version`,`update_time`,`status`,`temperature`,`model_strength`,`software_pass`,`valid_type`,`valid_start_time`,`valid_end_time`,`mqtt_clientid`,`mqtt_password`,`is_delete`,`created_at`,`updated_at` from `gateway_manage` where `serial_number` = '5c2f04527915c814000094c000000000' and `is_delete` = 0 limit 1, error: context canceled","level":"error","span":"f921ac5297c2fe69","trace":"4266059703319be49ee75b7d8a85f9e1"}

**Comment by MarkJoyMa** [comment]
The call timed out. The timeout set by the context may have expired. You can check whether the timeout setting has been set on the call link.
