### ISSUE TITLE
timeout work, but get empty response

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#2700]
**Describe the bug**
api request timeout, bug get Empty reply from server

**To Reproduce**
curl http://127.0.0.1:3333/demo\?user\=a

1. The code is

```
func handle(w http.ResponseWriter, r *http.Request) {
	var req Request
	err := httpx.Parse(r, &req)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	time.Sleep(time.Second * 7) //强制超时
	httpx.OkJson(w, "hello, "+req.User)
}
```
  

完整代码：
[demo.zip](https://github.com/zeromicro/go-zero/files/10216186/demo.zip)

2. The error is
<img width="568" alt="image" src="https://user-images.githubusercontent.com/81024796/207274733-713ccf69-fbc7-4cc9-aa35-6b2aef97d2f7.png">

Except:
Request Timeout

**Comment by chowyu12** [comment]
找到原因了，问题在这边的超时设置：https://github.com/zeromicro/go-zero/blob/master/rest/engine.go#L285
![image](https://user-images.githubusercontent.com/81024796/210028918-d8296421-422e-48e5-8296-f2dbd7f85477.png)

服务端连接在超时时间没到就关闭了连接

**Comment by kevwan** [comment]
@chowyu12 Please give a try.

**Comment by smithyj** [comment]
good fix
