### ISSUE TITLE
Want to activate # 548 Can the paging query interface be added to the generated code

### ISSUE THREAD

**Issue by echo-LuGuang** [zeromicro/go-zero#2703]
goctl自动生成model代码时，应该添加分页查询/列表查询的可选参数。
就如 https://github.com/zeromicro/go-zero/issues/548#issuecomment-799149315 所说
————————————————————————————————
When goctl automatically generates model code, optional parameters for paging query/list query should be added.
Just like https://github.com/zeromicro/go-zero/issues/548#issuecomment-799149315

**Comment by fyyang** [comment]
可以自定义模板啊老兄

**Comment by echo-LuGuang** [comment]
> 可以自定义模板啊老兄

是的，只不过如果能提供额外模板参数就更好了。

它应该支持更多，即使用户不使用这些功能。这就是为什么我们称 go-zero 是一个框架。
普通用户不想使用模板。所以框架应该：为普通用户提供所有功能，并为高级用户自行更改模板。

**Comment by fyyang** [comment]
模板参数, 你可以看一下goctl源码里面都有, 你可以看看

**Comment by chenyangguang** [comment]
It seems that it is better give an example about filter pagize model data in docs.
Like an example said how to use  `QueryRows` .
