### ISSUE TITLE
grpc timeout setting

### ISSUE THREAD

**Issue by edison-dev** [zeromicro/go-zero#2707]
I want to set the timeout time of grpc for breakpoint debugging. I found that it can be passed through the ClientOption function. However, the ClientOptions defined in ClientOption is internal and cannot be compiled.
```
// MustNewClient returns a Client, exits on any error.
func MustNewClient(c RpcClientConf, options ...ClientOption) Client {
	cli, err := NewClient(c, options...)
	if err != nil {
		log.Fatal(err)
	}

	return cli
}
```

**Comment by kevwan** [comment]
It's type aliased in zrpc package. You can use it.
