### ISSUE TITLE
How to share middleware among multiple services?

### ISSUE THREAD

**Issue by ofey404** [zeromicro/go-zero#2716]
Hello, I wonder how to share middleware like `JwtBlockList` among multiple services.

Given an API file like this, `goctl` would generate middleware under `internal/` directory.

```golang
@server(
	jwt: Auth
	group: user
	middleware: JwtBlockList
)
```

Are there any API syntax could refer to a public reused middleware, like in `pkg/middleware/jwtblocklist/`

**Comment by kevwan** [comment]
Add the middleware literally in your code.
