### ISSUE TITLE
Multiple protobuf files are supported

### ISSUE THREAD

**Issue by yasin-wu** [zeromicro/go-zero#2723]
rpc服务的参数(message)必须写在主protobuf(service)文件里面吗？

**Comment by anqiansong** [comment]
Yes

**Comment by yasin-wu** [comment]
可以提供多protobuf文件的支持吗？要是一个RPC文件过长也不好维护

**Comment by Mikaelemmmm** [comment]
这个是protobuf、grpc的问题，你可以把内部多个字段的message独立出去一个protobuf文件，然后import进来引入到当前文件的message内， 基本文件也不会太长

**Comment by Mikaelemmmm** [comment]
这个是protobuf问题，你可以把内部多个字段的message独立出去一个protobuf文件，然后import进来引入到当前文件的message内， 基本文件也不会太长

**Comment by yasin-wu** [comment]
OK！Thank you!
