### ISSUE TITLE
Need supported returns (string)

### ISSUE THREAD

**Issue by coverthesea** [zeromicro/go-zero#2728]
The author replied that he would support it in the future, but he doesn't seem to support it now
I need to return an html view,I don't know what to do.

**Comment by wubin1989** [comment]
@coverthesea Do you need this feature in what kind of use cases? Most projects are made of frontend and backend. People is coding Vuejs or Reactjs to make frontend pages, seldom using golang html/template these days.

**Comment by coverthesea** [comment]
> @coverthesea Do you need this feature in what kind of use cases? Most projects are made of frontend and backend. People is coding Vuejs or Reactjs to make frontend pages, seldom using golang html/template these days.

Now it is a simple service status interface

**Comment by smithyj** [comment]
I think feature is so bad，you can try to `SSR` in frontend

**Comment by Mikaelemmmm** [comment]
> The author replied that he would support it in the future, but he doesn't seem to support it now I need to return an html view,I don't know what to do.

https://github.com/zeromicro/zero-examples/blob/main/chat/main.go
