### ISSUE TITLE
Goctl RPC Generate Problem

### ISSUE THREAD

**Issue by TanYongF** [zeromicro/go-zero#2733]
when I use `goctl rpc new greet` to generate a new rpc service, the console show a red line:
`[profiling] error parsing flags: when -address isn't specified, you must include -stream-stats-catapult-json
`
Besides, the code is not generated well, but the folder is generated right. 
How can I slove this problem, and what cause this issue?
Thanks for your reply.

**Comment by TanYongF** [comment]
And there is a familar issue : https://github.com/zeromicro/go-zero/issues/2185

**Comment by kevwan** [comment]
@anqiansong PTAL.

**Comment by anqiansong** [comment]
Have you enabled the grpc profile, please see https://github.com/grpc/grpc-go/blob/v1.52.0/profiling/cmd/flags.go#L72

**Comment by NStart** [comment]
I also encountered the same problem, and it was solved after trying to delete cmd.exe in the bin directory. This command will affect the cmd command of the system, and this cmd.exe is precisely compiled by the protoc-gen-go-grpc project

**Comment by NStart** [comment]
I also encountered the same problem, and it was solved after trying to delete cmd.exe in the bin directory. This command will affect the cmd command of the system, and this cmd.exe is precisely compiled by the protoc-gen-go-grpc project @TanYongF

**Comment by TanYongF** [comment]
Ok thanks!
