### ISSUE TITLE
Menu position on goland for goctl plugin.

### ISSUE THREAD

**Issue by maliyan** [zeromicro/go-zero#2734]
用Goland新建文件时，Goctl会在靠前面的位置，这样会影响正常的用户体验
例如：正常新建文件只需要 cmd + n , 回车，即可
这个插件排在了前面，就需要4步骤才可以，即cmd + n , ↓，↓，回车

希望不要影响原有用户使用体验，多谢！

![a8897a655c64f01aef83e1741cbb6ae4](https://user-images.githubusercontent.com/5624855/210026302-df297393-3433-4253-a60d-f81c509ba198.png)

**Comment by anqiansong** [comment]
这不是 go-zero 相关问题，请将此问题移动至  https://github.com/zeromicro/goctl-intellij 仓库
This is not a go-zero related issue, please move this issue to https://github.com/zeromicro/goctl-intellij repository

**Comment by kevwan** [comment]
Fixed. Thanks for reporting! Please update your goctl plugin.
