### ISSUE TITLE
ParseJsonBody doesn't accept arrays.

### ISSUE THREAD

**Issue by chounvwudi** [zeromicro/go-zero#2735]
go-zero作为服务端，接收的request body 是数组，ParseJsonBody 函数无法处理，如图的请求
![微信截图_20221231175741](https://user-images.githubusercontent.com/10561960/210132530-3fb47824-ca18-416d-8f3c-1ea842214281.png)
难道只能是json对象吗？

**Comment by kevwan** [comment]
@chounvwudi Please give a try.

**Comment by chounvwudi** [comment]
### I have got a error like this!  
**error: `json: cannot unmarshal array into Go value of type map[string]interface {}`**

![11](https://user-images.githubusercontent.com/10561960/210190053-0d620288-b8c8-491f-8abf-b4394bcc280a.png)

**Comment by chounvwudi** [comment]
![2](https://user-images.githubusercontent.com/10561960/210191918-98c4a806-e759-4b12-9969-a59ff02cec84.png)

**Comment by chounvwudi** [comment]
I think the method "ParseJsonBody" can not adapt array body like this

**Comment by chounvwudi** [comment]
I'm a beginner.Maybe my idea is not accurate

**Comment by chounvwudi** [comment]
非常感谢@kevwan的及时帮助，您的修改确实解决了部分问题，现在又有新的问题，请原谅我没办法用英文描述的很清楚。
您修改了Unmarshal方法，但是我感觉这个方法可能存在参数使用的错误。举例说明：

`type CreateOriginalMsgReq struct {
	Tag   string `json:"tag"`
	MsgId string `json:"msgId"`
	Data  string `json:"data"`
}`

`
var req []types.CreateOriginalMsgReq

		if err := httpx.Parse(r, &req); err != nil {
			httpx.Error(w, err)
			return
		}
`

httpx.Parse方法有几个预处理 ParsePath，ParseForm，ParseHeaders，最终都会执行到Unmarshal，我在调试的时候发现，参数i和参数v的使用可能是不准确的。我是个初学者，有些问题描述的不到位，用截图解释一下。
![33333](https://user-images.githubusercontent.com/10561960/210206758-95298716-bf72-44f8-909a-acd9d00a3876.png)

![11111](https://user-images.githubusercontent.com/10561960/210206789-0f6bd66f-d8ad-4715-99f0-f1c490beaf80.png)

![22222](https://user-images.githubusercontent.com/10561960/210206793-27369128-146c-4972-af0f-bcd059338322.png)

这几个截图，是在调试ParseHeaders的时候的内存信息。其实ParsePath和ParseForm有同样的问题，为了能调试到ParseHeaders，我直接把源码中ParsePath和ParseForm的预处理注释掉了。switch iv: i.(type)  iv 的类型是map[string]interface{},而elemType.Kind()的类型是Slice，导致无法执行。如果把ParsePath，ParseForm，ParseHeaders全部注释掉，只执行ParseJsonBody能够正常执行。所以我觉的Unmarshal可能有问题。

**Comment by kevwan** [comment]
There must be names with headers and path vars.

**Comment by 474420502** [comment]
@kevwan  jsonbody传不了数组. 要有特殊语法支持吗? 我也是这个问题, 其实实现很简单, 但是框架里没做？

**Comment by 474420502** [comment]
@kevwan  我看了你的代码, 其实你这个只单元测试了ParseJsonBody,但是前面的ParsePath解析就直接返回err了, 到不了ParseJsonBody这步, 你还没修复这个解析不了Json的Body的数组问题, 你没有想protobuf那样有语法支持. 这样你还需要有一个很好的约定来实现数组这个问题.

**Comment by lvphps** [comment]
jsonbody cannot pass an array     api文件里怎么定义结构体
