### ISSUE TITLE
Optional Auth

### ISSUE THREAD

**Issue by jjkoh95** [zeromicro/go-zero#2739]
**Is your feature request related to a problem? Please describe.**
Can we have optional JWT? 
- So we can have single API that returns personalized widgets (with JWT), or default widgets (without JWT).
- So we can add in user metadata to response if there's JWT.

**Describe the solution you'd like**
```text
// .api file
@server(
  jwt: OptionalAuth // I don't know what's the appropriate clause/syntax here
)
```
```go
rest.WithJwt("secret", rest.WithJwtOptional(true))
```

- Include an optional flag in API file and an additional option `rest.WithJwtOptional(true)` like above, so it doesn't throw 401 if JWT is not passed.

**Describe alternatives you've considered**
```go
func (m *OptionalAuthMiddleware) Handle(next http.HandlerFunc) http.HandlerFunc {
	authHandler := handler.Authorize(m.secret)(next)

	return func(w http.ResponseWriter, r *http.Request) {
		if token := r.Header.Get("Authorization"); token == "" {
			next(w, r)
			return
		}
		authHandler.ServeHTTP(w, r)
	}
}
```
I'm using custom middleware above

**Additional context**
I'm curious to know what is the correct/idiomatic way to achieve optional auth. If there is none, I believe exposing an optional flag will provide convenience for above use case.

Happy New Year!

**Comment by Mikaelemmmm** [comment]
> **Is your feature request related to a problem? Please describe.** Can we have optional JWT?
> 
> * So we can have single API that returns personalized widgets (with JWT), or default widgets (without JWT).
> * So we can add in user metadata to response if there's JWT.
> 
> **Describe the solution you'd like**
> 
> ```
> // .api file
> @server(
>   jwt: OptionalAuth // I don't know what's the appropriate clause/syntax here
> )
> ```
> 
> ```go
> rest.WithJwt("secret", rest.WithJwtOptional(true))
> ```
> 
> * Include an optional flag in API file and an additional option `rest.WithJwtOptional(true)` like above, so it doesn't throw 401 if JWT is not passed.
> 
> **Describe alternatives you've considered**
> 
> ```go
> func (m *OptionalAuthMiddleware) Handle(next http.HandlerFunc) http.HandlerFunc {
> 	authHandler := handler.Authorize(m.secret)(next)
> 
> 	return func(w http.ResponseWriter, r *http.Request) {
> 		if token := r.Header.Get("Authorization"); token == "" {
> 			next(w, r)
> 			return
> 		}
> 		authHandler.ServeHTTP(w, r)
> 	}
> }
> ```
> 
> I'm using custom middleware above
> 
> **Additional context** I'm curious to know what is the correct/idiomatic way to achieve optional auth. If there is none, I believe exposing an optional flag will provide convenience for above use case.
> 
> Happy New Year!


This can be solved by using a middleware that does not pass jwt to pass without validation; pass jwt to validate, and 401 if the validation does not pass, like this: https://github.com/Mikaelemmmm/go-zero-looklook/blob/main/common/middleware /commonJwtAuthMiddleware.go

**Comment by jjkoh95** [comment]
Thanks for the prompt response!

Was just wondering if there's a built-in way to do it, I will stick with the middleware approach.

Thanks once again!
