### ISSUE TITLE
Underscores are deleted in config map keys.

### ISSUE THREAD

**Issue by zhouzun8709** [zeromicro/go-zero#2743]
**Describe the bug**
配置文件cds.json:
  "CusTypeDir": {
    "ZZ_SW_RECV_DECMSG": "/sw/decmsg/receive",
    "ZZ_SW_RECV_SAS": "/sw/sas/receive",
    "ZZ_SW_RECV_RMFT": "/sw/rmft/receive",
    "ZZ_SW_RECV_MFT": "/sw/mft/receive",
    "ZZ_SW_RECV_CIQ": "/sw/ciq/receive",
    "ZZ_SW_RECV_COO": "/sw/coo/receive",
    "ZZ_SGT_RECV": "/sgt/receive"
  },
转成map类型：
CusTypeDir map[string]string
结果把key的名字带下划线全部删除，如下结果：
map[zZSGTRECV:/sgt/receive zZSWRECVCIQ:/sw/ciq/receive zZSWRECVCOO:/sw/coo/receive zZSWRECVDECMSG:/sw/decmsg/receive zZSWRECVMFT:/sw/mft/receive zZSWRECVRMFT:/sw/rmft/receive zZSWRECVSAS:/sw/sas/receive]
![image](https://user-images.githubusercontent.com/34676599/210327276-13665028-b425-431d-b428-9e8b725e23d6.png)
![image](https://user-images.githubusercontent.com/34676599/210327324-320985c2-37c7-447e-bd97-3ec8fa0594e6.png)
![image](https://user-images.githubusercontent.com/34676599/210327356-a9a3cb96-28e6-4c61-8874-727dbe492940.png)

**Comment by kevwan** [comment]
Which version are you using? Fixed in master.

**Comment by kevwan** [comment]
fixed in #2730
