### ISSUE TITLE
After proto uses --multiple, how does api ServiceContext merge multiple rpc clients

### ISSUE THREAD

**Issue by HalcyonDaysssss** [zeromicro/go-zero#2772]
proto:

service User
service Token

The rpc client directory generates corresponding userClient and tokenClient.
The service-context of the api svc. How SysRPC merge userClient, tokenClient.

Similar to the following:
SysRPC interface {
userClient.User
tokenClient.Token
}

return &ServiceContext{
SysRPC: userClient.NewUser, tokenClient.NewToken
}

proto:

service User
service Token

rpc client目录生成对应的userClient,tokenClient。
api svc的service-context。如何SysRPC合并userClient,tokenClient.

类似如下：
SysRPC    interface {
		userClient.User
		tokenClient.Token
}

return &ServiceContext{
SysRPC: userClient.NewUser, tokenClient.NewToken
}

**Comment by anqiansong** [comment]
I can understand your needs. from the perspective of code generation, I do not recommend this. If you add another group next time, goctl generation must invade user code, which is very risky
