### ISSUE TITLE
slowThreshold  should depends on the timeout config 

### ISSUE THREAD

**Issue by akalittle** [zeromicro/go-zero#2775]
**The problem**
As for now ,  the slowThreshold is default to :
```go
const (
	limitBodyBytes       = 1024
	defaultSlowThreshold = time.Millisecond * 500
)

var slowThreshold = syncx.ForAtomicDuration(defaultSlowThreshold)

``` 

However the timeout set is 3000ms,  and there are lots of logs in production.

**My solution**

In `engine.go`: 

```go
func (ng *engine) getLogHandler() func(http.Handler) http.Handler {
	if ng.conf.Verbose {
		return handler.DetailedLogHandler
	}

	return handler.LogHandler
}
```

Maybe we can add a  line of additional code 👍 
```go 
func (ng *engine) getLogHandler() func(http.Handler) http.Handler {

        //  SetSlowThreshold here 
        handler.SetSlowThreshold(time.Millisecond * time.Duration(ng.conf.Timeout))
	if ng.conf.Verbose {
		return handler.DetailedLogHandler
	}

	return handler.LogHandler
}
```

**Comment by kevwan** [comment]
not necessary to set this line of code:
```go
handler.SetSlowThreshold(time.Millisecond * time.Duration(ng.conf.Timeout))
```

it's timeout, will be logged.

**Comment by akalittle** [comment]
> not necessary to set this line of code:
> 
> ```go
> handler.SetSlowThreshold(time.Millisecond * time.Duration(ng.conf.Timeout))
> ```
> 
> it's timeout, will be logged.

Ok. I can add `handler.SetSlowThreshold(my custom slow call time )` in main file.
