### ISSUE TITLE
goctl cannot be found

### ISSUE THREAD

**Issue by Yangjy12** [zeromicro/go-zero#2788]
![image](https://user-images.githubusercontent.com/87263707/212281249-5be39ebf-f03c-464e-ae0c-b6c5b8aa9981.png)
goctl已经anchu安装成功，
![image](https://user-images.githubusercontent.com/87263707/212281467-004a3619-b35b-4b7d-9eb1-f6676ed69e83.png)
l路径中已经存在goctl，
检查gopath的bin已经加入到了环境变量中。但还是出现这种情况，是为什么？

**Comment by kevwan** [comment]
Make sure goctl can be found in your terminal.

**Comment by iliyasali2107** [comment]
hi, i run `GO111MODULE=on go get -u github.com/zeromicro/go-zero/tools/goctl` and it downloaded in to go/pkg/mod, and `goctl api -o shorturl.api` is not working because `goctl` is not found, can you help me to solve this?
