### ISSUE TITLE
How to regenerate code in tools/goctl/api/parser/g4?

### ISSUE THREAD

**Issue by rpstw** [zeromicro/go-zero#2796]
There seems no clear doc or script about it.

**Comment by anqiansong** [comment]
I recommend referring to the [official website](https://www.antlr.org/) to learn about g4

**Comment by rpstw** [comment]
I understand how to use g4. 

The problem is I have to **guess** how to regenerate it since there is no steps stated clearly. 

Specifically

- which version of antlr4 should be used. 
- how to split one of the generated file

**Comment by anqiansong** [comment]
First, you need to keep Goland 2020.3.5 or below, install version 1.15 of `ANTLR v4` for Goland plugin , and then use https://github.com/zeromicro/go-zero/blob/master/tools/goctl/api/parser/g4 /gen/api/file_splitor_test.go unit test file splits the generated g4 code.
