### ISSUE TITLE
Does go-zero have a package implementation of the hook function?

### ISSUE THREAD

**Issue by ShyunnY** [zeromicro/go-zero#2810]

**Comment by kevwan** [comment]
For what kind of hook?

**Comment by ShyunnY** [comment]
I would like to add the execution function either before or after the execution business function, if this package is not currently available, I can submit a pr in the util package and let you see if it fits. Thank you for your reply on New Year's Eve and I wish you a happy new year.

**Comment by kevwan** [comment]
You can use middleware to achieve this.

**Comment by ShyunnY** [comment]
Middleware acts before and after logic, but I don't really want that. Because I have the flexibility to add hooks to other functions when I call them from within the logic

**Comment by kevwan** [comment]
You can wrap the func with a closure.
