### ISSUE TITLE
"handler/authhandler.go:103","content":"authorize failed: no token present in request

### ISSUE THREAD

**Issue by Jerry-yz** [zeromicro/go-zero#2839]
go-zero请求报错, 请问怎么解决这个问题

**Comment by kevwan** [comment]
Authentication enabled in server side, but no authentication info in requests.

**Comment by Jerry-yz** [comment]
> 
第一次用不太懂这里的认证，没有看到认证校验，参数在哪里传递

**Comment by kevwan** [comment]
Don't add `Auth` in your api file.

**Comment by Jerry-yz** [comment]
#

> Don't add `Auth` in your api file.

若果要通过认证，该怎么传参数

**Comment by kevwan** [comment]
https://go-zero.dev/docs/advance/jwt/
or
https://go-zero.dev/cn/docs/advance/jwt/
