### ISSUE TITLE
Can goctl specify the version to generate rpc

### ISSUE THREAD

**Issue by charliecen** [zeromicro/go-zero#2850]
The old project is goctl 1.38, go-zero is 1.3.4. After goctl is upgraded to 1.4.4, the generated rpc code is different from before. Can I specify the goctl version to generate rpc code?

**Comment by anqiansong** [comment]
No, you can't, the only way to keep code do not change is do not upgrade goctl

**Comment by charliecen** [comment]
> No, you can't, the only way to keep code do not change is do not upgrade goctl

ok
