### ISSUE TITLE
POST: field message is not set 

### ISSUE THREAD

**Issue by joker1499** [zeromicro/go-zero#2851]
![image](https://user-images.githubusercontent.com/94731061/216963285-4dd85873-5896-4e5a-9511-a2240801b992.png)

![image](https://user-images.githubusercontent.com/94731061/216963388-6ee194e5-4499-4bfd-aa91-05edac244812.png)
Is there a problem with my format? Postman can't pass it

**Comment by joker1499** [comment]
go version 1.19.3 
os: windows
go-zero latest

**Comment by chenquan** [comment]
@joker1499 reference: https://learning.postman.com/docs/sending-requests/requests/#raw-data

**Comment by joker1499** [comment]
thanks your guide @chenquan
