### ISSUE TITLE
Parse config value contains "abc$123" error with UseEnv

### ISSUE THREAD

**Issue by stonever** [zeromicro/go-zero#2853]
The Config value "abc$123" should not be regarded as env, it's reasonable only '${xxx}' regarded as env
`
err = conf.Load(file, &ret, conf.UseEnv())
`

**Comment by kevwan** [comment]
Yes, you're right. But for now, if we change to ${xxx}, there will be a compatibility problem.

I suggest you to use `env` tag in config struct instead of `UseEnv()`.
