### ISSUE TITLE
model surport  the same query scenarios in both transactional and non-transactional scenarios

### ISSUE THREAD

**Issue by bbq-oba** [zeromicro/go-zero#2855]
When a model have an` insertxxx()` method
the session can also be called directly
such as `model.withsession(session).insertxxx()`
reducing the code repetition for the same query scenarios in both transactional and non-transactional scenarios.

and give some transactional and non-transactional best practices for reference.

**Comment by kevwan** [comment]
It's supported in v1.5.4 already.
