### ISSUE TITLE
hope to get cpu usage in darwin

### ISSUE THREAD

**Issue by Danny5487401** [zeromicro/go-zero#2864]
```shell
{"@timestamp":"2023-02-10T15:56:09.650+08:00","caller":"stat/usage.go:61","content":"CPU: 0m, MEMORY: Alloc=2.8Mi, TotalAlloc=15636.6Mi, Sys=24.7Mi, NumGC=8669","level":"stat"}

```

![image](https://user-images.githubusercontent.com/64348131/218035747-f4d3f82e-cfd1-498c-9433-c118ac884f09.png)

**Comment by kevwan** [comment]
What's the purpose to get cpu usage in darwin?

We usually develop on darwin, but not using darwin for production.

**Comment by Danny5487401** [comment]
Just for Developing in local.it is all right for me to look activity monitoring in darwin.
