### ISSUE TITLE
How can I generate *.proto  with another proto file?

### ISSUE THREAD

**Issue by fakecore** [zeromicro/go-zero#2865]
```
--common

  --proto

    common.proto

--user

  --rpc

    xx.proto

    xx1.proto
```
xx.proto content
```
import "common/proto/common.proto"
```
```
goctl rpc protoc user.proto --go_out=. --go-grpc_out=. --zrpc_out=. -I ../..
```
And I tried to use goctl rpc protoc in the `/xx/user/rpc` path but failed with the error "user.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think)."

So what should I do now?

**Comment by anqiansong** [comment]
Maybe you can try:
```
$ goctl rpc protoc -I ../.. user.proto --go_out=. --go-grpc_out=. --zrpc_out=. 
```
or
```
$ goctl rpc protoc --proto_path ../.. user.proto --go_out=. --go-grpc_out=. --zrpc_out=. 
```
if it does not work, plz try the following command can be executed successfully
```
 $ protoc --proto_path ../.. user.proto --go_out=. --go-grpc_out=. --zrpc_out=. 
```

**Comment by fakecore** [comment]
> Maybe you can try:
> 
> ```
> $ goctl rpc protoc -I ../.. user.proto --go_out=. --go-grpc_out=. --zrpc_out=. 
> ```
> 
> or
> 
> ```
> $ goctl rpc protoc --proto_path ../.. user.proto --go_out=. --go-grpc_out=. --zrpc_out=. 
> ```
> 
> if it does not work, plz try the following command can be executed successfully
> 
> ```
>  $ protoc --proto_path ../.. user.proto --go_out=. --go-grpc_out=. --zrpc_out=. 
> ```

thank you for comment
