### ISSUE TITLE
Suggestion to improve default timeout of 3 seconds

### ISSUE THREAD

**Issue by fondoger** [zeromicro/go-zero#2876]
I write a http api that normally takes 2~10 seconds to handle a http request.

However, in the client side, the request sometimes fails, some times succeeds, with an error "connection closed while receiving data". Meanwhile, in the server side, the log messages is always look successfully because I can always see a 200 Status OK.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/22270677/218326682-0908f157-9f39-49d0-be2c-7dbc25690ef4.png">

So I keep trying to troubleshoot the issue in the client side. It took me a whole day to troubleshoot this issue. Until I see this post: https://my.oschina.net/yunduansing/blog/5466167

One would never think of that the issue is in the server side when all the log messages looks successful. It is not just me that encountered this issue.

The best solution is to remove the default timeout of 3 seconds. Or add some log messages to explicitly tell users that **the connection is dropped in the server side** when the request takes more than 3 seconds.

**Comment by chenquan** [comment]
Custom timeout(`Timeout`): https://go-zero.dev/docs/configuration/api?_highlight=timeout#restrestconf

**Comment by chenquan** [comment]
You can adjust through this function(`SetSlowThreshold`)：

https://github.com/zeromicro/go-zero/blob/072db116c36c16dce78d8431515320e82ebd0748/rest/handler/loghandler.go#L112-L114

**Comment by zhoushuguang** [comment]
Set a conservative timeout expecting to be able to fail fast, otherwise a large number of requests will cause blocking

**Comment by fondoger** [comment]
It is fine to add a timeout. But we need a more straightforward way to know the existence of timeout. Otherwise, it will cause troubles for people who don't know there is a timeout. I believe all the go-zero users won't find out that there is actually a default timeout of 3 seconds until they finally encountered this difficult issue.

For example: 
1. We can print a warning log messages when the timeout is reached.
2. We can show a `500` status code in log, instead of a `200` status code when timeout.

**Comment by fondoger** [comment]
FYI: there is an open issue about this since 2022:  https://github.com/zeromicro/go-zero/issues/2140
