### ISSUE TITLE
debug go-zero reids timeout seting Timeout

### ISSUE THREAD

**Issue by dahaipublic** [zeromicro/go-zero#2878]
debug go-zero reids 超时有这个问题吗

**Comment by dahaipublic** [comment]
搞错了是接口调用rpc超时 自己配置超时就可以了

**Comment by kevwan** [comment]
Close it?

**Comment by dahaipublic** [comment]
Name: User
Host: 0.0.0.0
Port: 8000

Mysql:
  DataSource: root:123456@tcp(mysql:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: redis:6379
    Pass:
    Type: node

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

UserRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: user.rpc
  Timeout: 300000 # 300s，方便debug测试,设置rpc服务的响应的超时时间，若超过300s还未返回则结束请求

Timeout: 300000 # 300s，方便debug测试,设置rpc服务的响应的超时时间，若超过300s还未返回则结束请求
