### ISSUE TITLE
  How svcCtx is used in middleware

### ISSUE THREAD

**Issue by timzzx** [zeromicro/go-zero#2881]
How svcCtx is used in middleware

**Comment by timzzx** [comment]
```go
// write main.go
// Router list This method also uses global variables
varx.RouterList = server.Routes()
varx.Ctx = ctx
```
I used global variables to solve this problem, Is there a better way?

**Comment by Suyghur** [comment]
I add params what I want to used in NewXXXXMiddleware(a *A) func

**Comment by timzzx** [comment]
> I add params what I want to used in NewXXXXMiddleware(a *A) func

Is that so
```go
type xxxMiddleMiddleware struct {
    db     *query.Query
}

func NewxxxMiddleMiddleware(db *query.Query) *LoginMiddleMiddleware {
	return &xxxMiddleMiddleware{
          db : db,
      }
}

```
The code is automatically generated, I didn't want to modify it. I understood as you said
