### ISSUE TITLE
[goctl api] Got a error when i use `goctl api java`

### ISSUE THREAD

**Issue by kfy333** [zeromicro/go-zero#2886]
**Describe the bug**
Got a error when i use `goctl api java`

**To Reproduce**

1. The code is

   ```sh
   goctl api java --api=./xx.api --dir=java
   ```

2. The error is

   ```
   2023/02/15 17:56:50 Type UserProfile generate error, unsupported primitive type []string
   ```

**Expected behavior**
what you expected: generate the java api class files succeed

**Screenshots**
![image](https://user-images.githubusercontent.com/46022335/219006733-8573f677-06c5-4b1c-bb8c-ab2d4697a989.png)

**Environments (please complete the following information):**
 - OS: windows
 - go-zero version v1.4.1
 - goctl version v1.4.4

**More description**

**Comment by anqiansong** [comment]
Please post the content of the key api file, thank you
