### ISSUE TITLE
go-zero version 1.4.4 envconfig.go:84:13: undefined: envconfig.WithTLSConfig

### ISSUE THREAD

**Issue by yasin-wu** [zeromicro/go-zero#2890]
../../../../../pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.10.0/internal/otlpconfig/envconfig.go:84:13: undefined: envconfig.WithTLSConfig

**Comment by firma** [comment]
go mod version change
```
go.opentelemetry.io/otel v1.10.0
go.opentelemetry.io/otel/trace v1.10.0
```

**Comment by yanwenchuang** [comment]
go.opentelemetry.io/otel v1.13.0 // indirect
	go.opentelemetry.io/otel/exporters/jaeger v1.13.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.13.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.13.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.13.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.13.0 // indirect
Reference link
https://github.com/open-telemetry/opentelemetry-go/issues/3548
