### ISSUE TITLE
The api service doesn't seem to have been gracefully turned off, despite the code in core/signals.

### ISSUE THREAD

**Issue by iidst** [zeromicro/go-zero#2908]
The api service doesn't seem to have been gracefully turned off, despite the code in core/signals.
Press ctrl+c to exit directly, "exit status 0xc000013a" is displayed
`
Who can answer it，Thanks

**Comment by kevwan** [comment]
Use SIGTERM to graceful stop, not SIGINT.

**Comment by iidst** [comment]
OK，Thanks。
Elegant shutdowns are successed in Linux, but not in Windows,
When I look at the source code, `proc.AddWrapUpListener` function is selected based on the operating system, while Windows simply returns the function
windows cannot shut down gracefully？

**Linux  `proc. AddWrapUpListener`**
```go
func AddWrapUpListener(fn func()) (waitForCalled func()) {
	return wrapUpListeners.addListener(fn)
}
```

**Windows`proc. AddWrapUpListener`**
```go
// AddWrapUpListener returns fn itself on windows, lets callers call fn on their own.
func AddWrapUpListener(fn func()) func() {
	return fn
}
```
