### ISSUE TITLE
golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369 can not be downloaded

### ISSUE THREAD

**Issue by WangQu** [zeromicro/go-zero#2909]
when install goctl, there is an error happened because "golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369 " can not be downloaded

**Comment by kevwan** [comment]
Please check your network.

**Comment by WangQu** [comment]
> Please check your network.

Hey  budy, my network is Okay. I've tried more than 30 times and failed.  There's a obvious mistake in **"/tools/goctl/go.mod"  line 48** , cos **the special version cannot be found.**

**Comment by kevwan** [comment]
what's the error details?
