### ISSUE TITLE
import .api files not format

### ISSUE THREAD

**Issue by xmwilldo** [zeromicro/go-zero#2910]
### What category of issue (<code>goctl</code> or <code>sdk</code>)?
goctl
### What type of issue (<code>feature</code>|<code>bug</code>|<code>suggestion</code>)?
suggestion
### What version of Goctl are you using (<code>goctl --version</code>)?

<pre>
$ goctl --version
1.4.4
</pre>

### What operating system and processor architecture are you using ?
<pre>
ARCH = "amd64"
GOCTL_VERSION = "1.4.4"
GO_VERSION = "go1.19.6"
OS = "linux"
</pre>

### What did you do?
I import b.api file in a.api, but b.api not format when I run goctl command

### What did you expect to see?
b.api format

### What did you see instead?

b.api not format

**Comment by anqiansong** [comment]
You can post the actual execution results, thank you！
