### ISSUE TITLE
Scaning rows will fail when using goctl tools from remote database that has filed type bug when generating (filed1 int DEFAULT '0')  

### ISSUE THREAD

**Issue by Danny5487401** [zeromicro/go-zero#2914]
**Describe the bug**
```sql
`customer_company_count` int DEFAULT '0',  
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/64348131/220802979-1deb5507-d5f1-4ebc-9037-3a140a35eb81.png">

![image](https://user-images.githubusercontent.com/64348131/220803053-c799df64-44d3-4b35-ba9a-eac270cf3c9c.png)

when it scans the rows and does the transfer ,it will fail.
![image](https://user-images.githubusercontent.com/64348131/220803102-35036220-e7c1-4abc-a822-3c971f613347.png)

**To Reproduce**

when the field of  is null but not 0 ,it will come out with error.So the generates model field shoule be  sql.NullInt64 .

when i use goctl to generate model
```shell
goctl model mysql datasource --url "user:password@tcp(host:3306)/database" --table "client"
```

```shell
(⎈ |prod-ctx:default)➜  glluestoragestats git:(main) goctl -v     
goctl version 1.4.4 darwin/arm64

same issue with goctl version 1.5.0 darwin/arm64

```

it will be this way from information_schema.COLUMNS
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/64348131/220812601-76c70341-609b-4e39-92b7-42b52b50787f.png">

this is the  bug code! @kevwan 

![image](https://user-images.githubusercontent.com/64348131/220814539-3154c1e3-f207-4f26-8e56-fcd2652807dd.png)

![image](https://user-images.githubusercontent.com/64348131/220813993-43e9f2a1-1429-42c5-b03a-2b8de01a06a1.png)

**Comment by anqiansong** [comment]
If the field has a default value, the query result should not be null, you can post your picture, the following is my test result：
![image](https://user-images.githubusercontent.com/10302073/222622632-c3ccf31e-9180-4544-b926-f1df1d7d1a20.png)

**Comment by Danny5487401** [comment]
it is easy when u insert into order vaulues ()

> If the field has a default value, the query result should not be null, you can post your picture, the following is my test result： ![image](https://user-images.githubusercontent.com/10302073/222622632-c3ccf31e-9180-4544-b926-f1df1d7d1a20.png)

```shell
use test;
create table `order` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'Id',
    `code` varchar(255)  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '客户企业corpId',
    `ticket_id` bigint unsigned NULL DEFAULT '0' COMMENT  '工单ID',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工单卡片';

insert into `order` (code,ticket_id)value (null,null);
```

when u inset null into table field .
<img width="766" alt="image" src="https://user-images.githubusercontent.com/64348131/222625428-e6f51463-ebae-40af-89b2-2d7ff7c01506.png">
 @anqiansong
