### ISSUE TITLE
[collection] Add `TimingWheel.HasKey()` method

### ISSUE THREAD

**Issue by ofey404** [zeromicro/go-zero#2918]
`TimingWheel{}` uses a unique key to identify a task.

However, it doesn't have a `HasKey()` method to check whether a key is existed.

```go
func (tw *TimingWheel) SetTimer(key, value any, delay time.Duration) error
```

## Solution

Create a `HasKey()` method.

## Alternative

The user could track the existence of keys by maintaining an external copy of `timers *SafeMap`.

But naturally it's not natural, wasting memory, and has concurrency issue.

**Comment by kevwan** [comment]
```go
keys := make(map[string]struct{})
// add keys

...

tw, err := collection.NewTimingWheel(time.Second, 600, func(key, value interface{}) {
        // remove key
	job(&count)
})
```

**Comment by ofey404** [comment]
Yes, this snippet works.

Besides, all timer operations are within a specific goroutine, for the golang map is not thread-safe.
