### ISSUE TITLE
context deadline exceeded，设置时间context不生效

### ISSUE THREAD

**Issue by Youngerzkc** [zeromicro/go-zero#2930]
api yaml文件均已经设置 timeout ，但是不生效。依然是2秒context到期
api.yaml 添加设置timeout
<img width="380" alt="image" src="https://user-images.githubusercontent.com/24718560/221461982-adb4cdfa-0797-4bec-a6e3-b6b0d14a0f9d.png">
rpc 添加设置
<img width="444" alt="image" src="https://user-images.githubusercontent.com/24718560/221462561-b19f39ae-23ab-43a5-9774-f5072722ad22.png">

**Comment by Youngerzkc** [comment]
1

**Comment by wahson-gong** [comment]
1

**Comment by zhou2ding** [comment]
碰到了相同的问题，请问大佬最后如何解决的？

**Comment by Alice52** [comment]
@Youngerzkc so how to config context timeout?

**Comment by zhou2ding** [comment]
> @Youngerzkc so how to config context timeout?
在api.yaml中设置api的timeout和它依赖的rpc的timeout，在rpc.yaml也设置timeout
![image](https://github.com/user-attachments/assets/8dfe0db5-6916-4cfe-93fc-b2a4eead5f1f)
![image](https://github.com/user-attachments/assets/ed9a5e1f-7fee-4f2f-b1c3-5542a4ba2977)

**Comment by Alice52** [comment]
> > @Youngerzkc so how to config context timeout?
> > 在api.yaml中设置api的timeout和它依赖的rpc的timeout，在rpc.yaml也设置timeout
> > ![image](https://private-user-images.githubusercontent.com/26682497/366360836-8dfe0db5-6916-4cfe-93fc-b2a4eead5f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDIwODgsIm5iZiI6MTcyNjEwMTc4OCwicGF0aCI6Ii8yNjY4MjQ5Ny8zNjYzNjA4MzYtOGRmZTBkYjUtNjkxNi00Y2ZlLTkzZmMtYjJhNGVlYWQ1ZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAwNDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZDlkYzZhYjkyZTA2NjE2MWJkZjBhMzgyYzM2NWE5YWJhOTM0NDI0NTQxZGQ1ZjA2OWMyNTg4MzFjMjBjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XvbsRg52gT0NUpwodTAvnlzo7fNnWIZRRnXLYdvEmwI)
> > ![image](https://private-user-images.githubusercontent.com/26682497/366360939-ed9a5e1f-7fee-4f2f-b1c3-5542a4ba2977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDIwODgsIm5iZiI6MTcyNjEwMTc4OCwicGF0aCI6Ii8yNjY4MjQ5Ny8zNjYzNjA5MzktZWQ5YTVlMWYtN2ZlZS00ZjJmLWIxYzMtNTU0MmE0YmEyOTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAwNDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYWMwY2UzOGJkMzUxZDBiOTZjM2NlYzcwM2NlMGVkODE0MmViMWJkN2JhNGNiZmQxOTBjYjQ0MzUwOTIwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ZXR1ac50lRPNen7SqWT3McRWtb_4wSsK7GEnK30pCo)

API.yaml 中的 RPC.Timeout 没有看到哪里有解析使用，可以指个北嘛

**Comment by zhou2ding** [comment]
> 没有看到哪里有解析

在zrpc.RpcClientConf中
![image](https://github.com/user-attachments/assets/a4c7c4b6-f70c-4d4c-8f1a-ecaf0e5bf2e5)
