### ISSUE TITLE
goctl rpc protoc has bug when using "google/protobuf/empty.proto" and how to integrated with third party proto like "google/api/annotations.proto"

### ISSUE THREAD

**Issue by Danny5487401** [zeromicro/go-zero#2936]
![image](https://user-images.githubusercontent.com/64348131/221767350-acfb118f-b17d-474c-824d-2d8ea143e379.png)

hope to get compatible with thirdparty proto

**Comment by anqiansong** [comment]
goctl rpc generation does not support the request body and response body in the rpc method to be imported from the outside, and must be under the same package

**Comment by Danny5487401** [comment]
> goctl rpc generation does not support the request body and response body in the rpc method to be imported from the outside, and must be under the same package

when  will it  be supported ?

**Comment by Danny5487401** [comment]
@anqiansong @kevwan  how to integrated with third party proto like "google/api/annotations.proto"
