### ISSUE TITLE
decryptBody support r.ContentLength > 1MB

### ISSUE THREAD

**Issue by yasin-wu** [zeromicro/go-zero#2945]
开启HTTP通信加密时，Body无法超过1MB

**Comment by chenquan** [comment]
Settings you want to get the maximum value.
https://github.com/zeromicro/go-zero/blob/de4924a2746cf50934a906e136475a4b80bcccd0/rest/config.go#L53

**Comment by yasin-wu** [comment]
这个配置不会对CryptionHandler中的maxBytes起作用
