### ISSUE TITLE
How to get in touch regarding a security concern? 

### ISSUE THREAD

**Issue by cokeBeer** [zeromicro/go-zero#2948]
**Describe the bug**
Hello 👋

I found a potential security issue in go-zero, how can I get in touch with you in a private way and submit my security report?

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

**More description**
I have submitted a report in https://github.com/zeromicro/go-zero/security/advisories but seems no one notice it.

**Comment by MarkJoyMa** [comment]
OK, thanks, received, let's take a look at the report first and contact you later

**Comment by MarkJoyMa** [comment]
https://github.com/zeromicro/go-zero/pull/2949
