### ISSUE TITLE
sqlx has a bug like sql: Scan error on column index 4, name "create_time": unsupported Scan, storing driver.Value type []uint8 into type *time.Time

### ISSUE THREAD

**Issue by chenyangguang** [zeromicro/go-zero#2956]
I do as go-zero doc file  said: 

https://go-zero.dev/cn/docs/advance/model-gen

but when run this article code, I found that the sqlx does not work right  after i run it on mac .

1. The code is

   ```go

	// User defines an data structure for mysql
	User struct {
		ID         int64     `db:"id"`
		Name       string    `db:"name"`
		Password   string    `db:"password"`
		Gender     string    `db:"gender"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}

   
   ```

2. The error is

   ```
   sql: Scan error on column index 4, name "create_time": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
   ```

It seems that sqlx does't work well on column create_time, update_time . 

**Environments (please complete the following information):**
 - OS: mac [13.0.1]
 - go-zero version [1.4.4]
 - goctl version [1.4.4]

Any help should  appriciate.

**Comment by jan-bar** [comment]
![image](https://user-images.githubusercontent.com/14202095/222614139-f899f297-4b13-4242-9201-75f9a21d9945.png)

You should add these two DSN that you connect to MySQL

**Comment by fivezjd** [comment]
github.com/go-sql-driver parses data of type mysql timestamp into a string by default. Only when parseTime=true is specified in the DSN can it be mapped to the time.Time type in the model structure, or as follows
`CreateTime string  db:"create_time"`

**Comment by chenyangguang** [comment]
That's cool. All right . Thank you so much for your help.

**Comment by kevwan** [comment]
@chenyangguang problem solved?

**Comment by chenyangguang** [comment]
> @chenyangguang problem solved?

Thank you . Done
