### ISSUE TITLE
When i use go mod tidy, this error occurs

### ISSUE THREAD

**Issue by Brownjy** [zeromicro/go-zero#2965]
go mod tidy
go: finding module for package github.com/zeromicro/go-zero/core/logx
go: finding module for package github.com/zeromicro/go-zero/core/conf 
go: finding module for package github.com/zeromicro/go-zero/rest      
go: finding module for package github.com/zeromicro/go-zero/rest/httpx
go: found github.com/zeromicro/go-zero/core/conf in github.com/zeromicro/go-zero v1.4.4
go: found github.com/zeromicro/go-zero/rest in github.com/zeromicro/go-zero v1.4.4      
go: found github.com/zeromicro/go-zero/rest/httpx in github.com/zeromicro/go-zero v1.4.4
go: found github.com/zeromicro/go-zero/core/logx in github.com/zeromicro/go-zero v1.4.4 
go: github.com/zeromicro/go-zero@v1.4.4 requires                                                                                                 
        google.golang.org/grpc@v1.50.1 requires                                                                                                  
        github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1: parsing go.mod: go.mod:1: unexpected input character '\x00'

**Comment by Brownjy** [comment]
my go.mod:
module github.com/zero-demo

go 1.19

**Comment by kevwan** [comment]
Bad go.mod file. Check it.
