### ISSUE TITLE
Proposal for restTracingHandler

### ISSUE THREAD

**Issue by ShyunnY** [zeromicro/go-zero#2967]
Hello, I think the TracingHandler in the handle package of rest should support reading the X-Request-ID in http.Request through the configuration file. I think that in a single project, TracingHandler is the first span of the trace, and X-Request-ID should be written into the attribute of the span.

**Comment by chenquan** [comment]
Use `Traceparent` in headers.
```bash
curl --location --request GET 'http://localhost:8888/users/1' \
--header 'Traceparent: 00-0fc9485ce4e0d098f4439229ffc992c9-11097b7692891a4e-00' 
```
