### ISSUE TITLE
goctl can't show protobuf version

### ISSUE THREAD

**Issue by loloxwg** [zeromicro/go-zero#2969]
> GOCTL_OS=darwin
> GOCTL_ARCH=arm64
> GOCTL_HOME=/Users/xwg/.goctl
> GOCTL_DEBUG=False
> GOCTL_CACHE=/Users/xwg/.goctl/cache
> GOCTL_VERSION=1.5.0
> PROTOC_VERSION=
> PROTOC_GEN_GO_VERSION=v1.28.1
> PROTO_GEN_GO_GRPC_VERSION=1.3.0

**Comment by anqiansong** [comment]
Please make sure your protoc is installed and PATH is set
