### ISSUE TITLE
I think that in zero's zrpc, when the server registers the service through etcd, there is a logical problem in etcdKey splicing

### ISSUE THREAD

**Issue by ShyunnY** [zeromicro/go-zero#2981]
When I was looking at the source code of zrpc server tonight, I found that when registering, I cannot fully control the service registration key on etcd through the NewRpcPubServer function or configuration file.
As shown below：
`if p.id > 0 {
		p.fullKey = makeEtcdKey(p.key, p.id)
	} else {
		p.fullKey = makeEtcdKey(p.key, int64(lease))
	}`
And how to modify p.id function
`func WithId(id int64) PubOption {
	return func(publisher *Publisher) {
		publisher.id = id
	}
}`

The above is excerpted from the source code in go-zero. I found that when the server is registered, it does not support modifying the p.id through parameters. Because sometimes, I don't want to use the lease id to splice the etcd key in the configuration file.

Is the way I use it wrong or manual modification is really not supported here. Hope to reply! Thank u!

**Comment by kevwan** [comment]
would you please describe the steps and what you want in each step?
