### ISSUE TITLE
How to set timeout for individual route in rest?

### ISSUE THREAD

**Issue by jiriyao** [zeromicro/go-zero#2984]
现在配置文件yaml里的Timeout 是全局设置api 超时的，问题：
一、能不能单独设置某个请求的超时时长？
二、可不可以取消或者某个路由的超时时长设置，也就是不超时？

感谢大大们

**Comment by kevwan** [comment]
`rest.WithTimeout`

**Comment by jiriyao** [comment]
> 
thanks
What annotation in .api files for this? not found in https://go-zero.dev/ 
btw: rest.WithTimeout is global timeout for all routes

**Comment by jiriyao** [comment]
OK got it thanks
like this
@server(
	middleware: CommonRoute
	timeout : 10000ms
)
