### ISSUE TITLE
cache component may cache expired data

### ISSUE THREAD

**Issue by zhongyuanjia** [zeromicro/go-zero#3000]
**Describe the bug**

<img width="786" alt="图片" src="https://user-images.githubusercontent.com/13273073/224000603-ff5c118a-2fe3-4e0c-809f-918260a97cae.png">

From the above figure we can see that in extreme cases the cache will cache expired data

**To Reproduce**

```go
go func() {
  c.Take(key, val, func() (interface{}, error) {
    val := getFromDB(ctx)
    // Perform some time-consuming operations, or GC jitter.
    time.Sleep(time.Second)
    return val
  })
}()

go func() {
  updateDB()
  c.Del(key)
}()
```

**Expected behavior**
Dont cache expired data

**Environments (please complete the following information):**
 - OS: Macos
 - go-zero version 1.5.0

**Comment by kevwan** [comment]
I talked about this scenario in my presentations. It's a rarely happened case. It's hard to solve it well without bringing the system too complicated.

**Comment by zhongyuanjia** [comment]
<img width="924" alt="图片" src="https://user-images.githubusercontent.com/13273073/224101892-82aca4e1-106d-47b5-b115-b87fac0f826c.png">

Using updating placeholders can solve this problem. I submitted an MR, you can see if it is feasible.

**Comment by kevwan** [comment]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/1918356/224229640-5affa9eb-211a-4468-8ac5-4e066ebb069c.png">
What if the parts go into the place where arrow points to?

**Comment by zhongyuanjia** [comment]
@kevwan
