### ISSUE TITLE
cannot be used ‘Redis redis.RedisConf’ in rpc

### ISSUE THREAD

**Issue by chemwol** [zeromicro/go-zero#3017]
**Describe the bug**
cannot be used ‘Redis redis.RedisConf’ in rpc

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   type Config struct {
	zrpc.RpcServerConf
	Redis redis.RedisConf
   }
   ```

2. The error is

   ```
   config file etc/queue.yaml, duplicated key host
   ```

**Environments (please complete the following information):**
 - OS: windows
 - go-zero version 1.5.0
 - goctl version 1.5.0

**Comment by kevwan** [comment]
If you use Redis like this, the config item will be used for both your `Redis` and `Redis` inside of `zrpc.RpcServerConf`. This is a potential bug that we've met.
