### ISSUE TITLE
request type must defined in test.proto

### ISSUE THREAD

**Issue by bb7788** [zeromicro/go-zero#3030]
go-zero生成 这种嵌套的message的时候，报
line 8:3, request type must defined in test.proto，怎么解决？

<img width="762" alt="image" src="https://user-images.githubusercontent.com/14172278/225180970-4e6eb305-f5b3-496f-afb4-be029e639bb3.png">

**Comment by anqiansong** [comment]
Does not support the request body and response body in the three-party proto file
