### ISSUE TITLE
redis ping err

### ISSUE THREAD

**Issue by iyyzh** [zeromicro/go-zero#3044]
**Describe the bug**
Due to aws redis design issues, it is not possible to ping but can be used. In version 1.5.0, go zero added the logic of not being able to start if ping fails. It is recommended to delete this thing or just prompt?

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
      // NewRedis returns a Redis with given options.
      func NewRedis(conf RedisConf, opts ...Option) (*Redis, error) {
	    if err := conf.Validate(); err != nil {
		    return nil, err
	    }
    
	    if conf.Type == ClusterType {
		    opts = append([]Option{Cluster()}, opts...)
	    }
	    if len(conf.Pass) > 0 {
		    opts = append([]Option{WithPass(conf.Pass)}, opts...)
	    }
	    if conf.Tls {
		    opts = append([]Option{WithTLS()}, opts...)
	    }
    
	    rds := newRedis(conf.Host, opts...)
	    if !rds.Ping() {
		    return nil, ErrPing
	    }
    
	    return rds, nil
      }
      
      
      
     // MustNewRedis returns a Redis with given options.
    func MustNewRedis(conf RedisConf, opts ...Option) *Redis {
	    rds, err := NewRedis(conf, opts...)
	    if err != nil {
		    log.Fatal(err)
	    }
    
	    return rds
    }
   ```

2. The error is

   ```
    if !rds.Ping() {
		    return nil, ErrPing
    }
   ```

**Comment by kevwan** [comment]
Is there any docs from AWS that tells PING is not allowed?

**Comment by iyyzh** [comment]
aws no direct documents(Configuring the icmp protocol does not work). However, Redis itself is also connected through the tcp or tls protocol. It is also common sense that we cannot ping but can operate Redis

**Comment by Dong148** [comment]
go-redis v8不支持redis7

**Comment by Dong148** [comment]
最近有相关的更新计划吗 @kevwan
