### ISSUE TITLE
Is it possible to use `goctl quickstart` from a git repo

### ISSUE THREAD

**Issue by akalittle** [zeromicro/go-zero#3046]
It's feature when we didn't use monorepo and we need to start lots of project based on go-zero.
Therefore, we have owned a customized go-zero template.
When we need to start a new project. Just clone the template and did some changes like project name.

Is it possible to :
`goctl quickstart -url=xxx -moduleName=xxx`

**Comment by anqiansong** [comment]
I understand that what you need is not the `goctl quickstart` command, but remote template management，You can execute remote templates through --remote, so you don't need to change the template for each project

**Comment by akalittle** [comment]
yep. Is this feature under your consideration?
