### ISSUE TITLE
conf.Load not compatible with unexported fields.

### ISSUE THREAD

**Issue by clukboy** [zeromicro/go-zero#3058]
type Config1 struct {
   name string
}

type Config struct {
   Config1
   Age int
}

func TestName(t *testing.T) {
   config := `
name: zs
Age: 213
`
   var c1 Config
   err := conf.LoadFromYamlBytes([]byte(config), &c1)
   t.Log(err)

}

这是一个例子

**Comment by kevwan** [comment]
which version are you using?
