### ISSUE TITLE
Problems on generating model code.

### ISSUE THREAD

**Issue by fuckqqcom** [zeromicro/go-zero#3062]
最新的模版生成的model层代码
多了一个model.tpl，model-new.tpl和model-gen.tpl
那自定义方法其实就在xxxmodel.go里面自定义

希望这个里面导出的类型和find里面一样多
```
Execute(map[string]any{
			"withCache":                 withCache,
			"upperStartCamelObject":     camel,
			"lowerStartCamelObject":     stringx.From(camel).Untitle(),
			"originalPrimaryKey":        wrapWithRawString(table.PrimaryKey.Name.Source(), postgreSql),
			"lowerStartCamelPrimaryKey": util.EscapeGolangKeyword(stringx.From(table.PrimaryKey.Name.ToCamel()).Untitle()),
			"dataType":                  table.PrimaryKey.DataType,
			"cacheKey":                  table.PrimaryCacheKey.KeyExpression,
			"cacheKeyVariable":          table.PrimaryCacheKey.KeyLeft,
			"postgreSql":                postgreSql,
			"data":                      table,
		})
这样所有自定义的方法都在一个模版里面可以修改，不用修改其他的部分模版，比较好维护

**Comment by xhochipe** [comment]
现在比如我想查询id集合，就必须在find相关的模版中改，比如 var ids []string ，模版中 var ids  []{{.dataType}}这样只能在find相关的模版中加，其他模版中 dataType没有导出

**Comment by anqiansong** [comment]
I understand that at present, template extensions are available. The reason for splitting at the beginning is that the content of a single template file will be relatively large. Templates have a lot of scenarios with the same variables but different values, so it is not suitable for large refactor
