### ISSUE TITLE
Why does the RPC response struct ignore the empty slice ?

### ISSUE THREAD

**Issue by Sean04111** [zeromicro/go-zero#3065]
The code is :
![image](https://user-images.githubusercontent.com/96430610/227725723-ffdf2f81-a59e-4795-9d63-36bd37c3a70b.png)
And I got :
![image](https://user-images.githubusercontent.com/96430610/227725757-a7868b8f-13c4-41ee-944e-6a52aa709c7f.png)

**Comment by trungdlp-wolffun** [comment]
Because it is `nil slice` not `empty slice`.
nil pointer will ignore in JSON Marshal, Proto Marshal with `omitempty` struct tag

Ref: https://gosamples.dev/empty-vs-nil-slice/

**Comment by Sean04111** [comment]
> Because it is `nil slice` not `empty slice`. nil pointer will ignore in JSON Marshal, Proto Marshal with `omitempty` struct tag
> 
> Ref: https://gosamples.dev/empty-vs-nil-slice/

Well, I tried that again
The Proto file :
![image](https://user-images.githubusercontent.com/96430610/230785399-8be50b4c-843e-4b94-aaa4-cca8d005397a.png)
The RPC logic:
![image](https://user-images.githubusercontent.com/96430610/230785415-59905bf2-5c92-445a-ae14-e2ecbd8144eb.png)
API(using RPC,and I tried to print the result):
![image](https://user-images.githubusercontent.com/96430610/230785510-be3b69fb-ba72-4a23-a976-c8af58455b12.png)
And I got:
![image](https://user-images.githubusercontent.com/96430610/230785480-e2fba40b-bfd6-43f5-bbc0-4ff3dbd4fa97.png)
It seems that the empty slice(repeated filed)  was missing ?
