### ISSUE TITLE
Missing primary key in mysql model

### ISSUE THREAD

**Issue by diPhantxm** [zeromicro/go-zero#3068]
**Describe the bug**
I have an sql query creating one table. When I execute `goctl model mysql ddl -s "mysql.sql" -dir mysql -c`, it returns error "table Users: missing primary key", but it actually has primary key

**To Reproduce**
MySQL query:
```mysql
CREATE TABLE Users(
    id int primary key,
    username varchar(255) not null
)
```
```bash
goctl model mysql ddl -s "mysql.sql" -dir mysql -c
```
 returns "table Users: missing primary key"

Built on commit #3064

**Comment by diPhantxm** [comment]
I figured out that to make it works you need to define primary key as a constraint like this:
```
CREATE TABLE Users(
    id int,
    username varchar(255) not null,
    primary key(id)
)
```
I think it's a good idea to document it somewhere or to implement this case.

**Comment by anqiansong** [comment]
goctl has already clearly reminded, this is more reflective and problem-solving than documentation
