### ISSUE TITLE
Questions on RPC yaml config.

### ISSUE THREAD

**Issue by suguer** [zeromicro/go-zero#3120]
```
Name: whois.rpc
ListenOn: 0.0.0.0:30000
Etcd:
  Hosts:
  - ip:2379
  Key: whois.rpc
```
请问一下 etcd在B主机上,rpc在A主机的docker上,如果ListenOn写0.0.0.0的话 etcd会记录docker内网的IP, 可以怎么部署让etcd记录需要的外网IP:端口

**Comment by kevwan** [comment]
It's not recommend to use this kind of deployment. On your local laptop, you can use direct host:port, without docker.
