### ISSUE TITLE
goctl protocCmd style

### ISSUE THREAD

**Issue by wangyi12358** [zeromicro/go-zero#3133]
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/39055759/232263006-d528e427-42a2-44a8-a2a3-b62891a7c2a5.png">
Hello, how long will this feature be released.

**Comment by xyqlll** [comment]
I also found this problem

**Comment by xyqlll** [comment]
“rpc --style” cannot be used

**Comment by xyqlll** [comment]
> PR #3112 has already fix it, you can upgrade goctl to the latest version by `github.com/zeromicro/go-zero/tools/goctl@master`

fine

**Comment by kevwan** [comment]
fixed.
