### ISSUE TITLE
Let default tag effective in response

### ISSUE THREAD

**Issue by NX-Official** [zeromicro/go-zero#3172]
Current default tag only effective in request

However, in some cases, it's very useful, such as set a pre-defined response which means have no errors

![image](https://user-images.githubusercontent.com/58617692/234050264-89c388cf-7f67-4bc8-940f-b86391f5db7f.png)

**Comment by NX-Official** [comment]
I know it can be solved by Template Modification, but it is inconvenience for developing multiple projects simultaneously. 
And I don't think it's a bad idea for most people.

**Comment by princejha95** [comment]
Hi @NX-Official 

I am new to go-zero and wanted to contribute to the project. On going through the guidelines mentioned in CONTRIBUTING.md file, i checked for the issues with label good first issue but found no issues with such label. So i am planning to pick this up. Do you think it will be a good first issue for me ?
