### ISSUE TITLE
flush error

### ISSUE THREAD

**Issue by asppj** [zeromicro/go-zero#3178]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   runtime error: invalid memory address or nil pointer dereference
goroutine 105 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
github.com/zeromicro/go-zero/core/logx.writeStack({0xc000a60280, 0x40})
github.com/zeromicro/go-zero@v1.5.1/core/logx/logs.go:462 +0x4d
github.com/zeromicro/go-zero/core/logx.ErrorStack({0xc000791948?, 0x99?, 0x3?})
github.com/zeromicro/go-zero@v1.5.1/core/logx/logs.go:113 +0x25
github.com/zeromicro/go-zero/core/rescue.Recover({0x0, 0x0, 0x79eaa9?})
github.com/zeromicro/go-zero@v1.5.1/core/rescue/recover.go:15 +0x78
panic({0x13555c0, 0x22cc7c0})
runtime/panic.go:884 +0x213
bufio.(*Writer).Flush(0xc0003a0dc0)
bufio/bufio.go:628 +0x56
net/http.(*response).FlushError(0xc00068e460)
net/http/server.go:1706 +0x3a
net/http.(*response).Flush(0x40bbbd?)
net/http/server.go:1699 +0x19
github.com/zeromicro/go-zero/rest/internal/response.(*WithCodeResponseWriter).Flush(0x40bbbd?)
github.com/zeromicro/go-zero@v1.5.1/rest/internal/response/withcoderesponsewriter.go:19 +0x35
github.com/zeromicro/go-zero/rest/internal/response.(*WithCodeResponseWriter).Flush(0x40bbbd?)
github.com/zeromicro/go-zero@v1.5.1/rest/internal/response/withcoderesponsewriter.go:19 +0x35
github.com/zeromicro/go-zero/rest/internal/response.(*WithCodeResponseWriter).Flush(0x40bbbd?)
github.com/zeromicro/go-zero@v1.5.1/rest/internal/response/withcoderesponsewriter.go:19 +0x35
github.com/zeromicro/go-zero/rest/internal/response.(*WithCodeResponseWriter).Flush(0x140c900?)
github.com/zeromicro/go-zero@v1.5.1/rest/internal/response/withcoderesponsewriter.go:19 +0x35
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by asppj** [comment]
这个找到原因了: 在 SSE 推流的时候 for 循环 Write、Flu；sh 如果启用了 timeout中中间件，由于超时会导致bufio.(*Writer).Flush(0xc0003a0dc0) panic;
把Timeout中间件关了就好了

**Comment by jiriyao** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> The reason for this is found: when SSE pushes the stream, the for loop Write, Flu; sh If the timeout middleware is enabled, the timeout will cause bufio.(*Writer).Flush(0xc0003a0dc0) panic; Just turn off the Timeout middleware

`
turn off timeout , but  ok is false in handler for request
Middlewares:
  Timeout: false

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	flusher, ok := w.(http.Flusher)` // ok =false why?
}

**Comment by littleriver125** [comment]
func Test1Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// 设置响应头的 Content-Type 为 application/octet-stream
		w.Header().Set("Content-Type", "application/octet-stream")

		// 获取响应写入器对象，并判断是否支持刷新缓冲区
		flusher, ok := w.(http.Flusher)
		if !ok {
			http.Error(w, "Streaming unsupported!", http.StatusInternalServerError)
			return
		}

		flusher.Flush()
		httpx.Ok(w)
	}
}


运行之后flusher 为 nil
