### ISSUE TITLE
Multi-environment configuration merge support

### ISSUE THREAD

**Issue by greper** [zeromicro/go-zero#3186]
**Describe the solution you'd like**
First , I know ` go run app.go-f etc/app.yaml` can switch config

But I don't want to copy all the configuration in app-prod.yaml

I want to configure only the parts that must be modified in app-prod.yaml and inherit the rest from app.yaml

```
configs := []*configFiles
conf.MustLoad(configFiles, &c, conf.UseEnv())
```
We can use loader to load multiple configuration files as json, and then combine the previous configuration with the later configuration, and finally convert into a config struct

**Describe alternatives you've considered**

**Additional context**

**Comment by kevwan** [comment]
The core team will have a discussion on this. Thanks for your ideas!
