### ISSUE TITLE
why metrics and pprof  listen in one port?

### ISSUE THREAD

**Issue by ghost** [zeromicro/go-zero#3206]

**Comment by kevwan** [comment]
What's the benefit to separate them?

**Comment by nezhuhos** [comment]
metrics 现在默认运行在： 9101端口，这种改动后续升级非常不方便，需要所有服务的配置文件同步更新

**Comment by nezhuhos** [comment]
升级go-zero版本必须注意要修改配置文件，这样操作很不友好

**Comment by zcong1993** [comment]
1. metrics pprof 都是为了暴露服务可观测性，而且一般都是仅内网暴露的 http 服务，分成多个端口没什么优势。并且 DevServer 的功能都可以控制开启关闭。
2. Prometheus 配置目前仍然可以使用，但是我们推荐迁移到 DevServer。
3. 我们后续会让 DevServer 配置兼容 Prometheus 配置，方便大家升级框架。
