### ISSUE TITLE
Add IPv6 support to go-zero

### ISSUE THREAD

**Issue by xiang-xx** [zeromicro/go-zero#3223]
Hello go-zero maintainers,

First of all, I'd like to thank you for your work on go-zero. It has been of great help to us.

I encountered an issue where go-zero does not support IPv6. The reason seems to be that grpc uses a special format when working with IPv6 addresses. You can refer to this specific line of code in the grpc repository for more information: https://github.com/grpc/grpc-go/blob/master/internal/resolver/dns/dns_resolver.go#L358

In some environments, such as certain versions of Kubernetes clusters, container group IPs only support IPv6 addresses. Thus, it is important for go-zero to support IPv6 in order to help us use load balancing effectively in these situations.

Could you please add IPv6 support to go-zero, so that it can be used seamlessly in environments where IPv6 is required for load balancing? Your assistance in this matter would be greatly appreciated.

Thank you for your time and consideration.

**Comment by MarkJoyMa** [comment]
Okay, thank you for your proposal, but it is best if you can submit a PR to participate in the joint construction, thank you.
