### ISSUE TITLE
 *kube.EventHandler does not implement 

### ISSUE THREAD

**Issue by anyone0034** [zeromicro/go-zero#3231]
**Describe the bug**
```
F:\app\env\go.1.20.2_gopath\pkg\mod\github.com\zeromicro\go-zero@v1.5.2\zrpc\resolver\internal\kubebuilder.go:71:32: cannot use handler (variable of type *kube.EventHandler) as "k8s.io/client-go/tools/cache".ResourceEventHandler value in argument to in.Informer().AddEventHandler: *kube.EventHandler does not implement "k8s.io/client-go/tools/cache".ResourceEventHandler (wrong type for method OnAdd)
                have OnAdd(any)
                want OnAdd(interface{}, bool)
```

**To Reproduce**
使用了go get -u之后，就出现了。之前是一切正常，使用go clean -modcache清空缓存，还是一样有。

1. The code is

   ```go
   
   ```

2. The error is

   
```
   google.golang.org/grpc/reflection/grpc_reflection_v1alpha
github.com/zeromicro/go-zero/core/stores/cache
github.com/zeromicro/go-zero/core/stores/sqlx
github.com/zeromicro/go-zero/core/stores/builder
github.com/zeromicro/go-zero/zrpc/resolver/internal
# github.com/zeromicro/go-zero/zrpc/resolver/internal
F:\app\env\go.1.20.2_gopath\pkg\mod\github.com\zeromicro\go-zero@v1.5.2\zrpc\resolver\internal\kubebuilder.go:71:32: cannot use handler (variable of type *kube.EventHandler) as "k8s.io/client-go/tools/cache".ResourceEventHandler value in argument to in.Informer().AddEventHandler: *kube.EventHandler does not implement "k8s.io/client-go/tools/cache".ResourceEventHandler (wrong type for method OnAdd)
                have OnAdd(any)
                want OnAdd(interface{}, bool)
google.golang.org/grpc/reflection
github.com/zeromicro/go-zero/core/stores/sqlc
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15609924/236969284-5c31a64b-75da-4175-ad6b-29a83eaafec4.png)

**Environments (please complete the following information):**
 - OS: [e.g. Linux] windows
 - go-zero version [e.g. 1.2.1] v1.5.2
 - goctl version [e.g. 1.2.1, optional] goctl version 1.5.2 windows/amd64

**More description**

**Comment by Chen-Guorui** [comment]
同样有这个问题，请问您是怎么解决的呀

**Comment by kevwan** [comment]
Make sure you're using the correct version of k8s client.

**Comment by lingyao2333** [comment]
My user these
k8s.io/api v0.26.3 // indirect
k8s.io/apimachinery v0.27.0-alpha.3 // indirect
k8s.io/client-go v0.26.3 // indirect
k8s.io/klog/v2 v2.90.1 // indirect
k8s.io/kube-openapi v0.0.0-20230307230338-69ee2d25a840 // indirect
k8s.io/utils v0.0.0-20230209194617-a36077c30491 // indirect
sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
sigs.k8s.io/structured-merge-diff/v4 v4.2.3 // indirect
sigs.k8s.io/yaml v1.3.0 // indirect
