### ISSUE TITLE
Have you considered using generics in the api?

### ISSUE THREAD

**Issue by CloverOS** [zeromicro/go-zero#3235]
<img width="685" alt="q" src="https://github.com/zeromicro/go-zero/assets/3244971/4e82e001-90a3-49cb-be73-8cdd68196dff">
Just like this, it is very convenient to unify the data return body

**Comment by kevwan** [comment]
No, because API file is for many programming languages.

**Comment by JasonMing** [comment]
> <img alt="q" width="685" src="https://user-images.githubusercontent.com/3244971/237100667-4e82e001-90a3-49cb-be73-8cdd68196dff.png"> Just like this, it is very convenient to unify the data return body

@CloverOS You could install an interceptor to achieve this goal, that's how we do it.
