### ISSUE TITLE
why go-zero v1.4.3 upgrade v1.5.2 go run error 

### ISSUE THREAD

**Issue by ctra-wang** [zeromicro/go-zero#3236]
`error: config file etc/weixinapi.yaml, unsupported type: func`
in v1.4.3 go run with this yaml is ok
but in v1.5.2 go run with the same yaml throw the error "config file etc/weixinapi.yaml, unsupported type: func
"

**Comment by reatang** [comment]
`type Config struct` does not support the `func` type, check your Confg struct
