### ISSUE TITLE
How to use the project layout from third party libraries on generating api?

### ISSUE THREAD

**Issue by testwill** [zeromicro/go-zero#3254]
如果不能支持，像k8s里面的结构很大，拷贝过来写很麻烦。能不能直接支持

**Comment by testwill** [comment]
type (
	ApiLog {
		ClusterId  string `json:"cluster_id"`
		audit.EventList//"k8s.io/apiserver/pkg/apis/audit" audit.EventList这个就是k8s的库中的一个结构体
	}

)


@server(
	group: logtest
	prefix: api
)
service Gateway {

	@doc(
		summary: "test"
	)
	@handler ApiLogPush
	post /logtest/api_log (ApiLog) returns (Empty);
}

**Comment by panhow** [comment]
@kevwan i got the same problems here
for example, i am writing a web server to provide mutating webhooks, the input is from package "sigs.k8s.io/controller-runtime/pkg/webhook/admission", request body struct is "admission.Request".

How can i define it in api files?
