### ISSUE TITLE
How to close the rest BreakingHandler or reduce its the sensitivity

### ISSUE THREAD

**Issue by yunduansing** [zeromicro/go-zero#3263]
Besides modifying the source code of the go-zero rest,I want to reduce  the sensitivity of the BreakingHandler
![image](https://github.com/zeromicro/go-zero/assets/11469334/c8c04aa9-cb06-4902-9ed9-cd6817ee1943)

**Comment by MarkJoyMa** [comment]
You can set the configuration of breakRestConf.MiddlewaresConf.Breaker = false
