### ISSUE TITLE
Feature: I hope to provide the push function of rpc to API gatway

### ISSUE THREAD

**Issue by maomao94** [zeromicro/go-zero#3264]
提供一个类似这种的方法
func GetDefaultGatewayConn(name string) []*grpc.ClientConn {
}

// rpc logic 可以反向推送给api
for _, v := range grpcCons {
  //todo
}

目的：可以方便去做分布式ws 集群的推送

**Comment by MarkJoyMa** [comment]
For such a scenario, is it possible to directly push the rpc configuration information to the api? After receiving the api, establish the corresponding rpc connection.
