### ISSUE TITLE
Go-Zero Should NOT set the global otel TracerProvider

### ISSUE THREAD

**Issue by JasonMing** [zeromicro/go-zero#3284]
`otel.SetTracerProiver()` and `otl.SetErrorHandler()` is a global call should be called in the host process, never in the library.

Go-Zero integrates the initialization of otel is very handy in most scenarios, but this behavior cannot be disabled may be confused in some times, especially in the highly customized business cases.

It would be great if a switch can be added into `trace.Config` like:

```go
// github.com/zeromicro/go-zero/core/trace
package trace

type Config struct {
	InitOtel bool      // user can set to false to prevent go-zero calling the otel.SetTracerProvider
	...
}

```

**Comment by kevwan** [comment]
Would you please submit a PR?

**Comment by JasonMing** [comment]
> Would you please submit a PR?

@kevwan Sure, please check [this](#3292) PR #3292
