### ISSUE TITLE
Feature: I hope to provide the Redis Stream API

### ISSUE THREAD

**Issue by tobehardest** [zeromicro/go-zero#3289]
I want to use Redis Stream to implement some functions during the development process, but I found that there is no Redis Stream API in go-zero. Is it possible to add some Stream APIs to go-zero?

**Comment by tobehardest** [comment]
OK, I will do it.

**Comment by shaozi17** [comment]
> OK, I will do it.

How's it going?

**Comment by tobehardest** [comment]
> > OK, I will do it.
> 
> How's it going?

Still working.

**Comment by PittYao** [comment]
> > > OK, I will do it.
> > 
> > 
> > How's it going?
> 
> Still working.

I also join

**Comment by tobehardest** [comment]
Do you have contact?

**Comment by PittYao** [comment]
> 

v: DailyRotten

**Comment by PittYao** [comment]
> Do you have contact?

v: DailyRotten
