### ISSUE TITLE
Potential leak in pool.go

### ISSUE THREAD

**Issue by hhheiaenia** [zeromicro/go-zero#3293]
I notice that all the p.cond.Wait() and p.cond.Signal() are protected by the mutex lock r.cond.L.Lock() in the file https://github.com/zeromicro/go-zero/blob/master/core/syncx/pool.go#LL82C16-L82C16. 
So I doubt whether this situation can cause a deadlock. 

Maybe what I said is not right, thank you for taking a look.

**Comment by kevwan** [comment]
`p.cond.Wait()` automatically unlock the `p.cond.L`.

You can refer to the golang docs.
