### ISSUE TITLE
goctl dart error

### ISSUE THREAD

**Issue by tourdt** [zeromicro/go-zero#3310]
### What version of Goctl are you using (<code>goctl --version</code>)?

<pre>
$ goctl --version
1.4.3
</pre>

### What operating system and processor architecture are you using ?
<pre>
GO_VERSION = "go1.18"
OS = "darwin"
ARCH = "arm64"
GOCTL_VERSION = "1.4.3"
</pre>

type (
       ProductCollectAddReq {
		Desc         string   `json:"desc,optional" comment:"集合描述"`
		Videos       []*Media `json:"videos,optional" comment:"视频列表"`
		Pics         []*Media `json:"pics,optional" comment:"图片列表"`
		ParentShopId int64    `json:"parentShopId,default=0" comment:"父店铺ID(供应商店铺ID)"`
	}

	ProductCollectUpdateReq {
		Id int64 `json:"id" comment:"产品集合ID"`
		ProductCollectAddReq
	}
)

goctl api dart -api api/app.api -dir ./tttt

get error: 
  template: dataTemplate:14:40: executing "dataTemplate" at <getPropertyFromMember .>: error calling getPropertyFromMember: cannot get property name of ""

**Comment by kevwan** [comment]
Please try goctl v1.5.2, couple dart related bugs fixed.

**Comment by tourdt** [comment]
I Update goctl to v1.5.2, 
2023/06/02 08:42:38 template: dataTemplate:19:35: executing "dataTemplate" at <getPropertyFromMember .>: error calling getPropertyFromMember: cannot get property name of ""

**Comment by tourdt** [comment]
> Please try goctl v1.5.2, couple dart related bugs fixed.

I Update goctl to v1.5.2,
2023/06/02 08:42:38 template: dataTemplate:19:35: executing "dataTemplate" at <getPropertyFromMember .>: error calling getPropertyFromMember: cannot get property name of ""
