### ISSUE TITLE
希望加个英译中的机器人

### ISSUE THREAD

**Issue by kpvt001** [zeromicro/go-zero#3312]
期望官方理解，因为很多中国用户在尝试和使用 go-zero，部分中国用户因非母语且工作环境是全中文交流原因，无法正常参与交流。

**特别是学生群体，我们无法参与交流。**

**Comment by JasonMing** [comment]
<img width="945" alt="image" src="https://github.com/zeromicro/go-zero/assets/1220848/10650a50-82c2-4981-ad80-46addabe29ca">
可以用下chrome自带的页面翻译功能

**Comment by kpvt001** [comment]
> 

中译英的机器人都有，英译中不难吧？

**Comment by kevwan** [comment]
暂无计划。
