### ISSUE TITLE
Sqlx error: Scan error on column index 4....converting driver.Value type []uint8 (\"\") to a int: invalid syntax

### ISSUE THREAD

**Issue by milkb32** [zeromicro/go-zero#3313]
### 【description】
When I use **sqlx** to query rows, the following error occured:
**sql: Scan error on column index 4, name \"operator\": converting driver.Value type []uint8 (\"\") to a int: invalid syntax**

my code is like this:

![image](https://github.com/zeromicro/go-zero/assets/87603580/d1b4b267-31b5-4f2f-ab1f-161976c6cf99)

![image](https://github.com/zeromicro/go-zero/assets/87603580/af5ede1a-4660-4dc5-bd05-ca3afe2373f2)
query is like: `SELECT id,obj_id,reason_id,obj_created_at,operator,created_at, modified_at, reason FROM.......`
**attention: the field sort of query and struct "ObjAggregate" is not the same**

And i found out that if  i modify the struct from anonymous into normal struct, this error is not occured:
![image](https://github.com/zeromicro/go-zero/assets/87603580/804ae4a9-9eb5-41e3-9312-7b6d99020d31)

### 【debug】
 i fount that this error is because of the following step (core/stores/sqlx/orm.go:70)：
![image](https://github.com/zeromicro/go-zero/assets/87603580/2367364c-7c00-4f0a-a19c-fb9d3aec7fbe)

when "v" is  a struct with anonymous struct
    `fields := unwrapFields(v)` 
     the variable "fields" has the same size with the struct "ObjAggregate",  
but for this step: 
    `taggedMap, err := getTaggedFieldValueMap(v)`  
    the size of "v" is actually 2, and  "taggedMap" is nil
so  when unmarshal rows:
![image](https://github.com/zeromicro/go-zero/assets/87603580/fdd1e598-d684-429d-a6a6-117c036320fc)
the field sort of "values" and scanner is not the same, and the error occured...

### 【suggestion】
How about  modify this step(core/stores/sqlx/orm.go:70):  
`"taggedMap,err := getTaggedFieldValueMap(v)"`  replace "v" into "fields" ?

**Comment by kevwan** [comment]
@milkb32 I found that you're using v1.2.4, it's too early version, try the latest version please.

**Comment by milkb32** [comment]
> @milkb32 I found that you're using v1.2.4, it's too early version, try the latest version please.

Thank`s for the reply. The latest version v1.5.3 is ok.
