### ISSUE TITLE
goctl api go --home parameter error when loading non-existent folders

### ISSUE THREAD

**Issue by elza2** [zeromicro/go-zero#3320]
**Describe the bug**
![image](https://github.com/zeromicro/go-zero/assets/44083691/ef7a5b9b-cf09-4fef-b2bd-683e3f181246)

```
goctl api go -api ./api/apis/hello.api --dir ./app --home ./api/.goctl

app/etc/test-api.yaml exists, ignored generation
app/internal/config/config.go exists, ignored generation
app/test.go exists, ignored generation
app/internal/svc/servicecontext.go exists, ignored generation
2023/06/05 11:57:01 open api/.goctl/1.5.3/api: no such file or directory
```
the 1.5.3 path is inexplicably found in the file path, causing the generation failure.

**To Reproduce**
```
goctl api go -api ./api/apis/hello.api --dir ./app --home ./api/.goctl
```

**Environments (please complete the following information):**
 - OS: Mac
 - go-zero version 1.5.2
 - goctl version 1.5.2

**Comment by elza2** [comment]
#3319

**Comment by lxy1992** [comment]
I meet this same problem today, its cause by the new version 1.5.3. I have not see a note about it in the release log of version 1.5.3. So, I guess its maybe a bug, or a big change lack of notice. I work around it by lock the version in 1.5.2. 
I read this PR, but I suggest to fix this problem in a positive way.
