### ISSUE TITLE
open template\1.5.3\api: The system cannot find the path specified.

### ISSUE THREAD

**Issue by lynnssb** [zeromicro/go-zero#3322]
I reported this error when using goctl to initialize the template. There was no such problem in the previous version.
![微信图片_20230605161325](https://github.com/zeromicro/go-zero/assets/65780532/818dbbd5-0a8d-42a1-8e8e-9818ef17ec1b)

![c0412a3a3a58c28c8f3e8bc8f435209](https://github.com/zeromicro/go-zero/assets/65780532/2c3f23c0-eeb1-49a5-891f-d5a156dba8fd)

**Comment by anqiansong** [comment]
I noticed that there is a new issue out of #3217 pr, I will roll back this part of the code as soon as possible

**Comment by lynnssb** [comment]
ok, thanks!

**Comment by anqiansong** [comment]
The pr #3319 has already fixed it.
