### ISSUE TITLE
Dynamic parameter transmission to modify the default mysql database connection pool configuration

### ISSUE THREAD

**Issue by Daikunwu** [zeromicro/go-zero#3330]
**I want to use mysql database connection pooling,  but the configuration parameters of the connection pool are default。。。。

Excuse me, do you support dynamic parameter transmission to modify the default configuration?**

Just like this~

**
package sqlx

import (
	"database/sql"
	"io"
	"sync"
	"time"
	"github.com/zeromicro/go-zero/core/syncx"
)

const (
	maxIdleConns = 64
	maxOpenConns = 64
	maxLifetime  = time.Minute
)

type SqlConfig struct {
	MaxIdleCount int
	MaxOpenConns int
	MaxLifetime  time.Duration
}

var connManager = syncx.NewResourceManager()

type pingedDB struct {
	*sql.DB
	once sync.Once
}

func getCachedSqlConn(driverName, server string, conf SqlConfig) (*pingedDB, error) {
	val, err := connManager.GetResource(server, func() (io.Closer, error) {
		conn, err := newDBConnection(driverName, server, conf)
		if err != nil {
			return nil, err
		}

		return &pingedDB{
			DB: conn,
		}, nil
	})
	if err != nil {
		return nil, err
	}

	return val.(*pingedDB), nil
}

func getSqlConn(driverName, server string, conf SqlConfig) (*sql.DB, error) {
	pdb, err := getCachedSqlConn(driverName, server, conf)
	if err != nil {
		return nil, err
	}

	pdb.once.Do(func() {
		err = pdb.Ping()
	})
	if err != nil {
		return nil, err
	}

	return pdb.DB, nil
}

func newDBConnection(driverName, datasource string, conf SqlConfig) (*sql.DB, error) {
	conn, err := sql.Open(driverName, datasource)
	if err != nil {
		return nil, err
	}

	// we need to do this until the issue https://github.com/golang/go/issues/9851 get fixed
	// discussed here https://github.com/go-sql-driver/mysql/issues/257
	// if the discussed SetMaxIdleTimeout methods added, we'll change this behavior
	// 8 means we can't have more than 8 goroutines to concurrently access the same database.
	if conf.MaxIdleCount > 0 {
		conn.SetMaxIdleConns(conf.MaxIdleCount)
	} else {
		conn.SetMaxIdleConns(maxIdleConns)
	}

	if conf.MaxOpenConns > 0 {
		conn.SetMaxOpenConns(conf.MaxOpenConns)
	} else {
		conn.SetMaxOpenConns(maxOpenConns)
	}

	if conf.MaxLifetime > 0 {
		conn.SetConnMaxLifetime(conf.MaxLifetime)
	} else {
		conn.SetConnMaxLifetime(maxLifetime)
	}

	return conn, nil
}
**

**Comment by kevwan** [comment]
Would you please let me know it's for what kind of scenario?

**Comment by Daikunwu** [comment]
> Would you please let me know it's for what kind of scenario?
目前底层实现了数据库连接池，默认64，但是不太满足业务需求
1、数据库连接池的参数可以支持动态配置，这种方式我可以通过sqlx.NewSqlConnFromDB，初始化好DB，并设置好链接池参数配置【已解决】
2、我需要实现最小空闲链接配置，即当DB查询没有太多的时候，也能保持最低10个长连接，即最小空闲连接数

**Comment by Daikunwu** [comment]
closed
