### ISSUE TITLE
How can I ignore the struct that is defined in the `.api` file?

### ISSUE THREAD

**Issue by nomeduck** [zeromicro/go-zero#3333]
environment:
goctl version 1.5.2 darwin/amd64

First, I defined a struct in `api/types.tpl` to import some package types.
Second, I also defined a struct with the same name in `greet.api`, purely as a placeholder.
Now, how can I ignore the struct in `greet.api` to prevent generating duplicate structs in `types/types.go`?

Could someone assist me? Thank you!

**Comment by kevwan** [comment]
If you want to ignore it, why to define it?
