### ISSUE TITLE
how i can using 1 handler for two path /user and user/:id

### ISSUE THREAD

**Issue by handestd** [zeromicro/go-zero#3335]
i wanna handle /user & user/:id by one handler if parameter :id is empty 

![image](https://github.com/zeromicro/go-zero/assets/19203922/4c5ae7be-c04f-442d-a743-a5371da3d329)

i try to define struct like this:
**Id string `path:"id,optional"`** 

but, when i access get /user then i get '404 not found page'

**Comment by kevwan** [comment]
why not use different handlers?
