### ISSUE TITLE
Cannot run goctl api new on Android device

### ISSUE THREAD

**Issue by usernamethatsnottaken1** [zeromicro/go-zero#3339]
**Describe the bug**
No template file was generated except api file.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   goctl api new test
   ```

2. The error is

![Screenshot_2023-06-12-13-58-07-953_com termux-edit](https://github.com/zeromicro/go-zero/assets/136300834/826f0b18-ac12-41d4-a475-603346ddc64e)

![Screenshot_2023-06-12-14-12-07-634_com termux-edit](https://github.com/zeromicro/go-zero/assets/136300834/da116b38-a696-474d-8a35-c8581516affe)

**Environments (please complete the following information):**
 - OS: [Linux (Android 13 with Termux runtime)]
 - go-zero version [1.5.3]
 - goctl version [1.5.3]

**Comment by usernamethatsnottaken1** [comment]
I use thin client connect to my phone to code. All things like helix editor gopls go compiler are working really well and it has very good performance. I will appreciate if you guys can fix it.😂

**Comment by usernamethatsnottaken1** [comment]
I use thin client to connect to my phone. All things like go compiler gopls helix editor are working well and It has good performance. I will appreciate if you guys can fix it. Thanks a lot.😂

**Comment by kevwan** [comment]
Not planned yet.
