### ISSUE TITLE
Adding heating and restart function in monomer applications

### ISSUE THREAD

**Issue by abnereel** [zeromicro/go-zero#3344]
Using go zero to develop individual applications, I found that the development efficiency is quite high. Currently, when deployed on the server, I found that it is not possible to gracefully restart. Upon checking the source code, I found that it can be gracefully shut down, but it cannot be gracefully restarted.

After compiling the go zero monolithic application, execute the command nohup The application program is running on the server. After the configuration is modified, it is hoped that the kill command can achieve the effect of hot restarting the application and reloading the configuration.

I have tried to execute the following command, but I still feel that there are some issues. I hope the official can increase the low-level support:
kill processID && nohup ./application &

**Comment by kevwan** [comment]
Thanks for your issue! But I think supervisord might be your choice.
