### ISSUE TITLE
proto group

### ISSUE THREAD

**Issue by dyjfighting** [zeromicro/go-zero#3345]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

rpc grouping should generate a unified call package file so that the previous api calls do not need to be modified

**Comment by anqiansong** [comment]
This is implemented in the first version of rpc grouping support, during use, it will be found that if different folders use the same package, then import aliases will be everywhere when the package is imported, which is not a good design .
