### ISSUE TITLE
http.ResponseWriter Flush  not work 

### ISSUE THREAD

**Issue by puguojingm** [zeromicro/go-zero#3347]
**Describe the bug**

I want to return  data with Transfer-Encoding: chunked. After calling the  w.(http.Flusher). Flush() method,  the client did not immediately receive the data, but waited until the entire response was finished before returning the data. The same code using the native net/http can return data in real-time.

 net/http:

```
func httpServer() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		flusher, ok := w.(http.Flusher)
		if !ok {
			panic("expected http.ResponseWriter to be an http.Flusher")
		}
		w.Header().Set("X-Content-Type-Options", "nosniff")
		for i := 1; i <= 20; i++ {
			tmp := NlpResp{
				MatchID: i,
				Audio:   "abc",
				Hai:     "data",
				Text:    "test",
			}
			marshal, err := json.Marshal(tmp)
			if err != nil {
				return
			}
			_, err = w.Write(marshal)
			if err != nil {
				log.Print(err)
				return
			}

			flusher.Flush() // Trigger "chunked" encoding and send a chunk...
			time.Sleep(1 * time.Second)
		}
	})

	log.Print("Listening on localhost:8080")
	log.Fatal(http.ListenAndServe("0.0.0.0:8888", nil))
}
```

**go-zero**
```go
func AudioHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		flusher, ok := w.(http.Flusher)
		if !ok {
			panic("expected http.ResponseWriter to be an http.Flusher")
		}
		w.Header().Set("X-Content-Type-Options", "nosniff")
		for i := 1; i <= 20; i++ {
			tmp := NlpResp{
				MatchID: i,
				Audio:   "aduio",
				Hai:     "data",
				Text:    "test",
			}
			marshal, err := json.Marshal(tmp)
			if err != nil {
				return
			}
			_, err = w.Write(marshal)
			if err != nil {

				return
			}
			flusher.Flush() // Trigger "chunked" encoding and send a chunk...
			time.Sleep(1 * time.Second)
		}
	}

}
```

**Environments (please complete the following information):**
 - OS: [Windows]
 - go-zero version [1.5.3]

**More description**

**Comment by anqiansong** [comment]
I have done a test, the two results are the same, and will not return immediately, only after the data is returned.

**Comment by linganmin** [comment]
> I have done a test, the two results are the same, and will not return immediately, only after the data is returned.

i hove similar case，you can try the following code， the case is SSE for goang and front code，but  until the entire response was finished before returning the data with gozero.


`
package main

import (
	"fmt"
	"net/http"
	"time"
)

func main() {
	http.HandleFunc("/stream", streamHandler)
	http.ListenAndServe(":8080", nil)
}

func streamHandler(w http.ResponseWriter, r *http.Request) {
	// 设置响应头，指定内容类型为text/event-stream
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	dataChan := make(chan string)
	doneChan := make(chan struct{})

	go generateData(dataChan, doneChan)

	for {
		select {
		case data, ok := <-dataChan:
			if !ok {
				return
			}

			// 构建SSE消息
			message := fmt.Sprintf("data: %s\n\n", data)
			// 发送SSE消息给客户端
			_, err := w.Write([]byte(message))
			if err != nil {
				return
			}

			// 刷新响应，确保消息立即发送到客户端
			if flusher, ok := w.(http.Flusher); ok {
				flusher.Flush()
			}
		case <-r.Context().Done():
			close(doneChan)
			return
		}
	}
}

func generateData(dataChan chan<- string, doneChan <-chan struct{}) {
	defer close(dataChan)

	for i := 1; i <= 10; i++ {
		select {
		case <-doneChan:
			return
		default:
			data := time.Now().Format(time.RFC3339)
			dataChan <- data
			time.Sleep(1 * time.Second)
		}
	}
}


`

`
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<head>
    <title>SSE Example</title>
</head>
<body>
<h1>SSE Example</h1>
<button id="startButton">开始</button>
<div id="output">回答：</div>
<script>
  const startButton = document.getElementById('startButton');
  const outputElement = document.getElementById('output');
  let eventSource;
  startButton.addEventListener('click', function() {
    if (!eventSource) {
        eventSource = new EventSource('http://127.0.0.1:8080/stream');
      eventSource.onmessage = function(event) {
        const message = event.data;
        outputElement.innerHTML += message;
      };
      eventSource.onerror = function(event) {
        console.error('Error: ' + event);
      };
      
      // 服务器定义了事件流：event:end，因此监听 :end 事件来结束 eventSource
      eventSource.addEventListener('end', function(event) {
        console.log('SSE 连接已关闭');
        eventSource.close();
      });
    }
  });
</script>
</body>
</html>



`

**Comment by u2nyakim** [comment]
哈喽，你们这个问题解决了吗？我今天也碰到了这个。

**Comment by linganmin** [comment]
> 哈喽，你们这个问题解决了吗？我今天也碰到了这个。

先把Timeout的中间件关掉了，临时解决一下

配置文件里


`
Middlewares:
  Timeout: False
`

**Comment by u2nyakim** [comment]
> > 哈喽，你们这个问题解决了吗？我今天也碰到了这个。
> 
> 先把Timeout的中间件关掉了，临时解决一下
> 
> 配置文件里
> 
> ```
> Middlewares:
>   Timeout: False
> ```

Thank you. I have modified the code for the framework and resolved this issue. 🥰

**Comment by kevwan** [comment]
Fixed.
