### ISSUE TITLE
Failed to deploy projects written in go-zero with docker-compose.

### ISSUE THREAD

**Issue by regboy8** [zeromicro/go-zero#3356]
go版本：1.20
错误信息:
`
[+] Building 31.8s (3/3) FINISHED                                                                                                      
 => [internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 807B                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                   0.0s
 => ERROR [internal] load metadata for docker.io/library/golang:1.20                                                             31.7s
------
 > [internal] load metadata for docker.io/library/golang:1.20:
------
failed to solve: golang:1.20: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ee/ee074dc439b820ee494a55e6221f065372fa14dc923d732fd0c434d4f0d4b4ea/data?verify=1686898423-K4WDiMDSR0sA%2F30rxOapsQjf%2Fl4%3D": dial tcp 104.18.121.25:443: i/o timeout

`

**Comment by Mikaelemmmm** [comment]
Is it convenient to give the contents of your dockerfile?
