### ISSUE TITLE
etcd error with required revision has been compacted

### ISSUE THREAD

**Issue by loop321** [zeromicro/go-zero#3364]
go-zero version: v1.4.4
etcd version:  v3.4.14
When go-zero's RPC is called, it consumes a lot of memory and the program reports the following error:
{"@timestamp":"2023-06-20T10:37:47.022+08:00","caller":"internal/registry.go:314","content":"etcd monitor chan has been canceled, error: etcdserver: mvcc: required revision has been compacted","level":"error"}

How should solve this problem? thinks!

**Comment by re-dylan** [comment]
This is an issue with Etcd. 
Please check https://github.com/etcd-io/etcd/issues/10450

**Comment by loop321** [comment]
Thank you, we will optimize the configuration of etcd first and observe for a while. 
In addition, when the error occurs, it may cause an infinite loop and memory leak , Apart from the problem with etcd, it may be related to this code segment:    discov/internal/registry.go:

```
for {
    if c.watchStream(cli, key, rev) {
        return
    }
}
```

**Comment by loop321** [comment]
@re-dylan Thank you, we will optimize the configuration of etcd first and observe for a while.
In addition, when the error occurs, it may cause an infinite loop and memory leak , Apart from the problem with etcd, it may be related to this code segment: discov/internal/registry.go:
```
for {
    if c.watchStream(cli, key, rev) {
        return
    }
}
```
