### ISSUE TITLE
The httpc.Do method automatically adds a newline character after the request body.

### ISSUE THREAD

**Issue by kevin0527** [zeromicro/go-zero#3372]
**Describe the bug**
The `httpc.Do` method automatically adds a newline character after the request body.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

client code:
   ```go
   package main

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"

	"github.com/zeromicro/go-zero/rest/httpc"
)

type Foo struct {
	A int `json:"a"`
	B int `json:"b"`
}

func main() {
	bs, _ := json.Marshal(Foo{A: 1, B: 2})
	http.Post("http://localhost:8080/post", "application/json", bytes.NewBuffer(bs))
	httpc.Do(context.Background(), http.MethodPost, "http://localhost:8080/post", Foo{A: 3, B: 4})
}
   ```

server code:
```go
package main

import (
	"fmt"
	"io"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.POST("/post", func(c *gin.Context) {
		bs, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.JSON(500, err.Error())
			return
		}
		fmt.Println("req body:", string(bs))
		c.JSON(200, "ok")
	})
	r.Run(":8080")
}
```

2. The error is
![image](https://github.com/zeromicro/go-zero/assets/6269347/ca92e24d-371c-4d9d-9d7d-29204dab2bbb)

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. macOS]
 - go-zero version [1.5.3]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by chenquan** [comment]
`json` automatically inserts the newline character:

https://github.com/zeromicro/go-zero/blob/92e5819e9120e11361f89d2cdb0224d48327fe73/rest/httpc/requests.go#L93

https://github.com/golang/go/blob/a031f4ef83edc132d5f49382bfef491161de2476/src/encoding/json/stream.go#L201-L220

**Comment by kevin0527** [comment]
This can potentially cause an issue: If the client directly uses json.Marshal to serialize the request body for signature calculation, it will result in different signatures being computed on the client and server sides.

**Comment by chenquan** [comment]
> This can potentially cause an issue: If the client directly uses json.Marshal to serialize the request body for signature calculation, it will result in different signatures being computed on the client and server sides.

Replacing the following code with `json.Marshal` will also have the same problem.
https://github.com/zeromicro/go-zero/blob/f296c182f78e743af2291b564a4b6b48628547bf/rest/httpc/requests.go#L92-L93

**Comment by kevin0527** [comment]
> > This can potentially cause an issue: If the client directly uses json.Marshal to serialize the request body for signature calculation, it will result in different signatures being computed on the client and server sides.
> 
> Replacing the following code with `json.Marshal` will also have the same problem.
> 
> https://github.com/zeromicro/go-zero/blob/f296c182f78e743af2291b564a4b6b48628547bf/rest/httpc/requests.go#L92-L93

So it ultimately depends on how the user chooses. If they opt to use `httpc.Do`, then they must use the approach `json.NewEncoder(&buf).Encode(jsonVars)` to retrieve the request body's content for signature calculation.
