### ISSUE TITLE
Generating API code from the remote template in the new version has an error.

### ISSUE THREAD

**Issue by xmwilldo** [zeromicro/go-zero#3374]
**To Reproduce**
Steps to reproduce the behavior, if applicable:

![uTools_1687743939498](https://github.com/zeromicro/go-zero/assets/16560252/88f52ec3-7aab-451b-92b8-71b6e988ff48)

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: Linux
 - go-zero version: 1.5.3
 - goctl version: 1.5.3

**Comment by Mikaelemmmm** [comment]
Please try it with the master version
eg :  go install github.com/zeromicro/go-zero/tools/goctl@master
