### ISSUE TITLE
只要使用 w.(http.Flusher).Flush()，response header就会被重置

### ISSUE THREAD

**Issue by tqqya** [zeromicro/go-zero#3375]
![image](https://github.com/zeromicro/go-zero/assets/89236571/4cf847e2-cc45-4502-812b-c1ac23978617)
如图，只要使用了w.(http.Flusher).Flush()，response header就会被重置
![image](https://github.com/zeromicro/go-zero/assets/89236571/32538b40-133c-4649-b660-157fdeb1010a)

请求大佬们解决

**Comment by anyoptional** [comment]
It seems that timeoutWriter should use a copy of original http headers, I'll test it.

**Comment by anyoptional** [comment]
w.(http.Flusher).Flush() leads underlying http.ResponseWriter calls #Write(...), which calls
#WriteHeader(...) implicitly. As http.ResponseWriter's doc says, changing the header map after
a call to WriteHeader (or Write) has no effect. Dive deep into TimeoutHandler implementation,
it copies timeoutWriter's header into underlying http.ResponseWriter's header when receiving a done
signal, at that point a Flush call is made, so the copy has no effect. Solotion is copy header when 
calling timeoutWriter's #WriteHeader(...) method, which keeps underlying  http.ResponseWriter's header
in sync. @kevwan @tqqya

**Comment by yuetchn** [comment]
I have also encountered the same problem, how should I solve it?

**Comment by kevwan** [comment]
Fixed.
