### ISSUE TITLE
mark flow

### ISSUE THREAD

**Issue by LeeDF** [zeromicro/go-zero#3379]
want feature like:
1.  set http header mark flow, like header: flow-color: flow1
2.  set some label when service  register, like zrpc.NewServer({"flow-color": "flow1"})
3.  zrpc load balance support custom selector, i can select the service with label flow1

**Comment by chenquan** [comment]
Reference: https://github.com/chenquan/zero-flow

**Comment by LeeDF** [comment]
> Reference: https://github.com/chenquan/zero-flow

why not merge to this repo

**Comment by chenquan** [comment]
> > Reference: https://github.com/chenquan/zero-flow
> 
> good implement，set tag with url query， why not merge to this repo

This implementation is disruptive and needs further optimization.

**Comment by LeeDF** [comment]
> > > Reference: https://github.com/chenquan/zero-flow
> > 
> > 
> > good implement，set tag with url query， why not merge to this repo
> 
> This implementation is disruptive and needs further optimization.

ok, expect
