### ISSUE TITLE
The file generated when model has unique key is incorrect

### ISSUE THREAD

**Issue by xmwilldo** [zeromicro/go-zero#3380]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:
when model has  unique key 
![uTools_1687938889104](https://github.com/zeromicro/go-zero/assets/16560252/17bd64c1-cbab-4e07-9eb4-20319f7b8a76)

when model not has unique key
![uTools_1687938957909](https://github.com/zeromicro/go-zero/assets/16560252/2ab4eefd-068c-42e8-839c-db510e8d094d)

why newData ???????

**Expected behavior**
newData  -> data

**Environments (please complete the following information):**
 - OS:  Linux
 - go-zero version: 1.5.3
 - goctl version: 1.5.3

**Comment by KesonAn** [comment]
When there is a unique index, the historical data will be queried, and the unique index cache of the historical data will be deleted, mainly to ensure cache consistency.

**Comment by xmwilldo** [comment]
got it, thanks
