### ISSUE TITLE
Does gozero redis have a good way to store an object with a hash type

### ISSUE THREAD

**Issue by yuff20** [zeromicro/go-zero#3390]
gozero's built-in Redis-wrapped hmset can only handle map[string]string data

Now an object to store hash data structure, is there a better way to handle it?
![image](https://github.com/zeromicro/go-zero/assets/19644886/0d7063e4-e50b-4cc3-96bd-36cec1dffd62)

**Comment by kevwan** [comment]
Would you please submit a PR?

**Comment by PittYao** [comment]
> Would you please submit a PR?

Just change map[string]string to map[string]interface{}.all right?
![image](https://github.com/zeromicro/go-zero/assets/26101917/f55dc665-431c-4561-9b7c-d32f391950b0)
