### ISSUE TITLE
goctl api format can't find dependencies in the same directory.

### ISSUE THREAD

**Issue by guaosi** [zeromicro/go-zero#3392]
**Describe the bug**

用goctl api go -api 生成的时候，.api可以找到有些type在同文件夹下其他.api文件里的。但是我用 goctl api format 去格式化api文件的时候，他就找不到依赖了，会报type没有定义。是我使用的姿势不对吗

例如，存在A、B、C三个type,A跟B位于 x.api , C依赖到A且C位于xxx.api文件，此时 `goctl api go -api `生成命令正常且不报错，`goctl api format -dir.` 此时会报` x.api,can not found declaration 'A' in context`

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```shell
   goctl api format -dir .
   ```

2. The error is

   ```
   xxx.api, /path/api/proto/xxx.api line 14:2 can not found declaration 'XXX' in context
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: Ubuntu20.04
 - go-zero version 1.3.3
 - goctl version 1.3.3

**More description**

**Comment by chenquan** [comment]
Please Show your `.api` file.

**Comment by chenquan** [comment]
Please show your `.api` file.

**Comment by KesonAn** [comment]
According to the [documentation](https://go-zero.dev/docs/tutorials/api/faq#1-%E6%80%8E%E4%B9%88%E4%BD%93%E9%AA%8C%E6%96%B0%E7%9A%84-api-%E7%89%B9%E6%80%A7), open the preview the new version of the parser, and then call `goctl api format` to format the code
