### ISSUE TITLE
bulkinsert does not support doaller placeholders

### ISSUE THREAD

**Issue by fiecato** [zeromicro/go-zero#3394]
### What category of issue (<code>goctl</code> or <code>sdk</code>)?
**sdk**

the source code in `core/stores/sqlx/bulkinserter.go`
``` golang
func parseInsertStmt(stmt string) (bulkStmt, error) {
        ...
	var variables int
	var valueFormat string
	var suffix string
	left := strings.IndexByte(lower[pos:], '(')
	if left > 0 {
		right = strings.IndexByte(lower[pos+left:], ')')
		if right > 0 {
			values := lower[pos+left : pos+left+right]
			for _, x := range values {
				if x == '?' {
					variables++
				}
			}
			valueFormat = stmt[pos+left : pos+left+right+1]
			suffix = strings.TrimSpace(stmt[pos+left+right+1:])
		}
	}

	if variables == 0 {
		return emptyBulkStmt, fmt.Errorf("no variables: %q", stmt)
	}
        ....
}
```

### What type of issue (<code>feature</code>|<code>bug</code>|<code>suggestion</code>)?
Maybe a **bug**. I am not sure

When calculating `variables` in `parseInsertStmt`, only the mysql placeholder `?` is judged, and the postgresql placeholder `$` is not judged, resulting in 
```
no variables: \"insert into \\\"org\\\".\\\"role_user\\\" (created_at,updated_at,role_id,user_id) values ($1, $2, $3, $4)\"
```

### What version of Goctl are you using (<code>goctl --version</code>)?

<pre>
$ goctl --version
1.4.4
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using ?
<pre>
ARCH = "arm64"
GOCTL_VERSION = "1.4.4"
GO_VERSION = "go1.20.2"
OS = "darwin"
</pre>

### What did you do?

[demo](https://go.dev/play/p/yArCjNLCKqd) but need redis

**Comment by kevwan** [comment]
Verified in v1.5.3?

**Comment by fiecato** [comment]
> Verified in v1.5.3?

Yes. error still exists。

```
no variables: \"insert into \\\"org\\\".\\\"role_user\\\" (created_at,updated_at,role_id,user_id) values ($1, $2, $3, $4)\"
```

**Comment by kevwan** [comment]
Just use `?` instead of `$x`.

**Comment by fiecato** [comment]
> Just use `?` instead of `$x`.

Oh, I forgot to say, I use `postgresql`

**Comment by fiecato** [comment]
> Just use `?` instead of `$x`.

You mean `postgresql` also use `?` as placeholder in bulk insert?
