### ISSUE TITLE
希望继续完善文档，虽然本次文档改动有进步但是还是不够详细，对于新手来说用起来很不友好

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#3398]

**Comment by KesonAn** [comment]
Thank you for suggestion, the documentation cannot be aimed at all novices. Everyone has different foundations and the level of novices is different. We welcome participation in documentation contributions to improve together.

**Comment by kevwan** [comment]
Thanks! Got it. We have put lots of work on the docs and will keep going.
