### ISSUE TITLE
goctl model pg gen postgresql not ignore create_time update_time in insert func

### ISSUE THREAD

**Issue by puyongcl** [zeromicro/go-zero#3404]
insert.go
-- if camel == "CreateTime" || camel == "UpdateTime" || camel == "CreateAt" || camel == "UpdateAt" {
++ if table.isIgnoreColumns(field.Name.Source()) {

cmd.go
in pg cmd arg not have init isIgnoreColumns

so ignore not work

**Comment by kesonan** [comment]
it will be optimized on #3427
