### ISSUE TITLE
How to generate model with session with goctl model?

### ISSUE THREAD

**Issue by Marsanor** [zeromicro/go-zero#3411]
```
type (

	userModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByMobile(ctx context.Context, mobile string) (*User, error)
		Update(ctx context.Context, session sqlx.Session, data *User) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *User) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}
}
```

**Comment by MarkJoyMa** [comment]
You can refer to the template of goctl to define your own model template.
https://go-zero.dev/docs/tutorials/cli/template

**Comment by Marsanor** [comment]
I have modified the insert template in the model. Although the desired method has been generated, the parameters in the corresponding interface of the method are still the default parameters. How can I modify the method input parameters in the jtype interface？

> You can refer to the template of goctl to define your own model template. https://go-zero.dev/docs/tutorials/cli/template
