### ISSUE TITLE
should we return error if usingDifferentKeys is true

### ISSUE THREAD

**Issue by 781778304** [zeromicro/go-zero#3415]
processField func in core\mapping\unmarshaler.go
```
func (u *Unmarshaler) processField(field reflect.StructField, value reflect.Value, m Valuer,
	fullName string) error {
	...
	if usingDifferentKeys(u.key, field) {
		return nil
	}
	...
}
```
why we return nil when `usingDifferentKeys `returns true? No parameter will be parsed successfully if programmer using the wrong struct tag.

**Comment by MarkJoyMa** [comment]
When the tag and field are inconsistent, recursive parsing will not be performed. If mandatory inspection is required, the configuration of tag default and optional will not be performed.
