### ISSUE TITLE
When using goctl, one .api import another .api with wrong path, wrong path is generated with goctl api plugin -p

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#3419]
goctl api plugin -p zero-swagger="swagger -filename advertise.json" --api="advertise.api" --dir .对应的advertise.api引入其他.api就会出现/Users/li/Documents/go/gopath/src/bot/service/gateway/admin/api/v0/advertise/v0/common/public.api找不到，真实路径应该是/Users/li/Documents/go/gopath/src/bot/service/gateway/admin/api/v0/common/public.api代码问题在tools/goctl/api/parser/parser.go的parsedApi, err := astParser.Parse(filename)

**Comment by kesonan** [comment]
it was resolved on https://github.com/zeromicro/goctl-go-compact/pull/13
