### ISSUE TITLE
How to get all the api routes and methods in logic?

### ISSUE THREAD

**Issue by yudan215** [zeromicro/go-zero#3447]
go-zero如何在logic获取所有api地址和请求方法

求指点迷津～！

**Comment by smithyj** [comment]
Context 注入

**Comment by kevwan** [comment]
What's the scenarios that you need this feature?

**Comment by yudan215** [comment]
> What's the scenarios that you need this feature?

想在接口把对应的api和请求方法·还有在api设置的doc中文返回，用户可以使用选择的方式选择某些角色需要用到哪些接口

**Comment by yudan215** [comment]
> Context 注入

请问是否有demo
