### ISSUE TITLE
请教etcd连接错误的问题

### ISSUE THREAD

**Issue by gzlboy** [zeromicro/go-zero#3448]
etcd是跑在k8s中通过nodeport暴露出来的，测试发现go-zero rpc项目跑起来后，有注册到etcd中(可以看到key)，
![微信图片_20230728094135](https://github.com/zeromicro/go-zero/assets/1492060/716289a9-3792-49cc-bb6d-51bacada13c1)
但没过一会，控制台就会报错：

{"level":"warn","ts":"2023-07-28T10:35:11.907167+0800","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000632000/192.168.1.125:30279",
"attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp: lookup apisix-release-etcd-0.apisix-release-etc
d-headless.default.svc.cluster.local: no such host\""}

{"level":"info","ts":"2023-07-28T10:36:16.909427+0800","logger":"etcd-client","caller":"v3@v3.5.9/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}

注： apisix-release-etcd-0.apisix-release-etcd-headless.default.svc.cluster.local是之前安装apisix一起安装etcd时注册的svc，我也奇怪为何go-zero会对这个内网service发起请求？

报错之后没多久，在etcd中的key就不见了，也就是go-zero rpc项目下线了，请问可能是什么原因呀？

附配置：
![微信图片_20230728104158](https://github.com/zeromicro/go-zero/assets/1492060/5f7f7ab9-62af-4115-a701-b46b84a6e870)
注：
30279是etcd在k8s中暴露出来的nodeport

使用的go-zero版本是v1.5.4

**Comment by Notmeor** [comment]
遇到同样问题， 请问如何解决的？

**Comment by suguer** [comment]
所以这个问题有解决么,我也遇到过
