### ISSUE TITLE
I use goctl api go. API path contains .

### ISSUE THREAD

**Issue by zxc941615** [zeromicro/go-zero#3450]
I have a .api file like the image below.
when I use `goctl api go` to create a new api service. it will return error.
Any possible that I can contain `.` in the API path?
<img width="568" alt="截圖 2023-07-28 下午5 54 46" src="https://github.com/zeromicro/go-zero/assets/49036455/a2337030-3506-465b-87bc-2dc7f4907dc2">

**Comment by kesonan** [comment]
The request path needs to satisfy the routing rules, please refer to https://go-zero.dev/docs/tutorials/api/route/rule for details.
