### ISSUE TITLE
In the api file, using `any` instead of `interface {}`  report an error

### ISSUE THREAD

**Issue by anyone0034** [zeromicro/go-zero#3455]
**Describe the bug**
In the api file, using `any` instead of `interface {}`  report an error

1. The code is

   ```go
       PageHomeResp{
        PageConfig map[string]interface{} `json:"page_config"`
        PageConfig2 map[string]any `json:"page_config"`            //  report error
    }
   ```

2. The error is

   ```
    can not found declaration 'any' in context
   ```

**Environments (please complete the following information):**
 - OS: windows
 - go-zero version [e.g. 1.2.1]:1.5.2
 - goctl version [e.g. 1.2.1, optional]:1.20.2

**Comment by smithyj** [comment]
update goctl and go-zero

**Comment by Mikaelemmmm** [comment]
goctl currently does not support any in the generated struct.

**Comment by kevwan** [comment]
`interface{}` doesn't work as well.
