### ISSUE TITLE
Prompt problems of the API files in goland.

### ISSUE THREAD

**Issue by foolishlittlefox** [zeromicro/go-zero#3458]
@server(
    ...
    maxBytes: 1048576
)

在 goland 的ide中会报语法错误
mismatched input '1048576' expecting {PATH, DURATION, IDENT}
请问如何处理

**Comment by chenquan** [comment]
Please upgrade `goctl` to the latest version.

**Comment by foolishlittlefox** [comment]
> Please upgrade `goctl` to the latest version.

goctl 1.1.4 已经是最新版的,没用

**Comment by foolishlittlefox** [comment]
> Please upgrade `goctl` to the latest version.
插件版本 goctl 1.1.4
 命令版本 goctl version 1.5.4 darwin/amd64
mac的

**Comment by chenquan** [comment]
Try using the terminal to execute the command.

**Comment by kevwan** [comment]
> > Please upgrade `goctl` to the latest version.
> 
> goctl 1.1.4 已经是最新版的,没用

goctl v1.5.4 is the latest version.

**Comment by kesonan** [comment]
This is a bug in the goland intellij plugin, please forward this issue to https://github.com/zeromicro/goctl-intellij
