### ISSUE TITLE
Document description Error

### ISSUE THREAD

**Issue by longsizhuo** [zeromicro/go-zero#3466]
**Describe the bug**
in [Document](https://go-zero.dev/docs/tasks/cli/grpc-demo) `Write simple logic code` part we can find the `we can find ~/workspace/api/demo/internal/logic/demologic.go files` sentence, but there's not `demologic.go` file in any folders insteal of `demoserver.go`.
**Screenshots**
<img width="780" alt="image" src="https://github.com/zeromicro/go-zero/assets/114939201/ec1df147-ef78-405e-ab88-cb2ea6d2e185">

**Comment by kesonan** [comment]
Thanks for the feedback, the document was written incorrectly, the document has been fixed, the correct value is `~/workspace/rpc/demo/internal/logic/pinglogic.go`

**Comment by longsizhuo** [comment]
> Thanks for the feedback, the document was written incorrectly, the document has been fixed, the correct value is `~/workspace/rpc/demo/internal/logic/pinglogic.go`

ok
