### ISSUE TITLE
Dot(.) char is not working in HTTP GET query tags.

### ISSUE THREAD

**Issue by c1pyerten** [zeromicro/go-zero#3478]
Api file description:
```
type Req {
	ClaimId string `form:"openid.claim_id"`
	Ns string `form:"openid.ns"`
}
```

Generated struct:
```
type Req struct {
	ClaimId string `form:"openid.claim_id"`
	Ns      string `form:"openid.ns"`
}
```

Request called:
`curl localhost:8888/test?openid.claim_id=xx&openid.ns=123`

Cant parse fields tagged with dot(.).

**Comment by kevwan** [comment]
Because `.` is used to find the nested values, like below:

```go
ClaimId string `form:"openid.claim_id"`
```

go-zero parses the value from the map like below:

```go
map[string]any{
    "openid": map[string]any{
          "claim_id": "the-id",
    },
}
```

**Comment by kevwan** [comment]
@c1pyerten Please verify the problem with the code from my PR.

**Comment by kevwan** [comment]
Fixed.
