### ISSUE TITLE
When goctl generates rpc, can we add a mock rpc？

### ISSUE THREAD

**Issue by liuxianloveqiqi** [zeromicro/go-zero#3480]
When goctl generates rpc, can we add a **mock** rpc？, because in the team development, a service depends on other rpc, but because the other rpc is not registered, the service can not be started, so can we generate a **mock** rpc like this, which returns the default fake data

**Comment by kevwan** [comment]
We're working on this feature. Will be released soon.

**Comment by gzlboy** [comment]
Looking forward to this feature！
