### ISSUE TITLE
How to define the Query and JSION requests in API ？Which tag could I use?

### ISSUE THREAD

**Issue by Marsanor** [zeromicro/go-zero#3486]
POST /online_status?appKey=someappKey&timestamp=1408710653491&nonce=14314&signature=45beb7cc7307889a8e711219a47b7cf6a5b000e8 HTTP/1.1
Host: example.com
Content-Type: application/json

[
  {
    "userid": "apert60541",
    "status": "1",
    "os": "iOS",
    "time": 1437982625625,
    "clientIp":"172.20.10.94:41748",
    "sessionId":"0O6Bvfvik_L9R_NxR6GqQb"
  },
  {
    "userid": "apert60592",
    "status": "1",
    "os": "Android",
    "time": 1437982625625,
    "clientIp":"172.20.10.94:41748",
    "sessionId":"0O9Fvfvik_L9R_NaR3GqYz"
  },
  {
    "userid": "apert60533",
    "status": "2",
    "os": "Android",
    "time": 1437982625625,
    "clientIp":"172.20.10.94:41748",
    "sessionId":"0O4Hvfvik_L3B_XaR7GxAf"
  }
]

**Comment by chenquan** [comment]
You can use  `form` and `json`.
