### ISSUE TITLE
An issue regarding the redirection of log output with logx.

### ISSUE THREAD

**Issue by ZTaboo** [zeromicro/go-zero#3488]
After creating the API, using the following code results in successful output to Kafka:
```go

type KafkaWriter struct {
	Pusher *kq.Pusher
}

func (w *KafkaWriter) Write(p []byte) (n int, err error) {
	err = w.Pusher.Push(strings.TrimSpace(string(p)))
	if err != nil {
		return 0, err
	}
	return len(p), nil
}

func newKafkaWriter(pusher *kq.Pusher) *KafkaWriter {
	return &KafkaWriter{
		Pusher: pusher,
	}
}

func initLog(in *KafkaWriter) {
	logx.SetWriter(logx.NewWriter(in))
	in.Pusher.Push("api")
}
```
However, directly using logx.SetWriter within the RPC service seems ineffective; it requires MustSetup to be applied first for proper output:
```go
func initLog(in *KafkaWriter) {
	in.Pusher.Push("user")
	var cfg logc.LogConf
	_ = conf.FillDefault(&cfg)
	logx.MustSetup(cfg)
	logx.SetWriter(logx.NewWriter(in))
}
```
I'm not sure if this is a bug. Are there any experts who are familiar with this issue?

**Comment by chenquan** [comment]
Hi! Can you provide a complete code case?

**Comment by ZTaboo** [comment]
> Hi! Can you provide a complete code case?

The second part of the code is where it differs from the first part. The difference lies in the initLog function. In the second part (RPC service), using setWriter directly for logx output redirection doesn't result in a successful reset, while in the API section it works.
