### ISSUE TITLE
Can the original redis client be exposed?

### ISSUE THREAD

**Issue by relxet** [zeromicro/go-zero#3539]
I want to use the original redis client initialized by gozero, because a hook has been added, and the trace is in this hook

**Comment by relxet** [comment]
> You can just use `redis.New(...)`, the underlying connections are shared.

i mean the v8 Client and ClusterClient

**Comment by kevwan** [comment]
We're not going to expose v8 clients.

We're planning to upgrade to v9, if we exposed the v8 clients, we cannot keep the compatibility, and the client code should be changed after the release.
