### ISSUE TITLE
goctl api go error  when go 1.21.0 in go.mod

### ISSUE THREAD

**Issue by edieruby** [zeromicro/go-zero#3540]
when go 1.21.0 in go.mod
goctl api go error occur:
Error: go: go.mod already exists

change to go 1.18 in go.mod
goctl api go is okay.

**Comment by edieruby** [comment]
It seems that
go x.y.z not support
go x.y support

**Comment by relxet** [comment]
This is because you used go work, add the current project to go work and try again

**Comment by edieruby** [comment]
> This is because you used go work, add the current project to go work and try again

not used go work.
just change to go 1.18 in go.mod
the command works

**Comment by kesonan** [comment]
Please change to version go1.21.0, and then execute the following command in the same directory specified by `goctl api go`, and observe the result?
```shell
go list -m -f {{.GoMod}}
```

**Comment by edieruby** [comment]
> Please change to version go1.21.0, and then execute the following command in the same directory specified by `goctl api go`, and observe the result?
> 
> ```shell
> go list -m -f {{.GoMod}}
> ```

Thank you.
1.21.0 is installed by install multiple versions of Go 
current go is still 1.20.6
goctl use go 1.20.6, it doesn't support x.y.z

**Comment by relxet** [comment]
> > Please change to version go1.21.0, and then execute the following command in the same directory specified by `goctl api go`, and observe the result?
> > ```shell
> > go list -m -f {{.GoMod}}
> > ```
> 
> Thank you. 1.21.0 is installed by install multiple versions of Go current go is still 1.20.6 goctl use go 1.20.6, it doesn't support x.y.z

it support x.y.z

just run ```go work use <project_dir>`` to add this project

**Comment by relxet** [comment]
i think it seems like a bug, i am not sure if it is a gozero bug or not?
 i also use go 1.21.0 and have this problem. add this project to go work and the problem is fixed.

**Comment by edieruby** [comment]
> i think it seems like a bug, i am not sure if it is a gozero bug or not? i also use go 1.21.0 and have this problem. add this project to go work and the problem is fixed.


It's the problem of my environment. Not BUG.
installed multiple go version.

My default cmd go -> go 1.20.6
                   cmd go1.21.0 -> go 1.21.0
When run goctl , it uses my default go.
go 1.20.6 not suppot go x.y.z in the go.mod.

**Comment by relxet** [comment]
i also have this problem,so i think its not your problem 🤣
