### ISSUE TITLE
Can add a middleware that supports single routing

### ISSUE THREAD

**Issue by xjl12322** [zeromicro/go-zero#3548]
So I need to split multiple routing groups. I just want to specify an interface under the same routing group that requires jwt verification. Other interfaces do not need to
For example in the following example, I need the add, getById method jwt check。No other method is needed
@server(
	prefix: book/v1
	group: book
)
service book-api{
	jwt: JwtAuth
	@handler add
	post /add (AddBookReq) returns (AddBookResp)
	jwt: JwtAuth
	@handler getById
	get /get(GetBookByIdReq) returns (GetBookByIdResp)
	@handler getByIdList
	post /getIdList(GetBookByIdListReq) returns (GetBookByIdListResp)`` }`

**Comment by kevwan** [comment]
Sure, you can separate the jwt related routes from others in API file.

**Comment by xjl12322** [comment]
So I need to split multiple routing groups.  I just want to specify an interface under the same routing group that requires jwt verification.  Other interfaces do not need to
For example in the following example, I need the add, getById method jwt check。No other method is needed
`@server(
	prefix: book/v1
	group: book
)
service book-api{
	@doc(
		description: "添加"
		summary: "添加"
	)
	jwt: JwtAuth
	@handler add
	post /add (AddBookReq) returns (AddBookResp)
	@doc(
		description: "id获取"
		summary: "id获取"
	)
	jwt: JwtAuth
	@handler getById
	get /get(GetBookByIdReq) returns (GetBookByIdResp)
	@doc(
		description: "idlist获取"
		summary: "idlist获取"
	)
	@handler getByIdList
	post /getIdList(GetBookByIdListReq) returns (GetBookByIdListResp)`

**Comment by xjl12322** [comment]
> Sure, you can separate the jwt related routes from others in API file.

So I need to split multiple routing groups.  I just want to specify an interface under the same routing group that requires jwt verification.  Other interfaces do not need to
For example in the following example, I need the add, getById method jwt check。No other method is needed
`@server(`
`	prefix: book/v1`
`	group: book`
`)`
`service book-api{`
`	jwt: JwtAuth`
`	@handler add`
`	post /add (AddBookReq) returns (AddBookResp)`
`	jwt: JwtAuth`
`	@handler getById`
`	get /get(GetBookByIdReq) returns (GetBookByIdResp)`
`	@handler getByIdList`
`	post /getIdList(GetBookByIdListReq) returns (GetBookByIdListResp)``
`}`
