### ISSUE TITLE
using datetime field under the model: Unable to query anything

### ISSUE THREAD

**Issue by daifuyang** [zeromicro/go-zero#3549]
**Describe the bug**
How to use a datetime field under the 'model'? I can't query anything. Can you help me?

**To Reproduce**
select `id`,`name`,`voice`,`desc`,`sample_rate_hertz`,`voice_type`,`words_per_minute`,`gender`,`status`,`created_at`,`updated_at`,`deleted_at` from `voice` where deleted_at = ?

? = 0

has no data

select `id`,`name`,`voice`,`desc`,`sample_rate_hertz`,`voice_type`,`words_per_minute`,`gender`,`status`,`created_at`,`updated_at`,`deleted_at` from `voice` where deleted_at = 0
has data list 

**Expected behavior**

**Screenshots**
![image](https://github.com/zeromicro/go-zero/assets/19951467/de390d81-eedc-450a-848a-309bd6e76393)

**Environments (please complete the following information):**
 - OS: [e.g. macos]
 - go-zero version [e.g. 1.5.5]
 - goctl version [e.g. 1.5.5]

**Comment by klen-ygs** [comment]
Add parseTime=true“ in the end of mysql connection string.
