### ISSUE TITLE
Optimization Of Go-zero LogConf

### ISSUE THREAD

**Issue by guoshengfei** [zeromicro/go-zero#3552]
**Describe the bug**
When the configuration log is split in file mode and by size, the original file continues to be written after the service is restarted until the rewrite size is configured to be re-split.

**Expected behavior**
Restarting the service does not affect the log to split by size

**Environments (please complete the following information):**
 - OS: [ubuntu 22.04]
 - go-zero version [1.4.0]

**Comment by kevwan** [comment]
I'll work on it.

**Comment by guoshengfei** [comment]
cool man
发自我的 iPhone

在 2023年9月21日，22:22，Kevin Wan ***@***.***> 写道：

﻿

I'll work on it.
