### ISSUE TITLE
logx.Infof causes go GC when log level is used to suppress the logs.

### ISSUE THREAD

**Issue by 19910211** [zeromicro/go-zero#3571]
logx.Infof  等函数在 logLevel  等级较高时 比如errorLevel，
 会参数大量的无效的string 造成内存膨胀，导致频繁GC。
   程序是fmt.Sprintf(format, v...)后再 判断 是否打印
   建议可以在相应的logx 日志文件调用之前，有一个函数判断一些是否可以调用当前日志级别的函数
if  isdebug() {
      l.debugf(format string, v ...any)
}

建议这个 IsDebug() 等函数还可以暴露到包外面
if logx.IsDebug(){
           logx.Debugf(format string, v ...any)
}

**Comment by 19910211** [comment]
我的使用的版本是 最新的1.5.5版本的，如果我用的 errorLevel 级别， l *richLogger) Infof 函数中  fmt.Sprintf(format, v...) 会执行， 但这其实是多余的动作， 而且这些 变量还会逃逸到堆中，在代码中肯定会有大量的 debug 级别的日志
![1695612860951](https://github.com/zeromicro/go-zero/assets/27328836/da81f94a-ef8c-4047-b441-e26e7f69957c)
![1695612899580](https://github.com/zeromicro/go-zero/assets/27328836/9faefc23-fb0f-42d8-8074-47ac0e4686fc)

**Comment by kevwan** [comment]
@19910211 Please help to review the PR. Thanks!
