### ISSUE TITLE
How to turn off the breaker middleware?

### ISSUE THREAD

**Issue by lidaqi001** [zeromicro/go-zero#3580]
How to turn off the breaker middleware?

I have a need to import 10,000 pieces of data, and I always get an error "circuit breaker is open" when executing the task.

**Comment by lidaqi001** [comment]
The database used is mongodb, and the break point is an error returned by mongo

Using the mongo package that comes with the framework "github.com/zeromicro/go-zero/core/stores/monc"

**Comment by kevwan** [comment]
I recommend you'd better dig into why the errors happened, which cause circuit breaker to protect the successive requests. Not just disable breaker itself.
