### ISSUE TITLE
Need better documents.

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#3583]
强烈建议官方文档能向goframe那样好好的去打磨，完全可以照着goframe抄啊。目前来说文档阻碍性太大太大了，希望能向goframe那样条理清晰、模块明确。让人看了一目了然

**Comment by zhenhua1** [comment]
发现咱们的go-zero官网弄出来就不管理，没有更新，也没有框架新增的功能去加入到文档中

**Comment by kevwan** [comment]
All documents are here. Would you please contribute to improve it? Thanks!

**Comment by kevwan** [comment]
Closing for now, reopen if needed. Thanks!

**Comment by CaiCandong** [comment]
> All documents are here. Would you please contribute to improve it? Thanks!

We need more contributors and PRs. Many open-source projects close because the author is the only one who maintains them.

**Comment by kevwan** [comment]
We have lots of contributors, not only go-zero repo, but also the document repo `portal`.

We've made 3 times rewriting of the documentation. But we still need more contributors and put more effects on the doc.

And you're definitely welcome. Thanks!
