### ISSUE TITLE
v1.5.6 reports it's version as v1.5.5

### ISSUE THREAD

**Issue by p-linnane** [zeromicro/go-zero#3595]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v1.5.6 of goctl, we noticed the version is still being reported as v1.5.5. This is causing our tests to fail due to the version mismatch.

Relates to https://github.com/Homebrew/homebrew-core/pull/146343

**Comment by kevwan** [comment]
Thanks for your reporting!

Sorry for the inconvinience! I drafted the relase and then updated ther goctl version, I guess it's not updated when I release goctl.

I'm not sure how to fix the issue. Would you please give some advises?

We're in a national holiday, sorry for the delayed reply.

**Comment by p-linnane** [comment]
The best thing to do would be to fix the version and make a new release.

**Comment by p-linnane** [comment]
The issue is that this commit did not make it into the v1.5.6 tag: https://github.com/zeromicro/go-zero/commit/4878f90546fa3c744a9c5acec9308dec87454bc2.

The v1.5.6 tag is this commit: https://github.com/zeromicro/go-zero/commit/421e6617b16bc576e9ce3e8bf7d0405d8fbd04d9

**Comment by p-linnane** [comment]
I see now that you cut releases specifically for goctl, separate from the main tag. Switching to use that specific release fixed our issue. Thank you!

**Comment by kevwan** [comment]
> I see now that you cut releases specifically for goctl, separate from the main tag. Switching to use that specific release fixed our issue. Thank you!

Awesome! Thank you very much!
