### ISSUE TITLE
v1.5.6: zip: not a valid zip file

### ISSUE THREAD

**Issue by May-Yaha** [zeromicro/go-zero#3608]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
![image](https://github.com/zeromicro/go-zero/assets/17535606/4944161d-66e2-451a-8253-382a0626bcfc)

   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: MacOS M1   14.0.1
 - go-zero version latest 1.5.6
 - goctl version 1.5.6

**More description**

**Comment by kevwan** [comment]
I guess you might got a network problem?

<img width="341" alt="image" src="https://github.com/zeromicro/go-zero/assets/1918356/50c74b79-ea21-4395-a001-133b30b91093">

**Comment by kevwan** [comment]
Answered, closing.

If more questions, please reopen it.
