### ISSUE TITLE
Where is go.mod generated?

### ISSUE THREAD

**Issue by TZY0101** [zeromicro/go-zero#3614]
In DoGenProject() I only see the generation etc, config, main, serviceContext... But I didn't find out how go.mod was generated.

"goctl api new demo" This command calls CreateServiceCommand, where I also didn't find go.mod generation.

**Comment by kevwan** [comment]
Please find it in `tools/goctl/util/pathx/path.go`.

**Comment by kevwan** [comment]
Answered, closing.

If more questions, please reopen it.
