### ISSUE TITLE
config file xxx, type mismatch for field "xxx", expect "string", actual "string"

### ISSUE THREAD

**Issue by lee86** [zeromicro/go-zero#3622]
**Describe the bug**
If the field "password" is configured as a string in config.go, when the field "password" is set to a pure number in config.yml, an error will be reported and exit

**To Reproduce**
1. The config.yml is
config.yml
   ```go
   password: 123456
   ```

2. The config.go is
config.go
   ```go
   type Config struct {
     Password   string   `json:"password"`
   }
   ```

3. The main.go is
main.go
   ```go
   func main() {
	var sc Config
	conf.MustLoad("etc/config.yml", &sc)
   }
   ```
4. The error is

   ```
   error: config file config.yml, type mismatch for field "password", expect "string", actual "string"
   ```

**Expected behavior**
The field "password" can be parsed correctly

**Screenshots**
![image](https://github.com/zeromicro/go-zero/assets/25501580/82de4621-fd5c-44e6-9c3e-2452173f94f9)

**Environments (please complete the following information):**
 - OS: windows10 ltsc
 - go-zero version v1.5.5
 - goctl version 1.5.5 windows/amd64

**More description**

config.yml
   ```go
   password: "123456"
   ```
The field "password" can be parsed correctly......

**Comment by MarkJoyMa** [comment]
Yes, go-zero's configuration file and configuration-defined fields are similar to strong type matching. The same field is not supported for matching multiple types for the time being.

**Comment by kevwan** [comment]
Fixed, and the error message is now:

```type mismatch for field "password", expect "string", actual "number"`

As you mentioned, the following is correct to parse `123456` as string.

```password: "123456"```
