### ISSUE TITLE
[Documentation] Misleading Error in readme #backgrounds-of-go-zero

### ISSUE THREAD

**Issue by sohamtembhurne** [zeromicro/go-zero#3631]
**Describe the bug**
Unsuitable statement in readme.md. [🔗](https://github.com/zeromicro/go-zero/tree/d71c0da7b72dcd19d55b21b8919b53004d50e530#backgrounds-of-go-zero)

**Expected behavior**
There should be a bullet point explaining the advantage of the architecture instead of 
`I have rich experience in designing microservice architectures`

**Screenshots**
![image](https://github.com/zeromicro/go-zero/assets/82658685/dc8c3654-ff26-4d64-8dda-7ea2816df2d7)

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by sohamtembhurne** [comment]
Would you like me to work on this issue ?

**Comment by kevwan** [comment]
Sure.
