### ISSUE TITLE
Does go zero support api wildcard?

### ISSUE THREAD

**Issue by DominguitoLamo** [zeromicro/go-zero#3716]
I created a file server in go zero in hope of visiting the sub-directory. However, it didn't work. I found the doc where I couldn't find any wildcard information. It seems that go zero only support one level route-path matching.

**Comment by fynxiu** [comment]
Regarding your issue, you might try using a route definition like /static/:file, which I suggest as a potential solution.
If you could provide some specific code examples, it would help us understand your issue better and allow us to provide more detailed solutions or code suggestions.

**Comment by DominguitoLamo** [comment]
> Regarding your issue, you might try using a route definition like `/static/:file`, which I suggest as a potential solution. If you could provide some specific code examples, it would help us understand your issue better and allow us to provide more detailed solutions or code suggestions.

Yes, I tried to do a file server in go zero project, where I hoped to visit the files in a sub-directory.

**Comment by POABOB** [comment]
> > Regarding your issue, you might try using a route definition like `/static/:file`, which I suggest as a potential solution. If you could provide some specific code examples, it would help us understand your issue better and allow us to provide more detailed solutions or code suggestions.
> 
> Yes, I tried to do a file server in go zero project, where I hoped to visit the files in a sub-directory.

I have a example of file server that supporting sub-directory. 
The `registerHandlers` is the most important func that implentment sub-directory.
```go
package main

import (
	"github.com/zeromicro/go-zero/rest/router"
	"net/http"
	"strings"

	"github.com/zeromicro/go-zero/rest"
)

func dirHandler(prefix, fileDir string) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		handler := http.StripPrefix(prefix, http.FileServer(http.Dir(fileDir)))
		handler.ServeHTTP(w, req)
	}
}

func registerHandlers(engine *rest.Server, prefix, dirPath string) {
	// Set up the dir level
	dirLevel := []string{":1", ":2", ":3", ":4", ":5", ":6", ":7", ":8"}
	for i := 1; i < len(dirLevel); i++ {
		path := prefix + strings.Join(dirLevel[:i], "/")
		engine.AddRoute(
			rest.Route{
				Method:  http.MethodGet,
				Path:    path,
				Handler: dirHandler(prefix, dirPath),
			})
	}
}

func main() {
	// custom 404
	rt := router.NewRouter()
	rt.SetNotFoundHandler(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		w.Write([]byte("404 not found."))
	}))
	server := rest.MustNewServer(rest.RestConf{Port: 8080}, rest.WithRouter(rt))

	//Register file handler
	registerHandlers(server, "/static/", "./assets/")

	server.Start()
}
```
My files:
![image](https://github.com/zeromicro/go-zero/assets/38785340/62cb61c1-9198-450d-9c99-8f875416048e)
Browser: 
![image](https://github.com/zeromicro/go-zero/assets/38785340/73947a00-a592-4f68-9a54-22c8cbb13ed0)

reference:
- https://juejin.cn/post/6868984705480720392

**Comment by DominguitoLamo** [comment]
> > > Regarding your issue, you might try using a route definition like `/static/:file`, which I suggest as a potential solution. If you could provide some specific code examples, it would help us understand your issue better and allow us to provide more detailed solutions or code suggestions.
> > 
> > 
> > Yes, I tried to do a file server in go zero project, where I hoped to visit the files in a sub-directory.
> 
> I have a example of file server that supporting sub-directory. The `registerHandlers` is the most important func that implentment sub-directory.
> 
> ```go
> package main
> 
> import (
> 	"github.com/zeromicro/go-zero/rest/router"
> 	"net/http"
> 	"strings"
> 
> 	"github.com/zeromicro/go-zero/rest"
> )
> 
> func dirHandler(prefix, fileDir string) http.HandlerFunc {
> 	return func(w http.ResponseWriter, req *http.Request) {
> 		handler := http.StripPrefix(prefix, http.FileServer(http.Dir(fileDir)))
> 		handler.ServeHTTP(w, req)
> 	}
> }
> 
> func registerHandlers(engine *rest.Server, prefix, dirPath string) {
> 	// Set up the dir level
> 	dirLevel := []string{":1", ":2", ":3", ":4", ":5", ":6", ":7", ":8"}
> 	for i := 1; i < len(dirLevel); i++ {
> 		path := prefix + strings.Join(dirLevel[:i], "/")
> 		engine.AddRoute(
> 			rest.Route{
> 				Method:  http.MethodGet,
> 				Path:    path,
> 				Handler: dirHandler(prefix, dirPath),
> 			})
> 	}
> }
> 
> func main() {
> 	// custom 404
> 	rt := router.NewRouter()
> 	rt.SetNotFoundHandler(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
> 		w.Write([]byte("404 not found."))
> 	}))
> 	server := rest.MustNewServer(rest.RestConf{Port: 8080}, rest.WithRouter(rt))
> 
> 	//Register file handler
> 	registerHandlers(server, "/static/", "./assets/")
> 
> 	server.Start()
> }
> ```
> 
> My files: ![image](https://user-images.githubusercontent.com/38785340/284476735-62cb61c1-9198-450d-9c99-8f875416048e.png) Browser: ![image](https://user-images.githubusercontent.com/38785340/284476650-73947a00-a592-4f68-9a54-22c8cbb13ed0.png)
> 
> reference:
> 
> * https://juejin.cn/post/6868984705480720392

thank you, it helps me a lot

**Comment by vuhoanglam** [comment]
this is just a tricky way, we really need to support wildcard route
