### ISSUE TITLE
Supports CockroachDB 

### ISSUE THREAD

**Issue by accaolei** [zeromicro/go-zero#3718]
Supporting CockroachDB in Goctl is challenging due to compatibility issues with index retrieval methods, causing a "missing primary key" error when generating PostgreSQL models. I hope to see Goctl incorporating support for CockroachDB within the English-speaking community.

**Comment by kesonan** [comment]
There are no plans to support some edge of the sql language generation, if you are interested, you can fork goctl code for reference modification.
