### ISSUE TITLE
an document err

### ISSUE THREAD

**Issue by samuelyao314** [zeromicro/go-zero#3759]
**Describe the bug**
 
an error at documment: https://go-zero.dev/docs/tasks/grpc/client/quickstart 

```go
func main() {
    var clientConf zrpc.RpcClientConf
    conf.MustLoad("etc/client.yaml", &clientConf)
    conn := zrpc.MustNewClient(clientConf)
    resp, err := client.Ping(context.Background(), &greet.Request{})
    if err != nil {
        log.Fatal(err)
        return
    }

    log.Println(resp)
}
```

correct code

```go
func main() {
    var clientConf zrpc.RpcClientConf
    conf.MustLoad("etc/client.yaml", &clientConf)
    conn := zrpc.MustNewClient(clientConf)
    client := greet.NewGreetClient(conn.Conn())
    resp, err := client.Ping(context.Background(), &greet.Request{})
    if err != nil {
        log.Fatal(err)
        return
    }

    log.Println(resp)
}
```

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by kesonan** [comment]
Thanks for your contribution, we have already fix it.
