### ISSUE TITLE
only one service expected

### ISSUE THREAD

**Issue by GuoxinL** [zeromicro/go-zero#3762]
**Describe the bug**
The document describes that multiple services can be defined in proto, but the error "only one service expected" is reported in actual use.

**To Reproduce**
Steps to reproduce the behavior, if applicable:
```proto
// 声明 proto 语法版本，固定值
syntax = "proto3";

// proto 包名
package greet;

// 生成 golang 代码后的包名
option go_package = "example/proto/greet";

// 定义结构体
message SendMessageReq{
  string message = 1;
}
message SendMessageResp{
  int32 status = 1;
}

message GetMessageReq{
  int32 id = 1;
}
message GetMessageResp{
  string message = 1;
}

// 定义 Greet 服务
service Greet {
  // 定义客户端流式 rpc
  rpc SendMessage(stream SendMessageReq) returns (SendMessageResp);
  // 定义服务端流式 rpc
  rpc GetMessage(GetMessageReq) returns (stream GetMessageResp);
  // 定义双向流式 rpc
  rpc PushMessage(stream SendMessageReq) returns (stream GetMessageResp);
}

// 定义 Message 服务
service Message {
  // 定义客户端流式 rpc
  rpc SendMessage(stream SendMessageReq) returns (SendMessageResp);
  // 定义服务端流式 rpc
  rpc GetMessage(GetMessageReq) returns (stream GetMessageResp);
  // 定义双向流式 rpc
  rpc PushMessage(stream SendMessageReq) returns (stream GetMessageResp);
}

```
1. The code is

   ```go
   goctl rpc protoc ./proto/greet.proto --go_out=./test --go-grpc_out=./test --zrpc_out=./test
   ```
![image](https://github.com/zeromicro/go-zero/assets/19989609/111ab1fe-ddb6-4255-943a-cf46d39dc97a)

2. The error is

   ```
   only one service expected
   ```

**Expected behavior**
You want to support multiple services to generate Protos

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]
![image](https://github.com/zeromicro/go-zero/assets/19989609/d75404a7-be47-44bf-bbff-8de4dfc7cd6a)

**More description**

**Comment by chenquan** [comment]
Refer to the documentation：https://go-zero.dev/docs/tutorials/cli/rpc
<img width="913" alt="image" src="https://github.com/zeromicro/go-zero/assets/20548053/95ca160e-1c87-42d3-9a2d-7091c86d464f">

**Comment by GuoxinL** [comment]
wow, thank you.
