### ISSUE TITLE
Why redis.Exists() accept only one key in go-zero?

### ISSUE THREAD

**Issue by striveQiao** [zeromicro/go-zero#3765]
func (s *Redis) ExistsCtx(ctx context.Context, key string) (val bool, err error) {
	err = s.brk.DoWithAcceptable(func() error {
		conn, err := getRedis(s)
		if err != nil {
			return err
		}

		v, err := conn.Exists(ctx, key).Result() // 这里go-redis是可以传入批量key的
		if err != nil {
			return err
		}

		val = v == 1
		return nil
	}, acceptable)

	return
}
这里可以加入多个传入吗，为什么只能传入单个啊

**Comment by kevwan** [comment]
Woud you please submit a PR?

**Comment by codeErrorSleep** [comment]
I am interested in this issue and hope to assist in resolving it.Thanks.
