### ISSUE TITLE
returns type must defined in message.proto

### ISSUE THREAD

**Issue by GuoxinL** [zeromicro/go-zero#3772]
May I ask why the object in the file cannot be referenced in the return value of go-zero rpc, which can be compiled successfully with the original command, why set this restriction in goctl
 

Generate code using goctl:
![image](https://github.com/zeromicro/go-zero/assets/19989609/70cf116b-1fc5-4eb5-bb75-30ad66f0cb80)

Generate code using protoc:
![image](https://github.com/zeromicro/go-zero/assets/19989609/c27bdec5-f1dd-4638-9bc6-8ff13bb2160e)

**Comment by GuoxinL** [comment]
goctl's interception of external references to proto weakens proto's capabilities, which I don't think should be done.

**Comment by GuoxinL** [comment]
![image](https://github.com/zeromicro/go-zero/assets/19989609/6d78ae83-3496-4dc8-b26d-12809681d07a)

**Comment by kesonan** [comment]
Pls see https://go-zero.dev/docs/tutorials/proto/faq#2-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BD%BF%E7%94%A8-goctl-%E7%94%9F%E6%88%90-grpc-%E4%BB%A3%E7%A0%81%E6%97%B6-proto-%E4%B8%8D%E6%94%AF%E6%8C%81%E4%BD%BF%E7%94%A8%E5%8C%85%E5%A4%96-proto-%E5%92%8C-service

**Comment by kesonan** [comment]
Pls see https://go-zero.dev/docs/tutorials/proto/faq#2-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BD%BF%E7%94%A8-goctl-%E7%94%9F%E6%88%90-grpc-%E4%BB%A3%E7%A0%81%E6%97%B6-proto-%E4%B8%8D%E6%94%AF%E6%8C%81%E4%BD%BF%E7%94%A8%E5%8C%85%E5%A4%96-proto-%E5%92%8C-service
