### ISSUE TITLE
API does not support nested definitions

### ISSUE THREAD

**Issue by ShaPoHun** [zeromicro/go-zero#3792]
**Describe the bug**
无法实现官方文档的例子，api 不支持嵌套定义
![image](https://github.com/zeromicro/go-zero/assets/18458406/3fa0248b-d39d-4cf5-afd1-8726ad5e1a61)

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

![image](https://github.com/zeromicro/go-zero/assets/18458406/11bd6387-c05a-4c00-8a93-f78a44e20e6f)

2. The error is
![image](https://github.com/zeromicro/go-zero/assets/18458406/ea7fe5f7-a167-49e2-8d72-9c43726421e1)

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS:  macos
 - go-zero version 1.6.0
 - goctl version 1.6.0

**More description**

**Comment by codeErrorSleep** [comment]
Haven't supported it yet.
![image](https://github.com/zeromicro/go-zero/assets/20470033/0d982a4e-0add-43bf-a130-7f52573de98c)
