### ISSUE TITLE
protobuf import "google/protobuf/any.proto" and catch the error: File not found

### ISSUE THREAD

**Issue by hongyuxuan** [zeromicro/go-zero#3835]
I want to use `google.protobuf.Any` in xxx.proto, so I add `import "google/protobuf/any.proto";`, and when I use goctl command like this:
```powershell
goctl rpc protoc .\xxx.proto --go_out=./types --go-grpc_out=./types --zrpc_out=.
```
it reports errors: 
```powershell
google/protobuf/any.proto: File not found.
xxx.proto:5:1: Import "google/protobuf/any.proto" was not found or had errors.
xxx.proto:48:3: "google.protobuf.Any" is not defined.
```

so how can I use google.protobuf.Any with goctl ?

**Comment by kesonan** [comment]
Please use -I to specify the source of the proto

**Comment by hongyuxuan** [comment]
> Please use -I to specify the source of the proto

yes, it works

**Comment by hongyuxuan** [comment]
I manually download google/protobuf and put it in my GOPATH, then use -I to specify the source of the proto
