### ISSUE TITLE
googleBreaker drop ratio incorrect

### ISSUE THREAD

**Issue by WebFeng** [zeromicro/go-zero#3837]
https://github.com/zeromicro/go-zero/blob/1b9b3cada7118f05f95e907c597c43eeb8d761c6/core/breaker/googlebreaker.go#L65

googleBreaker drop ratio incorrect, because requests are not b.markFailure() when they b.accept() != nil.

reference： 
https://sre.google/sre-book/handling-overload/
https://github.com/go-kratos/kratos/blob/34d9666e0e1bbd8fb74a8b54f5bca0a223c1ebd8/middleware/circuitbreaker/circuitbreaker.go#L61

In the Google SRE article, ’requests’ means the total number of requests.

<img width="1218" alt="image" src="https://github.com/zeromicro/go-zero/assets/10397830/28e0e7ce-aacf-464b-9106-53a0c2376212">

@kevwan

**Comment by kevwan** [comment]
This is by design. I've some fine tunning with original google algorithm.

This is one of them. Another is protection hyperparameter.

**Comment by WebFeng** [comment]
> This is by design. I've some fine tunning with original google algorithm.
> 
> This is one of them. Another is protection hyperparameter.

I would like to take the liberty to ask why such a design is made and what is its special significance?

**Comment by kevwan** [comment]
I'll show you some stress test data later. Maybe in weeks. Kind of busy these days.

**Comment by kevwan** [comment]
<img width="1391" alt="image" src="https://github.com/zeromicro/go-zero/assets/1918356/74a46be1-8216-49d3-9b93-ec6a479ef00f">

For the original algorithm, less requests passed the circuit breaker, it recovers from the unavailable slower. After more investigation, I think it might be better to use the total number of requests.

Thanks for pointing it out!
