### ISSUE TITLE
syntax error: expected ':' | 'IDENT' | 'INT', got '('

### ISSUE THREAD

**Issue by cloudmer** [zeromicro/go-zero#3848]
**Describe the bug**
```golang
@server(
    group: user
    prefix: user
    jwt: JwtAuth
    middleware: Authorization, Casbin
)

service manage {

    @doc "user list"
    @handler List
    post /list (UserListRequest) returns (UserListResponse)

    @doc "create user"
    @handler Create
    post / (CreateUserRequest) returns (CreateUserResponse)

}

```

```shell
goctl api go -api *.api -dir ../  --style=goZero
```

```shell
syntax error: expected ':' | 'IDENT' | 'INT', got '('
```

The location of the problem is
```golang
    post / (CreateUserRequest) returns (CreateUserResponse)
```

**Expected behavior**

```txt
post / 

The goctl API seems to force me to write an address, hoping that previous versions do not force me to write an address
```

**Screenshots**
<img width="1506" alt="image" src="https://github.com/zeromicro/go-zero/assets/11722888/988fc0bf-e9d4-48f1-a0ed-74b202a08e44">

**Environments (please complete the following information):**
 - OS: [macOS sonoma version:14.2.1]
 - go-zero version [github.com/zeromicro/go-zero v1.6.1]
 - goctl version [goctl version 1.6.1 darwin/arm64]

**Comment by kesonan** [comment]
This issue has been fixed in #3834
