### ISSUE TITLE
cannot generate main page access by using goctl api

### ISSUE THREAD

**Issue by samxinyuliang** [zeromicro/go-zero#3877]
**Describe the bug**
my main page statement like this:
{
	@handler dealWithMainPage
	get /
}
**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is
```
goctl api go -api XXX.api -dir . 
```

2. The error is
```
" XXX.api 812:1 syntax error: expected ':' | 'IDENT' | 'INT', got '}'   "
```

**Expected behavior**
I just want I can use it to generate api like 1.6.0

**Screenshots**
![image](https://github.com/zeromicro/go-zero/assets/42970762/27410049-3555-4fb4-8952-4640e2ebc227)

**Environments (please complete the following information):**
 - OS: MacOS
 - go-zero version v1.4.4
 - goctl version v1.6.1

**More description**

**Comment by kesonan** [comment]
duplicate issue with #3848, please install from master to fix it.
