### ISSUE TITLE
Feature Request: postgres, unsupported database type: int4range

### ISSUE THREAD

**Issue by x1rh** [zeromicro/go-zero#3894]
**Is your feature request related to a problem? Please describe.**
使用goctl生成postgres的model失败，提示不支持`int4range`类型：
![image](https://github.com/zeromicro/go-zero/assets/19431348/b291eb1b-472e-457e-b961-15827c2e8bf6)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kesonan** [comment]
Fixed on #4062 4062
