### ISSUE TITLE
go-zero 1.6.2 redis bug

### ISSUE THREAD

**Issue by kissIce** [zeromicro/go-zero#3923]
**Describe the bug**
go-zero 1.6.2版本依赖的go-redis版本 在执行命令前会执行子命令 setinfo 。但是这个命令是在Redis 版本 7.2.0 开始可用。 对于低版本的redis 会报错。提示  ERR unknown subcommand 'setinfo'. Try CLIENT HELP.    建议在cache.CacheConf的配置里面新增对应的开关 DisableIdentity: true 或者框架默认开启这个选项以防止redis低于7.2的版本导致的报错

**To Reproduce**

<img width="1496" alt="image" src="https://github.com/zeromicro/go-zero/assets/18099374/e0da38e5-80f2-485a-9475-6129e2c478b4">

1. The code is

   ```<img width="858" alt="image" src="https://github.com/zeromicro/go-zero/assets/18099374/a76ecea3-024d-474c-8f48-42314d3e64b3">
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [MAC os 13.4.1]
 - go-zero version [e.g. 1.6.2]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by codeErrorSleep** [comment]
这个应该是go-redis v9.5.0才加的特性
go-zero 1.6.2依赖的go-redis版本还是v9.4.0,所以这里应该问题不大

**Comment by kevwan** [comment]
Still using v9.4.0, not a problem.
