### ISSUE TITLE
Mysql Chinese messy code.

### ISSUE THREAD

**Issue by snailmounts** [zeromicro/go-zero#4016]
When I read a Chinese string  from mysql database I got a messy code `æ˜µç§° è¯¦ç»†åœ°å`. 

this is my database table:
```
CREATE TABLE user (
    id bigint AUTO_INCREMENT,
...
    nickname varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'The nickname',
...
) ENGINE = InnoDB 
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci COMMENT 'user table';
```

and this is my database connect string:
```
DataSource: root:123@tcp(localhost:3306)/dbname?charset=utf8mb4&parseTime=True&collation=utf8mb4_unicode_ci
```
How to fix it? Thanks!

**Comment by POABOB** [comment]
I think you set the table and column to ensure that the data is UTF-8, but we can try setting the database below.
```sql
ALTER DATABASE <dbname> CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by snailmounts** [comment]
Thank you @POABOB! Very strange, I have set the charset to `utf8mb4` and collation to `utf8mb4_unicode_ci` for both of the **Database** and **data table**.  But still cannot get the correct Chinese string. Maybe there have something wrong with the version of my `go-sql-driver`, `golang` or `go-zero`.

**Comment by snailmounts** [comment]
The reason for this problem is that I did not set the character-set when importing data from *.sql file using the mysql command line tool, so the string in the utf8 encoding sql file had been imported into database as an incorrect format.
