### ISSUE TITLE
add redis flush commands

### ISSUE THREAD

**Issue by Guvanchhojamov** [zeromicro/go-zero#4018]
Why in core redis package we don't have redis FLUSH commands? 

It would be better if we add the FLUSH commands: 
[https://github.com/zeromicro/go-zero/blob/master/core/stores/redis/redis.go](https://github.com/zeromicro/go-zero/blob/master/core/stores/redis/redis.go)

**Comment by POABOB** [comment]
There are many flush-type commands in the [document](https://pkg.go.dev/github.com/redis/go-redis/v9#Client.FlushAll).

- FlushAll: Delete all the keys of **all the existing databases**, not just the currently selected one **synchronously**. 
- FlushAllAsync: Delete all the keys of **all the existing databases**, not just the currently selected one **asynchronously**. 
- FlushDB: Deletes all keys from **the connection's current database synchronously**.
- FlushDBAsync: Deletes all keys from **the connection's current database asynchronously**.
- FunctionFlush: Deletes all the libraries **synchronously**.
- FunctionFlushAsync: Deletes all the libraries **asynchronously**.
- ScriptFlush: Flush the Lua scripts cache.

Which types are the important ones that we need to implement. I can tackle this issue.

**Comment by Guvanchhojamov** [comment]
@POABOB Thank you for response 
I need:

- FlushAll: Delete all the keys of all the existing databases, not just the currently selected one synchronously.
- FlushDB: Deletes all keys from the connection's current database synchronously.

**Comment by kevwan** [comment]
We're not planning to support FLUSH programmatically.

**Comment by Guvanchhojamov** [comment]
Why? 
I think Some may need this?! 
For example I needed)

**Comment by kevwan** [comment]
It's not safe to use FLUSH in service code.

**Comment by Guvanchhojamov** [comment]
@kevwan Yes, you are right.
But, How can We solve this if  We need FLUSH commands?

**Comment by kevwan** [comment]
I recommend you to do FLUSH from commands.

**Comment by Guvanchhojamov** [comment]
@kevwan , Yes, I also think it will be right way.  Thank you.

**Comment by Guvanchhojamov** [comment]
So, We can close the issue as completed)
