### ISSUE TITLE
Support array field for Request DTO

### ISSUE THREAD

**Issue by shyandsy** [zeromicro/go-zero#4025]
**Is your feature request related to a problem? Please describe.**

It supports array field object in the api specification right now, and it should be work in controller
```
GetVersionReq {
		Statuses                     []string   `form:"statuses[],omitempty,optional"`
}
```

unfortunately, it doesn't work because there is a tiny mass in httpx package. The form.Get method only return one string rather than string array
![image](https://github.com/zeromicro/go-zero/assets/5271457/bd0e7ed0-6b92-46e5-8439-d783e386dfa7)

**Describe the solution you'd like**

we should not use the Get method directly if we wanna support array field..... btw, I am curiose why Go design the method like this. It make no sense....right? 

```
Get(key string) string
```

![image](https://github.com/zeromicro/go-zero/assets/5271457/5b062383-93e9-4abb-9168-3c0aaaeb9ef1)

Alternatively, I will access the map directly like what saying in the comment

**Describe alternatives you've considered**

**Additional context**

**Comment by kevwan** [comment]
fixed by #4026

**Comment by ch3nnn** [comment]
> fixed by #4026

I found this PR flawed.  see https://github.com/zeromicro/go-zero/pull/4015#issuecomment-2029997509

bug url example: 

`"/a?name=hello&age=18&percent=3.4&statuses=try"` 

error parse  `statuses` is nil,  instead of `[]string{"try"}`.


```
=== RUN   TestParseForm
    requests_test.go:31: 
        	Error Trace:	/Users/chentong/project/go/go-zero/rest/httpx/requests_test.go:31
        	Error:      	Expected nil, but got: &fmt.wrapError{msg:"fullName: `statuses`, error: `string: `try`, error: `invalid character 'y' in literal true (expecting 'u')``", err:(*fmt.wrapError)(0x14000098900)}
        	Test:       	TestParseForm
    requests_test.go:35: 
        	Error Trace:	/Users/chentong/project/go/go-zero/rest/httpx/requests_test.go:35
        	Error:      	Not equal: 
        	            	expected: []string{"try"}
        	            	actual  : []string(nil)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,2 @@
        	            	-([]string) (len=1) {
        	            	- (string) (len=3) "try"
        	            	-}
        	            	+([]string) <nil>
        	            	 
        	Test:       	TestParseForm
--- FAIL: TestParseForm (0.00s)

预期:[]string{"try"}
实际:[]string(nil)
```

@shyandsy @kevwan

**Comment by shyandsy** [comment]
i will fix this tomorrow



Yang Shi
201-15 bridgeland dr south
R3Y 0E7


chentong ***@***.***>于2024年4月2日 周二00:00写道：

**Comment by shyandsy** [comment]
@ch3nnn  @kevin0527 

https://github.com/zeromicro/go-zero/pull/4052

this is the new pr for this issue, could you guys help to check?
