### ISSUE TITLE
[ Discuss ] If necessary do strict fields type mapping when generate model from database table fields

### ISSUE THREAD

**Issue by ak5w** [zeromicro/go-zero#4041]
**Is your feature request related to a problem? Please describe.**

As we know, when we use `goctl model mysql ...` to generate golang model,  will converter to int64 (no strict mode) from different integer, like tinyint or int8, all will convert to int64.

**Describe the solution you'd like**
I think we should be rigorous and careful on the mapping issue from database filed type to golang model. At least, can provider a very strict mode or way to mapping, or convert exactly according to the types defined in the database table.

**Describe alternatives you've considered**

1.  A value with int64 in golang model, may be **overflow** when store into a tinyint in database. I think this case is unaccepable who has purpose on high-quality.

2. for [3519](https://github.com/zeromicro/go-zero/issues/3519) below words, I think as a framework, should not cover the not exact case (as below).

> in many cases, database developers do not add unsigned constraints to unsigned types.

**Additional context**
We should not pay for the unreasonable design of database field types, especially for a high-quality microservice frameworks

**Comment by kevwan** [comment]
Good idea, thanks!

We'll make the type mapping configurable. It should come in the release this month or next month.

**Comment by kesonan** [comment]
it was fixed on #4062
