### ISSUE TITLE
goctl is not the latest version in kevinwan/goctl image

### ISSUE THREAD

**Issue by jaronnie** [zeromicro/go-zero#4050]
**Describe the bug**
goctl is not the latest version in kevinwan/goctl image. 

**To Reproduce**

1. The code is

   ```shell
$ docker run --rm -it -v `pwd`:/app kevinwan/goctl:latest goctl --version

goctl version 1.3.5 linux/amd64
   ```

2. The error is

goctl is not the latest.

**Expected behavior**
Expect the latest version goctl.

**Environments (please complete the following information):**
 - OS: [Linux]

**Comment by kesonan** [comment]
Thanks, We will update it to the latest version.

**Comment by kevwan** [comment]
fixed.
