### ISSUE TITLE
bug on sql concatenation

### ISSUE THREAD

**Issue by fuckqqcom** [zeromicro/go-zero#4117]
goctl : 1.6.4

我拼接批量插入的代码
sql部分: ```
INSERT INTO `document_accounts` (`id`,`tenant_id`,`app_id`,`platform_id`,`associate_account_id`,`name`,`avatar`,`intro`,`code`,`biz`,`original_count`,`article_count`,`joined_time`,`sort`,`open_status`,`deleted_status`,`version`,`deleted_time`,`created_time`,`updated_time`,`created_by`,`updated_by`,`deleted_by`,`note`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

参数部分:
<img width="510" alt="image" src="https://github.com/zeromicro/go-zero/assets/9391575/65aea622-c13b-460b-ab7a-963922902160">
![image](https://github.com/zeromicro/go-zero/assets/9391575/9fcaf484-f911-406f-a3df-251bb9df3243)

```
然后再这块开始报错,我参数和占位符的个数都能对上，都是24个

**Comment by kevwan** [comment]
You have args with length 1. Please check it again.

**Comment by fuckqqcom** [comment]
> You have args with length 1. Please check it again.
> 
> Or can you give the sql and args, I'll have a test.

万总，代码和数据早上已经私信发你了微信了
