### ISSUE TITLE
How does proto define this type? map[string][]int64 

### ISSUE THREAD

**Issue by vine2024** [zeromicro/go-zero#4135]
```
type mess struct { 
	uid int64 
	list map[string][]int64
} 
```

The following approach is wrong
```
message Mess {
  int64 uid = 1;
  map<string, repeated int64> list = 2;
}
```

The following method works, but it’s not the result I want.
```
message Mess {
  int64 uid = 1;
  message Repeatedint64 {
    repeated int64 versus_user_id = 1;
  }
  map<string, Repeatedint64> list = 2;
}
```

https://github.com/protocolbuffers/protobuf/issues/2388
I have checked the relevant information, but go-zero does not support external references. How should I solve this?

**Comment by vine2024** [comment]
我下载了google官网的包，放到环境变量里。然后执行
`protoc -I . --go_out=./proto --go-grpc_out=./proto  ./proto/source/test/slot.proto`
报错：
The import path must contain at least one period ('.') or forward slash ('/') character.
排查后发现是官方包struct.proto文件内容option go_package = "types";
改为option go_package = "./types";后重新生成，可以正常生成了，
但是打开生成后的文件发现types 引用路径有问题：
```
import (
	types "/types"
...
)
```
请问这个问题怎么解决？

**Comment by kesonan** [comment]
Did you file the issue in the wrong place? This is go-zero, not proto. Maybe https://protobuf.dev/ can be helpful to you.
