### ISSUE TITLE
请问什么时候可以完善go-zero文档，可以参照goframe，文档一定要及时跟随代码迭代进行跟新

### ISSUE THREAD

**Issue by zhenhua1** [zeromicro/go-zero#4140]

**Comment by kesonan** [comment]
我看你对我们文档使用挺频繁的，应该有很深的感受，可以积极贡献，共建哈，请勿重复提 issue. 
I see that you use our documents quite frequently. You should have a deep feeling about it and you can actively contribute and build together. Please do not push issues repeatedly.
