### ISSUE TITLE
vscode set "editor.formatOnSave": true, changing api with copmlains `go: malformed module path "/": trailing slash`

### ISSUE THREAD

**Issue by iwalkerr** [zeromicro/go-zero#4161]
1. The code is

   ```go
   go: malformed module path "/": trailing slash
    @server(
	    prefix: /api/v1/class
	    middleware: Auth
	    group: frontend/class
    )
    service homework-api {
	    @doc(
		    summary: "获取班级列表"
	    )
	    @handler List
	    post /list(ClassListReq) returns(ClassListResp)
    }
   ```

2. The error is

   ```
   go: malformed module path "/": trailing slash
   ```

**Screenshots**
vscode 设置"editor.formatOnSave": true,更改api自动保存顶部会出现go: malformed module path "/": trailing slash

**Environments (please complete the following information):**
 - OS: [e.g. Mac]
 - go-zero version [e.g. go 1.22.0]
 - goctl version [e.g. 1.6.5, optional]

**Comment by kevwan** [comment]
Please submit the issue to "https://github.com/zeromicro/goctl-vscode"

**Comment by iwalkerr** [comment]
> Please submit the issue to "https://github.com/zeromicro/goctl-vscode"

thank you

**Comment by kesonan** [comment]
fixed on https://github.com/zeromicro/go-zero/issues/4161
