### ISSUE TITLE
Why the `withSession` Method is not exported?

### ISSUE THREAD

**Issue by zzhaolei** [zeromicro/go-zero#4166]
RT

想问一下是基于什么考虑的将 model 模板中的 withSession 设为非导出方法的？现在是否可以修改为导出方法？

**Comment by kesonan** [comment]
withSession is currently not exportable and is only available in non-cache mode. If it can be exported, incorrect use may cause cache consistency failure, and the user's behavior is beyond our control. This can provide instability to the stability of the framework

**Comment by MYHZ79** [comment]
hi there
so how implement db transactions with generated db model?

**Comment by zzhaolei** [comment]
Modify `withSession` in the `xxxmodel.go` file to `WithSession`

```go
var session: sqlx.SqlConn = ... 
tx := m.Withsession(sqlxconn)
tx.Insert(....)
```

**Comment by MYHZ79** [comment]
> withSession is currently not exportable and is only available in non-cache mode. If it can be exported, incorrect use may cause cache consistency failure, and the user's behavior is beyond our control. This can provide instability to the stability of the framework

does using ```WithSession``` in non-cache mode causes inconsistency too? if answer is "No" can i ask why it's not exported for non-cache generated model?
