### ISSUE TITLE
Why use int64 as the universal type for all sql INTs ?

### ISSUE THREAD

**Issue by yunfan** [zeromicro/go-zero#4202]
as the title asked

i ask this because for normally web data, the frontend need real integer number type , but int64 especially uint64 is out of the scope, which leads the result that even tinyint field should use string representation in json format, this highly add up the total entropy for the whole developer team

**Comment by kevwan** [comment]
You can use config to define the type mapping.

**Comment by kesonan** [comment]
Pls see https://go-zero.dev/docs/tutorials/cli/model#%E6%B7%BB%E5%8A%A0-goctl-%E5%86%85%E7%BD%AE%E4%B8%8D%E6%94%AF%E6%8C%81%E7%9A%84%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84

**Comment by yunfan** [comment]
> You can use config to define the type mapping.

so it could also overwrite the default mapping?

**Comment by yunfan** [comment]
> Pls see https://go-zero.dev/docs/tutorials/cli/model#%E6%B7%BB%E5%8A%A0-goctl-%E5%86%85%E7%BD%AE%E4%B8%8D%E6%94%AF%E6%8C%81%E7%9A%84%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84

also the cmd in document told that i could use `goctl config` to generate a new config file while i got the error like the following
```
$ goctl config
go: /home/jyf/work/huishang/RuwuMallServer/go.mod already exists
Usage:
  goctl config [command]

Available Commands:
  clean       Clean goctl config file
  init        Initialize goctl config file

Flags:
  -h, --help   help for config


Use "goctl config [command] --help" for more information about a command.

```

and trying `goctl config init`  got me another error for the project had already exists, yes, i want to generate a new config file for the current project

```
$ goctl config init
go: /home/jyf/work/huishang/RuwuMallServer/go.mod already exists
Error: go: /home/jyf/work/huishang/RuwuMallServer/go.mod already exists
Usage:
  goctl config init [flags]

Flags:
  -h, --help   help for init


go: /home/jyf/work/huishang/RuwuMallServer/go.mod already exists

```

**Comment by yunfan** [comment]
also by using `strace` i found that when goctl trying to generate model from database, it has not even open any config file under my project directory

i had checked and ensure that my goctl version is `1.6.5` and  experiment has been setted to `on`

**Comment by kesonan** [comment]
Could you show your result after executed command `go list -json -m`.

**Comment by yunfan** [comment]
> Could you show your result after executed command `go list -json -m`.

```
jyf@x1:~
$ go list -json -m
{
        "Path": "command-line-arguments",
        "Main": true,
        "GoVersion": "1.22.3"
}

```

**Comment by kesonan** [comment]
Okay, looks like it's a go module environment problem, you add me on wechat, we'll look at it remotely

**Comment by yunfan** [comment]
thanks for the kindly help from author, and now this issue has been totally solved.

the reason is that as a newbie gopher that my project were using `vendor` and i had not done `go mod tidy` either which caused goctl can not init config
