### ISSUE TITLE
For certain query methods, can go-zero be set to not prevent cache penetration?

### ISSUE THREAD

**Issue by palp1tate** [zeromicro/go-zero#4210]
When using go-zero's built-in ORM framework to query the database, the data corresponding to the mobile phone number cannot be found in the database. Go-zero still caches this key and sets the value to *, and the expiration time is set to one minute. This is because go-zero's cache strategy is to prevent cache penetration.

The problem with this strategy is that if someone tries to register with the same phone number within one minute, the registration process will think that the number has not been registered before due to the way it is marked as non-existent in the cache. This can lead to multiple registrations of the same phone number. However, once the cache expires, if the number has been successfully registered, another query will show that it is registered and the system will function normally at that point.

```go
//registerlogic.go
func (l *RegisterLogic) Register(in *user.RegisterReq) (*user.RegisterResp, error) {
	userEntity, err := l.svcCtx.UserModel.FindByPhone(l.ctx, in.Phone)
	if err != nil && !errors.Is(err, models.ErrNotFound) {
		return nil, errors.Wrapf(errorx.NewDBErr(), "find user by phone err %v , req %v", err, in.Phone)
	}
	//......

	_, err = l.svcCtx.UserModel.Insert(l.ctx, userEntity)
	if err != nil {
		return nil, errors.Wrapf(errorx.NewDBErr(), "insert user err %v , req %v", err, in)
	}

	//......
}

//usermodel_gen.go
func (m *defaultUserModel) FindByPhone(ctx context.Context, phone string) (*User, error) {
	userPhoneKey := fmt.Sprintf("%s%v", cacheUserPhonePrefix, phone)
	var resp User
	err := m.QueryRowCtx(ctx, &resp, userPhoneKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, phone)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
```

If there is no more convenient solution here, I also tried to customize a method to avoid setting cache avalanche:
```go
func (m *defaultUserModel) FindByPhone(ctx context.Context, phone string) (*User, error) {
	userPhoneKey := fmt.Sprintf("%s%v", cacheUserPhonePrefix, phone)
	var resp User

	// 先查询缓存
	err := m.GetCacheCtx(ctx, userPhoneKey, &resp)
	if err == nil {
		return &resp, nil
	}

	// 缓存未命中，查询数据库
	query := fmt.Sprintf("select %s from %s where phone = ? limit 1", userRows, m.table)
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, phone)
	if err != nil {
		if err == sqlc.ErrNotFound {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// 数据库查询成功，将结果更新到缓存
	err = m.SetCacheCtx(ctx, userPhoneKey, resp)
	if err != nil {
		return nil, err
	}

	return &resp, nil
}
```
If possible, in the parameter passing of the following code, can add a policy to indicate whether to enable cache penetration prevention. The default value is true, which means it is enabled. Users can specify false when passing parameters, so that go-zero does not need to set the cache value to an empty value. The above is just my humble opinion, and I look forward to your help and correction.
```go
m.QueryRowCtx(ctx, &resp, userPhoneKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, phone)
```

**Comment by chenquan** [comment]
The cache is deleted after the `l.svcCtx.UserModel.Insert(l.ctx, userEntity)` call.

**Comment by palp1tate** [comment]
> The cache is deleted after the `l.svcCtx.UserModel.Insert(l.ctx, userEntity)` call is successful.
* FindByPhone and Insert use different cache keys. The former uses the phone number, while the latter uses the ID.
* In fact, when the entire Register function is successfully called, the redis database will generate a key with an expiration time of 1 minute, which means that repeated registration can be performed within this 1 minute.

**Comment by chenquan** [comment]
show your `Insert` code.

**Comment by palp1tate** [comment]
> show your `Insert` code.

```go
func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	userIdKey := fmt.Sprintf("%s%v", cacheUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Avatar, data.Nickname, data.Phone, data.Password, data.Status, data.Sex)
	}, userIdKey)
	return ret, err
}
```

**Comment by chenquan** [comment]
> > show your `Insert` code.显示您的 `Insert` 代码。
> 
> ```go
> func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
> 	userIdKey := fmt.Sprintf("%s%v", cacheUserIdPrefix, data.Id)
> 	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
> 		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
> 		return conn.ExecCtx(ctx, query, data.Id, data.Avatar, data.Nickname, data.Phone, data.Password, data.Status, data.Sex)
> 	}, userIdKey)
> 	return ret, err
> }
> ```

Set the `phone number` and `ID` fields to UNIQUE and regenerate the model code.

**Comment by palp1tate** [comment]
> > > show your `Insert` code.显示您的 `Insert` 代码。
> > 
> > 
> > ```go
> > func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
> > 	userIdKey := fmt.Sprintf("%s%v", cacheUserIdPrefix, data.Id)
> > 	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
> > 		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
> > 		return conn.ExecCtx(ctx, query, data.Id, data.Avatar, data.Nickname, data.Phone, data.Password, data.Status, data.Sex)
> > 	}, userIdKey)
> > 	return ret, err
> > }
> > ```
> 
> Set the `phone number` and `ID` fields to UNIQUE and regenerate the model code.

LGTM!!!Thank you very much!
