### ISSUE TITLE
Gateway proxy http request 404

### ISSUE THREAD

**Issue by adcwb** [zeromicro/go-zero#4212]
Reference Links： https://go-zero.dev/docs/tutorials/gateway/grpc

This is completely in accordance with the official demo example. I don't know why the request is 404.

gRPC request
![image](https://github.com/zeromicro/go-zero/assets/39952131/985044fb-c93c-4fb9-9253-93b74341b431)

gateway http request
![image](https://github.com/zeromicro/go-zero/assets/39952131/aaa301f8-cd43-47dd-9d80-c3b9d3f51f8c)

$ goctl -v
goctl version 1.6.4 windows/amd64

$ protoc --version 
libprotoc 3.19.4

$  protoc-gen-go --version 
protoc-gen-go.exe v1.33.0

$  protoc-gen-go-grpc --version 
protoc-gen-go-grpc 1.3.0

**Comment by kevwan** [comment]
Sorry, the config file in docs was not correctly indented. I've modified it.

**Comment by adcwb** [comment]
OK, thanks for your help
