### ISSUE TITLE
error reading server preface: http2: frame too large

### ISSUE THREAD

**Issue by 793383996** [zeromicro/go-zero#4242]
rpc error: code = Unavailable desc = last connection error: connection error: desc = "error reading server preface: http2: frame too large"'

Creating a new API service and encountering an exception when calling RBC, with the environment version being 1.23.

**Comment by kevwan** [comment]
You might need to set MaxMsgSize of gRPC.

```go
svr.AddOptions(grpc.MaxSendMsgSize(...))
svr.AddOptions(grpc.MaxRecvMsgSize(...))
```

**Comment by 793383996** [comment]
Thx
The cause of this problem is port reuse but no error warning was reported. It has been solved. Thank you
