### ISSUE TITLE
goctl auto expand struct

### ISSUE THREAD

**Issue by edieruby** [zeromicro/go-zero#4288]
goctl -v
goctl version 1.7.0 windows/amd64

![image](https://github.com/user-attachments/assets/c94a11d9-d5b8-4e47-998f-3d7c1b1e4f5b)

error:
struct will auto expand
*struct same as before

**Comment by loocor** [comment]
The team is aware of this bug and will include a fix in the next release; 
if necessary, you can revert to a previous release, or go to the master branch and compile it yourself, where the code has already been fixed.

**Comment by kevwan** [comment]
fixed in #4281
