### ISSUE TITLE
go-zero 利用nacos做服务发现 rpc不通

### ISSUE THREAD

**Issue by 18767156402** [zeromicro/go-zero#4376]
项目背景
accountCenter--账号服务
workZone--核心作业区
baseService--基础服务提供者
其中
accountCenter服务-订阅accountCenter、workZone、baseService 3个rpc服务
workZone-订阅accountCenter的rpc服务
baseService-订阅accountCenter的rpc服务
其中workZone和baseService 都是正常启动，维度accountCenter启动报错
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/1b6ae24c-2475-4762-bcaf-685b671853ab">

该问题困扰好久，看有人可以帮忙指导一下么

**Comment by xiaocode337317439** [comment]
> 项目背景 accountCenter--账号服务 workZone--核心作业区 baseService--基础服务提供者 其中 accountCenter服务-订阅accountCenter、workZone、baseService 3个rpc服务 workZone-订阅accountCenter的rpc服务 baseService-订阅accountCenter的rpc服务 其中workZone和baseService 都是正常启动，维度accountCenter启动报错 <img alt="image" width="1464" src="https://private-user-images.githubusercontent.com/7996875/367129648-1b6ae24c-2475-4762-bcaf-685b671853ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODY2MjcsIm5iZiI6MTczMTU4NjMyNywicGF0aCI6Ii83OTk2ODc1LzM2NzEyOTY0OC0xYjZhZTI0Yy0yNDc1LTQ3NjItYmNhZi02ODViNjcxODUzYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTIxMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI4YjQzMTlhZTI0MWRmYzliZWMxNzllZDhhZDQzZmUwMjZmMzFlN2JhZWU2NmVlN2RmMjEzNGY0ZTJjNmJjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4I5alcaQxQBWamA75ZnOIVT2dWbeItEXfUI6QrsBquQ">
> 
> 该问题困扰好久，看有人可以帮忙指导一下么

请问解决了吗？

**Comment by xiaocode337317439** [comment]
> 项目背景 accountCenter--账号服务 workZone--核心作业区 baseService--基础服务提供者 其中 accountCenter服务-订阅accountCenter、workZone、baseService 3个rpc服务 workZone-订阅accountCenter的rpc服务 baseService-订阅accountCenter的rpc服务 其中workZone和baseService 都是正常启动，维度accountCenter启动报错 <img alt="image" width="1464" src="https://private-user-images.githubusercontent.com/7996875/367129648-1b6ae24c-2475-4762-bcaf-685b671853ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODY3MTAsIm5iZiI6MTczMTU4NjQxMCwicGF0aCI6Ii83OTk2ODc1LzM2NzEyOTY0OC0xYjZhZTI0Yy0yNDc1LTQ3NjItYmNhZi02ODViNjcxODUzYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTIxMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjYjA3ZjFkZWU1ODI4YmRiYzkwNGI2OWM0ODRiOGE5OTQ4YThlNzVjMzc3MzQ2M2U2MTc2OWYyMzcxZDBjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vXX99-TNet6bhlYrgi9-H-IZ4Pm-ajJKfEfIygl6BsU">
> 
> 该问题困扰好久，看有人可以帮忙指导一下么

请问下最后你是怎么弄的？我也是总不成功
```go
func NewGrpcClientConn(nc *NacosConfig, serverName string) *grpc.ClientConn {
	target := fmt.Sprintf(
		"nacos://%s:%d/%s?namespaceid=%s&groupname=%s",
		RegisterIp,
		RegisterPort,
		serverName,
		nc.NamespaceId,
		GroupName,
	)
	return zrpc.MustNewClient(zrpc.RpcClientConf{
		Target: target,
	}).Conn()
}
```

**Comment by 18767156402** [comment]
> > 项目背景 accountCenter--账号服务 workZone--核心作业区 baseService--基础服务提供者 其中 accountCenter服务-订阅accountCenter、workZone、baseService 3个rpc服务 workZone-订阅accountCenter的rpc服务 baseService-订阅accountCenter的rpc服务 其中workZone和baseService 都是正常启动，维度accountCenter启动报错 <img alt="image" width="1464" src="https://private-user-images.githubusercontent.com/7996875/367129648-1b6ae24c-2475-4762-bcaf-685b671853ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODY3MTAsIm5iZiI6MTczMTU4NjQxMCwicGF0aCI6Ii83OTk2ODc1LzM2NzEyOTY0OC0xYjZhZTI0Yy0yNDc1LTQ3NjItYmNhZi02ODViNjcxODUzYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTIxMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjYjA3ZjFkZWU1ODI4YmRiYzkwNGI2OWM0ODRiOGE5OTQ4YThlNzVjMzc3MzQ2M2U2MTc2OWYyMzcxZDBjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vXX99-TNet6bhlYrgi9-H-IZ4Pm-ajJKfEfIygl6BsU">
> > 该问题困扰好久，看有人可以帮忙指导一下么
> 
> 请问下最后你是怎么弄的？我也是总不成功
> 
> ```go
> func NewGrpcClientConn(nc *NacosConfig, serverName string) *grpc.ClientConn {
> 	target := fmt.Sprintf(
> 		"nacos://%s:%d/%s?namespaceid=%s&groupname=%s",
> 		RegisterIp,
> 		RegisterPort,
> 		serverName,
> 		nc.NamespaceId,
> 		GroupName,
> 	)
> 	return zrpc.MustNewClient(zrpc.RpcClientConf{
> 		Target: target,
> 	}).Conn()
> }
> ```

go-zero的 文档没有问题，我是 写成了 Target: naocs://[usr:pwd]@host:8848/accountCenter?namespaceid=pre&timeout=5000s 其实[]这个符号要去掉，他们这里是表示用户名和密码可选的意思，后面我直接去掉[]就好了，不过最近发现nacos的服务发现还有别的问题，时间长了会api调rpc访问不通，换成etcd就没有这个问题
