### ISSUE TITLE
Please don't use json tag in config, use zero tag to replace json tag

### ISSUE THREAD

**Issue by studyzy** [zeromicro/go-zero#4438]
**Is your feature request related to a problem? Please describe.**
In config [document](https://go-zero.dev/docs/tutorials/go-zero/configuration/overview), user use json tag like this:
```go
type Config struct {
    Name string // 没有任何 tag，表示配置必填
    Port int64 `json:",default=8080"` // 如果配置中没有配置，将会初始成 8080
    Path string `json:",optional"`
}
```
but golangci-lint show error:
```
SA5008: unknown JSON option "default=8080" (staticcheck)
 SA5008: unknown JSON option "optional" (staticcheck)
```
**Describe the solution you'd like**
Use your own tag, don't use  **json** tag.
for example:
```
type Config struct {
    Name string // 没有任何 tag，表示配置必填
    Port int64 `zero:"default=8080"` // 如果配置中没有配置，将会初始成 8080
    Path string `zero:"optional"`
}
```

**Comment by kesonan** [comment]
This requirement is very personalized and is not supported. Have you tried the `//nolint:all` comment to ignore the lint of the modified structure?

**Comment by studyzy** [comment]
OK. ignore this issue.
