### ISSUE TITLE
Graceful shutdown on windows

### ISSUE THREAD

**Issue by Han1enG** [zeromicro/go-zero#4460]
Hello author. 
Is it true that graceful shutdown does not work on Windows platform? I found the corresponding logic in Linux or Darwin in the code.

![image](https://github.com/user-attachments/assets/b4324a3f-d08f-443a-92a9-0f07e10770e6)

My scenario is on Windows platform. I hope that when receiving the termination signal, the cached log will be saved to the file before exiting. But in fact, the program is terminated immediately.

```go
func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	server := rest.MustNewServer(c.RestConf, rest.WithCors())
	Init()
	server.Use(middleware.AuthInterceptor)
	server.Use(middleware.GlobalExceptionMiddleware)
	ctx := svc.NewServiceContext(c)
	handler.RegisterHandlers(server, ctx)

	group := service.NewServiceGroup()
	defer group.Stop()
	group.Add(&ws.WebSocketService{})
	group.Add(server)
	logx.Info("Starting http server at:", c.Host, c.Port)
	waitForCalled := proc.AddShutdownListener(func() {
	    // ...save cached logs to file before exiting
	})
	group.Start()
	waitForCalled()
}
```

Looking forward to your reply, thank you

**Comment by kevwan** [comment]
It's by design, we don't have a plan to support it on Windows.

**Comment by Han1enG** [comment]
> It's by design, we don't have a plan to support it on Windows.

Thanks for your reply.
