### ISSUE TITLE
goctl生成的文件名全部转换成小写了，可否保留原来定义的大写？

### ISSUE THREAD

**Issue by gzlboy** [zeromicro/go-zero#4468]
有的文件名比较长，原来模板定义里采用驼峰式的命名规范，但生成的文件名全部变成小写了，可读性较差，请问有配置项可以保留大写吗？

**Comment by kesonan** [comment]
https://go-zero.dev/docs/tutorials/cli/style

**Comment by gzlboy** [comment]
多谢！，没注意到这个文档
