### ISSUE TITLE
[Question] How to handle OPTIONS preflight

### ISSUE THREAD

**Issue by Cluster2a** [zeromicro/go-zero#4517]
Hey, I am trying to figure out, how to handle CORS, especially the OPTIONS preflight.

I tried to implement middleware that returns HTTP.StatusNoContent if an OPTIONS call is being made, but I always get a 405.

The framework is not processing the request as there is no such route.

What is the general approach to handling CORS?

Best - Alex

**Comment by kevwan** [comment]
Use `rest.WithCors`, `rest.WithCorsHeaders` or `rest.WithCustomCors`.

**Comment by Cluster2a** [comment]
@kevwan, thanks a lot! I think this should be documented somewhere.

**Comment by Cluster2a** [comment]
@kevwan, thanks a lot! I think this should be documented somewhere.

**Comment by kevwan** [comment]
https://go-zero.dev/faq/http/cors
