### ISSUE TITLE
Why not generate very common model/database operation methods such as BulkInsert , BulkUpdate, or SoftDelete via goctl model by default？ 

### ISSUE THREAD

**Issue by dahuzihaidao** [zeromicro/go-zero#4528]
goctl model only generate very a few model operation methods, common methods like  BulkInsert , BulkUpdate, or SoftDelete are not provided. Why not provide these methods?

**Comment by kesonan** [comment]
Because these are not general business methods

**Comment by dahuzihaidao** [comment]
All right, however it is pretty common in my opinion :)

It's better at least provide a option for users to choose between populating more rich db operation methods or less standard one, which may suit all people's needs.

Thanks!
