### ISSUE TITLE
FindOneByUsernameDeletedAt method generated by goctl model failed to find records with 'deleted_at' field is Null.

### ISSUE THREAD

**Issue by dahuzihaidao** [zeromicro/go-zero#4529]
**Describe the bug**

Below is the FindOneByUsernameDeletedAt method,  and when I use this method to query specific username with deleted_at equaling Null, no rows are returned. 

`l.svcCtx.UsersModel.FindOneByUsernameDeletedAt(l.ctx, req.Username, sql.NullTime{Valid: false})`

![image](https://github.com/user-attachments/assets/2941c925-1804-447c-a64c-8703b9bd6c78)

**Possible solutions"
![image](https://github.com/user-attachments/assets/17c36bef-1dd9-41e1-b3b1-419523a39504)

Need to use "deleted_at is Null“ to filter data. What is the best workaround for now? I believe that the columns with Null value all have this similar problem.

**Comment by kesonan** [comment]
I don't think this is a code generation problem. When generating code, I can't determine whether your sql.NullTime is null.

**Comment by dahuzihaidao** [comment]
> I don't think this is a code generation problem. When generating code, I can't determine whether your sql.NullTime is null.

So to work this around, I can only set a default value like '1970-01-01 00:00:00' to indicate/mock NULL value instead?
