### ISSUE TITLE
生成代码能否增加导入和分页查询接口

### ISSUE THREAD

**Issue by panzhaohui** [zeromicro/go-zero#548]
数据表生成model代码能否增加常用的批量导入和分页查询接口。

**Comment by kevwan** [comment]
@anqiansong

**Comment by anqiansong** [comment]
@panzhaohui 目前看来分页代码的生成不是所有的业务都会要，如果都生成的会导致一些无用的代码，后续可以考虑把模板参数完全提供出来，开发人员自定义模板，这个方式理论可以满足定制化需求。

**Comment by brady-wang** [comment]
没有分页,确实有点不方便

**Comment by william-best** [comment]
It should support more, even users do not use these func. That's why we call go-zero is a framework.

**Comment by william-best** [comment]
It should support more, even users do not use these func. That's why we call go-zero is a framework.
common users do not want to use template. So the framework should :  give all the func for common user,  and change template themself for advance users.

**Comment by feitian124** [comment]
+1
希望可以有分页和批量id查询接口

**Comment by leafmirror** [comment]
批量插入有demo吗

**Comment by wanderBee** [comment]
+1
希望可以有分页和过滤条件查询

**Comment by yktimes** [comment]
+1

**Comment by godLei6** [comment]
+1

**Comment by he2121** [comment]
> @panzhaohui 目前看来分页代码的生成不是所有的业务都会要，如果都生成的会导致一些无用的代码，后续可以考虑把模板参数完全提供出来，开发人员自定义模板，这个方式理论可以满足定制化需求。

生成代码还要考虑生成无用的代码吗 生成代码有比无用好

**Comment by godLei6** [comment]
或者goctl中生成的时候可以指定是否生成

**Comment by veezhang** [comment]
+1

**Comment by chengcxy** [comment]
分页 +1

**Comment by uyuan** [comment]
+1

**Comment by wavechao** [comment]
+1

**Comment by kevwan** [comment]
> @panzhaohui 目前看来分页代码的生成不是所有的业务都会要，如果都生成的会导致一些无用的代码，后续可以考虑把模板参数完全提供出来，开发人员自定义模板，这个方式理论可以满足定制化需求。

调研下，看看是否可以通过插件的方式支持？

**Comment by dyzsoft** [comment]
+1

**Comment by Jetereting** [comment]
+1

**Comment by waltcow** [comment]
+1

**Comment by Jetereting** [comment]
+1

**Comment by Jetereting** [comment]
+1

**Comment by randomjoho** [comment]
+1

**Comment by zzhzero** [comment]
+1

**Comment by CharliHui** [comment]
+1 求分页代码生成

**Comment by VogueSogetsu** [comment]
+1 for 分页

**Comment by yigeqiji** [comment]
Is this issue still being tracked?

**Comment by echo-LuGuang** [comment]
+1 for pagination
![image](https://user-images.githubusercontent.com/50095011/206991548-5f8a28fe-ea7c-4228-840f-f31f4b06f39f.png)
