### ISSUE TITLE
Wanted: open source projects powered by go-zero / 基于 go-zero 的开源项目

### ISSUE THREAD

**Issue by kevwan** [zeromicro/go-zero#653]
## open source projects powered by go-zero

Thanks sincerely for constantly using and supporting go-zero. We will try our best to make go-zero better, and keep growing go-zero community. To attract more developers to use and contribute to go-zero, please submit PRs to 

[https://github.com/zeromicro/awesome-zero](https://github.com/zeromicro/awesome-zero)

---

非常感谢每一位持续关注并使用 go-zero 的朋友。我们会持续投入，尽力把 go-zero 变得更好，努力让 go-zero 社区更加繁荣。为了更好的聆听社区的声音，吸引更多的人使用和参与，我们期待您提交PR到

[https://github.com/zeromicro/awesome-zero](https://github.com/zeromicro/awesome-zero)

再次感谢你的参与!!!

**Comment by xiaopenggithub** [comment]
[go-zero微服务落地实战]bookstore案例(全端实现参考)

https://github.com/xiaopenggithub/zindle

目前实现：

读者借(还)书app（uni-app开发）
后台管理（权限使用casbin）

**Comment by hhstore** [comment]
## zeromall:
- https://github.com/zeromicro/zeromall
- 基于 go-zero 的B2B2C电商平台

## pkg:

- https://github.com/better-go/pkg
- go-zero 的一些扩展组件

## cookiecutter-go:

- https://github.com/better-go/cookiecutter-go
- go 项目初始化脚手架, 支持 go-zero 微服务项目初始化.

**Comment by godLei6** [comment]
go-things:
依照腾讯云物联网平台打造的物联网云平台,无缝迁移,基于go-zero框架,目前支持mqtt协议,支持数据模板检验,日志记录,数据流转,实时数据反馈,低代码数据流转,用户及设备互联互通.使用了kafka,redis,mysql,MongoDB,etcd开源框架.
地址:https://gitee.com/godLei6/things

**Comment by langbin522** [comment]
> 
> 
> [go-zero微服务落地实战]bookstore案例(全端实现参考)
> 
> https://github.com/xiaopenggithub/zindle
> 
> 目前实现：
> 
> 读者借(还)书app（uni-app开发）
> 后台管理（权限使用casbin）

恕我直言，这个真不算是微服务。或者说我理解的微服务已变样了。你这样写跟用GIN或者其它的WEB框架一样的，压根没有微服务的理念

**Comment by hhstore** [comment]
无意中发现的一个数据中台: 

https://github.com/jackluo2012/datacenter

**Comment by wuleiming2009** [comment]
https://github.com/mt-team/mt-zero

**Comment by Mikaelemmmm** [comment]
https://github.com/Mikaelemmmm/go-zero-looklook

**Comment by Mikaelemmmm** [comment]
基于go-zero 全面技术栈开发最小可用项目，帮助go-zero社区更完善

**Comment by Mikaelemmmm** [comment]
https://github.com/Mikaelemmmm/go-zero-looklook 

基于go-zero 全面技术栈开发最小可用项目，帮助go-zero社区更完善

**Comment by gocpplua** [comment]
> 图书馆后台https://gitee.com/wu_wen_yi/library-system-admin

looks great

**Comment by Matrix-X** [comment]
元匠科技
PowerX 开源客域系统，CRM+电商+SCRM
https://powerx.artisan-cloud.com
https://github.com/ArtisanCloud/PowerX

**Comment by jaronnie** [comment]
Jzero[基于 go-zero 框架定制的企业级后端代码框架脚手架]
* 同时支持在项目中使用 grpc, grpc-gateway, api
* 支持多 proto 多 service(多人开发友好)
* 一键创建项目(jzero new)
* 一键生成各种代码(jzero gen)

文档站: https://jzero.jaornnie.com
github: https://github.com/jaronnie/jzero

**Comment by atlas-u** [comment]
atlas-zero

- https://github.com/cls-cloud/atlas-zero

- 基于go-zero实现的后台开发脚手架（多租户）

**Comment by me-cs** [comment]
https://github.com/me-cs/dianping-gozero
  基于 go-zero 开发的完整点评系统，采用微服务架构（API Gateway + 5个独立 RPC 服务），配备前后端完整解决方案。

  核心功能包括：用户系统（手机验证码登录、JWT认证）、店铺系统（分类浏览、地理位置搜索）、博客系统（发布探店笔记、图片上传）、社交功能（关注/取关、点赞排行榜、Feed流推送）、优惠券系统（普通券、高并发秒杀券，Redis Lua脚本保证原子 性）、订单系统（一人一单限制、分布式锁）。

  技术亮点：完整的可观测性方案（Jaeger链路追踪 + Prometheus监控 + Grafana可视化）、多层缓存策略（Cache-Aside模式）、服务注册发现（etcd）、Docker容器化部署。

  提供详细的开发文档，包含从零开始的环境搭建、API接口说明、数据库设计、部署指南、故障排查等。支持一键启动所有服务，新手友好。

  适合学习微服务架构和高并发系统设计。

**Comment by wsrh8888** [comment]
https://github.com/wsrh8888/beaver-server

基于 go-zero 开发的IM社交软件， 项目包含了桌面端、移动端2大部分。
核心功能： IM社交的全部

技术亮点： 基于微服务的社交软件，包含多个api和rpc服务，该项目非常适合初学者学习

提供详细的开发文档和视频教程，包含从零开始的环境搭建。

**Comment by mmfiRan** [comment]
https://github.com/mmfiRan/ran-feed
一个基于 go-zero 框架构建的信息流（Feed）系统后端，围绕发布、互动、社交关系与信息流分发构建完整业务闭环。

支持文章/视频发布、点赞/评论/收藏等互动能力，以及关注关系与多种信息流场景（推荐流、关注流、个人发布与收藏列表），并提供高性能的计数与数据统计能力。
