### ISSUE TITLE
how to add i18n in go-zero projects? is there any document?

### ISSUE THREAD

**Issue by feitian124** [zeromicro/go-zero#784]
i'd like to add i18n to my project using [i18n](https://github.com/kataras/i18n).

[go-i18n](https://github.com/nicksnyder/go-i18n) has more stars, but do not support below style out of box:

```go
	// Fmt style.
enText := i18n.Tr("en", "hi", "John Doe") // or "en-US"
elText := i18n.Tr("el", "hi", "John Doe")
zhText := i18n.Tr("zh", "hi", "John Doe")
```

image we have two locale like `en` and `zh`,   
`www.mysite.com?lang=en` will cause **request** use `en` locale,  
`www.mysite.com?lang=zh` will cause **request** use `zh` locale,  
is there any mechanism like `plugin`, `filter` let me can do i18n in controller(handler), service(logic)  but do not need add a lang field to very request struct?

**Comment by feitian124** [comment]
gin does not support i18n out of box but has middlewares.
iris support i18n out of box for a long time.

https://github.com/gin-gonic/gin/issues/1382

**Comment by kevwan** [comment]
Not in the roadmap of this year.
