### ISSUE TITLE
zrpc的直连模式

### ISSUE THREAD

**Issue by CodingPlatelets** [zeromicro/go-zero#848]
直连模式的方式应改为：
Feedback:
    Endpoints：
      - localhost:xxxx
   而不应该是之前issue中写的：
Feedback:
    Endpoints：
        Hosts：
          - localhost:xxxx
因为源码func NewDirectClientConf(endpoints []string, app, token string) RpcClientConf {
	return RpcClientConf{
		Endpoints: endpoints,
		App:       app,
		Token:     token,
	}
}
第一个结构体是个string数组

**Comment by kevwan** [comment]
配置就是这么写的，你这个是哪里看到的？
```
Feedback:
  Endpoints：
  - localhost:xxxx
```

**Comment by CodingPlatelets** [comment]
https://github.com/tal-tech/go-zero/issues/366
此处，然后这个issue的最后一条也是我们团队的同学补上去的。doc没有相关描述，希望能加上。

**Comment by kevwan** [comment]
> #366
> 此处，然后这个issue的最后一条也是我们团队的同学补上去的。doc没有相关描述，希望能加上。

那是社区的一个同学回复的，Hosts是多余的

**Comment by CodingPlatelets** [comment]
希望能加到dev上面把。现在用etcd做服务发现好像已经不多了吧，直连可能用的更多一些吧。

**Comment by kevwan** [comment]
> 希望能加到dev上面把。现在用etcd做服务发现好像已经不多了吧，直连可能用的更多一些吧。

直连根本就不是服务发现吧，不能自动侦测节点。

**Comment by CodingPlatelets** [comment]
直连当然不是用做服务发现，我说的是现在服务发现用的不多了，很多用直连了，所以希望加上这个doc

**Comment by kevwan** [comment]
> 直连当然不是用做服务发现，我说的是现在服务发现用的不多了，很多用直连了，所以希望加上这个doc

好的，我们看看加在文档哪里

**Comment by kevwan** [comment]
@anqiansong 文档有地方加下这个吗？

**Comment by anqiansong** [comment]
fixed on https://go-zero.dev/cn/faq.html
