### ISSUE TITLE
internal/types 是否可以按照 group 分组？

### ISSUE THREAD

**Issue by veezhang** [zeromicro/go-zero#947]

**Comment by kevwan** [comment]
@anqiansong 我记得types文件的生成在最新版本里已经去掉了？

**Comment by veezhang** [comment]
我使用的是 1.1.10 ，应该是最新版本。
```shell
goctl -v     
goctl version 1.1.10 darwin/amd64
```

**Comment by anqiansong** [comment]
@kevwan 这个一直没有支持group
@veezhang types group意义不大，目前group只针对service

**Comment by veezhang** [comment]
@anqiansong types 如果没有 group 的概念，那么所有的参数都必须不同名称。
比如某个 group 下有 CreateRequest，其他的地方也有，那么就冲突了
这样就必须是加上前缀或者后缀来区分了，而这个前缀或者后缀通常是 group

**Comment by veezhang** [comment]
我看 service 和 handler 都是分 group 的， 这个是否也会考虑区分下？

**Comment by kevwan** [comment]
> 我看 service 和 handler 都是分 group 的， 这个是否也会考虑区分下？

这个分组的价值是什么呢？

**Comment by kevwan** [comment]
我觉得这个必要性不大，之前group是为了针对一个服务不同路由设置不同中间件和鉴权等，不是为了分包

**Comment by xhochipe** [comment]
@veezhang 你是不是想重复利用比如 create  update del 在不同的group里面，现在的是即使不同的group，handler也不能重复，这样的话，必须要加上必须XXXCreate  XXXUpdate  XXXDel ,对吧

**Comment by veezhang** [comment]
@xhochipe 是的， 不然都要加上前缀或者后缀，这样参数结构体定义就长了

**Comment by xhochipe** [comment]
@veezhang 这个比较实用，在定义api的时候，就可以直接写curd，然后按照group分组，但是定义type的时候最好也可以这样，就可以做到统一了

**Comment by xhochipe** [comment]
![c80135e5f65cc897279dc30148b39a3](https://user-images.githubusercontent.com/9391575/153002864-cc169ad2-85df-45f9-b18a-d03f69af2450.png)

**Comment by xhochipe** [comment]
![image](https://user-images.githubusercontent.com/9391575/153016208-e5203b41-3214-41d2-b323-68d15f0b188a.png)
