### ISSUE TITLE
Goland中的goctl插件不可用

### ISSUE THREAD

**Issue by VingoYang** [zeromicro/go-zero#949]
现象：在terminal中安装了goctl 1.1.10，terminal中能成功执行goctl的相关命令。goctl已经加入系统PATH路径。然后在Goland 2021.1.3版本中安装了goctl插件(TAL 0.7.15)，但是在Goland中按照文档描述执行“New Api File","Api Code"等操作时报错：goctl not found

系统版本：macOS Big Sur 11.2
CPU型号：Apple M1

**Comment by kevwan** [comment]
@anqiansong 看下哈

**Comment by anqiansong** [comment]
> 现象：在terminal中安装了goctl 1.1.10，terminal中能成功执行goctl的相关命令。goctl已经加入系统PATH路径。然后在Goland 2021.1.3版本中安装了goctl插件(TAL 0.7.15)，但是在Goland中按照文档描述执行“New Api File","Api Code"等操作时报错：goctl not found
> 
> 系统版本：macOS Big Sur 11.2
> CPU型号：Apple M1

你先排查一下安装的goctl的path是不是在bash的path中，因为idea的Goctl插件读取的是bash的，如果这个排查没问题，请尽量提供一下信息：
* 安装goctl（二进制）的步骤，安装所在路径，该路径是否在path下
* go env

**Comment by anqiansong** [comment]
Fixed on https://github.com/zeromicro/goctl-intellij/releases/tag/v0.7.16, try again please!
