### ISSUE TITLE
[bug反馈]QueryRowPartial 方法貌似有个bug

### ISSUE THREAD

**Issue by ldmid666** [zeromicro/go-zero#966]
![image](https://user-images.githubusercontent.com/49946804/131072009-695ecb11-ed4c-443f-baa1-b459050f7b01.png)
QueryRowPartial 方法貌似有个bug，感觉字段和类型解析出现错位。
报错内容：sql: Scan error on column index 2, name "sale_province_name": unsupported Scan, storing driver.Value type <nil> into type *time.Time
而sale_province_name 这个字段是NullString类型不是time类型。当把time.Time字段放到下面的时候，就不会出错

**Comment by kevwan** [comment]
你这里用的是gorm吧？sqlx的tag是db

**Comment by ldmid666** [comment]
哦哦gorm引起的呀，那我改下试试去
