### ISSUE TITLE
API return 不支持除普通结构体、数组(向前兼容，后续考虑废弃)外的其他数据类型作为响应体

### ISSUE THREAD

**Issue by veezhang** [zeromicro/go-zero#987]
请问，为什么会考虑废弃数组？

如果废弃的话，根据 https://go-zero.dev/cn/template.html 来实现统一格式的body相应，则那么无法支持 Data 为数组的情况，如下：

```
{
  "code": 0,
  "msg": "OK",
  "data": [{},{}]
}
```

你们是否会再考虑考虑？

**Comment by kevwan** [comment]
> 请问，为什么会考虑废弃数组？
> 
> 如果废弃的话，根据 https://go-zero.dev/cn/template.html 来实现统一格式的body相应，则那么无法支持 Data 为数组的情况，如下：
> 
> ```
> {
>   "code": 0,
>   "msg": "OK",
>   "data": [{},{}]
> }
> ```
> 
> 你们是否会再考虑考虑？

没明白

**Comment by anqiansong** [comment]
> 请问，为什么会考虑废弃数组？
> 
> 如果废弃的话，根据 https://go-zero.dev/cn/template.html 来实现统一格式的body相应，则那么无法支持 Data 为数组的情况，如下：
> 
> ```
> {
>   "code": 0,
>   "msg": "OK",
>   "data": [{},{}]
> }
> ```
> 
> 你们是否会再考虑考虑？

api语法定义时建议都一JSONObject响应，这就是为什么return不允许数组，基本数据类型等格式，而为什么数组仍然能用，这是当时语法没有限制严格，有些使用goctl比较早的公司已经定义了这样的文件，因此做了向前兼容，在将来可能会强制限制。

**Comment by veezhang** [comment]
@kevwan @anqiansong 
抱歉，我可能表达的不够清晰，我也能理解返回的 body 一般是 `JSONObject` 类型。

这里我详细表达下我的意思，希望可以一起讨论下：

跟你你们的文档 https://go-zero.dev/cn/template.html 来实现实现统一格式的body相应，格式如下

```
{
  "code": 0,
  "msg": "OK",
  "data": {}
}
```

这里的 body 是 `JSONObject` 类型，`data` 也是 `JSONObject` 类型，我想说的是这里 `data` 为数组的情况个人认为还是比较常见的。

也就是说 `body` 是 `JSONObject` 类型，但是 `data` 并不一定是 `JSONObject` 类型。

而如果按照文档修改模板，如下：

```go
package handler

import (
    "net/http"
    "greet/response"

    {{.ImportPackages}}
)

func {{.HandlerName}}(ctx *svc.ServiceContext) http.HandlerFunc {
    return func(w http.ResponseWriter, r *http.Request) {
        {{if .HasRequest}}var req types.{{.RequestType}}
        if err := httpx.Parse(r, &req); err != nil {
            httpx.Error(w, err)
            return
        }{{end}}

        l := logic.New{{.LogicType}}(r.Context(), ctx)
        {{if .HasResp}}resp, {{end}}err := l.{{.Call}}({{if .HasRequest}}req{{end}})
        {{if .HasResp}}reponse.Response(w, resp, err){{else}}reponse.Response(w, nil, err){{end}}

    }
}
```

简单的一个 `reponse.Response` 实现如下：

```
type (
	responseBody struct {
		Code    int         `json:"code"`
		Message string      `json:"message"`
		Data    interface{} `json:"data"`
	}
)

func Response(w http.ResponseWriter, resp interface{}, err error) {
	if err != nil {
		httpx.Error(w, err) // Or response non-zero as code
		return
	}

	httpx.OkJson(w, &responseBody{
		Code:    0,
		Message: "Success",
		Data:    resp,
	})
}

```

模板中的 `resp` ，也就是 logic 返回的数据不再是整个 `body` 了， 而是 `body` 中某个字段，在这里的是 `data` 。而同时这个 `resp` 的数据结构也就是在 `api` 文件中需要定义的。

比如我们需要返回一个类似如下的数据：

```
{
  "code": 0,
  "msg": "OK",
  "data": ["id1", "id2"],
}
```

这时候，没办法在 `api` 中定义结构了

1⃣️数组的返回将被废弃

```
get /api/resources/() returns ([]string); // 这里将不支持使用 []
```

2⃣️不支持alias

```
type MyData []string // 这里又不支持alias
get /api/resources/() returns (MyData); 
```

这两种不支持，那么可能需要类似如下这种定义了：

```
type MyData {
    Items []MyDataItem `json:"items"`
}
type MyDataItem {
     ID string `json:"id"`
}
get /api/resources/() returns (MyData); 
```

而这种定义，感觉有点儿不够优雅，需要多定义一个数据结构，返回的数据结构也需要多一层 `items` 。

_注： 我这里为了凸显问题，特意定义了一个 `MyDataItem` 。_

以上是我想表达的，希望您有空可以看看，谢谢！

**Comment by veezhang** [comment]
Any news?

**Comment by chenquan** [comment]
这部分设计我也存在疑惑?

**Comment by anqiansong** [comment]
returns 的array类型将会被弃用的原因是有两点：
* 通过JSONObject包装，前端在json解析上可以不用考虑JSONArray的case，他们只用基于一个CodeData这样一个结构体去写Data对应的结构体即可
* 大部门情况要返回array，分页的case比较多，如果仅仅是返回一个array，而没有 page 相关信息，这也形成不了规范

综上情况，才考虑弃用JSONArray

**Comment by veezhang** [comment]
@anqiansong 我能理解大部分是是返回  JSONObject，也能理解返回 array 中大部分是分页，有 page, count 类似这种。

但是在做抉择的时候，是否也要给某些情况的一个选择，比如下拉列表框，要获取支持的情况，比如操作系统，比如版本信息。这种情况下，page, count 类似这种是多余的，可能 array 是更好的选择。

感觉您说的**前端在json解析上可以不用考虑JSONArray的case**，只是规范问题，而且我上面提到的 case 也符合这个规范，只是为了统一 code，api 中定义的 response 只会返回部分数据。

是否可以再考虑为了 **前端在json解析上可以不用考虑JSONArray的case**  而废弃这个功能？
是否可以考虑给其他 case 一种可能，而不是在接口上多一个无用的 items（类似） ？
是否可以考虑人为定义（比如公司代码规范）规范约束不能用 array ，而不是在框架层面减少这个功能，或者可以有开关可以开启？

**Comment by cyouraku** [comment]
仔细看了楼上的讨论，确实感觉把代码规范写到了框架里确实有点多虑了，估计将来使用的人多了或许会成为一个FQA。（希望未来能有更多人使用go-zero，加油！）

**Comment by wavechao** [comment]
大家这部分现在是怎么解决的哈

**Comment by Gkirito** [comment]
> 仔细看了楼上的讨论，感觉把代码规范写到了框架里确实有点多虑了，估计将来使用的人多了或许会成为一个FQA。（希望未来能有更多人使用go-zero，加油！）

非常赞同老哥的观点，还有 @veezhang 把代码规范写到框架里，有点过了，这部分不同公司前后端对接有自己的想法，不应该把你们公司或者自己的代码规范放入框架里，造成用这个框架就得遵守这个框架的规范了，而不是公司的规范；况且喜欢把code和msg放到body里还是仅通过http code来区分不同的业务，不同公司，甚至不同发开之间本来就有不同的意见，希望尽快支持纯数组返回，而不是还需要包一层

**Comment by kevwan** [comment]
感谢大家的反馈！

v1.2.4 版本里会加上。

**Comment by kevwan** [comment]
Progress update:
1. array is already supported, we're not going to remove this feature
2. `returns (int)`, `returns (string)` will be supported

**Comment by Gkirito** [comment]
> Progress update:
> 
> 1. array is already supported, we're not going to remove this feature
> 2. `returns (int)`, `returns (string)` etc will be supported

I found the `returns ([]type)` format is still not supported

**Comment by diandengs** [comment]
goctl version 1.4.0里取消了这种用法么？api定义时，return ([]string)直接报红了，不能框架里加这种限制，公司php项目更换为gozero，还得公司前端一起改，有些东西不能从框架上限制，虽然不规范但有些东西不是说他不规范就必须要去改的，要不要规范应该交与使用人员来处理，现在框架直接限制了，这种成本，直接就限制了使用gozero了

**Comment by CJD666** [comment]
1.5.3对[]type格式支持吗？

**Comment by blkcor** [comment]
so, what is the resolution?
